/**
 * O'qituvchi paneli matnlari — RU va UZ.
 *
 * NEGA ALOHIDA LUG'AT: ilovaning umumiy `shared/i18n` katalogi 4 tilni
 * saqlaydi va o'quvchi interfeysi uchun mo'ljallangan. Panel faqat ikki
 * tilda (ustozlar ruscha yoki o'zbekcha yozadi) va matni ko'p — umumiy
 * katalogga qo'shilsa, u yerdagi har bir tilga 200 dan ortiq keraksiz
 * kalit tushib qolardi.
 */

const ru = {
  /* ── Umumiy ─────────────────────────────────────────────────────────── */
  save: 'Сохранить',
  saving: 'Сохраняем…',
  saved: 'Сохранено',
  cancel: 'Отмена',
  delete: 'Удалить',
  close: 'Закрыть',
  open: 'Открыть',
  edit: 'Изменить',
  add: 'Добавить',
  back: 'Назад',
  next: 'Далее',
  loading: 'Загружаем…',
  yes: 'Да',
  no: 'Нет',
  all: 'Все',
  today: 'Сегодня',
  tomorrow: 'Завтра',
  minutesShort: 'мин',
  sum: 'сум',
  search: 'Поиск ученика, урока, документа',
  nothingFound: 'Ничего не найдено',
  errorGeneric: 'Не удалось выполнить действие',

  /* ── Menyu ──────────────────────────────────────────────────────────── */
  groupWork: 'Работа',
  groupCabinet: 'Кабинет',
  groupProfile: 'Профиль',
  navDashboard: 'Главная',
  navSchedule: 'Расписание',
  navStudents: 'Мои ученики',
  navLessons: 'Уроки',
  navClass: 'Онлайн-класс',
  navIncome: 'Доходы',
  navSubscription: 'Подписка',
  navMessages: 'Сообщения',
  navReviews: 'Отзывы',
  navProfile: 'Мой профиль',
  navAnketa: 'Анкета',
  navDocuments: 'Документы',
  navSettings: 'Настройки',
  navHelp: 'Помощь',
  navMore: 'Ещё',
  teacherRole: 'Преподаватель',

  /* ── Bildirishnomalar ───────────────────────────────────────────────── */
  notifications: 'Уведомления',
  notificationsEmpty: 'Уведомлений пока нет',
  markAllRead: 'Отметить всё прочитанным',

  /* ── Bosh sahifa ────────────────────────────────────────────────────── */
  greetingMorning: 'Доброе утро',
  greetingDay: 'Добрый день',
  greetingEvening: 'Добрый вечер',
  todaySummary: 'сегодня {lessons} урок(ов), {trials} пробный(х)',
  addFreeTime: '+ Добавить свободное время',
  openSchedule: 'Открыть расписание',
  statLessonsToday: 'Уроков сегодня',
  statTrialsToday: '{n} пробный урок',
  statStudents: 'Учеников',
  statActive: '{n} активных',
  statNewWeek: 'Новых за неделю',
  statWaitingTrial: '{n} ждут пробный',
  statLessonsDone: 'Проведено уроков',
  statAllTime: 'за всё время',
  statIncome: 'Доход за месяц',
  vsPrevMonth: '{n}% к прошлому месяцу',
  incomeTrialNote: 'пробные уроки',
  nextLesson: 'Следующий урок',
  trialTag: 'Пробный',
  regularTag: 'Обычный',
  doneTag: 'Завершён',
  cancelledTag: 'Отменён',
  startsIn: 'До начала {n} мин',
  lessonNow: 'Урок идёт',
  openStudent: 'Открыть ученика',
  goToLesson: 'Перейти к уроку',
  todaySchedule: 'Расписание на сегодня',
  wholeDay: 'Весь день →',
  noLessonsToday: 'Сегодня уроков нет',
  newStudents: 'Новые ученики',
  allArrow: 'Все →',
  noNewStudents: 'Новых учеников пока нет',
  waitingTime: 'Ждёт времени',
  quickActions: 'Быстрые действия',
  qaFreeTime: 'Свободное время',
  qaStudents: 'Мои ученики',
  qaStartLesson: 'Начать урок',
  qaEditProfile: 'Изменить профиль',
  noNextLesson: 'Запланированных уроков нет',
  noNextLessonHint: 'Добавьте свободное время — ученики начнут записываться на пробный урок.',

  /* ── Jadval ─────────────────────────────────────────────────────────── */
  scheduleTitle: 'Расписание',
  scheduleSubtitle: 'Часовой пояс Ташкент (UTC+5)',
  blockTime: 'Заблокировать время',
  weekPrev: '‹ Прошлая',
  weekThis: 'Эта неделя',
  weekNext: 'Следующая ›',
  slotFree: 'Свободно',
  slotBooked: 'Забронировано',
  slotTrial: 'Пробный',
  slotBlocked: 'Заблокировано',
  weeklyRules: 'Повторяющееся расписание',
  weeklyRulesHint: 'Каждую неделю в это время ученики могут забронировать урок',
  noWeeklyRules: 'Повторяющихся часов пока нет',
  oneTimeSlots: 'Разовые часы и блокировки',
  noExceptions: 'Разовых изменений нет',
  wholeDayBlocked: 'весь день',
  openTimeTag: 'Свободно',
  blockedTag: 'Заблокировано',
  unblock: 'Открыть',
  emptyDaySchedule: 'Свободное время не указано',
  addTimeTitle: 'Добавить свободное время',
  addTimeSubtitle: 'Ученики смогут забронировать эти часы',
  fieldDate: 'Дата',
  fieldStart: 'Начало',
  fieldEnd: 'Окончание',
  fieldLessonLength: 'Длительность урока',
  repeatWeekly: 'Повторять каждую неделю',
  repeatWeeklyHint: 'Каждый {weekday}, {from} — {to}',
  saveTime: 'Сохранить время',
  blockTitle: 'Заблокировать время',
  blockSubtitle: 'В это время ученики не смогут забронировать урок',
  blockWholeDayHint: 'Оставьте время пустым — заблокируется весь день',
  reasonOptional: 'Причина (необязательно)',
  blockAction: 'Заблокировать',
  scheduleSaved: 'Расписание изменено',
  viewDay: 'День',
  viewWeek: 'Неделя',
  viewMonth: 'Месяц',
  today_: 'Сегодня',
  slotPast: 'Прошло',
  addHere: '+ Свободное время',
  clickEmptyHint: 'Нажмите на клетку — время откроется для записи (зелёное). Нажмите ещё раз — закроется.',
  historyTitle: 'История изменений',
  historyEmpty: 'Изменений пока не было',
  evBooked: '{student} забронировал урок на {when}',
  evCancelled: '{student} отменил урок {when}',
  evOpen: 'Вы открыли время {when}',
  evBlock: 'Вы заблокировали время {when}',
  evRule: 'Вы добавили свободное время: каждый {weekday}, {from} — {to}',
  monthLessons: '{n} урок(ов)',
  monthFree: '{n} свободно',
  dayEmpty: 'В этот день свободное время не указано',

  /* ── O'quvchilar ────────────────────────────────────────────────────── */
  studentsTitle: 'Мои ученики',
  studentsSummary: '{total} ученик(ов) · {active} активных · {new} новых за неделю',
  searchStudent: 'Поиск ученика',
  filterAll: 'Все',
  filterNew: 'Новые',
  filterActive: 'Активные',
  filterTrial: 'Пробные',
  filterFinished: 'Завершившие',
  statusActive: 'Активный',
  statusTrial: 'Пробный',
  statusFinished: 'Завершил',
  statusNew: 'Новый',
  lessonsCount: '{n} уроков',
  noLessonsYet: 'уроков нет',
  studentsEmpty: 'В этом разделе учеников нет',
  nextLessonShort: 'Следующий урок',
  dash: '—',

  /* ── O'quvchi kartochkasi ───────────────────────────────────────────── */
  allStudents: '← Все ученики',
  write: 'Написать',
  startLesson: 'Начать урок',
  learningSince: 'Учится с {date}',
  levelLabel: 'Уровень {level}',
  statTotal: 'Всего уроков',
  statDone: 'Проведено',
  statCancelled: 'Отменено',
  statUpcoming: 'Запланировано',
  lessonHistory: 'История уроков',
  colDate: 'Дата',
  colTime: 'Время',
  colTopic: 'Тема',
  colStatus: 'Статус',
  colStudent: 'Ученик',
  colDuration: 'Длительность',
  colType: 'Тип',
  noHistory: 'Уроков пока не было',
  noTopic: 'Тема не указана',
  teacherNotes: 'Заметки преподавателя',
  notePlaceholder: 'Например: хорошо понимает речь, но испытывает сложности с падежами',
  addNote: 'Добавить заметку',
  notesEmpty: 'Заметок пока нет',
  reportOpen: 'Отчёт',

  /* ── Darslar ────────────────────────────────────────────────────────── */
  lessonsTitle: 'Уроки',
  lessonsSummary: '{done} проведено · {planned} запланировано',
  filterUpcoming: 'Предстоящие',
  filterToday: 'Сегодня',
  filterCompleted: 'Завершённые',
  filterCancelled: 'Отменённые',
  lessonsEmpty: 'В этом разделе уроков нет',
  timeNotSet: 'Время не назначено',
  onlineTag: 'Онлайн',

  /* ── Dars hisoboti ──────────────────────────────────────────────────── */
  reportTitle: 'Урок завершён',
  reportSubtitle: '{student} · {kind} · {minutes} мин',
  reportWhatStudied: 'Что изучили на уроке',
  reportWhatStudiedPh: 'Темы, упражнения, материалы',
  reportPositives: 'Что получилось',
  reportPositivesPh: 'Сильные стороны ученика',
  reportNegatives: 'Над чем работать',
  reportNegativesPh: 'Ошибки и сложности',
  reportHomework: 'Домашнее задание',
  reportHomeworkPh: 'Что ученик делает до следующего урока',
  reportComment: 'Комментарий для себя',
  reportCommentPh: 'Личные наблюдения по уроку',
  reportRating: 'Оценка урока',
  reportTrialResult: 'Результат пробного урока',
  reportLevel: 'Определённый уровень',
  reportReady: 'Готов продолжить обучение?',
  reportReadyYes: 'Готов продолжить',
  reportReadyNo: 'Не готов',
  reportSaveDraft: 'Сохранить черновик',
  reportFinish: 'Завершить урок',
  reportSaved: 'Отчёт сохранён',
  reportFinished: 'Урок завершён, ученику отправлен запрос на отзыв',
  reportBack: '← К урокам',

  /* ── Anketa ─────────────────────────────────────────────────────────── */
  anketaTitle: 'Анкета преподавателя',
  anketaSubtitle: 'Шаг {step} из 12 · профиль заполнен на {pct}%',
  anketaSaveExit: 'Сохранить и выйти',
  notFilledField: 'Не заполнено',
  missingCount: 'Не заполнено разделов: {n}',
  missingTitle: 'Эти разделы не заполнены',
  missingHint: 'Заполните их — без этого профиль не уйдёт на проверку.',
  allFilled: 'Все разделы заполнены',
  fill: 'Заполнить',
  anketaAutoSave: 'Черновик сохраняется автоматически',
  anketaSend: 'Отправить на модерацию',
  payNeededTitle: 'Сначала оплатите размещение',
  payNeededText:
    'Документы уходят на проверку модератору только после оплаты. Оплатите — и кнопка отправки станет активной.',
  payNow: 'Оплатить через Rahmat',
  payOpening: 'Открываем оплату…',
  payDone: 'Оплата получена',
  payPrice: 'Стоимость: {sum} сум',
  anketaSent: 'Анкета отправлена на проверку',
  stepLabel: 'Шаг {n}',
  step1: 'Личные данные',
  step2: 'Контактные данные',
  step3: 'Паспортные данные',
  step4: 'Фотография',
  step5: 'Где вы учились',
  step6: 'Опыт работы',
  step7: 'Специализация',
  step8: 'Языки',
  step9: 'Достижения и сертификаты',
  step10: 'О себе и методика',
  step11: 'Видео-презентация',
  step12: 'Предпросмотр профиля',
  fFirstName: 'Имя',
  fLastName: 'Фамилия',
  fBirthDate: 'Дата рождения',
  fGender: 'Пол',
  fMale: 'Мужской',
  fFemale: 'Женский',
  fEmail: 'Email',
  fTelegram: 'Telegram',
  fRegion: 'Область',
  fCity: 'Город',
  fPassportNumber: 'Серия и номер паспорта',
  fPassportIssuedBy: 'Кем выдан',
  fPassportIssuedAt: 'Дата выдачи',
  fAvatar: 'Ссылка на фото',
  eduTitle: 'Учебные заведения',
  eduHint: 'Перечислите все места учёбы: университет, институт, колледж, лицей или курсы. Пишите так, как написано в дипломе.',
  eduInstitution: 'Название учебного заведения',
  eduInstitutionPh: 'Например: Узбекский государственный университет мировых языков',
  eduSpecialty: 'Направление / специальность',
  eduSpecialtyPh: 'Например: Русский язык и литература',
  eduDegree: 'Уровень',
  eduStartYear: 'Год поступления',
  eduEndYear: 'Год окончания',
  eduAdd: '+ Добавить учебное заведение',
  eduEmpty: 'Пока ничего не добавлено',
  eduExample: 'Пример: УзГУМЯ · Русский язык и литература · Бакалавр · 2012 — 2016',
  eduDegreeBachelor: 'Бакалавр',
  eduDegreeMaster: 'Магистр',
  eduDegreeCollege: 'Колледж / лицей',
  eduDegreeCourse: 'Курсы',
  eduDegreeOther: 'Другое',
  certTitleField: 'Название сертификата',
  certTitlePh: 'Например: Преподавание русского как иностранного',
  certIssuer: 'Кто выдал',
  certIssuerPh: 'Например: Институт Пушкина',
  certYear: 'Год',
  certAdd: '+ Добавить сертификат',
  certEmpty: 'Сертификаты не добавлены',
  certHint: 'Добавьте курсы, дипломы и награды, подтверждающие вашу квалификацию. К каждому сертификату можно прикрепить фото — оно появится в вашем профиле.',
  certImage: 'Фото сертификата',
  certImageAdd: 'Загрузить фото',
  certImageChange: 'Заменить фото',
  certImageRemove: 'Удалить фото',
  certImageHint: 'JPG, PNG или WEBP, до 4 МБ. Фото видно ученикам в вашем профиле.',
  certImageUploading: 'Загружается…',
  certImageSaved: 'Фото сертификата загружено',
  certImageTooBig: 'Файл больше 4 МБ — выберите фото поменьше',
  certImageWrongType: 'Только JPG, PNG или WEBP',
  rowDelete: 'Удалить',
  fEducation: 'Образование',
  fExperience: 'Опыт преподавания (лет)',
  fSubjects: 'Что вы преподаёте',
  fLevels: 'Уровни учеников',
  fLanguages: 'Языки',
  fCertificates: 'Сертификаты',
  fAchievements: 'Достижения',
  fAbout: 'Расскажите о себе',
  fHeadline: 'Короткое описание',
  fVideo: 'Ссылка на видео',
  fPrice: 'Стоимость месячного курса (сум)',
  chooseOption: 'Выберите',
  selectHint: 'Можно выбрать несколько',
  privateHint:
    'Эти данные нужны для проверки личности и не показываются ученикам. Доступ есть только у вас и у модераторов FalaRus.',
  contactHint:
    'Телефон и email не показываются ученикам. Всё общение проходит внутри FalaRus.',
  photoHint: 'Фотография — первое, что видит ученик. Лицо хорошо видно, нейтральный фон, без фильтров.',
  photoUpload: 'Загрузить фото',
  photoReplace: 'Заменить фото',
  photoDelete: 'Удалить фотографию',
  photoFormats: 'JPG, PNG или WEBP · до 4 МБ · обрежется в квадрат автоматически',
  photoEmpty: 'Фотография не загружена',
  photoSaved: 'Фотография сохранена',
  photoPreviewTitle: 'Так фото увидят ученики',
  photoInMenu: 'В шапке кабинета',
  photoInList: 'В списке преподавателей',
  photoInProfile: 'В публичном профиле',
  photoRule1: 'Лицо хорошо видно, взгляд в камеру',
  photoRule2: 'Хорошее освещение, нейтральный фон',
  photoRule3: 'Профессиональный внешний вид',
  photoRule4: 'Без сильных фильтров, тёмных и групповых фото',
  photoSample: 'Пример',
  photoSampleHint: 'Такое фото проходит модерацию с первого раза',
  photoGuideOpen: 'Посмотреть образец',
  photoGuideTitle: 'Образец фото для аватарки',
  photoGuideFull: 'Открыть в полном размере',
  photoGuideCard: 'Правильные и неправильные фото',
  aboutHint: 'Кто вы, сколько лет преподаёте, с какими учениками работаете и почему вам это нравится.',
  videoHint: '1–3 минуты · тихое помещение · камера на уровне глаз · говорите естественно.',
  videoWhyTitle: 'Зачем нужно видео',
  videoWhyText:
    'Видео — главный способ выбрать преподавателя: ученик видит вас и слышит вашу речь ещё до первого урока. Профили с видео получают заметно больше записей на пробный урок.',
  videoTipsTitle: 'Рекомендации',
  videoUpload: 'Загрузить видео',
  videoReplace: 'Записать/загрузить заново',
  videoDelete: 'Удалить видео',
  videoFormats: 'MP4, MOV или WEBM · до 100 МБ · 1–3 минуты',
  videoEmpty: 'Видео ещё не загружено',
  videoUploading: 'Загружаем… {n}%',
  videoStatusPending: 'На проверке у модератора',
  videoStatusPendingText: 'Обычно проверка занимает до 2 рабочих дней. После одобрения видео увидят все ученики.',
  videoStatusApproved: 'Видео одобрено',
  videoStatusApprovedText: 'Видео опубликовано в вашем профиле и видно ученикам.',
  videoStatusRejected: 'Видео отклонено',
  videoModerationNote: 'Видео проверяет администратор FalaRus. Ученикам оно показывается только после одобрения.',
  videoQuestionsTitle: 'О чём рассказать',
  charsLeft: '{n} / 1000',
  previewHint: 'Так ваш профиль увидят ученики. Паспорт, телефон и email в публичной части не показываются.',
  openFullPreview: 'Открыть предпросмотр',

  /* ── Profil ─────────────────────────────────────────────────────────── */
  profileTitle: 'Мой профиль',
  profileSubtitle: 'Внутренние данные видны только модераторам FalaRus, публичная часть — ученикам',
  viewAsStudent: 'Посмотреть как ученик',
  stDraftTitle: 'Черновик анкеты',
  stDraftText: 'Завершите анкету, чтобы отправить её на проверку.',
  stDraftCta: 'Продолжить заполнение',
  stReviewTitle: 'Профиль на модерации',
  stReviewText: 'Проверяем документы, видео и данные об образовании. Обычно занимает до 3 рабочих дней.',
  stReviewCta: 'Посмотреть анкету',
  stActiveTitle: 'Профиль подтверждён',
  stActiveText: 'Ваш профиль опубликован и виден ученикам.',
  stActiveCta: 'Посмотреть как ученик',
  stRejectedTitle: 'Профиль отклонён',
  stRejectedCta: 'Исправить профиль',
  stPausedTitle: 'Профиль приостановлен',
  stPausedText: 'Профиль временно скрыт от учеников. Свяжитесь с поддержкой FalaRus.',
  stPausedCta: 'Связаться с поддержкой',
  editAnketa: 'Редактировать анкету',
  myDocuments: 'Мои документы',
  publicPart: 'Публичная часть профиля',
  publicPartHint: 'видна ученикам',
  privatePart: 'Закрытая часть',
  privatePartHint: 'только вы и модераторы',
  fieldSpecialization: 'Специализация',
  fieldLevelsAge: 'Уровни',
  fieldPrice: 'Стоимость курса',
  fieldVideo: 'Видео-презентация',
  videoUploaded: 'Загружено',
  videoMissing: 'Не загружено',
  fieldPassport: 'Паспорт',
  fieldContacts: 'Контакты',
  notFilled: 'Не заполнено',
  filledPercent: 'Заполнено на {pct}%',
  ofSteps: '{done} из {total}',
  continueFilling: 'Продолжить заполнение',
  ratingTitle: 'Рейтинг',
  noRatingYet: 'Оценок пока нет',
  reviewsCount: '{n} отзывов',

  /* ── Ommaviy ko'rinish ──────────────────────────────────────────────── */
  previewBanner: 'Предпросмотр · так ваш профиль видят ученики',
  exitPreview: 'Выйти из предпросмотра',
  aboutTeacher: 'О преподавателе',
  educationBlock: 'Образование',
  experienceBlock: 'Опыт работы',
  certificatesBlock: 'Сертификаты и достижения',
  reviewsBlock: 'Отзывы учеников',
  speaks: 'Говорит',
  yearsExp: '{n} лет опыта',
  lessonsDoneShort: '{n} уроков',
  trialFree: 'Пробный урок · 30 минут',
  bookTrial: 'Записаться на пробный урок',
  writeTeacher: 'Написать преподавателю',
  teacherStats: 'Статистика преподавателя',
  emptyAbout: 'Раздел «О себе» пока не заполнен',

  /* ── Daromad ────────────────────────────────────────────────────────── */
  incomeTitle: 'Доходы',
  incomeMonth: 'Этот месяц',
  incomeFromTrials: 'С пробных уроков',
  incomeManual: 'Внесено вручную',
  incomeAuto: 'автоматически',
  incomeManualHint: 'месячный курс и другое',
  incomeLast6: 'Последние 6 месяцев',
  incomeAdd: 'Добавить доход',
  incomeAmount: 'Сумма (сум)',
  incomeDate: 'Дата',
  incomeNote: 'Комментарий',
  incomeEmpty: 'Записей пока нет',

  /* ── Obuna ──────────────────────────────────────────────────────────── */
  subscriptionTitle: 'Подписка',
  subscriptionSubtitle: 'Пока подписка активна, ваш профиль виден ученикам в поиске',
  subActive: 'Подписка активна',
  subActiveUntil: 'Активна до {date} · осталось {days} дн.',
  subInactive: 'Подписка не активна',
  subInactiveText: 'Профиль не показывается в поиске преподавателей.',
  subFreeLessons: 'Бесплатные пробные уроки: {used} из {limit}',
  subFreeHint: 'Первые {limit} пробных уроков проходят без подписки.',
  subRenew: 'Продлить подписку',
  subHistory: 'История оплат',
  subEmpty: 'Оплат пока не было',
  subEndsIn: 'Подписка заканчивается через {days} дн.',
  subEndsHint: 'Чтобы продолжать получать новых учеников, продлите тариф заранее.',

  /* ── Xabarlar ───────────────────────────────────────────────────────── */
  messagesTitle: 'Сообщения',
  messagesEmpty: 'Переписок пока нет',
  messagesHint: 'Чат открывается после оплаты пробного урока учеником',
  chooseChat: 'Выберите переписку',
  messagePlaceholder: 'Сообщение…',
  send: 'Отправить',

  /* ── Sharhlar ───────────────────────────────────────────────────────── */
  reviewsTitle: 'Отзывы',
  reviewsEmpty: 'Отзывов пока нет',
  reviewsHint: 'Ученик оставляет отзыв после завершённого пробного урока',
  reviewLiked: 'Понравилось',
  reviewMissing: 'Чего не хватило',
  reviewEnrolled: 'Записался на курс',
  reviewNotEnrolled: 'Не записался',

  /* ── Onlayn dars ────────────────────────────────────────────────────── */
  classTitle: 'Онлайн-класс',
  classSubtitle: 'Видеокомната FalaRus — ученик заходит по той же ссылке',
  classNoRoom: 'Видеокомната ещё не выдана',
  classNoRoomHint: 'Комнату открывает администратор FalaRus. Напишите в поддержку, если она нужна.',
  classEnter: 'Войти в комнату',
  classSessions: 'Запланированные уроки',
  classAddSession: 'Добавить урок',
  classSessionTitle: 'Название',
  classSessionStart: 'Начало',
  classSessionDuration: 'Длительность (мин)',
  classNoSessions: 'Запланированных уроков нет',
  classJoin: 'Войти',
  classCopyLink: 'Скопировать ссылку',
  classLinkCopied: 'Ссылка скопирована',

  /* ── Hujjatlar ──────────────────────────────────────────────────────── */
  documentsTitle: 'Документы',
  documentsSubtitle: 'JPG, PNG, WEBP или PDF · до 8 МБ · проверяет модератор',
  docPassport: 'Паспорт',
  docDiploma: 'Диплом',
  docCertificate: 'Сертификат',
  docOther: 'Другое',
  docAdd: '+ {kind}',
  docPending: 'На проверке',
  docApproved: 'Подтверждён',
  docRejected: 'Отклонён',
  documentsEmpty: 'Документы ещё не загружены',
  uploaded: 'Загружено',

  /* ── Sozlamalar va yordam ───────────────────────────────────────────── */
  settingsTitle: 'Настройки',
  settingsLanguage: 'Язык панели',
  settingsAccount: 'Аккаунт',
  accEdit: 'Мои данные',
  accSaved: 'Данные сохранены',
  passTitle: 'Смена пароля',
  passCurrent: 'Текущий пароль',
  passNew: 'Новый пароль',
  passRepeat: 'Повторите новый пароль',
  passChange: 'Сменить пароль',
  passChanged: 'Пароль изменён',
  accPhoto: 'Фото профиля',
  settingsPhone: 'Телефон',
  settingsEmail: 'Email',
  settingsPassword: 'Пароль',
  settingsPasswordHint: 'Ссылка для смены пароля придёт на вашу почту',
  settingsPasswordSend: 'Отправить ссылку',
  settingsPasswordSent: 'Ссылка отправлена на почту',
  settingsPasswordNoEmail: 'К аккаунту не привязана почта — напишите в поддержку',
  logout: 'Выйти из аккаунта',
  helpTitle: 'Помощь',
  helpSubtitle: 'Частые вопросы преподавателей',
  helpContact: 'Написать в поддержку',
  helpQ1: 'Как ученики меня находят?',
  helpA1:
    'Ученик открывает раздел «Преподаватели», фильтрует по уровню и специализации и записывается на пробный урок. В поиске показываются только подтверждённые профили с активной подпиской.',
  helpQ2: 'Когда ученик может забронировать урок?',
  helpA2:
    'Только в те часы, которые вы отметили свободными в разделе «Расписание». Забронированное время автоматически становится занятым.',
  helpQ3: 'Как проходит пробный урок?',
  helpA3:
    'После оплаты открывается чат с учеником и видеокомната. После урока заполните отчёт — ученик получит запрос на отзыв.',
  helpQ4: 'Когда я получаю деньги?',
  helpA4:
    'Оплата пробного урока проходит через FalaRus. Оплату месячного курса вы получаете напрямую и записываете её в разделе «Доходы».',

  /* ── Kirish ─────────────────────────────────────────────────────────── */
  gateTitle: 'Кабинет преподавателя',
  gateText: 'Войдите в аккаунт преподавателя, чтобы открыть кабинет.',
  gateLogin: 'Войти',
  gateRegister: 'Стать преподавателем',
  gateStudentTitle: 'Этот раздел для преподавателей',
  gateStudentText: 'Вы вошли как ученик. Кабинет преподавателя открывается отдельным аккаунтом.',
  gateHome: 'На главную',
} as const;

export type PanelDict = { [K in keyof typeof ru]: string };

const uz: PanelDict = {
  /* ── Umumiy ─────────────────────────────────────────────────────────── */
  save: 'Saqlash',
  saving: 'Saqlanmoqda…',
  saved: 'Saqlandi',
  cancel: 'Bekor qilish',
  delete: 'Oʻchirish',
  close: 'Yopish',
  open: 'Ochish',
  edit: 'Oʻzgartirish',
  add: 'Qoʻshish',
  back: 'Ortga',
  next: 'Keyingi',
  loading: 'Yuklanmoqda…',
  yes: 'Ha',
  no: 'Yoʻq',
  all: 'Hammasi',
  today: 'Bugun',
  tomorrow: 'Ertaga',
  minutesShort: 'daq',
  sum: 'soʻm',
  search: 'Oʻquvchi, dars yoki hujjatni qidirish',
  nothingFound: 'Hech narsa topilmadi',
  errorGeneric: 'Amal bajarilmadi',

  /* ── Menyu ──────────────────────────────────────────────────────────── */
  groupWork: 'Ish',
  groupCabinet: 'Kabinet',
  groupProfile: 'Profil',
  navDashboard: 'Bosh sahifa',
  navSchedule: 'Jadval',
  navStudents: 'Oʻquvchilarim',
  navLessons: 'Darslar',
  navClass: 'Onlayn dars',
  navIncome: 'Daromad',
  navSubscription: 'Obuna',
  navMessages: 'Xabarlar',
  navReviews: 'Sharhlar',
  navProfile: 'Mening profilim',
  navAnketa: 'Anketa',
  navDocuments: 'Hujjatlar',
  navSettings: 'Sozlamalar',
  navHelp: 'Yordam',
  navMore: 'Yana',
  teacherRole: 'Oʻqituvchi',

  /* ── Bildirishnomalar ───────────────────────────────────────────────── */
  notifications: 'Bildirishnomalar',
  notificationsEmpty: 'Hozircha bildirishnoma yoʻq',
  markAllRead: 'Hammasini oʻqilgan deb belgilash',

  /* ── Bosh sahifa ────────────────────────────────────────────────────── */
  greetingMorning: 'Xayrli tong',
  greetingDay: 'Xayrli kun',
  greetingEvening: 'Xayrli kech',
  todaySummary: 'bugun {lessons} ta dars, {trials} ta sinov darsi',
  addFreeTime: '+ Boʻsh vaqt qoʻshish',
  openSchedule: 'Jadvalni ochish',
  statLessonsToday: 'Bugungi darslar',
  statTrialsToday: '{n} ta sinov darsi',
  statStudents: 'Oʻquvchilar',
  statActive: '{n} ta faol',
  statNewWeek: 'Hafta ichida yangi',
  statWaitingTrial: '{n} ta sinov kutmoqda',
  statLessonsDone: 'Oʻtkazilgan darslar',
  statAllTime: 'jami',
  statIncome: 'Shu oydagi daromad',
  vsPrevMonth: 'oʻtgan oyga {n}%',
  incomeTrialNote: 'sinov darslari',
  nextLesson: 'Keyingi dars',
  trialTag: 'Sinov',
  regularTag: 'Oddiy',
  doneTag: 'Tugagan',
  cancelledTag: 'Bekor qilingan',
  startsIn: 'Boshlanishiga {n} daqiqa',
  lessonNow: 'Dars ketmoqda',
  openStudent: 'Oʻquvchini ochish',
  goToLesson: 'Darsga oʻtish',
  todaySchedule: 'Bugungi jadval',
  wholeDay: 'Butun kun →',
  noLessonsToday: 'Bugun dars yoʻq',
  newStudents: 'Yangi oʻquvchilar',
  allArrow: 'Barchasi →',
  noNewStudents: 'Hozircha yangi oʻquvchi yoʻq',
  waitingTime: 'Vaqt kutilmoqda',
  quickActions: 'Tez amallar',
  qaFreeTime: 'Boʻsh vaqt',
  qaStudents: 'Oʻquvchilarim',
  qaStartLesson: 'Darsni boshlash',
  qaEditProfile: 'Profilni tahrirlash',
  noNextLesson: 'Rejalashtirilgan dars yoʻq',
  noNextLessonHint: 'Boʻsh vaqt qoʻshsangiz, oʻquvchilar sinov darsiga yozila boshlaydi.',

  /* ── Jadval ─────────────────────────────────────────────────────────── */
  scheduleTitle: 'Jadval',
  scheduleSubtitle: 'Toshkent vaqti (UTC+5)',
  blockTime: 'Vaqtni bloklash',
  weekPrev: '‹ Oldingi',
  weekThis: 'Shu hafta',
  weekNext: 'Keyingi ›',
  slotFree: 'Boʻsh',
  slotBooked: 'Band',
  slotTrial: 'Sinov',
  slotBlocked: 'Bloklangan',
  weeklyRules: 'Takrorlanuvchi jadval',
  weeklyRulesHint: 'Har hafta shu vaqtda oʻquvchilar dars band qila oladi',
  noWeeklyRules: 'Takrorlanuvchi vaqt hali yoʻq',
  oneTimeSlots: 'Bir martalik vaqtlar va bloklar',
  noExceptions: 'Bir martalik oʻzgarish yoʻq',
  wholeDayBlocked: 'butun kun',
  openTimeTag: 'Boʻsh',
  blockedTag: 'Bloklangan',
  unblock: 'Ochish',
  emptyDaySchedule: 'Boʻsh vaqt belgilanmagan',
  addTimeTitle: 'Boʻsh vaqt qoʻshish',
  addTimeSubtitle: 'Oʻquvchilar shu soatlarga yozila oladi',
  fieldDate: 'Sana',
  fieldStart: 'Boshlanishi',
  fieldEnd: 'Tugashi',
  fieldLessonLength: 'Bitta dars uzunligi',
  repeatWeekly: 'Har hafta takrorlansin',
  repeatWeeklyHint: 'Har {weekday}, {from} — {to}',
  saveTime: 'Vaqtni saqlash',
  blockTitle: 'Vaqtni bloklash',
  blockSubtitle: 'Bu vaqtda oʻquvchilar dars band qila olmaydi',
  blockWholeDayHint: 'Vaqtni boʻsh qoldirsangiz — butun kun bloklanadi',
  reasonOptional: 'Sabab (ixtiyoriy)',
  blockAction: 'Bloklash',
  scheduleSaved: 'Jadval yangilandi',
  viewDay: 'Kun',
  viewWeek: 'Hafta',
  viewMonth: 'Oy',
  today_: 'Bugun',
  slotPast: 'Oʻtdi',
  addHere: '+ Boʻsh vaqt',
  clickEmptyHint: 'Katakni bosing — oʻsha soat yozilish uchun ochiladi (yashil). Yana bossangiz — yopiladi.',
  historyTitle: 'Oʻzgarishlar tarixi',
  historyEmpty: 'Hozircha oʻzgarish boʻlmagan',
  evBooked: '{student} {when} ga dars band qildi',
  evCancelled: '{student} {when} darsini bekor qildi',
  evOpen: 'Siz {when} vaqtini ochdingiz',
  evBlock: 'Siz {when} vaqtini blokladingiz',
  evRule: 'Siz boʻsh vaqt qoʻshdingiz: har {weekday}, {from} — {to}',
  monthLessons: '{n} ta dars',
  monthFree: '{n} ta boʻsh',
  dayEmpty: 'Bu kunga boʻsh vaqt belgilanmagan',

  /* ── O'quvchilar ────────────────────────────────────────────────────── */
  studentsTitle: 'Oʻquvchilarim',
  studentsSummary: '{total} ta oʻquvchi · {active} ta faol · {new} ta yangi',
  searchStudent: 'Oʻquvchini qidirish',
  filterAll: 'Hammasi',
  filterNew: 'Yangi',
  filterActive: 'Faol',
  filterTrial: 'Sinov',
  filterFinished: 'Tugatgan',
  statusActive: 'Faol',
  statusTrial: 'Sinov',
  statusFinished: 'Tugatgan',
  statusNew: 'Yangi',
  lessonsCount: '{n} ta dars',
  noLessonsYet: 'dars yoʻq',
  studentsEmpty: 'Bu boʻlimda oʻquvchi yoʻq',
  nextLessonShort: 'Keyingi dars',
  dash: '—',

  /* ── O'quvchi kartochkasi ───────────────────────────────────────────── */
  allStudents: '← Barcha oʻquvchilar',
  write: 'Xabar yozish',
  startLesson: 'Darsni boshlash',
  learningSince: '{date} dan beri',
  levelLabel: '{level} daraja',
  statTotal: 'Jami darslar',
  statDone: 'Oʻtkazilgan',
  statCancelled: 'Bekor qilingan',
  statUpcoming: 'Rejalashtirilgan',
  lessonHistory: 'Darslar tarixi',
  colDate: 'Sana',
  colTime: 'Vaqt',
  colTopic: 'Mavzu',
  colStatus: 'Holat',
  colStudent: 'Oʻquvchi',
  colDuration: 'Davomiyligi',
  colType: 'Turi',
  noHistory: 'Hali dars boʻlmagan',
  noTopic: 'Mavzu yozilmagan',
  teacherNotes: 'Oʻqituvchi eslatmalari',
  notePlaceholder: 'Masalan: nutqni yaxshi tushunadi, lekin kelishiklarda qiynaladi',
  addNote: 'Eslatma qoʻshish',
  notesEmpty: 'Hozircha eslatma yoʻq',
  reportOpen: 'Hisobot',

  /* ── Darslar ────────────────────────────────────────────────────────── */
  lessonsTitle: 'Darslar',
  lessonsSummary: '{done} ta oʻtkazilgan · {planned} ta rejalashtirilgan',
  filterUpcoming: 'Kelayotgan',
  filterToday: 'Bugun',
  filterCompleted: 'Tugagan',
  filterCancelled: 'Bekor qilingan',
  lessonsEmpty: 'Bu boʻlimda dars yoʻq',
  timeNotSet: 'Vaqt belgilanmagan',
  onlineTag: 'Onlayn',

  /* ── Dars hisoboti ──────────────────────────────────────────────────── */
  reportTitle: 'Dars yakuni',
  reportSubtitle: '{student} · {kind} · {minutes} daqiqa',
  reportWhatStudied: 'Darsda nima oʻrganildi',
  reportWhatStudiedPh: 'Mavzular, mashqlar, materiallar',
  reportPositives: 'Nima yaxshi boʻldi',
  reportPositivesPh: 'Oʻquvchining kuchli tomonlari',
  reportNegatives: 'Nima ustida ishlash kerak',
  reportNegativesPh: 'Xatolar va qiyinchiliklar',
  reportHomework: 'Uy vazifasi',
  reportHomeworkPh: 'Keyingi darsgacha nima qiladi',
  reportComment: 'Oʻzim uchun izoh',
  reportCommentPh: 'Dars boʻyicha shaxsiy kuzatuv',
  reportRating: 'Darsga baho',
  reportTrialResult: 'Sinov darsi natijasi',
  reportLevel: 'Aniqlangan daraja',
  reportReady: 'Oʻqishni davom ettirishga tayyormi?',
  reportReadyYes: 'Davom etadi',
  reportReadyNo: 'Tayyor emas',
  reportSaveDraft: 'Qoralamani saqlash',
  reportFinish: 'Darsni yakunlash',
  reportSaved: 'Hisobot saqlandi',
  reportFinished: 'Dars yakunlandi, oʻquvchiga fikr soʻrovi yuborildi',
  reportBack: '← Darslarga',

  /* ── Anketa ─────────────────────────────────────────────────────────── */
  anketaTitle: 'Oʻqituvchi anketasi',
  anketaSubtitle: '{step}-qadam / 12 · profil {pct}% toʻldirilgan',
  anketaSaveExit: 'Saqlash va chiqish',
  notFilledField: 'Toʻldirilmagan',
  missingCount: '{n} ta boʻlim toʻldirilmagan',
  missingTitle: 'Bu boʻlimlar toʻldirilmagan',
  missingHint: 'Ularni toʻldiring — aks holda profil tekshiruvga ketmaydi.',
  allFilled: 'Hamma boʻlim toʻldirilgan',
  fill: 'Toʻldirish',
  anketaAutoSave: 'Qoralama saqlanadi',
  anketaSend: 'Tekshiruvga yuborish',
  payNeededTitle: 'Avval roʻyxat toʻlovini amalga oshiring',
  payNeededText:
    'Hujjatlar moderatorga faqat toʻlovdan keyin yuboriladi. Toʻlov qilsangiz — yuborish tugmasi ishga tushadi.',
  payNow: 'Rahmat orqali toʻlash',
  payOpening: 'Toʻlov ochilmoqda…',
  payDone: 'Toʻlov qabul qilindi',
  payPrice: 'Narxi: {sum} soʻm',
  anketaSent: 'Anketa tekshiruvga yuborildi',
  stepLabel: '{n}-qadam',
  step1: 'Shaxsiy maʼlumotlar',
  step2: 'Aloqa maʼlumotlari',
  step3: 'Pasport maʼlumotlari',
  step4: 'Surat',
  step5: 'Bilim dargohlari',
  step6: 'Ish tajribasi',
  step7: 'Mutaxassislik',
  step8: 'Tillar',
  step9: 'Yutuq va sertifikatlar',
  step10: 'Oʻzim va metodikam',
  step11: 'Video-taqdimot',
  step12: 'Profilni koʻrish',
  fFirstName: 'Ism',
  fLastName: 'Familiya',
  fBirthDate: 'Tugʻilgan sana',
  fGender: 'Jins',
  fMale: 'Erkak',
  fFemale: 'Ayol',
  fEmail: 'Email',
  fTelegram: 'Telegram',
  fRegion: 'Viloyat',
  fCity: 'Shahar',
  fPassportNumber: 'Pasport seriya va raqami',
  fPassportIssuedBy: 'Kim tomonidan berilgan',
  fPassportIssuedAt: 'Berilgan sana',
  fAvatar: 'Surat havolasi',
  eduTitle: 'Bilim dargohlari',
  eduHint: 'Qayerda oʻqigan boʻlsangiz — universitet, institut, kollej, litsey yoki kurs — hammasini yozing. Nomini diplomdagidek toʻliq yozing.',
  eduInstitution: 'Bilim dargohi nomi',
  eduInstitutionPh: 'Masalan: Oʻzbekiston davlat jahon tillari universiteti',
  eduSpecialty: 'Yoʻnalish / mutaxassislik',
  eduSpecialtyPh: 'Masalan: Rus tili va adabiyoti',
  eduDegree: 'Daraja',
  eduStartYear: 'Kirgan yil',
  eduEndYear: 'Bitirgan yil',
  eduAdd: '+ Bilim dargohi qoʻshish',
  eduEmpty: 'Hozircha hech nima qoʻshilmagan',
  eduExample: 'Namuna: OʻzDJTU · Rus tili va adabiyoti · Bakalavr · 2012 — 2016',
  eduDegreeBachelor: 'Bakalavr',
  eduDegreeMaster: 'Magistr',
  eduDegreeCollege: 'Kollej / litsey',
  eduDegreeCourse: 'Kurs',
  eduDegreeOther: 'Boshqa',
  certTitleField: 'Sertifikat nomi',
  certTitlePh: 'Masalan: Rus tilini chet tili sifatida oʻqitish',
  certIssuer: 'Kim bergan',
  certIssuerPh: 'Masalan: Pushkin instituti',
  certYear: 'Yil',
  certAdd: '+ Sertifikat qoʻshish',
  certEmpty: 'Sertifikat qoʻshilmagan',
  certHint: 'Malakangizni tasdiqlaydigan kurs, diplom va yutuqlarni qoʻshing. Har bir sertifikatga rasm biriktirsangiz, u profilingizda koʻrinadi.',
  certImage: 'Sertifikat rasmi',
  certImageAdd: 'Rasm yuklash',
  certImageChange: 'Rasmni almashtirish',
  certImageRemove: 'Rasmni oʻchirish',
  certImageHint: 'JPG, PNG yoki WEBP, 4 MB gacha. Rasmni oʻquvchilar profilingizda koʻradi.',
  certImageUploading: 'Yuklanmoqda…',
  certImageSaved: 'Sertifikat rasmi yuklandi',
  certImageTooBig: 'Fayl 4 MB dan katta — kichikroq rasm tanlang',
  certImageWrongType: 'Faqat JPG, PNG yoki WEBP',
  rowDelete: 'Oʻchirish',
  fEducation: 'Taʼlim',
  fExperience: 'Dars berish tajribasi (yil)',
  fSubjects: 'Nima oʻrgatasiz',
  fLevels: 'Oʻquvchilar darajasi',
  fLanguages: 'Tillar',
  fCertificates: 'Sertifikatlar',
  fAchievements: 'Yutuqlar',
  fAbout: 'Oʻzingiz haqingizda',
  fHeadline: 'Qisqa tavsif',
  fVideo: 'Video havolasi',
  fPrice: 'Oylik kurs narxi (soʻm)',
  chooseOption: 'Tanlang',
  selectHint: 'Bir nechtasini tanlash mumkin',
  privateHint:
    'Bu maʼlumotlar shaxsni tekshirish uchun kerak va oʻquvchilarga koʻrsatilmaydi. Faqat siz va FalaRus moderatorlari koʻradi.',
  contactHint:
    'Telefon va email oʻquvchilarga koʻrsatilmaydi. Barcha muloqot FalaRus ichida boradi.',
  photoHint: 'Suratni oʻquvchi birinchi boʻlib koʻradi. Yuz aniq koʻrinsin, fon sodda boʻlsin.',
  photoUpload: 'Suratni yuklash',
  photoReplace: 'Suratni almashtirish',
  photoDelete: 'Suratni oʻchirish',
  photoFormats: 'JPG, PNG yoki WEBP · 4 MB gacha · avtomatik kvadratga qirqiladi',
  photoEmpty: 'Surat yuklanmagan',
  photoSaved: 'Surat saqlandi',
  photoPreviewTitle: 'Oʻquvchilar suratni shunday koʻradi',
  photoInMenu: 'Kabinet tepasida',
  photoInList: 'Oʻqituvchilar roʻyxatida',
  photoInProfile: 'Ommaviy profilda',
  photoRule1: 'Yuz aniq koʻrinsin, nigoh kameraga',
  photoRule2: 'Yorugʻlik yaxshi, fon sodda',
  photoRule3: 'Koʻrinish ishchan boʻlsin',
  photoRule4: 'Kuchli filtr, qorongʻi va guruh surat boʻlmasin',
  photoSample: 'Namuna',
  photoSampleHint: 'Shunday surat tekshiruvdan birinchi safar oʻtadi',
  photoGuideOpen: 'Namunani koʻrish',
  photoGuideTitle: 'Avatar surati uchun namuna',
  photoGuideFull: 'Toʻliq oʻlchamda ochish',
  photoGuideCard: 'Toʻgʻri va notoʻgʻri suratlar',
  aboutHint: 'Kimsiz, necha yildan beri dars berasiz, qanday oʻquvchilar bilan ishlaysiz.',
  videoHint: '1–3 daqiqa · tinch xona · kamera koʻz balandligida · tabiiy gapiring.',
  videoWhyTitle: 'Video nima uchun kerak',
  videoWhyText:
    'Oʻquvchi ustoz tanlashda eng koʻp videoga tayanadi: u sizni birinchi darsdan oldin koʻradi va nutqingizni eshitadi. Videosi bor profillarga sinov darsiga yozilish sezilarli koʻp boʻladi.',
  videoTipsTitle: 'Tavsiyalar',
  videoUpload: 'Video yuklash',
  videoReplace: 'Qayta yozib yuklash',
  videoDelete: 'Videoni oʻchirish',
  videoFormats: 'MP4, MOV yoki WEBM · 100 MB gacha · 1–3 daqiqa',
  videoEmpty: 'Video hali yuklanmagan',
  videoUploading: 'Yuklanmoqda… {n}%',
  videoStatusPending: 'Moderator tekshiruvida',
  videoStatusPendingText: 'Tekshiruv odatda 2 ish kunigacha davom etadi. Tasdiqlangach videoni barcha oʻquvchilar koʻradi.',
  videoStatusApproved: 'Video tasdiqlangan',
  videoStatusApprovedText: 'Video profilingizda chop etilgan va oʻquvchilarga koʻrinadi.',
  videoStatusRejected: 'Video rad etilgan',
  videoModerationNote: 'Videoni FalaRus administratori tekshiradi. Oʻquvchilarga u faqat tasdiqlangach koʻrinadi.',
  videoQuestionsTitle: 'Nima haqida gapirish kerak',
  charsLeft: '{n} / 1000',
  previewHint: 'Profilingiz oʻquvchilarga shunday koʻrinadi. Pasport, telefon va email koʻrsatilmaydi.',
  openFullPreview: 'Toʻliq koʻrinishni ochish',

  /* ── Profil ─────────────────────────────────────────────────────────── */
  profileTitle: 'Mening profilim',
  profileSubtitle: 'Ichki maʼlumotlarni faqat moderatorlar koʻradi, ommaviy qismini — oʻquvchilar',
  viewAsStudent: 'Oʻquvchi koʻzi bilan koʻrish',
  stDraftTitle: 'Anketa qoralamasi',
  stDraftText: 'Anketani toʻldirib boʻling va tekshiruvga yuboring.',
  stDraftCta: 'Toʻldirishni davom ettirish',
  stReviewTitle: 'Profil tekshiruvda',
  stReviewText: 'Hujjatlar, video va taʼlim maʼlumotlari tekshirilmoqda. Odatda 3 ish kunigacha.',
  stReviewCta: 'Anketani koʻrish',
  stActiveTitle: 'Profil tasdiqlangan',
  stActiveText: 'Profilingiz chop etilgan va oʻquvchilarga koʻrinadi.',
  stActiveCta: 'Oʻquvchi koʻzi bilan koʻrish',
  stRejectedTitle: 'Profil rad etilgan',
  stRejectedCta: 'Profilni tuzatish',
  stPausedTitle: 'Profil toʻxtatilgan',
  stPausedText: 'Profil vaqtincha oʻquvchilarga koʻrinmaydi. FalaRus qoʻllab-quvvatlash xizmatiga yozing.',
  stPausedCta: 'Qoʻllab-quvvatlashga yozish',
  editAnketa: 'Anketani tahrirlash',
  myDocuments: 'Mening hujjatlarim',
  publicPart: 'Profilning ommaviy qismi',
  publicPartHint: 'oʻquvchilar koʻradi',
  privatePart: 'Yopiq qism',
  privatePartHint: 'faqat siz va moderatorlar',
  fieldSpecialization: 'Mutaxassislik',
  fieldLevelsAge: 'Darajalar',
  fieldPrice: 'Kurs narxi',
  fieldVideo: 'Video-taqdimot',
  videoUploaded: 'Yuklangan',
  videoMissing: 'Yuklanmagan',
  fieldPassport: 'Pasport',
  fieldContacts: 'Aloqa',
  notFilled: 'Toʻldirilmagan',
  filledPercent: '{pct}% toʻldirilgan',
  ofSteps: '{done} / {total}',
  continueFilling: 'Toʻldirishni davom ettirish',
  ratingTitle: 'Reyting',
  noRatingYet: 'Hozircha baho yoʻq',
  reviewsCount: '{n} ta sharh',

  /* ── Ommaviy ko'rinish ──────────────────────────────────────────────── */
  previewBanner: 'Koʻrib chiqish · profilingiz oʻquvchilarga shunday koʻrinadi',
  exitPreview: 'Koʻrishdan chiqish',
  aboutTeacher: 'Oʻqituvchi haqida',
  educationBlock: 'Taʼlim',
  experienceBlock: 'Ish tajribasi',
  certificatesBlock: 'Sertifikat va yutuqlar',
  reviewsBlock: 'Oʻquvchilar sharhi',
  speaks: 'Tillar',
  yearsExp: '{n} yil tajriba',
  lessonsDoneShort: '{n} ta dars',
  trialFree: 'Sinov darsi · 30 daqiqa',
  bookTrial: 'Sinov darsiga yozilish',
  writeTeacher: 'Oʻqituvchiga yozish',
  teacherStats: 'Oʻqituvchi statistikasi',
  emptyAbout: '«Oʻzim haqimda» boʻlimi hali toʻldirilmagan',

  /* ── Daromad ────────────────────────────────────────────────────────── */
  incomeTitle: 'Daromad',
  incomeMonth: 'Shu oy',
  incomeFromTrials: 'Sinov darslaridan',
  incomeManual: 'Qoʻlda kiritilgan',
  incomeAuto: 'avtomatik',
  incomeManualHint: 'oylik kurs va boshqa',
  incomeLast6: 'Oxirgi 6 oy',
  incomeAdd: 'Daromad qoʻshish',
  incomeAmount: 'Summa (soʻm)',
  incomeDate: 'Sana',
  incomeNote: 'Izoh',
  incomeEmpty: 'Hozircha yozuv yoʻq',

  /* ── Obuna ──────────────────────────────────────────────────────────── */
  subscriptionTitle: 'Obuna',
  subscriptionSubtitle: 'Obuna faol boʻlsa, profilingiz qidiruvda oʻquvchilarga koʻrinadi',
  subActive: 'Obuna faol',
  subActiveUntil: '{date} gacha faol · {days} kun qoldi',
  subInactive: 'Obuna faol emas',
  subInactiveText: 'Profil oʻqituvchilar qidiruvida koʻrinmaydi.',
  subFreeLessons: 'Bepul sinov darslari: {used} / {limit}',
  subFreeHint: 'Birinchi {limit} ta sinov darsi obunasiz oʻtadi.',
  subRenew: 'Obunani uzaytirish',
  subHistory: 'Toʻlovlar tarixi',
  subEmpty: 'Hozircha toʻlov boʻlmagan',
  subEndsIn: 'Obuna {days} kundan keyin tugaydi',
  subEndsHint: 'Yangi oʻquvchilar kelishda davom etishi uchun obunani oldindan uzaytiring.',

  /* ── Xabarlar ───────────────────────────────────────────────────────── */
  messagesTitle: 'Xabarlar',
  messagesEmpty: 'Hozircha yozishmalar yoʻq',
  messagesHint: 'Chat oʻquvchi sinov darsini toʻlagach ochiladi',
  chooseChat: 'Yozishmani tanlang',
  messagePlaceholder: 'Xabar…',
  send: 'Yuborish',

  /* ── Sharhlar ───────────────────────────────────────────────────────── */
  reviewsTitle: 'Sharhlar',
  reviewsEmpty: 'Hozircha sharh yoʻq',
  reviewsHint: 'Oʻquvchi sinov darsi tugagach sharh qoldiradi',
  reviewLiked: 'Nima yoqdi',
  reviewMissing: 'Nima yetishmadi',
  reviewEnrolled: 'Kursga yozildi',
  reviewNotEnrolled: 'Yozilmadi',

  /* ── Onlayn dars ────────────────────────────────────────────────────── */
  classTitle: 'Onlayn dars',
  classSubtitle: 'FalaRus video xonasi — oʻquvchi ham shu havoladan kiradi',
  classNoRoom: 'Video xona hali berilmagan',
  classNoRoomHint: 'Xonani FalaRus administratori ochadi. Kerak boʻlsa qoʻllab-quvvatlashga yozing.',
  classEnter: 'Xonaga kirish',
  classSessions: 'Rejalashtirilgan darslar',
  classAddSession: 'Dars qoʻshish',
  classSessionTitle: 'Nomi',
  classSessionStart: 'Boshlanishi',
  classSessionDuration: 'Davomiyligi (daq)',
  classNoSessions: 'Rejalashtirilgan dars yoʻq',
  classJoin: 'Kirish',
  classCopyLink: 'Havolani nusxalash',
  classLinkCopied: 'Havola nusxalandi',

  /* ── Hujjatlar ──────────────────────────────────────────────────────── */
  documentsTitle: 'Hujjatlar',
  documentsSubtitle: 'JPG, PNG, WEBP yoki PDF · 8 MB gacha · moderator tekshiradi',
  docPassport: 'Pasport',
  docDiploma: 'Diplom',
  docCertificate: 'Sertifikat',
  docOther: 'Boshqa',
  docAdd: '+ {kind}',
  docPending: 'Tekshiruvda',
  docApproved: 'Tasdiqlangan',
  docRejected: 'Rad etilgan',
  documentsEmpty: 'Hujjat hali yuklanmagan',
  uploaded: 'Yuklangan',

  /* ── Sozlamalar va yordam ───────────────────────────────────────────── */
  settingsTitle: 'Sozlamalar',
  settingsLanguage: 'Panel tili',
  settingsAccount: 'Hisob',
  accEdit: 'Mening maʼlumotlarim',
  accSaved: 'Maʼlumotlar saqlandi',
  passTitle: 'Parolni almashtirish',
  passCurrent: 'Joriy parol',
  passNew: 'Yangi parol',
  passRepeat: 'Yangi parolni takrorlang',
  passChange: 'Parolni almashtirish',
  passChanged: 'Parol almashtirildi',
  accPhoto: 'Profil surati',
  settingsPhone: 'Telefon',
  settingsEmail: 'Email',
  settingsPassword: 'Parol',
  settingsPasswordHint: 'Parolni almashtirish havolasi pochtangizga yuboriladi',
  settingsPasswordSend: 'Havola yuborish',
  settingsPasswordSent: 'Havola pochtaga yuborildi',
  settingsPasswordNoEmail: 'Hisobga pochta biriktirilmagan — qoʻllab-quvvatlashga yozing',
  logout: 'Hisobdan chiqish',
  helpTitle: 'Yordam',
  helpSubtitle: 'Oʻqituvchilar koʻp soʻraydigan savollar',
  helpContact: 'Qoʻllab-quvvatlashga yozish',
  helpQ1: 'Oʻquvchilar meni qanday topadi?',
  helpA1:
    'Oʻquvchi «Oʻqituvchilar» boʻlimini ochadi, daraja va mutaxassislik boʻyicha saralaydi va sinov darsiga yoziladi. Qidiruvda faqat tasdiqlangan va obunasi faol profillar koʻrinadi.',
  helpQ2: 'Oʻquvchi qachon dars band qila oladi?',
  helpA2:
    'Faqat «Jadval» boʻlimida boʻsh deb belgilagan soatlaringizda. Band qilingan vaqt avtomatik ravishda band boʻlib qoladi.',
  helpQ3: 'Sinov darsi qanday oʻtadi?',
  helpA3:
    'Toʻlovdan keyin oʻquvchi bilan chat va video xona ochiladi. Darsdan soʻng hisobotni toʻldiring — oʻquvchiga sharh soʻrovi boradi.',
  helpQ4: 'Pulni qachon olaman?',
  helpA4:
    'Sinov darsi toʻlovi FalaRus orqali oʻtadi. Oylik kurs toʻlovini toʻgʻridan-toʻgʻri olasiz va uni «Daromad» boʻlimiga yozib qoʻyasiz.',

  /* ── Kirish ─────────────────────────────────────────────────────────── */
  gateTitle: 'Oʻqituvchi kabineti',
  gateText: 'Kabinetni ochish uchun oʻqituvchi hisobingizga kiring.',
  gateLogin: 'Kirish',
  gateRegister: 'Oʻqituvchi boʻlish',
  gateStudentTitle: 'Bu boʻlim oʻqituvchilar uchun',
  gateStudentText: 'Siz oʻquvchi hisobi bilan kirgansiz. Oʻqituvchi kabineti alohida hisob bilan ochiladi.',
  gateHome: 'Bosh sahifaga',
};

export const PANEL_TEXTS = { ru, uz } as const;

export type PanelLang = keyof typeof PANEL_TEXTS;

/** `{key}` o'rniga qiymat qo'yadi: tpl('{n} ta dars', { n: 5 }). */
export function tpl(text: string, vars: Record<string, string | number>): string {
  return text.replace(/\{(\w+)\}/g, (_, k: string) =>
    vars[k] == null ? '' : String(vars[k])
  );
}

/** Hafta kunlari — 0 = yakshanba (Postgres `dow` bilan bir xil). */
export const WEEKDAYS: Record<PanelLang, string[]> = {
  ru: ['Воскресенье', 'Понедельник', 'Вторник', 'Среда', 'Четверг', 'Пятница', 'Суббота'],
  uz: ['Yakshanba', 'Dushanba', 'Seshanba', 'Chorshanba', 'Payshanba', 'Juma', 'Shanba'],
};

export const WEEKDAYS_SHORT: Record<PanelLang, string[]> = {
  ru: ['Вс', 'Пн', 'Вт', 'Ср', 'Чт', 'Пт', 'Сб'],
  uz: ['Yak', 'Du', 'Se', 'Cho', 'Pay', 'Ju', 'Sha'],
};

export const MONTHS: Record<PanelLang, string[]> = {
  ru: [
    'января',
    'февраля',
    'марта',
    'апреля',
    'мая',
    'июня',
    'июля',
    'августа',
    'сентября',
    'октября',
    'ноября',
    'декабря',
  ],
  uz: [
    'yanvar',
    'fevral',
    'mart',
    'aprel',
    'may',
    'iyun',
    'iyul',
    'avgust',
    'sentabr',
    'oktabr',
    'noyabr',
    'dekabr',
  ],
};

/** Anketadagi mutaxassislik variantlari (prototipdagi chiplar). */
export const SUBJECT_OPTIONS: Record<PanelLang, string[]> = {
  ru: [
    'Русский с нуля',
    'Разговорный русский',
    'Грамматика',
    'Произношение',
    'Русский для работы',
    'Русский для жизни в России',
    'Русский для мигрантов',
    'Русский для детей',
    'Подготовка к экзаменам',
    'Подготовка к патенту',
  ],
  uz: [
    'Noldan rus tili',
    'Soʻzlashuv rus tili',
    'Grammatika',
    'Talaffuz',
    'Ish uchun rus tili',
    'Rossiyada yashash uchun',
    'Migrantlar uchun',
    'Bolalar uchun',
    'Imtihonga tayyorgarlik',
    'Patentga tayyorgarlik',
  ],
};

export const LEVEL_OPTIONS = ['A0', 'A1', 'A2', 'B1', 'B2', 'C1', 'C2'];

export const LANGUAGE_OPTIONS: Record<PanelLang, string[]> = {
  ru: ['Русский', 'Узбекский', 'Английский', 'Казахский', 'Таджикский', 'Каракалпакский'],
  uz: ['Rus tili', 'Oʻzbek tili', 'Ingliz tili', 'Qozoq tili', 'Tojik tili', 'Qoraqalpoq tili'],
};

/** Video-taqdimotda nima aytish kerakligi (11-qadam). */
export const VIDEO_QUESTIONS: Record<PanelLang, string[]> = {
  ru: [
    'Как вас зовут и как к вам обращаться?',
    'Откуда вы и где сейчас живёте?',
    'Где вы учились и какая у вас специальность?',
    'Сколько лет вы преподаёте и где работали?',
    'С какими учениками и уровнями работаете?',
    'Как проходит ваш урок?',
    'Что ученик получит после занятий с вами?',
  ],
  uz: [
    'Ismingiz nima, sizga qanday murojaat qilishadi?',
    'Qayerdansiz va hozir qayerda yashaysiz?',
    'Qayerda oʻqigansiz, mutaxassisligingiz nima?',
    'Necha yildan beri dars berasiz, qayerda ishlagansiz?',
    'Qanday oʻquvchilar va darajalar bilan ishlaysiz?',
    'Darsingiz qanday oʻtadi?',
    'Oʻquvchi siz bilan oʻqigach nimaga erishadi?',
  ],
};
