import test from 'node:test';
import assert from 'node:assert/strict';
import { readFile } from 'node:fs/promises';
import { PGlite } from '@electric-sql/pglite';
import { money, dueDate, paymentFits, receiptFile } from '../server/operator/domain.js';
test('operator money/date validation preserves currency minor units and real Tashkent dates', () => {
    assert.equal(money('100,25'), '100.25');
    for (const x of ['1e3', '0', '-1', 'NaN', '1.999', '1000000000000'])
        assert.throws(() => money(x));
    assert.equal(paymentFits('50.01', '100.02', '50.01'), true);
    assert.equal(paymentFits('50.02', '100.02', '50.01'), false);
    assert.equal(dueDate('2027-01-01 15:30', 0), '2027-01-01T10:30:00.000Z');
    for (const d of ['2027-02-30 15:30', '2027-01-01 25:10', '2027-01-01'])
        assert.throws(() => dueDate(d, 0));
    assert.throws(() => dueDate('2020-01-01 10:00'));
    assert.throws(() => receiptFile({ document: { file_id: 'a', file_unique_id: 'b', file_size: 100, mime_type: 'text/html' } }));
    assert.equal(receiptFile({ photo: [{ file_id: 'a', file_unique_id: 'b', file_size: 100 }] }).mime, 'image/jpeg');
});
test('isolated operator ledger: pending/rejected do not settle debt, duplicate receipts prohibited, audit immutable', async () => {
    const db = await PGlite.create();
    try {
        await db.exec(`CREATE TABLE users(id bigint PRIMARY KEY);CREATE TABLE admins(id bigint PRIMARY KEY);CREATE TABLE payments(id bigint PRIMARY KEY);INSERT INTO users VALUES(1);INSERT INTO admins VALUES(1);`);
        await db.exec(await readFile(new URL('../server/operator/schema.sql', import.meta.url), 'utf8'));
        // Applying the additive migration twice is safe.
        await db.exec(await readFile(new URL('../server/operator/schema.sql', import.meta.url), 'utf8'));
        await db.exec(`INSERT INTO operator_accounts(login,name,password_hash) VALUES('operator','Operator','hash');
   INSERT INTO operator_contracts(user_id,operator_id,tariff,currency,total,source,due_at) VALUES(1,1,'three_month','RUB',1000,'Instagram',now());
   INSERT INTO operator_receipts(contract_id,operator_id,amount,file_id,file_unique_id,mime) VALUES(1,1,500,'file','unique','image/jpeg');`);
        const balance = async () => (await db.query<any>('SELECT paid,debt,pending FROM operator_balances')).rows[0];
        assert.deepEqual(await balance(), { paid: '0', debt: '1000.00', pending: '500.00' });
        await assert.rejects(db.exec(`INSERT INTO operator_receipts(contract_id,operator_id,amount,file_id,file_unique_id,mime) VALUES(1,1,500,'file','unique','image/jpeg')`));
        await db.exec("UPDATE operator_receipts SET status='rejected' WHERE id=1");
        assert.equal((await balance()).debt, '1000.00');
        await db.exec("UPDATE operator_receipts SET status='approved' WHERE id=1");
        assert.equal((await balance()).debt, '500.00');
        await db.exec(`INSERT INTO operator_audit(operator_id,user_id,action) VALUES(1,1,'receipt_submitted')`);
        await assert.rejects(db.exec('DELETE FROM operator_audit'));
        await assert.rejects(db.exec("UPDATE operator_audit SET action='fake'"));
        await db.exec(`INSERT INTO operator_outbox(method,payload,dedupe) VALUES('sendMessage','{}','due:1') ON CONFLICT DO NOTHING;INSERT INTO operator_outbox(method,payload,dedupe) VALUES('sendMessage','{}','due:1') ON CONFLICT DO NOTHING;`);
        assert.equal((await db.query<any>('SELECT count(*) n FROM operator_outbox')).rows[0].n, 1);
    }
    finally {
        await db.close();
    }
});
test('operator conversation + admin workflow: authorization, replay, installments, freeze and reports', async () => {
    process.env.DATABASE_URL = 'postgresql://test:test@127.0.0.1:1/test';
    process.env.OPERATOR_BOT_ENABLED = 'true';
    const db = await PGlite.create();
    const { pool } = await import('../server/lib/db.js');
    assert.ok(pool);
    const originalConnect = pool.connect, originalQuery = pool.query;
    const adapter = async (sql: string, args: any[] = []) => { const r = await db.query(sql, args); return { ...r, rowCount: r.rows.length || r.affectedRows || 0 }; };
    (pool as any).query = adapter;
    (pool as any).connect = async () => ({ query: adapter, release() { } });
    try {
        await db.exec(`CREATE TABLE users(id bigserial PRIMARY KEY,first_name text,last_name text,phone text UNIQUE,phone_raw text,phone_normalized text UNIQUE,country_code text,phone_verified boolean,phone_invalid boolean,account_type text,onboarded integer,email text UNIQUE,password text DEFAULT 'original',plan_name text,plan_expires_at timestamptz,created_at timestamptz DEFAULT now());
   CREATE TABLE admins(id bigint PRIMARY KEY);CREATE TABLE payments(id bigint PRIMARY KEY);
   CREATE TABLE leaderboard(user_id bigint PRIMARY KEY,total_points integer,rank integer,updated_at timestamptz);
   CREATE TABLE subscriptions(id bigserial PRIMARY KEY,user_id bigint,plan_type text,expires_at timestamptz,status text,started_at timestamptz DEFAULT now());
   INSERT INTO users(id,first_name,last_name,phone,email) VALUES(1,'Test','Mijoz','+998900000000','synthetic@example.invalid');INSERT INTO admins VALUES(1);`);
        await db.exec(await readFile(new URL('../server/operator/schema.sql', import.meta.url), 'utf8'));
        const bcrypt = (await import('bcryptjs')).default;
        await db.query('INSERT INTO operator_accounts(login,name,password_hash) VALUES($1,$2,$3)', ['op1', 'Operator One', await bcrypt.hash('Testpassword123!', 4)]);
        const { handleUpdate } = await import('../server/operator/service.js');
        const { decideReceipt } = await import('../server/operator/admin.js');
        const { reminders, serviceAuthorized } = await import('../server/operator/routes.js');
        assert.equal(serviceAuthorized('Bearer bad', 'x'.repeat(32)), false);
        assert.equal(serviceAuthorized('Bearer ' + 'x'.repeat(32), 'x'.repeat(32)), true);
        let id = 100;
        const send = async (text: string, tg = 123) => { const u = { update_id: id++, message: { message_id: id, chat: { id: tg, type: 'private' }, from: { id: tg }, text } }; await handleUpdate(u); return u; };
        const click = async (action: string, tg = 123) => { const u = { update_id: id++, callback_query: { id: String(id), from: { id: tg }, data: action, message: { message_id: id, chat: { id: tg, type: 'private' } } } }; await handleUpdate(u); return u; };
        const count = async (table: string) => (await db.query<any>(`SELECT count(*) n FROM ${table}`)).rows[0].n;
        await click('list:0');
        assert.equal(await count('operator_audit'), 0); // unauthorized search only prompts login
        await send('op1');
        await send('Testpassword123!');
        assert.equal((await db.query<any>('SELECT operator_id FROM operator_sessions WHERE telegram_id=123')).rows[0].operator_id, 1);
        await click('list:0');
        await click('user:1');
        await click('new:1');
        await click('tariff:three_month');
        await click('source:Instagram');
        await click('currency:RUB');
        await send('1000');
        await send('500');
        await send('2027-12-01 10:00');
        const receipt = async (unique: string) => handleUpdate({ update_id: id++, message: { message_id: id, chat: { id: 123, type: 'private' }, from: { id: 123 }, photo: [{ file_id: 'file-' + unique, file_unique_id: unique, file_size: 1024 }] } });
        await receipt('one');
        const submitted = await click('submit');
        assert.equal(await count('operator_receipts'), 1, JSON.stringify((await db.query('SELECT payload FROM operator_outbox ORDER BY id DESC LIMIT 4')).rows));
        assert.equal(await count('subscriptions'), 0, 'operator submission cannot activate tariff');
        await handleUpdate(submitted);
        await click('submit');
        assert.equal(await count('operator_receipts'), 1, 'replayed update and double click do not duplicate');
        await decideReceipt(1, 1, 'approved', '');
        assert.equal(await count('subscriptions'), 1);
        const expiry = (await db.query<any>('SELECT plan_expires_at FROM users')).rows[0].plan_expires_at;
        await assert.rejects(decideReceipt(1, 1, 'approved', ''));
        await click('settle:1');
        await send('500');
        await receipt('two');
        await click('submit');
        assert.equal((await db.query<any>('SELECT debt FROM operator_balances')).rows[0].debt, '500.00');
        await decideReceipt(2, 1, 'rejected', 'Wrong receipt');
        assert.equal((await db.query<any>('SELECT debt FROM operator_balances')).rows[0].debt, '500.00');
        await db.exec("UPDATE operator_contracts SET due_at=now()-interval '4 days'");
        await reminders();
        await reminders();
        assert.equal((await db.query<any>("SELECT count(*) n FROM operator_outbox WHERE dedupe LIKE 'overdue:%'")).rows[0].n, 1);
        await click('freeze:1');
        await send('Qarz muddati to‘rt kun o‘tgan');
        assert.equal(await count('operator_freezes'), 1);
        await click('unfreeze:1');
        await send('To‘lov kutilmoqda');
        assert.equal(await count('operator_freezes'), 1, 'unpaid debt cannot be marked settled by operator');
        await click('settle:1');
        await send('500');
        await receipt('three');
        await click('submit');
        await decideReceipt(3, 1, 'approved', '');
        assert.equal((await db.query<any>('SELECT debt FROM operator_balances')).rows[0].debt, '0.00');
        assert.equal(await count('subscriptions'), 1, 'installment does not extend tariff again');
        assert.deepEqual((await db.query<any>('SELECT plan_expires_at FROM users')).rows[0].plan_expires_at, expiry);
        await click('unfreeze:1');
        await send('Admin to‘lovni tasdiqladi');
        assert.equal(await count('operator_freezes'), 0);
        await click('report');
        await click('report:today');
        await click('debts');
        const { operatorAdminRoutes } = await import('../server/operator/admin.js');
        const adminRouter = operatorAdminRoutes();
        const invoke = (path: string, query: any) => new Promise<any>((resolve, reject) => {
            const layer = (adminRouter as any).stack.find((x: any) => x.route?.path === path);
            layer.route.stack[0].handle({query, adminId: 1}, {json: resolve, status: (status: number) => ({json: (body: any) => reject(new Error(status + ':' + JSON.stringify(body)))})}, reject);
        });
        const overview = await invoke('/overview', {});
        assert.equal(overview.rows.length, 3);
        assert.equal(overview.summary.find((r: any) => r.status === 'approved').amount, '1000.00');
        assert.equal(overview.debts[0].debt, '0.00');
        const filtered = await invoke('/overview', {status: 'approved', source: 'Instagram', tariff: 'three_month', from: '2026-01-01', to: '2028-01-01'});
        assert.equal(filtered.rows.length, 2);
        assert.ok((await invoke('/audit', {})).length > 0);
        const { issueOperatorReset, consumeOperatorReset } = await import('../server/operator/passwordReset.js');
        const { transaction } = await import('../server/operator/service.js');
        const link = await transaction(c => issueOperatorReset(c, 1, 1));
        const token = new URLSearchParams(new URL(link).hash.slice(1)).get('token')!;
        assert.equal((await db.query<any>('SELECT password FROM users WHERE id=1')).rows[0].password, 'original', 'issuing link does not lock customer out');
        await assert.rejects(transaction(c => issueOperatorReset(c, 1, 1)), /15 daqiqa/);
        await consumeOperatorReset(token, 'NewSecurePassword2026!');
        const stored = (await db.query<any>('SELECT password FROM users WHERE id=1')).rows[0].password;
        assert.ok(await bcrypt.compare('NewSecurePassword2026!', stored));
        await assert.rejects(consumeOperatorReset(token, 'AnotherSecurePassword2026!'), /yaroqsiz/);
        await db.exec("UPDATE operator_password_resets SET created_at=now()-interval '1 hour'");
        const expiredLink = await transaction(c => issueOperatorReset(c, 1, 1));
        await db.exec("UPDATE operator_password_resets SET expires_at=now()-interval '1 second'");
        await assert.rejects(consumeOperatorReset(new URLSearchParams(new URL(expiredLink).hash.slice(1)).get('token')!, 'SecurePassword2026!'), /yaroqsiz/);
        // New students are real platform users, with a separate pending payment.
        await db.exec("SELECT setval(pg_get_serial_sequence('users','id'),100)");
        const usersBefore = await count('users');
        await click('create_customer', 789);
        await send('Blocked outsider', 789);
        assert.equal(await count('users'), usersBefore);
        await click('create_customer');
        await send('Yangi'); await send('Oquvchi');
        await send('wrong phone');
        assert.equal((await db.query<any>('SELECT state FROM operator_sessions WHERE telegram_id=123')).rows[0].state.step, 'customer_phone');
        await send('+998 90 123 45 67'); await send('yangi@example.invalid');
        await click('menu');
        assert.equal(await count('users'), usersBefore, 'cancelled draft creates no account');
        await click('create_customer'); await send('Yangi'); await send('Oquvchi');
        await send('+998901234567'); await send('YANGI@example.invalid');
        const creation = await click('customer_confirm');
        await handleUpdate(creation); await click('customer_confirm');
        assert.equal(await count('users'), usersBefore + 1, 'replayed confirmation creates only one student');
        const student = (await db.query<any>("SELECT * FROM users WHERE email='yangi@example.invalid'")).rows[0];
        assert.equal(student.account_type, 'student');
        assert.equal(student.phone_normalized, '+998901234567');
        assert.equal(student.plan_expires_at, null);
        assert.equal((await db.query<any>("SELECT count(*) n FROM operator_audit WHERE user_id=$1 AND operator_id=1 AND action='customer_created'", [student.id])).rows[0].n, 1);
        const message = (await db.query<any>("SELECT payload FROM operator_outbox WHERE dedupe=$1", ['reset-link:' + creation.update_id])).rows[0].payload.text;
        const studentToken = message.match(/#token=([A-Za-z0-9_-]{43})/)[1];
        await consumeOperatorReset(studentToken, 'StudentPassword2026!');
        assert.ok(await bcrypt.compare('StudentPassword2026!', (await db.query<any>('SELECT password FROM users WHERE id=$1', [student.id])).rows[0].password));
        await click('tariff:six_month'); await click('source:Telegram'); await click('currency:UZS');
        await send('2000000'); await send('1000000'); await send('2027-12-01 10:00');
        await receipt('new-student-receipt'); await click('submit');
        const newReceipt = (await db.query<any>('SELECT r.id,c.operator_id,c.due_at,r.status FROM operator_receipts r JOIN operator_contracts c ON c.id=r.contract_id WHERE c.user_id=$1', [student.id])).rows[0];
        assert.equal(newReceipt.status, 'pending');
        assert.equal(newReceipt.operator_id, 1);
        assert.ok(newReceipt.due_at);
        assert.equal((await db.query<any>('SELECT plan_expires_at FROM users WHERE id=$1', [student.id])).rows[0].plan_expires_at, null);
        await decideReceipt(Number(newReceipt.id), 1, 'approved', '');
        assert.ok((await db.query<any>('SELECT plan_expires_at FROM users WHERE id=$1', [student.id])).rows[0].plan_expires_at);
        await click('create_customer'); await send('Takror'); await send('Mijoz');
        await send('+998 90 123 45 67'); await send('-'); await click('customer_confirm');
        assert.equal(await count('users'), usersBefore + 1, 'formatted duplicate phone reuses existing user');
        await click('create_customer'); await send('Boshqa'); await send('Mijoz');
        await send('+998901234568'); await send('YANGI@example.invalid'); await click('customer_confirm');
        assert.equal(await count('users'), usersBefore + 1, 'duplicate email does not create a second account');
        // Operator cannot bind the same login from another Telegram account.
        await send('/start', 456);
        await send('op1', 456);
        await send('Testpassword123!', 456);
        assert.equal((await db.query<any>('SELECT operator_id FROM operator_sessions WHERE telegram_id=456')).rows[0].operator_id, null);
        await db.exec('UPDATE operator_accounts SET active=false WHERE id=1');
        await click('list:0');
        assert.equal((await db.query<any>('SELECT operator_id FROM operator_sessions WHERE telegram_id=123')).rows[0].operator_id, null);
    }
    finally {
        (pool as any).query = originalQuery;
        (pool as any).connect = originalConnect;
        await pool.end();
        await db.close();
    }
});
