import test from 'node:test';
import assert from 'node:assert/strict';
import { readFile, mkdtemp, rm } from 'node:fs/promises';
import { tmpdir } from 'node:os';
import { join } from 'node:path';
import { PGlite } from '@electric-sql/pglite';
import { money, dueDate, paymentFits, receiptFile } from '../server/operator/domain.js';
test('operator money/date validation preserves currency minor units and real Tashkent dates', () => {
    assert.equal(money('100,25'), '100.25');
    for (const x of ['1e3', '0', '-1', 'NaN', '1.999', '1000000000000'])
        assert.throws(() => money(x));
    assert.equal(paymentFits('50.01', '100.02', '50.01'), true);
    assert.equal(paymentFits('50.02', '100.02', '50.01'), false);
    assert.equal(dueDate('2027-01-01 15:30', 0), '2027-01-01T10:30:00.000Z');
    for (const d of ['2027-02-30 15:30', '2027-01-01 25:10', '2027-01-01'])
        assert.throws(() => dueDate(d, 0));
    assert.throws(() => dueDate('2020-01-01 10:00'));
    assert.throws(() => receiptFile({ document: { file_id: 'a', file_unique_id: 'b', file_size: 100, mime_type: 'text/html' } }));
    assert.equal(receiptFile({ photo: [{ file_id: 'a', file_unique_id: 'b', file_size: 100 }] }).mime, 'image/jpeg');
});
test('isolated operator ledger: pending/rejected do not settle debt, duplicate receipts prohibited, audit immutable', async () => {
    const db = await PGlite.create();
    try {
        await db.exec(`CREATE TABLE users(id bigint PRIMARY KEY);CREATE TABLE admins(id bigint PRIMARY KEY);CREATE TABLE payments(id bigint PRIMARY KEY);INSERT INTO users VALUES(1);INSERT INTO admins VALUES(1);`);
        await db.exec(await readFile(new URL('../db/migrations/201_operator_debt_deferrals.sql', import.meta.url), 'utf8'));
        assert.equal((await db.query<any>("SELECT to_regclass('operator_debt_deferrals') table_name")).rows[0].table_name,null,'generic migrations can run without the optional operator ledger');
        await db.exec(await readFile(new URL('../server/operator/schema.sql', import.meta.url), 'utf8'));
        await db.exec(await readFile(new URL('../db/migrations/201_operator_debt_deferrals.sql', import.meta.url), 'utf8'));
        await db.exec(await readFile(new URL('../db/migrations/201_operator_debt_deferrals.sql', import.meta.url), 'utf8'));
        // Applying the additive migration twice is safe.
        await db.exec(await readFile(new URL('../server/operator/schema.sql', import.meta.url), 'utf8'));
        await db.exec(`INSERT INTO operator_accounts(login,name,password_hash) VALUES('operator','Operator','hash');
   INSERT INTO operator_contracts(user_id,operator_id,tariff,currency,total,source,due_at) VALUES(1,1,'three_month','RUB',1000,'Instagram',now());
   INSERT INTO operator_receipts(contract_id,operator_id,amount,file_id,file_unique_id,mime) VALUES(1,1,500,'file','unique','image/jpeg');`);
        const balance = async () => (await db.query<any>('SELECT paid,debt,pending FROM operator_balances')).rows[0];
        assert.deepEqual(await balance(), { paid: '0', debt: '1000.00', pending: '500.00' });
        await assert.rejects(db.exec(`INSERT INTO operator_receipts(contract_id,operator_id,amount,file_id,file_unique_id,mime) VALUES(1,1,500,'file','unique','image/jpeg')`));
        await db.exec("UPDATE operator_receipts SET status='rejected' WHERE id=1");
        assert.equal((await balance()).debt, '1000.00');
        await db.exec("UPDATE operator_receipts SET status='approved' WHERE id=1");
        assert.equal((await balance()).debt, '500.00');
        await db.exec(`INSERT INTO operator_audit(operator_id,user_id,action) VALUES(1,1,'receipt_submitted')`);
        await assert.rejects(db.exec('DELETE FROM operator_audit'));
        await assert.rejects(db.exec("UPDATE operator_audit SET action='fake'"));
        await db.exec(`INSERT INTO operator_outbox(method,payload,dedupe) VALUES('sendMessage','{}','due:1') ON CONFLICT DO NOTHING;INSERT INTO operator_outbox(method,payload,dedupe) VALUES('sendMessage','{}','due:1') ON CONFLICT DO NOTHING;`);
        assert.equal((await db.query<any>('SELECT count(*) n FROM operator_outbox')).rows[0].n, 1);
    }
    finally {
        await db.close();
    }
});
test('operator conversation + admin workflow: authorization, replay, installments, freeze and reports', async () => {
    process.env.DATABASE_URL = 'postgresql://test:test@127.0.0.1:1/test';
    process.env.OPERATOR_BOT_ENABLED = 'true';
    const db = await PGlite.create();
    const { pool } = await import('../server/lib/db.js');
    assert.ok(pool);
    const originalConnect = pool.connect, originalQuery = pool.query;
    const receiptDir = await mkdtemp(join(tmpdir(), 'falarus-mini-receipts-'));
    process.env.OPERATOR_RECEIPT_DIR = receiptDir;
    let lastDbError: unknown;
    const adapter = async (sql: string, args: any[] = []) => {
        try { const r = await db.query(sql, args); return { ...r, rowCount: r.rows.length || r.affectedRows || 0 }; }
        catch (e) { lastDbError = e; throw e; }
    };
    (pool as any).query = adapter;
    (pool as any).connect = async () => ({ query: adapter, release() { } });
    try {
        await db.exec(`CREATE TABLE users(id bigserial PRIMARY KEY,first_name text,last_name text,phone text UNIQUE,phone_raw text,phone_normalized text UNIQUE,country_code text,phone_verified boolean,phone_invalid boolean,account_type text,onboarded integer,email text UNIQUE,password text DEFAULT 'original',plan_name text,plan_expires_at timestamptz,created_at timestamptz DEFAULT now());
   CREATE TABLE admins(id bigint PRIMARY KEY);CREATE TABLE payments(id bigint PRIMARY KEY,user_id bigint,amount numeric,currency text,tariff_type text,payment_channel text,status text,product_code text,payment_time timestamptz,created_at timestamptz DEFAULT now());
   CREATE TABLE sales_crm_agents(id bigserial PRIMARY KEY,login text,name text,password_hash text,active boolean,role text);
   CREATE TABLE leaderboard(user_id bigint PRIMARY KEY,total_points integer,rank integer,updated_at timestamptz);
   CREATE TABLE subscriptions(id bigserial PRIMARY KEY,user_id bigint,plan_type text,expires_at timestamptz,status text,started_at timestamptz DEFAULT now());
   INSERT INTO users(id,first_name,last_name,phone,email) VALUES(1,'Test','Mijoz','+998900000000','synthetic@example.invalid');INSERT INTO admins VALUES(1);`);
        await db.exec(await readFile(new URL('../server/operator/schema.sql', import.meta.url), 'utf8'));
        await db.exec(await readFile(new URL('../db/migrations/204_operator_rahmat_attribution.sql', import.meta.url), 'utf8'));
        const bcrypt = (await import('bcryptjs')).default;
        await db.query('INSERT INTO operator_accounts(login,name,password_hash) VALUES($1,$2,$3)', ['op1', 'Operator One', await bcrypt.hash('Testpassword123!', 4)]);
        const { handleUpdate } = await import('../server/operator/service.js');
        const { decideReceipt } = await import('../server/operator/admin.js');
        const { reminders, serviceAuthorized } = await import('../server/operator/routes.js');
        assert.equal(serviceAuthorized('Bearer bad', 'x'.repeat(32)), false);
        assert.equal(serviceAuthorized('Bearer ' + 'x'.repeat(32), 'x'.repeat(32)), true);
        let id = 100;
        const send = async (text: string, tg = 123) => { const u = { update_id: id++, message: { message_id: id, chat: { id: tg, type: 'private' }, from: { id: tg }, text } }; await handleUpdate(u); return u; };
        const click = async (action: string, tg = 123) => { const u = { update_id: id++, callback_query: { id: String(id), from: { id: tg }, data: action, message: { message_id: id, chat: { id: tg, type: 'private' } } } }; await handleUpdate(u); return u; };
        const count = async (table: string) => (await db.query<any>(`SELECT count(*) n FROM ${table}`)).rows[0].n;
        await click('list:0');
        assert.equal(await count('operator_audit'), 0); // unauthorized search only prompts login
        await send('op1');
        await send('Testpassword123!');
        assert.equal((await db.query<any>('SELECT operator_id FROM operator_sessions WHERE telegram_id=123')).rows[0].operator_id, 1);
        await click('list:0');
        await click('user:1');
        await click('new:1');
        await click('tariff:three_month');
        await click('source:Instagram');
        await click('currency:RUB');
        await send('1000');
        await send('500');
        await send('2027-12-01 10:00');
        const receipt = async (unique: string) => handleUpdate({ update_id: id++, message: { message_id: id, chat: { id: 123, type: 'private' }, from: { id: 123 }, photo: [{ file_id: 'file-' + unique, file_unique_id: unique, file_size: 1024 }] } });
        await receipt('one');
        const submitted = await click('submit');
        assert.equal(await count('operator_receipts'), 1, JSON.stringify((await db.query('SELECT payload FROM operator_outbox ORDER BY id DESC LIMIT 4')).rows));
        assert.equal(await count('subscriptions'), 0, 'operator submission cannot activate tariff');
        await handleUpdate(submitted);
        await click('submit');
        assert.equal(await count('operator_receipts'), 1, 'replayed update and double click do not duplicate');
        await decideReceipt(1, 1, 'approved', '');
        assert.equal(await count('subscriptions'), 1);
        const expiry = (await db.query<any>('SELECT plan_expires_at FROM users')).rows[0].plan_expires_at;
        await assert.rejects(decideReceipt(1, 1, 'approved', ''));
        await click('settle:1');
        await send('500');
        await receipt('two');
        await click('submit');
        assert.equal((await db.query<any>('SELECT debt FROM operator_balances')).rows[0].debt, '500.00');
        await decideReceipt(2, 1, 'rejected', 'Wrong receipt');
        assert.equal((await db.query<any>('SELECT debt FROM operator_balances')).rows[0].debt, '500.00');
        await db.exec("UPDATE operator_contracts SET due_at='2026-01-01T00:00:00Z'");
        await reminders(new Date('2026-10-05T04:00:00Z'));
        await reminders(new Date('2026-10-05T04:00:00Z'));
        assert.equal((await db.query<any>("SELECT count(*) n FROM operator_outbox WHERE dedupe LIKE 'daily-debt:%'")).rows[0].n, 1);
        const { dueDebts } = await import('../server/operator/reminders.js');
        await db.exec("UPDATE operator_contracts SET due_at='2026-10-05T16:00:00Z'");
        assert.equal((await dueDebts(pool!, new Date('2026-10-05T04:00:00Z'), 1)).length, 1, 'later today is included');
        assert.equal((await dueDebts(pool!, new Date('2026-10-05T04:00:00Z'), 999)).length, 0, 'only assigned operator sees debt');
        await db.exec("UPDATE operator_contracts SET due_at='2026-10-05T19:00:00Z'");
        assert.equal((await dueDebts(pool!, new Date('2026-10-05T04:00:00Z'), 1)).length, 0, 'tomorrow Tashkent is excluded');
        await db.exec("UPDATE operator_contracts SET due_at='2026-01-01T00:00:00Z'");
        const reminderPayload = (await db.query<any>("SELECT payload FROM operator_outbox WHERE dedupe LIKE 'daily-debt:%'")).rows[0].payload;
        assert.match(reminderPayload.text, /Test Mijoz/);
        assert.match(reminderPayload.text, /\+998900000000/);
        assert.match(reminderPayload.text, /500.00/);
        await reminders(new Date('2026-10-05T09:00:00Z'));
        await reminders(new Date('2026-10-05T13:00:00Z'));
        await reminders(new Date('2026-10-05T14:00:00Z'));
        assert.equal((await db.query<any>("SELECT count(*) n FROM operator_outbox WHERE dedupe LIKE 'daily-debt:%'")).rows[0].n, 3);
        await reminders(new Date('2026-10-06T04:00:00Z'));
        assert.equal((await db.query<any>("SELECT count(*) n FROM operator_outbox WHERE dedupe LIKE 'daily-debt:%'")).rows[0].n, 4);
        await click('freeze:1');
        await send('Qarz muddati to‘rt kun o‘tgan');
        assert.equal(await count('operator_freezes'), 1);
        await click('unfreeze:1');
        await send('To‘lov kutilmoqda');
        assert.equal(await count('operator_freezes'), 1, 'unpaid debt cannot be marked settled by operator');
        await click('settle:1');
        await send('500');
        await receipt('three');
        await click('submit');
        await decideReceipt(3, 1, 'approved', '');
        assert.equal((await db.query<any>('SELECT debt FROM operator_balances')).rows[0].debt, '0.00');
        assert.equal(await count('subscriptions'), 1, 'installment does not extend tariff again');
        assert.equal((await dueDebts(pool!, new Date('2026-10-06T04:00:00Z'), 1)).length, 0, 'settled debt disappears from notifications');
        assert.deepEqual((await db.query<any>('SELECT plan_expires_at FROM users')).rows[0].plan_expires_at, expiry);
        await click('unfreeze:1');
        await send('Admin to‘lovni tasdiqladi');
        assert.equal(await count('operator_freezes'), 0);
        await click('report');
        await click('report:today');
        await click('debts');
        const { operatorAdminRoutes } = await import('../server/operator/admin.js');
        const adminRouter = operatorAdminRoutes();
        const invoke = (path: string, query: any) => new Promise<any>((resolve, reject) => {
            const layer = (adminRouter as any).stack.find((x: any) => x.route?.path === path);
            layer.route.stack[0].handle({query, adminId: 1}, {set() {}, json: resolve, status: (status: number) => ({json: (body: any) => reject(new Error(status + ':' + JSON.stringify(body)))})}, reject);
        });
        const overview = await invoke('/overview', {});
        assert.equal(overview.rows.length, 3);
        assert.equal(overview.summary.find((r: any) => r.status === 'approved').amount, '1000.00');
        assert.equal(overview.debts[0].debt, '0.00');
        const filtered = await invoke('/overview', {status: 'approved', source: 'Instagram', tariff: 'three_month', from: '2026-01-01', to: '2028-01-01'});
        assert.equal(filtered.rows.length, 2);
        assert.ok((await invoke('/audit', {})).length > 0);
        const { issueOperatorReset, consumeOperatorReset } = await import('../server/operator/passwordReset.js');
        const { transaction } = await import('../server/operator/service.js');
        const link = await transaction(c => issueOperatorReset(c, 1, 1));
        const token = new URLSearchParams(new URL(link).hash.slice(1)).get('token')!;
        assert.equal((await db.query<any>('SELECT password FROM users WHERE id=1')).rows[0].password, 'original', 'issuing link does not lock customer out');
        await assert.rejects(transaction(c => issueOperatorReset(c, 1, 1)), /15 daqiqa/);
        await consumeOperatorReset(token, 'NewSecurePassword2026!');
        const stored = (await db.query<any>('SELECT password FROM users WHERE id=1')).rows[0].password;
        assert.ok(await bcrypt.compare('NewSecurePassword2026!', stored));
        await assert.rejects(consumeOperatorReset(token, 'AnotherSecurePassword2026!'), /yaroqsiz/);
        await db.exec("UPDATE operator_password_resets SET created_at=now()-interval '1 hour'");
        const expiredLink = await transaction(c => issueOperatorReset(c, 1, 1));
        await db.exec("UPDATE operator_password_resets SET expires_at=now()-interval '1 second'");
        await assert.rejects(consumeOperatorReset(new URLSearchParams(new URL(expiredLink).hash.slice(1)).get('token')!, 'SecurePassword2026!'), /yaroqsiz/);
        // New students are real platform users, with a separate pending payment.
        await db.exec("SELECT setval(pg_get_serial_sequence('users','id'),100)");
        const usersBefore = await count('users');
        await click('create_customer', 789);
        await send('Blocked outsider', 789);
        assert.equal(await count('users'), usersBefore);
        await click('create_customer');
        await send('Yangi'); await send('Oquvchi');
        await send('wrong phone');
        assert.equal((await db.query<any>('SELECT state FROM operator_sessions WHERE telegram_id=123')).rows[0].state.step, 'customer_phone');
        await send('+998 90 123 45 67'); await send('yangi@example.invalid');
        await click('menu');
        assert.equal(await count('users'), usersBefore, 'cancelled draft creates no account');
        await click('create_customer'); await send('Yangi'); await send('Oquvchi');
        await send('+998901234567'); await send('YANGI@example.invalid');
        const creation = await click('customer_confirm');
        await handleUpdate(creation); await click('customer_confirm');
        assert.equal(await count('users'), usersBefore + 1, 'replayed confirmation creates only one student');
        const student = (await db.query<any>("SELECT * FROM users WHERE email='yangi@example.invalid'")).rows[0];
        assert.equal(student.account_type, 'student');
        assert.equal(student.phone_normalized, '+998901234567');
        assert.equal(student.plan_expires_at, null);
        assert.notEqual(student.password, '12345678');
        assert.ok(await bcrypt.compare('12345678', student.password), 'new operator-created student can sign in with the displayed initial password');
        assert.equal((await db.query<any>("SELECT count(*) n FROM operator_audit WHERE user_id=$1 AND operator_id=1 AND action='customer_created'", [student.id])).rows[0].n, 1);
        const message = (await db.query<any>("SELECT payload FROM operator_outbox WHERE dedupe=$1", ['reset-link:' + creation.update_id])).rows[0].payload.text;
        const studentToken = message.match(/#token=([A-Za-z0-9_-]{43})/)[1];
        await consumeOperatorReset(studentToken, 'StudentPassword2026!');
        assert.ok(await bcrypt.compare('StudentPassword2026!', (await db.query<any>('SELECT password FROM users WHERE id=$1', [student.id])).rows[0].password));
        await click('tariff:six_month'); await click('source:Telegram'); await click('currency:UZS');
        await send('2000000'); await send('1000000'); await send('2027-12-01 10:00');
        await receipt('new-student-receipt'); await click('submit');
        const newReceipt = (await db.query<any>('SELECT r.id,c.operator_id,c.due_at,r.status FROM operator_receipts r JOIN operator_contracts c ON c.id=r.contract_id WHERE c.user_id=$1', [student.id])).rows[0];
        assert.equal(newReceipt.status, 'pending');
        assert.equal(newReceipt.operator_id, 1);
        assert.ok(newReceipt.due_at);
        assert.equal((await db.query<any>('SELECT plan_expires_at FROM users WHERE id=$1', [student.id])).rows[0].plan_expires_at, null);
        await decideReceipt(Number(newReceipt.id), 1, 'approved', '');
        assert.ok((await db.query<any>('SELECT plan_expires_at FROM users WHERE id=$1', [student.id])).rows[0].plan_expires_at);
        await click('create_customer'); await send('Takror'); await send('Mijoz');
        await send('+998 90 123 45 67'); await send('-'); await click('customer_confirm');
        assert.equal(await count('users'), usersBefore + 1, 'formatted duplicate phone reuses existing user');
        await click('create_customer'); await send('Boshqa'); await send('Mijoz');
        await send('+998901234568'); await send('YANGI@example.invalid'); await click('customer_confirm');
        assert.equal(await count('users'), usersBefore + 1, 'duplicate email does not create a second account');
        // Operator cannot bind the same login from another Telegram account.
        await send('/start', 456);
        await send('op1', 456);
        await send('Testpassword123!', 456);
        assert.equal((await db.query<any>('SELECT operator_id FROM operator_sessions WHERE telegram_id=456')).rows[0].operator_id, null);
        const { operatorMiniAppRoutes } = await import('../server/operator/miniApp.js');
        const miniRouter = operatorMiniAppRoutes() as any;
        const invokeMini = (method: string, path: string, body = {}, file?: any, params = {}, operatorId = 1) => new Promise<any>((resolve, reject) => {
            lastDbError = undefined;
            const layer = miniRouter.stack.find((x: any) => x.route?.path === path && x.route.methods[method]);
            layer.route.stack.at(-1).handle({ body, query: body, file, params, operator: { id: operatorId, name: 'Operator One' } }, {
                set() {}, json: resolve,
                status: (status: number) => ({ json: (data: any) => reject(new Error(path + ':' + status + ':' + data.error, { cause: lastDbError })) }),
            }, reject);
        });
        const catalog = await invokeMini('get', '/me');
        assert.deepEqual(catalog.tariffs.map((t: any) => t.prices.find((p: any) => p.currency === 'UZS').amount), [400000, 530000, 790000]);
        assert.deepEqual(catalog.tariffs.map((t: any) => t.prices.find((p: any) => p.currency === 'RUB').amount), [3000, 4000, 6000]);
        const miniInput = { firstName: 'Mini', lastName: 'Student', phone: '+7 916 123 45 67', email: '-' };
        const miniStudent = await invokeMini('post', '/customers', miniInput);
        assert.equal(miniStudent.initialPassword, '12345678');
        const miniStored = (await db.query<any>('SELECT phone_normalized,password,plan_expires_at FROM users WHERE id=$1', [miniStudent.user.id])).rows[0];
        assert.equal(miniStored.phone_normalized, '+79161234567');
        assert.ok(await bcrypt.compare(miniStudent.initialPassword, miniStored.password));
        assert.equal(miniStored.plan_expires_at, null);
        await assert.rejects(invokeMini('post', '/customers', miniInput), /foydalanuvchi mavjud/);
        await assert.rejects(invokeMini('post', '/payments', { userId: miniStudent.user.id, tariff: 'month', source: 'Telegram', currency: 'UZS', total: '450000', amount: '400000' }), /Tarif narxi yangilangan/);
        const initialStats = await invokeMini('get', '/stats', { period: 'today' });
        const uploadPayment = { userId: miniStudent.user.id, tariff: 'month', source: 'Telegram', currency: 'UZS', total: '400000', amount: '400000' };
        const submittedMini = await invokeMini('post', '/payments', uploadPayment, { mimetype: 'application/pdf', buffer: Buffer.from('%PDF-isolated-test-one') });
        const pendingStats = await invokeMini('get', '/stats', { period: 'today' });
        assert.ok(pendingStats.history.some((r: any) => Number(r.id) === Number(submittedMini.receiptId) && r.status === 'pending'));
        assert.equal(pendingStats.salary.soldCourses, initialStats.salary.soldCourses, 'pending receipts earn no salary');
        await decideReceipt(Number(submittedMini.receiptId), 1, 'approved', '');
        const approvedStats = await invokeMini('get', '/stats', { period: 'today' });
        assert.equal(approvedStats.salary.soldCourses, initialStats.salary.soldCourses + 1);
        assert.ok(approvedStats.history.some((r: any) => Number(r.id) === Number(submittedMini.receiptId) && r.status === 'approved'));
        const rejectedMini = await invokeMini('post', '/payments', uploadPayment, { mimetype: 'application/pdf', buffer: Buffer.from('%PDF-isolated-test-two') });
        await decideReceipt(Number(rejectedMini.receiptId), 1, 'rejected', 'Invalid receipt');
        const rejectedStats = await invokeMini('get', '/stats', { period: 'today' });
        assert.equal(rejectedStats.salary.soldCourses, approvedStats.salary.soldCourses);
        assert.ok(!rejectedStats.debts.flatMap((d: any) => d.debtors).some((d: any) => Number(d.contract_id) === Number(rejectedMini.contractId)));

        await db.exec("INSERT INTO operator_accounts(login,name,password_hash) VALUES('other','Other Operator','hash')");
        let firstContract: number | undefined;
        for (let i = 0; i < 6; i++) {
            const timestamp = i < 3 ? '2026-08-28T08:00:00Z' : '2026-08-29T08:00:00Z';
            const currency = i < 3 ? 'RUB' : 'UZS';
            const amount = i < 3 ? 500 : 500000;
            const contract = (await db.query<any>("INSERT INTO operator_contracts(user_id,operator_id,tariff,currency,total,source,activated_at) VALUES(1,1,'month',$1,$2,'Telegram',$3) RETURNING id", [currency, amount * 2, timestamp])).rows[0].id;
            firstContract ??= contract;
            await db.query("INSERT INTO operator_receipts(contract_id,operator_id,amount,file_id,file_unique_id,mime,status,created_at,decided_at) VALUES($1,1,$2,'test',$3,'image/jpeg','approved','2026-08-27T08:00:00Z',$4)", [contract, amount, 'stats-' + i, timestamp]);
        }
        await db.query("INSERT INTO operator_receipts(contract_id,operator_id,amount,file_id,file_unique_id,mime,status,created_at,decided_at) VALUES($1,1,100,'test','stats-installment','image/jpeg','approved','2026-08-29T08:00:00Z','2026-08-29T08:00:00Z')", [firstContract]);
        await db.query('UPDATE operator_contracts SET operator_id=2 WHERE id=$1', [firstContract]);
        const rangeStats = await invokeMini('get', '/stats', { period: 'custom', from: '2026-08-28', to: '2026-08-29' });
        assert.equal(rangeStats.salary.soldCourses, 6, 'installments are not another sold course; reassigning debt does not move earned salary');
        assert.equal(rangeStats.salary.baseAmount, 180000);
        assert.equal(rangeStats.salary.bonusAmount, 100000, 'two daily bonuses of 50000');
        assert.equal(rangeStats.salary.totalAmount, 280000);
        assert.equal(rangeStats.salary.totalAmount, rangeStats.salaryDays.reduce((sum: number, day: any) => sum + day.totalAmount, 0));
        for (const currency of ['RUB', 'UZS']) {
            const approved = rangeStats.payments.find((r: any) => r.status === 'approved' && r.currency === currency);
            assert.equal(Number(approved.amount), rangeStats.salesDays.filter((r: any) => r.currency === currency).reduce((sum: number, r: any) => sum + Number(r.amount), 0));
        }
        assert.equal(rangeStats.history.length, 7, 'history follows the approval date, including receipts submitted on an earlier day');
        await assert.rejects(invokeMini('get', '/stats', { period: 'custom', from: '2026-02-30', to: '2026-03-02' }), /Sana/);
        await assert.rejects(invokeMini('get', '/stats', { period: 'custom', from: '2026-08-29', to: '2026-08-28' }), /Tugash/);
        // Debt actions in the mini app: admin-gated deferrals and installments on the existing contract.
        const { decideDebtDeferral, requestDebtDeferral } = await import('../server/operator/debtActions.js');
        const futureDate = (days: number) => new Date(Date.now() + days * 86400000 + 5 * 3600000).toISOString().slice(0,16).replace('T',' ');
        const debtContract = (await db.query<any>("INSERT INTO operator_contracts(user_id,operator_id,tariff,currency,total,source,activated_at,due_at) VALUES(1,1,'month','RUB',1000,'Telegram',now(),now()-interval '1 day') RETURNING id")).rows[0].id;
        await db.query("INSERT INTO operator_receipts(contract_id,operator_id,amount,file_id,file_unique_id,mime,status) VALUES($1,1,500,'base-debt','base-debt','image/jpeg','approved')", [debtContract]);
        const params = { id: debtContract };
        const dueBefore = (await db.query<any>('SELECT due_at FROM operator_contracts WHERE id=$1',[debtContract])).rows[0].due_at;
        const isNotified = async () => (await invokeMini('get','/notifications')).debts.some((d: any) => Number(d.contract_id) === Number(debtContract));
        assert.equal(await isNotified(),true);
        await assert.rejects(invokeMini('post','/contracts/:id/deferrals',{dueAt:futureDate(1),reason:'Mijoz bilan kelishildi'},undefined,params,2),/Shartnoma topilmadi/);
        await assert.rejects(invokeMini('post','/contracts/:id/deferrals',{dueAt:'2026-02-30 15:30',reason:'Mijoz bilan kelishildi'},undefined,params));
        await assert.rejects(invokeMini('post','/contracts/:id/deferrals',{dueAt:futureDate(1),reason:'x'},undefined,params),/Sabab/);
        const firstDeferral = await invokeMini('post','/contracts/:id/deferrals',{dueAt:futureDate(1),reason:'Mijoz bilan ertaga kelishildi'},undefined,params);
        assert.deepEqual((await db.query<any>('SELECT due_at FROM operator_contracts WHERE id=$1',[debtContract])).rows[0].due_at,dueBefore,'request does not change deadline');
        assert.equal(await isNotified(),true,'pending request does not suppress reminders');
        await assert.rejects(requestDebtDeferral(Number(debtContract),1,futureDate(2),'Yana kelishildi'),/allaqachon/);
        const pendingDeferrals = await invoke('/deferrals',{status:'pending',operator:'1'});
        assert.ok(pendingDeferrals.rows.some((d:any) => Number(d.id) === Number(firstDeferral.id) && d.phone === '+998900000000'));
        await assert.rejects(decideDebtDeferral(firstDeferral.id,1,'rejected',''),/Sabab/);
        await decideDebtDeferral(firstDeferral.id,1,'rejected','Kelishuv tasdiqlanmadi');
        assert.deepEqual((await db.query<any>('SELECT due_at FROM operator_contracts WHERE id=$1',[debtContract])).rows[0].due_at,dueBefore);
        assert.equal(await isNotified(),true,'rejection keeps old reminders');
        await assert.rejects(decideDebtDeferral(firstDeferral.id,1,'approved',''));
        const accepted = await requestDebtDeferral(Number(debtContract),1,futureDate(2),'Mijoz bilan qayta kelishildi');
        await db.query("INSERT INTO operator_outbox(method,payload,dedupe,contract_id) VALUES('sendMessage','{}',$1,$2)", [`daily-debt:queued:${debtContract}`,debtContract]);
        await decideDebtDeferral(accepted,1,'approved','Kelishuv tasdiqlandi');
        assert.equal(await isNotified(),false,'approved new future date suppresses notifications');
        assert.ok((await db.query<any>("SELECT delivered_at FROM operator_outbox WHERE dedupe=$1",[`daily-debt:queued:${debtContract}`])).rows[0].delivered_at,'approval cancels queued reminders');
        assert.equal((await db.query<any>('SELECT debt FROM operator_balances WHERE id=$1',[debtContract])).rows[0].debt,'500.00');
        await assert.rejects(decideDebtDeferral(accepted,1,'approved',''),'admin replay rejected');
        const newDue = (await db.query<any>('SELECT due_at FROM operator_contracts WHERE id=$1',[debtContract])).rows[0].due_at;
        assert.ok(!(await dueDebts(pool!,new Date(+new Date(newDue)-1000),1)).some(d=>Number(d.id)===Number(debtContract)),'same-day deferral waits until agreed time');
        assert.ok((await dueDebts(pool!,new Date(newDue),1)).some(d=>Number(d.id)===Number(debtContract)),'reminders resume at new deadline');
        const debtStats = await invokeMini('get','/stats',{period:'today'});
        assert.equal(debtStats.debts.flatMap((d:any)=>d.debtors).find((d:any)=>Number(d.contract_id)===Number(debtContract)).deferral.status,'approved');
        await assert.rejects(requestDebtDeferral(Number(debtContract),1,futureDate(1),'Oldingi sana'),/joriy muddatdan keyin/);
        const repeated = await requestDebtDeferral(Number(debtContract),1,futureDate(3),'Ikkinchi kelishuv');
        await decideDebtDeferral(repeated,1,'approved','');
        assert.equal((await db.query<any>('SELECT count(*) n FROM operator_debt_deferrals WHERE contract_id=$1',[debtContract])).rows[0].n,3,'all agreements preserved');
        assert.ok((await db.query<any>("SELECT count(*) n FROM operator_audit WHERE action='debt_deferral_approved' AND user_id=1")).rows[0].n>=2);
        assert.ok((await db.query<any>("SELECT count(*) n FROM operator_outbox WHERE dedupe LIKE 'deferral-decision:%'")).rows[0].n>=3,'operator receives admin decision');
        const settledLater = await requestDebtDeferral(Number(debtContract),1,futureDate(4),'Uchinchi kelishuv');
        const debtUpload = {mimetype:'application/pdf',buffer:Buffer.from('%PDF-debt-installment')};
        await assert.rejects(invokeMini('post','/contracts/:id/payments',{amount:'500'},debtUpload,params,2),/Shartnoma topilmadi/);
        await assert.rejects(invokeMini('post','/contracts/:id/payments',{amount:'501'},debtUpload,params),/Summa/);
        const contractsBefore = await count('operator_contracts');
        const subscriptionsBefore = await count('subscriptions');
        const debtPayment = await invokeMini('post','/contracts/:id/payments',{amount:'500'},debtUpload,params);
        assert.equal(await count('operator_contracts'),contractsBefore,'installment uses the existing contract');
        assert.equal((await db.query<any>('SELECT debt FROM operator_balances WHERE id=$1',[debtContract])).rows[0].debt,'500.00','receipt remains pending');
        await assert.rejects(invokeMini('post','/contracts/:id/payments',{amount:'1'},debtUpload,params),/Summa/,'pending payment reserves balance');
        await decideReceipt(Number(debtPayment.receiptId),1,'approved','');
        assert.equal((await db.query<any>('SELECT debt FROM operator_balances WHERE id=$1',[debtContract])).rows[0].debt,'0.00');
        assert.equal(await count('subscriptions'),subscriptionsBefore,'settlement does not activate another tariff');
        await assert.rejects(decideDebtDeferral(settledLater,1,'approved',''),/yopilgan/,'settled debt cannot be deferred');
        await decideDebtDeferral(settledLater,1,'rejected','Qarz to‘landi');
        await assert.rejects(requestDebtDeferral(Number(debtContract),1,futureDate(5),'Qayta kelishuv'),/qarz yo‘q/);

        const staleContract = (await db.query<any>("INSERT INTO operator_contracts(user_id,operator_id,tariff,currency,total,source,due_at) VALUES(1,1,'month','RUB',1000,'Telegram',now()-interval '1 day') RETURNING id")).rows[0].id;
        await db.query("INSERT INTO operator_receipts(contract_id,operator_id,amount,file_id,file_unique_id,mime,status) VALUES($1,1,500,'stale','stale','image/jpeg','approved')",[staleContract]);
        const staleRequest = await requestDebtDeferral(Number(staleContract),1,futureDate(1),'Kelishuv');
        await db.query('UPDATE operator_contracts SET operator_id=2 WHERE id=$1',[staleContract]);
        await assert.rejects(decideDebtDeferral(staleRequest,1,'approved',''),/operator o‘zgargan/);
        await decideDebtDeferral(staleRequest,1,'rejected','Mas’ul operator o‘zgardi');
        await db.query('UPDATE operator_contracts SET operator_id=1 WHERE id=$1',[staleContract]);
        const expiredRequest = await requestDebtDeferral(Number(staleContract),1,futureDate(1),'Kelishuv');
        await db.query("UPDATE operator_debt_deferrals SET requested_due_at=now()-interval '1 hour' WHERE id=$1",[expiredRequest]);
        await assert.rejects(decideDebtDeferral(expiredRequest,1,'approved',''),/muddat o‘tgan/);
        await decideDebtDeferral(expiredRequest,1,'rejected','Muddat o‘tdi');
        const changedRequest = await requestDebtDeferral(Number(staleContract),1,futureDate(1),'Kelishuv');
        await db.query("UPDATE operator_contracts SET due_at=due_at+interval '1 minute' WHERE id=$1",[staleContract]);
        await assert.rejects(decideDebtDeferral(changedRequest,1,'approved',''),/muddat o‘zgargan/);
        await decideDebtDeferral(changedRequest,1,'rejected','Muddat o‘zgardi');

        // A concurrent reminder using the old deadline must be cancelled even if queued after approval.
        await db.query("UPDATE operator_contracts SET due_at=now()-interval '1 hour' WHERE id=$1",[staleContract]);
        await db.query(`INSERT INTO operator_debt_deferrals(contract_id,operator_id,previous_due_at,requested_due_at,reason,status,admin_id,decided_at)
          SELECT id,1,due_at-interval '1 day',due_at,'Kelishildi','approved',1,now()-interval '10 seconds' FROM operator_contracts WHERE id=$1`,[staleContract]);
        const outboxDue = (await db.query<any>('SELECT due_at FROM operator_contracts WHERE id=$1',[staleContract])).rows[0].due_at;
        const queueReminder = async (key: string) => (await db.query<any>("INSERT INTO operator_outbox(method,payload,dedupe,contract_id) VALUES('sendMessage','{\"chat_id\":123}', $1,$2) RETURNING id",[key,staleContract])).rows[0].id;
        const outdated = await queueReminder(`daily-debt:old:${staleContract}:2026-01-01T00:00:00.000Z`);
        const current = await queueReminder(`daily-debt:current:${staleContract}:${new Date(outboxDue).toISOString()}`);
        const { operatorBotRoutes } = await import('../server/operator/routes.js');
        const outboxRouter = operatorBotRoutes({} as any) as any;
        await new Promise((resolve,reject) => {
          const layer = outboxRouter.stack.find((x:any)=>x.route?.path==='/outbox');
          layer.route.stack.at(-1).handle({}, {json:resolve,status:(status:number)=>({json:(data:any)=>reject(new Error(status+':'+JSON.stringify(data)))})},reject);
        });
        assert.equal((await db.query<any>('SELECT last_error FROM operator_outbox WHERE id=$1',[outdated])).rows[0].last_error,'debt_deferred');
        assert.equal((await db.query<any>('SELECT delivered_at,last_error FROM operator_outbox WHERE id=$1',[current])).rows[0].delivered_at,null,'reminder for the approved current deadline remains eligible');

        await db.exec('UPDATE operator_accounts SET active=false WHERE id=1');
        await click('list:0');
        assert.equal((await db.query<any>('SELECT operator_id FROM operator_sessions WHERE telegram_id=123')).rows[0].operator_id, null);
    }
    finally {
        (pool as any).query = originalQuery;
        (pool as any).connect = originalConnect;
        await pool.end();
        await db.close();
        await rm(receiptDir, { recursive: true, force: true });
        delete process.env.OPERATOR_RECEIPT_DIR;
    }
});
