import type { KioskQuestion } from '../../shared/kiosk.js';
export type PrivateQuestion = KioskQuestion & { correctIndex: number; explanation: string; explanationUz: string };
export const KIOSK_QUESTIONS: PrivateQuestion[] = [
  { id:'name', category:'Знакомство', categoryUz:'Tanishuv', text:'Как правильно представиться?', options:['Меня зовут Азиз.','Я зовут Азиз.','Мне зовут Азиз.','Мой зовут Азиз.'], correctIndex:0, explanation:'Говорим: «Меня зовут…».', explanationUz:'Ismni aytishda «Меня зовут…» deyiladi.' },
  { id:'work', category:'Работа', categoryUz:'Ish', text:'Выберите правильный вариант: «Я ___ в магазине».', options:['работа','работает','работаю','работать'], correctIndex:2, explanation:'С «я» используем форму «работаю».', explanationUz:'«Я» bilan «работаю» shakli ishlatiladi.' },
  { id:'metro', category:'Вежливое общение', categoryUz:'Odobli muloqot', text:'Как вежливо спросить дорогу к метро у незнакомого человека?', options:['Метро куда идти?','Извините, как пройти к метро?','Ты не знаешь метро?','Эй, метро где?'], correctIndex:1, explanation:'«Извините, как пройти…» — вежливая просьба.', explanationUz:'«Извините, как пройти…» — odobli savol.' },
  { id:'gender', category:'Грамматика', categoryUz:'Grammatika', text:'Выберите правильный вариант: «Это ___ работа».', options:['мой','моё','мои','моя'], correctIndex:3, explanation:'«Работа» — женский род, поэтому «моя».', explanationUz:'«Работа» ayol rodida, shuning uchun «моя».' },
  { id:'time', category:'Время', categoryUz:'Vaqt', text:'Встреча начинается в 15:30. Это…', options:['половина третьего','половина четвёртого дня','пятнадцать минут четвёртого','три часа ровно'], correctIndex:1, explanation:'15:30 — три часа тридцать минут, или половина четвёртого.', explanationUz:'15:30 — «три часа тридцать минут» yoki «половина четвёртого».' },
  { id:'shop', category:'В магазине', categoryUz:"Do'konda", text:'Как правильно спросить о цене?', options:['Сколько стоит этот хлеб?','Как много этот хлеб?','Который цена хлеб?','Сколько деньги хлеб?'], correctIndex:0, explanation:'Чтобы узнать цену, спросите: «Сколько стоит…?»', explanationUz:'Narxni bilish uchun «Сколько стоит…?» deb so‘rang.' },
  { id:'past', category:'Прошедшее время', categoryUz:"O'tgan zamon", text:'Анна говорит о вчерашнем дне: «Вчера я ___ домой поздно».', options:['пришёл','приду','пришла','приходить'], correctIndex:2, explanation:'Женщина говорит о себе: «я пришла».', explanationUz:'Ayol kishi o‘zi haqida «я пришла» deydi.' },
  { id:'document', category:'Документы', categoryUz:'Hujjatlar', text:'В анкете указано «Дата рождения». Что нужно написать?', options:['Сегодняшнюю дату','День, месяц и год своего рождения','Адрес проживания','Номер телефона'], correctIndex:1, explanation:'Дата рождения — день, месяц и год, когда вы родились.', explanationUz:'Tug‘ilgan sana — tug‘ilgan kun, oy va yil.' },
  { id:'case', category:'Повседневная речь', categoryUz:'Kundalik nutq', text:'Выберите правильный вариант: «Я жду ___».', options:['автобус','автобусом','автобусе','автобусу'], correctIndex:0, explanation:'Правильно: «жду автобус».', explanationUz:'To‘g‘ri shakl: «жду автобус».' },
  { id:'reading', category:'Понимание текста', categoryUz:'Matnni tushunish', text:'«Магазин закрыт до понедельника». Когда он откроется?', options:['В воскресенье','В субботу','Сегодня вечером','В понедельник'], correctIndex:3, explanation:'«До понедельника» означает, что магазин откроется в понедельник.', explanationUz:'«До понедельника» — do‘kon dushanba kuni ochiladi.' },
];
