import { useCallback, useEffect, useRef, useState } from 'react';
import { ArrowLeft, ArrowRight, Baby, Backpack, BriefcaseBusiness, Check, CheckCircle2, Clock3, Copy, Download, Globe2, GraduationCap, LoaderCircle, RotateCcw, Sparkles, Ticket, X } from 'lucide-react';
import { Helmet } from 'react-helmet-async';
import type { KioskAudience, KioskConfig, KioskLocale, KioskSession } from '../../shared/kiosk';
import { KIOSK_AUDIENCE_LABELS } from '../../shared/kiosk';
import { KioskApiError, kioskApi } from '../components/kiosk/api';
import '../components/kiosk/kiosk.css';

const STORAGE='falarus-kiosk-session-v1';
const text = {
  ru:{eyebrow:'Русский для детей, подростков и взрослых',title:<>Проверь свой русский <br/>за несколько минут</>,subtitle:'Выберите, для кого тест. Затем ответьте на 10 вопросов.',prize:'Скидка на курс',pitch:<>Пройди короткий тест и получи <strong>персональную скидку</strong> на обучение</>,start:'НАЧАТЬ ТЕСТ',native:'Testni boshlash',free:'Бесплатно · Без регистрации',data:'Давайте познакомимся',dataSub:'Сохраним ваш результат и персональную скидку.',name:'Ваше имя',phone:'Номер телефона',phoneHint:'С кодом страны: +998 или +7',consent:'Согласен на обработку данных для участия в тесте',marketing:'Хочу получать предложения по курсу (необязательно)',back:'Назад',continue:'ПРОДОЛЖИТЬ',question:'Вопрос',of:'из',answer:'Ответить',skip:'Не знаю',choose:'Выберите один ответ',done:'ТЕСТ ЗАВЕРШЁН',result:'Ваш результат',right:'правильных ответов',resultBody:'Вы сделали первый шаг. Практикуйтесь каждый день, чтобы увереннее понимать русский и говорить на нём.',informal:'Это короткая проверка знаний, а не официальный экзамен на уровень языка.',personal:'Ваша персональная скидка',get:'ПОЛУЧИТЬ КУПОН',expiry:'Скидка действует ещё',expired:'Срок скидки истёк',redeemed:'Скидка уже использована',saved:'Ваш купон готов',savedSub:'Сохраните код и покажите его менеджеру FalaRus при оформлении этого курса.',code:'Промокод',copy:'Скопировать',copied:'Скопировано',download:'Сохранить купон',new:'Начать новый тест',reset:'Завершить эту сессию?',resetBody:'На этом экране больше не будут отображаться ваши данные. Уже выданная скидка останется в системе.',cancel:'Продолжить',resetConfirm:'Завершить',loading:'Загружаем тест…',retry:'Повторить',unavailable:'Сейчас тест недоступен',unavailableSub:'Пожалуйста, вернитесь немного позже.',min:'Для скидки нужно правильных ответов:',notYet:'Ещё немного практики',notYetBody:'На этот раз баллов для скидки не хватило. Повторите материал и попробуйте снова.',correct:'Верно!',wrong:'Разберём ответ',timeout:'Время на вопрос закончилось',timed:'сек. на вопрос',privacy:'Политика конфиденциальности',rules:'Один купон на номер телефона. Повторный тест не продлевает срок скидки.',noSms:'Купон появится здесь после теста. SMS не отправляется.',ready:'Итоговая цена',feedback:'Предыдущий вопрос',close:'Закрыть',score:'Результат',validUntil:'Действует до',course:'Курс',end:'Закончить'},
  uz:{eyebrow:'Bolalar, o‘smirlar va kattalar uchun rus tili',title:<>Rus tilingizni bir necha <br/>daqiqada tekshiring</>,subtitle:'Test kim uchunligini tanlang. So‘ng 10 ta savolga javob bering.',prize:'Kurs uchun chegirma',pitch:<>Qisqa testdan o‘ting va ta’lim uchun <strong>shaxsiy chegirma</strong> oling</>,start:'TESTNI BOSHLASH',native:'Проверить свой русский',free:'Bepul · Ro‘yxatdan o‘tishsiz',data:'Keling, tanishamiz',dataSub:'Natijangiz va shaxsiy chegirmangizni saqlaymiz.',name:'Ismingiz',phone:'Telefon raqamingiz',phoneHint:'Mamlakat kodi bilan: +998 yoki +7',consent:'Testda qatnashish uchun ma’lumotlarim qayta ishlanishiga roziman',marketing:'Kurs takliflarini olishni xohlayman (ixtiyoriy)',back:'Orqaga',continue:'DAVOM ETISH',question:'Savol',of:'/',answer:'Javob berish',skip:'Bilmayman',choose:'Bitta javobni tanlang',done:'TEST YAKUNLANDI',result:'Sizning natijangiz',right:'ta to‘g‘ri javob',resultBody:'Birinchi qadamni qo‘ydingiz. Rus tilini yaxshiroq tushunish va unda ishonchli gapirish uchun har kuni mashq qiling.',informal:'Bu qisqa bilim tekshiruvi, rasmiy til darajasi imtihoni emas.',personal:'Shaxsiy chegirmangiz',get:'KUPONNI OLISH',expiry:'Chegirma amal qilish muddati',expired:'Chegirma muddati tugagan',redeemed:'Chegirmadan foydalanilgan',saved:'Kuponingiz tayyor',savedSub:'Kodni saqlang va ushbu kursni rasmiylashtirishda FalaRus menejeriga ko‘rsating.',code:'Promokod',copy:'Nusxalash',copied:'Nusxalandi',download:'Kuponni saqlash',new:'Yangi testni boshlash',reset:'Sessiyani yakunlaysizmi?',resetBody:'Ma’lumotlaringiz bu ekranda ko‘rinmaydi. Berilgan chegirma tizimda saqlanadi.',cancel:'Davom etish',resetConfirm:'Yakunlash',loading:'Test yuklanmoqda…',retry:'Qayta urinish',unavailable:'Test hozir mavjud emas',unavailableSub:'Iltimos, birozdan keyin qayting.',min:'Chegirma uchun kerakli to‘g‘ri javoblar:',notYet:'Yana biroz mashq qiling',notYetBody:'Bu safar chegirma uchun ball yetmadi. Mavzularni takrorlab, yana urinib ko‘ring.',correct:'To‘g‘ri!',wrong:'Javobni ko‘rib chiqamiz',timeout:'Savol vaqti tugadi',timed:'soniya har savolga',privacy:'Maxfiylik siyosati',rules:'Har telefon raqamiga bitta kupon. Takroriy test chegirma muddatini uzaytirmaydi.',noSms:'Kupon testdan keyin shu yerda ko‘rinadi. SMS yuborilmaydi.',ready:'Yakuniy narx',feedback:'Oldingi savol',close:'Yopish',score:'Natija',validUntil:'Amal qilish muddati',course:'Kurs',end:'Yakunlash'},
};
const clockText=(ms:number)=>{const s=Math.max(0,Math.floor(ms/1000));return [Math.floor(s/3600),Math.floor(s%3600/60),s%60].map(x=>String(x).padStart(2,'0')).join(':');};
const newToken=()=>Array.from(crypto.getRandomValues(new Uint8Array(32)),x=>x.toString(16).padStart(2,'0')).join('');
export default function KioskPage(){
  const [locale,setLocale]=useState<KioskLocale>('ru');const t=text[locale];
  const [audience,setAudience]=useState<KioskAudience|null>(null);
  const [config,setConfig]=useState<KioskConfig|null>(null);const [state,setState]=useState<KioskSession|null>(null);
  const [screen,setScreen]=useState<'intro'|'contact'|'quiz'|'result'|'coupon'>('intro');
  const [loading,setLoading]=useState(true);const [busy,setBusy]=useState(false);const [error,setError]=useState('');
  const [name,setName]=useState('');const [phone,setPhone]=useState('+7');const [consent,setConsent]=useState(false);const [marketing,setMarketing]=useState(false);
  const [selected,setSelected]=useState<number|null>(null);const [now,setNow]=useState(Date.now());const [copied,setCopied]=useState(false);
  const [resetOpen,setResetOpen]=useState(false);const resetDialog=useRef<HTMLDialogElement>(null);
  const token=useRef('');const inFlight=useRef(false);const offset=useRef(0);const attemptedTimeout=useRef('');const lastActivity=useRef(Date.now());
  const apply=useCallback((s:KioskSession)=>{offset.current=new Date(s.serverTime).getTime()-Date.now();setNow(Date.now()+offset.current);setState(s);setAudience(s.audience);setSelected(null);setScreen(s.status==='completed'?'result':'quiz');},[]);
  const initialize=useCallback(async()=>{setLoading(true);setError('');try{
    setConfig(await kioskApi.config());
    const saved=sessionStorage.getItem(STORAGE);
    if(saved){token.current=saved;try{const s=await kioskApi.session(saved);setLocale(s.locale);apply(s);}catch(e){if(e instanceof KioskApiError && [401,404].includes(e.status)){sessionStorage.removeItem(STORAGE);token.current='';}else throw e;}}
  }catch(e){setError((e as Error).message);}finally{setLoading(false);}},[apply]);
  useEffect(()=>{void initialize();},[initialize]);
  useEffect(()=>{window.scrollTo(0,0);},[screen,state?.index]);
  useEffect(()=>{const interval=setInterval(()=>setNow(Date.now()+offset.current),250);return()=>clearInterval(interval);},[]);
  const reset=useCallback(()=>{sessionStorage.removeItem(STORAGE);token.current='';setState(null);setScreen('intro');setName('');setPhone('+7');setAudience(null);setConsent(false);setMarketing(false);setError('');setSelected(null);setResetOpen(false);setCopied(false);lastActivity.current=Date.now();void kioskApi.config().then(setConfig).catch(()=>{});},[]);
  useEffect(()=>{if(resetOpen)resetDialog.current?.showModal();else resetDialog.current?.close();},[resetOpen]);
  useEffect(()=>{
    const active=()=>{lastActivity.current=Date.now();};window.addEventListener('pointerdown',active);window.addEventListener('keydown',active);
    const id=setInterval(()=>{if(screen!=='intro'&&!inFlight.current&&Date.now()-lastActivity.current>120000)reset();},1000);
    return()=>{window.removeEventListener('pointerdown',active);window.removeEventListener('keydown',active);clearInterval(id);};
  },[screen,reset]);
  const start=async(e:React.FormEvent)=>{e.preventDefault();if(inFlight.current||!audience)return;inFlight.current=true;setBusy(true);setError('');try{
    if(!token.current)token.current=newToken();sessionStorage.setItem(STORAGE,token.current);
    const source=new URLSearchParams(location.search).get('source')||new URLSearchParams(location.search).get('utm_source')||'website';
    apply(await kioskApi.start(token.current,{name,phone,consent,marketingConsent:marketing,locale,source,audience}));
  }catch(e){setError((e as Error).message);}finally{inFlight.current=false;setBusy(false);}};
  const answer=useCallback(async(choice:number|null)=>{if(!state||inFlight.current)return;inFlight.current=true;setBusy(true);setError('');try{apply(await kioskApi.answer(token.current,state.index,choice));}catch(e){setError((e as Error).message);}finally{inFlight.current=false;setBusy(false);}},[state,apply]);
  const remaining=state?.questionDeadline?Math.max(0,Math.ceil((new Date(state.questionDeadline).getTime()-now)/1000)):0;
  useEffect(()=>{if(screen!=='quiz'||!state||remaining>0||busy)return;const key=`${state.id}:${state.index}`;if(attemptedTimeout.current===key)return;attemptedTimeout.current=key;void answer(null);},[screen,state,remaining,busy,answer]);
  const coupon=state?.coupon;const offerExpired=!!coupon&&new Date(coupon.expiresAt).getTime()<=now;
  const money=(amount:number,currency:string)=>new Intl.NumberFormat(locale==='ru'?'ru-RU':'uz-UZ',{style:'currency',currency,maximumFractionDigits:2}).format(amount);
  const copy=async()=>{try{await navigator.clipboard.writeText(coupon!.code);setCopied(true);}catch{setError(locale==='ru'?'Выделите и скопируйте код вручную.':'Kodni belgilang va nusxalang.');}};
  const download=()=>{if(!coupon)return;const content=`FalaRus\n${t.course}: ${locale==='ru'?coupon.courseTitle:coupon.courseTitleUz}\n${t.code}: ${coupon.code}\n${t.prize}: ${coupon.discountPercent}%\n${t.validUntil}: ${new Date(coupon.expiresAt).toLocaleString(locale==='ru'?'ru-RU':'uz-UZ')}\n${t.rules}\n`;const url=URL.createObjectURL(new Blob([content],{type:'text/plain;charset=utf-8'}));const a=document.createElement('a');a.href=url;a.download=`FalaRus-${coupon.code}.txt`;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);};
  const offerStatus=coupon?.redeemedAt?t.redeemed:offerExpired?t.expired:null;
  return <div className="kiosk" lang={locale}>
    <Helmet><title>FalaRus — тест и скидка на курс</title><meta name="robots" content="noindex"/></Helmet>
    <header className="kiosk-header"><a className="kiosk-logo" href="/" aria-label="FalaRus — главная"><img src="/landing/falarus-mark.svg" alt=""/><span className="kiosk-brand-name">FalaRus <span>.uz</span></span></a><div className="kiosk-header-actions">
      {state&&<button className="kiosk-icon-button" onClick={()=>setResetOpen(true)} aria-label={t.end}><X size={22}/></button>}
      <div className="kiosk-language" aria-label="Язык / Til"><Globe2 size={20}/>{(['ru','uz'] as const).map(l=><button key={l} type="button" aria-pressed={locale===l} onClick={()=>setLocale(l)}>{l.toUpperCase()}</button>)}</div>
    </div></header>
    {error&&<div className="kiosk-error" role="alert"><span>{error}</span>{screen==='quiz'&&remaining===0?<button onClick={()=>void answer(null)} disabled={busy}>{t.retry}</button>:!config?<button onClick={()=>void initialize()}>{t.retry}</button>:null}</div>}
    {loading?<main className="kiosk-center"><LoaderCircle className="kiosk-spin" size={38}/><p>{t.loading}</p></main>:!config||(!config.enabled&&!state)?<main className="kiosk-center"><Clock3 size={50}/><h1>{t.unavailable}</h1><p>{t.unavailableSub}</p><button className="kiosk-button secondary" onClick={()=>void initialize()}>{t.retry}</button></main>:<>
      {screen==='intro'&&<main className="kiosk-hero">
        <span className="kiosk-eyebrow">{t.eyebrow}</span><h1>{t.title}</h1><p className="kiosk-subtitle">{t.subtitle}</p>
        <fieldset className="kiosk-audiences"><legend>{locale==='ru'?'Для кого тест?':'Test kim uchun?'}</legend><div>{([
          {key:'child',Icon:Baby,ru:'Для ребёнка',uz:'Bola uchun'},
          {key:'teen',Icon:Backpack,ru:'Для подростка',uz:'O‘smir uchun'},
          {key:'adult',Icon:BriefcaseBusiness,ru:'Для себя',uz:'O‘zim uchun'},
        ] as const).map(({key,Icon,ru,uz})=><button key={key} type="button" className={`kiosk-audience ${audience===key?'selected':''}`} aria-pressed={audience===key} onClick={()=>setAudience(key)}><Icon size={29}/><strong>{KIOSK_AUDIENCE_LABELS[key][locale]}</strong><small>{locale==='ru'?ru:uz}</small>{audience===key&&<CheckCircle2 size={21} className="kiosk-audience-check"/>}</button>)}</div></fieldset>
        <div className="kiosk-prize-row"><div className="kiosk-discount"><span>{t.prize}</span><strong>−{config.discountPercent}%</strong></div><p>{t.pitch}</p></div>
        <button className="kiosk-button primary start" disabled={!audience} onClick={()=>{lastActivity.current=Date.now();setScreen('contact');}}><Sparkles size={28}/><span>{t.start}<small>{t.native}</small></span><ArrowRight size={26}/></button>
        <div className="kiosk-meta"><span><CheckCircle2 size={18}/>{t.free}</span><span><Clock3 size={18}/>{config.questionSeconds} {t.timed}</span></div>
        {config.minimumCorrect>0&&<p className="kiosk-muted">{t.min} {config.minimumCorrect}/10</p>}
      </main>}
      {screen==='contact'&&<main className="kiosk-contact"><div className="kiosk-section-heading"><span className="kiosk-eyebrow">01 / 03</span><h1>{t.data}</h1><p>{t.dataSub}</p>{audience&&<span className="kiosk-audience-chip">{KIOSK_AUDIENCE_LABELS[audience][locale]} {locale==='ru'?'тест':'testi'}</span>}</div>
        <div className="kiosk-contact-grid"><form onSubmit={start} className="kiosk-form">
          <label>{t.name}<input autoFocus autoComplete="given-name" name="name" value={name} onChange={e=>setName(e.target.value)} minLength={2} maxLength={80} required placeholder={locale==='ru'?'Как к вам обращаться?':'Sizga qanday murojaat qilaylik?'}/></label>
          <label>{t.phone}<span className="kiosk-phone-countries"><button type="button" aria-pressed={phone.startsWith('+7')} onClick={()=>setPhone('+7')}>{locale==='ru'?'Россия':'Rossiya'} +7</button><button type="button" aria-pressed={phone.startsWith('+998')} onClick={()=>setPhone('+998')}>{locale==='ru'?'Узбекистан':'O‘zbekiston'} +998</button></span><input type="tel" inputMode="tel" autoComplete="tel" name="phone" value={phone} onChange={e=>setPhone(e.target.value)} maxLength={40} required/><small>{t.phoneHint}</small></label>
          <label className="kiosk-checkbox"><input type="checkbox" checked={consent} onChange={e=>setConsent(e.target.checked)} required/><span>{t.consent}. <a href="/huquqiy/maxfiylik" target="_blank" rel="noreferrer">{t.privacy}</a></span></label>
          <label className="kiosk-checkbox optional"><input type="checkbox" checked={marketing} onChange={e=>setMarketing(e.target.checked)}/><span>{t.marketing}</span></label>
          <div className="kiosk-form-actions"><button type="button" className="kiosk-button secondary" onClick={()=>{setError('');setScreen('intro');}} disabled={busy}><ArrowLeft size={22}/>{t.back}</button><button className="kiosk-button primary" disabled={busy}>{busy?<LoaderCircle className="kiosk-spin"/>:t.continue}<ArrowRight size={22}/></button></div>
        </form><aside className="kiosk-contact-aside"><Ticket size={44}/><div className="kiosk-discount"><span>{t.personal}</span><strong>−{config.discountPercent}%</strong></div><h2>{locale==='ru'?config.courseTitle:config.courseTitleUz}</h2><p>{t.noSms}</p><p className="kiosk-fine">{t.rules}</p></aside></div>
      </main>}
      {screen==='quiz'&&state?.question&&<main className="kiosk-quiz">
        <div className="kiosk-progress-row"><div className="kiosk-progress"><div className="kiosk-progress-caption"><span>{t.question} {state.index+1} {t.of} {state.total}</span><span>02 / 03</span></div><div className="kiosk-segments" role="progressbar" aria-valuenow={state.index+1} aria-valuemin={0} aria-valuemax={state.total} aria-label={t.question}>{Array.from({length:state.total},(_,i)=><i key={i} className={i<state.index?'done':i===state.index?'current':''}/>)}</div></div><div className={`kiosk-timer ${remaining<=5?'low':''}`} aria-label={`${remaining} ${t.timed}`}><Clock3 size={24}/><strong>{remaining}</strong></div></div>
        <div className="kiosk-question"><div className="kiosk-question-icon"><GraduationCap size={58}/></div><div><span className="kiosk-eyebrow">{locale==='ru'?state.question.category:state.question.categoryUz}</span><h1>{state.question.text}</h1></div></div>
        <fieldset className="kiosk-options" disabled={busy||remaining===0}><legend className="sr-only">{t.choose}</legend>{state.question.options.map((option,i)=><button type="button" key={`${state.index}-${i}`} className={`kiosk-option ${selected===i?'selected':''}`} onClick={()=>setSelected(i)} aria-pressed={selected===i}><span className="kiosk-letter">{'АБВГ'[i]}</span><span>{option}</span>{selected===i&&<CheckCircle2 size={27}/>}</button>)}</fieldset>
        {state.feedback&&<div className={`kiosk-feedback ${state.feedback.correct?'correct':''}`} role="status"><span>{t.feedback}: {state.feedback.timedOut?t.timeout:state.feedback.correct?t.correct:t.wrong}.</span> {locale==='ru'?state.feedback.explanation:state.feedback.explanationUz}</div>}
        <div className="kiosk-quiz-actions"><button className="kiosk-button ghost" onClick={()=>void answer(null)} disabled={busy||remaining===0}>{t.skip}</button><button className="kiosk-button primary" onClick={()=>void answer(selected)} disabled={busy||selected===null||remaining===0}>{busy?<LoaderCircle className="kiosk-spin"/>:t.answer}<ArrowRight size={24}/></button></div>
      </main>}
      {screen==='result'&&state&&<main className="kiosk-results"><section className="kiosk-result-copy"><span className="kiosk-eyebrow success">{t.done}</span><h1>{t.result},<br/>{state.name}!</h1><div className="kiosk-score"><strong>{state.correctCount}<span>/{state.total}</span></strong><span>{t.right}</span></div><p>{t.resultBody}</p><small>{t.informal}</small></section>
        <section className="kiosk-offer-card">{coupon?<><Ticket size={38} className="kiosk-gold"/><h2>{t.personal}</h2><div className="kiosk-discount big"><span>{t.prize}</span><strong>−{coupon.discountPercent}%</strong></div><p>{locale==='ru'?coupon.courseTitle:coupon.courseTitleUz}</p>{coupon.originalPrice!==null&&<div className="kiosk-price"><del>{money(coupon.originalPrice,coupon.currency)}</del><strong>{money(coupon.finalPrice!,coupon.currency)}</strong></div>}<div className={`kiosk-countdown ${offerStatus?'inactive':''}`}><Clock3 size={24}/><div><span>{offerStatus||t.expiry}</span>{!offerStatus&&<strong>{clockText(new Date(coupon.expiresAt).getTime()-now)}</strong>}</div></div><button className="kiosk-button success block" onClick={()=>setScreen('coupon')}><Ticket size={23}/>{t.get}<ArrowRight size={22}/></button><small>{t.rules}</small></>:<><GraduationCap size={52}/><h2>{t.notYet}</h2><p>{t.notYetBody}</p><p>{t.min} {state.config.minimumCorrect}/{state.total}</p><button className="kiosk-button primary" onClick={reset}><RotateCcw size={22}/>{t.new}</button></>}</section>
      </main>}
      {screen==='coupon'&&coupon&&<main className="kiosk-coupon-screen"><div className="kiosk-section-heading"><span className="kiosk-eyebrow success">03 / 03</span><h1>{t.saved}</h1><p>{t.savedSub}</p></div><section className="kiosk-coupon"><div className="kiosk-coupon-top"><img className="kiosk-coupon-brand" src="/landing/falarus-mark.svg" alt=""/><span>FalaRus</span><strong>−{coupon.discountPercent}%</strong></div><h2>{locale==='ru'?coupon.courseTitle:coupon.courseTitleUz}</h2><span className="kiosk-muted">{t.code}</span><div className="kiosk-coupon-code">{coupon.code}</div><div className="kiosk-coupon-valid">{offerStatus||`${t.validUntil}: ${new Date(coupon.expiresAt).toLocaleString(locale==='ru'?'ru-RU':'uz-UZ')}`}</div><div className="kiosk-coupon-actions"><button className="kiosk-button primary" onClick={()=>void copy()}>{copied?<Check size={21}/>:<Copy size={21}/>}<span aria-live="polite">{copied?t.copied:t.copy}</span></button><button className="kiosk-button secondary" onClick={download}><Download size={21}/>{t.download}</button></div><p className="kiosk-fine">{t.rules}</p></section><button className="kiosk-button ghost" onClick={()=>setResetOpen(true)}><RotateCcw size={20}/>{t.new}</button></main>}
    </>}
    <footer className="kiosk-footer"><span>FalaRus · {t.eyebrow}</span><a href="/huquqiy/maxfiylik" target="_blank" rel="noreferrer">{t.privacy}</a></footer>
    <dialog className="kiosk-dialog" ref={resetDialog} onCancel={()=>setResetOpen(false)}><h2>{t.reset}</h2><p>{t.resetBody}</p><div><button className="kiosk-button secondary" onClick={()=>setResetOpen(false)}>{t.cancel}</button><button className="kiosk-button primary" onClick={reset}>{t.resetConfirm}</button></div></dialog>
  </div>;
}
