/**
 * Generate optional memory keywords for patent choice questions.
 * Highlights key words in the question text only (not in answer options).
 *
 * Run: npx tsx scripts/generate_patent_keywords.ts
 */
import { writeFileSync } from 'node:fs';
import path from 'node:path';
import { PATENT_EXAM_VARIANTS, type PatentExamChoiceQuestion } from '../src/data/patentExamData';

export type PatentQuestionKeywordHints = {
  textKeyword?: string | null;
};

const STOP_WORDS = new Set([
  'в',
  'на',
  'по',
  'из',
  'до',
  'за',
  'от',
  'у',
  'и',
  'или',
  'не',
  'да',
  'нет',
  'для',
  'при',
  'со',
  'с',
  'к',
  'о',
  'об',
  'во',
  'что',
  'как',
  'где',
  'когда',
  'кто',
  'чей',
  'чья',
  'чьё',
  'чьи',
  'это',
  'этот',
  'эта',
  'эти',
  'тот',
  'та',
  'те',
  'можно',
  'нужно',
  'надо',
  'есть',
  'будет',
  'были',
  'был',
  'была',
  'будут',
  'только',
  'лишь',
  'такое',
  'такой',
  'такая',
  'такие',
]);

const QUESTION_TRIGGERS = [
  'услышать',
  'объявление',
  'говорят',
  'прочитать',
  'продаются',
  'продается',
  'необходимо',
  'разговор',
  'приезжает',
  'едет',
  'стоит',
  'записаться',
  'работает',
  'открыть',
  'купить',
  'иметь',
  'сделал',
  'хотят',
  'можно',
  'услышали',
  'слышите',
  'потерянных',
  'прививку',
  'билеты',
  'отправление',
  'экскурсия',
  'начинается',
];

function normalize(value: string): string {
  return value.toLocaleLowerCase('ru-RU').replace(/ё/g, 'е');
}

function tokenize(value: string): string[] {
  return value.match(/[\p{L}\p{N}-]+/gu) ?? [];
}

function sliceFromNormalized(text: string, normalizedNeedle: string): string | null {
  const normalizedText = normalize(text);
  const matchIndex = normalizedText.indexOf(normalizedNeedle);
  if (matchIndex === -1) return null;
  return text.slice(matchIndex, matchIndex + normalizedNeedle.length);
}

function questionTextKeyword(text: string): string | null {
  const normalized = normalize(text);

  for (const trigger of QUESTION_TRIGGERS) {
    const match = sliceFromNormalized(text, trigger);
    if (match) return match;
  }

  const words = tokenize(text);
  let best: string | null = null;
  for (const word of words) {
    const normalizedWord = normalize(word);
    if (word.length < 5 || STOP_WORDS.has(normalizedWord)) continue;
    if (!best || word.length > best.length) {
      best = word;
    }
  }

  return best;
}

function buildHints(question: PatentExamChoiceQuestion): PatentQuestionKeywordHints | null {
  const textKeyword = questionTextKeyword(question.text);
  return textKeyword ? { textKeyword } : null;
}

function collectQuestions(): PatentExamChoiceQuestion[] {
  const questions: PatentExamChoiceQuestion[] = [];
  for (const variant of PATENT_EXAM_VARIANTS) {
    for (const block of variant.blocks) {
      if (block.kind === 'audio-double') {
        questions.push(...block.subQuestions);
        continue;
      }
      if (block.kind === 'multiple-choice' || block.kind === 'image-choice') {
        questions.push(block.question);
      }
    }
  }
  return questions;
}

function main(): void {
  const keywords: Record<string, PatentQuestionKeywordHints> = {};

  for (const question of collectQuestions()) {
    const hints = buildHints(question);
    if (hints) {
      keywords[question.key] = hints;
    }
  }

  const outputPath = path.resolve('src/data/patentExamKeywords.ts');
  const payload = JSON.stringify(keywords, null, 2);
  const content = `/* eslint-disable */
// Generated by scripts/generate_patent_keywords.ts — edit manually or re-run the script.

export type PatentQuestionKeywordHints = {
  textKeyword?: string | null;
};

export const PATENT_QUESTION_KEYWORDS: Record<string, PatentQuestionKeywordHints> = ${payload};
`;

  writeFileSync(outputPath, content, 'utf8');
  console.log(`Wrote ${Object.keys(keywords).length} keyword hints to ${outputPath}`);
}

main();
