/**
 * Generate optional memory keywords for patent choice questions.
 * Highlights distinctive words in the correct option (and question text when found there).
 *
 * Run: npx tsx scripts/generate_patent_keywords.ts
 */
import { writeFileSync } from 'node:fs';
import path from 'node:path';
import { PATENT_EXAM_VARIANTS, type PatentExamChoiceQuestion } from '../src/data/patentExamData';

export type PatentQuestionKeywordHints = {
  textKeyword?: string | null;
  optionKeywords?: (string | null)[] | null;
};

const STOP_WORDS = new Set([
  'в',
  'на',
  'по',
  'из',
  'до',
  'за',
  'от',
  'у',
  'и',
  'или',
  'не',
  'да',
  'нет',
  'для',
  'при',
  'со',
  'с',
  'к',
  'о',
  'об',
  'во',
  'что',
  'как',
  'где',
  'когда',
  'кто',
  'чей',
  'чья',
  'чьё',
  'чьи',
  'это',
  'этот',
  'эта',
  'эти',
  'тот',
  'та',
  'те',
  'можно',
  'нужно',
  'надо',
  'есть',
  'будет',
  'были',
  'был',
  'была',
  'будут',
  'только',
  'лишь',
]);

function normalize(value: string): string {
  return value.toLocaleLowerCase('ru-RU').replace(/ё/g, 'е');
}

function tokenize(value: string): string[] {
  return value.match(/[\p{L}\p{N}-]+/gu) ?? [];
}

function uniqueKeywordInOption(option: string, allOptions: string[]): string | null {
  const others = allOptions.filter((item) => item !== option).map(normalize).join(' ');
  const words = tokenize(option);

  for (let length = words.length; length >= 1; length -= 1) {
    for (let start = 0; start <= words.length - length; start += 1) {
      const phraseWords = words.slice(start, start + length);
      const phrase = phraseWords.join(' ');
      if (phrase.length < 4) continue;
      if (phraseWords.every((word) => STOP_WORDS.has(normalize(word)))) continue;
      if (!normalize(option).includes(normalize(phrase))) continue;
      if (others.includes(normalize(phrase))) continue;
      return phrase;
    }
  }

  return null;
}

function questionTextKeyword(text: string, correctOption: string, optionKeyword: string | null): string | null {
  const candidates = new Set<string>();
  if (optionKeyword) candidates.add(optionKeyword);
  for (const word of tokenize(text)) {
    if (word.length >= 5 && !STOP_WORDS.has(normalize(word))) {
      candidates.add(word);
    }
  }

  const normalizedText = normalize(text);
  const normalizedCorrect = normalize(correctOption);

  for (const candidate of candidates) {
    const normalizedCandidate = normalize(candidate);
    if (normalizedText.includes(normalizedCandidate) && normalizedCorrect.includes(normalizedCandidate)) {
      const matchIndex = normalizedText.indexOf(normalizedCandidate);
      return text.slice(matchIndex, matchIndex + candidate.length);
    }
  }

  return null;
}

function buildHints(question: PatentExamChoiceQuestion): PatentQuestionKeywordHints | null {
  const correctOption = question.options[question.correctIndex];
  if (!correctOption || question.options.every((option) => /\/courses\/patent\/media\/.+\.(png|jpg|jpeg)$/i.test(option))) {
    return null;
  }

  const optionKeywords = question.options.map((option, index) => {
    if (index !== question.correctIndex) return null;
    return uniqueKeywordInOption(option, question.options);
  });

  const correctOptionKeyword = optionKeywords[question.correctIndex];
  const textKeyword = questionTextKeyword(question.text, correctOption, correctOptionKeyword);

  const hasOptionKeywords = optionKeywords.some((item) => item);
  if (!hasOptionKeywords && !textKeyword) {
    return null;
  }

  return {
    ...(textKeyword ? { textKeyword } : {}),
    ...(hasOptionKeywords ? { optionKeywords } : {}),
  };
}

function collectQuestions(): PatentExamChoiceQuestion[] {
  const questions: PatentExamChoiceQuestion[] = [];
  for (const variant of PATENT_EXAM_VARIANTS) {
    for (const block of variant.blocks) {
      if (block.kind === 'audio-double') {
        questions.push(...block.subQuestions);
        continue;
      }
      if (block.kind === 'multiple-choice' || block.kind === 'image-choice') {
        questions.push(block.question);
      }
    }
  }
  return questions;
}

function main(): void {
  const keywords: Record<string, PatentQuestionKeywordHints> = {};

  for (const question of collectQuestions()) {
    const hints = buildHints(question);
    if (hints) {
      keywords[question.key] = hints;
    }
  }

  const outputPath = path.resolve('src/data/patentExamKeywords.ts');
  const payload = JSON.stringify(keywords, null, 2);
  const content = `/* eslint-disable */
// Generated by scripts/generate_patent_keywords.ts — edit manually or re-run the script.

export type PatentQuestionKeywordHints = {
  textKeyword?: string | null;
  optionKeywords?: (string | null)[] | null;
};

export const PATENT_QUESTION_KEYWORDS: Record<string, PatentQuestionKeywordHints> = ${payload};
`;

  writeFileSync(outputPath, content, 'utf8');
  console.log(`Wrote ${Object.keys(keywords).length} keyword hints to ${outputPath}`);
}

main();
