/**
 * Generate Uzbek question hint map for patent practice tests.
 *
 * 1. Run: python3 scripts/extract_patent_question_hints.py
 * 2. Run: npm run generate:patent-hints
 */
import { readFileSync, writeFileSync } from 'node:fs';
import path from 'node:path';
import { PATENT_EXAM_VARIANTS } from '../src/data/patentExamData';

type HintMap = Record<string, string>;

const jsonPath = path.resolve('scripts/generated/patent_question_hints.json');
const outputPath = path.resolve('src/data/patentExamHints.ts');

const PROMPT_TRANSLATIONS: Record<string, string> = {
  'Прочитайте текст и вставьте пропущенное слово.': 'Матнни ўқинг ва тушириб қолдирилган сўзни киритинг.',
};

function main() {
  const extracted = JSON.parse(readFileSync(jsonPath, 'utf-8')) as HintMap;
  const hints: HintMap = {};

  for (const variant of PATENT_EXAM_VARIANTS) {
    for (const block of variant.blocks) {
      if (block.kind === 'written' && block.prompt) {
        const translated = PROMPT_TRANSLATIONS[block.prompt] ?? extracted[block.blockId];
        if (translated?.trim()) {
          hints[block.blockId] = translated.trim();
        }
        continue;
      }

      if (block.kind === 'audio-double') {
        for (const question of block.subQuestions) {
          const hint = extracted[question.key];
          if (hint?.trim() && normalize(hint) !== normalize(question.text)) {
            hints[question.key] = hint.trim();
          }
        }
        continue;
      }

      if (block.kind === 'multiple-choice' || block.kind === 'image-choice') {
        const hint = extracted[block.question.key];
        if (hint?.trim() && normalize(hint) !== normalize(block.question.text)) {
          hints[block.question.key] = hint.trim();
        }
      }
    }
  }

  const body = `/* eslint-disable */
// Generated by scripts/generate_patent_hints.ts — edit manually or re-run the script.

export const PATENT_QUESTION_HINTS: Record<string, string> = ${JSON.stringify(hints, null, 2)};
`;

  writeFileSync(outputPath, body, 'utf-8');
  console.log(`Wrote ${Object.keys(hints).length} hints to ${outputPath}`);
}

function normalize(value: string): string {
  return value.trim().toLocaleLowerCase('ru-RU').replace(/ё/g, 'е').replace(/\s+/g, ' ');
}

main();
