/**
 * Bir martalik: `kunlik_lexeme_fallback_extra.json` ni yozadi.
 *   node scripts/writeKunlikLexemeFallbackExtra.mjs
 */
import fs from 'fs';
import path from 'path';
import { fileURLToPath } from 'url';

const __dirname = path.dirname(fileURLToPath(import.meta.url));

const TR = {
  активным: 'faol (korinish)',
  без: '…siz',
  благодарю: 'rahmat',
  боится: 'qo‘rqadi',
  большое: 'katta',
  большой: 'katta',
  бояться: 'qo‘rqmoq',
  брату: 'akanga / ukanga',
  будем: 'bo‘lamiz',
  будет: 'bo‘ladi',
  буду: 'bo‘laman',
  вагона: 'vagon',
  важные: 'muhim',
  весело: 'shodiyona',
  вечерам: 'kechquruqlar',
  вечеру: 'kechgacha',
  вечность: 'abadiyat',
  видели: 'ko‘rdik',
  вижу: 'ko‘raman',
  вкусный: 'ta’mli',
  внимательным: 'diqqatli',
  'во-первых': 'birinchidan',
  вода: 'suv',
  воде: 'suvda',
  возле: 'yonida',
  вокзал: 'vokzal',
  вокруг: 'atrofida',
  вопросы: 'savollar',
  воскресенье: 'yakshanba',
  встретила: 'uchrashdi',
  встрече: 'uchrashuvda',
  второе: 'ikkinchi',
  выглянуло: 'ko‘rindi',
  выпить: 'ichmoq',
  вышел: 'chiqdi',
  где: 'qayerda',
  главное: 'asosiysi',
  глубоко: 'chuqur',
  году: 'yilda',
  годы: 'yillar',
  голос: 'ovoz',
  голоса: 'ovozlar',
  города: 'shaharlar',
  городу: 'shaharga',
  гостиницы: 'mehmonxona',
  готовы: 'tayyor',
  гуляем: 'sayr qilamiz',
  гулял: 'sayr qildi',
  давно: 'uzoqdan beri',
  дала: 'berdi',
  дел: 'ishlar',
  делаем: 'qilamiz',
  делаешь: 'qilasan',
  делаю: 'qilaman',
  делился: 'bo‘lishdi',
  дереве: 'daraxtda',
  деревню: 'qishloqqa',
  держали: 'ushlab turishdi',
  держит: 'ushlab turadi',
  детей: 'bolalar',
  дима: 'Dima',
  димы: 'Dimaning',
  диск: 'disk',
  для: 'uchun',
  дня: 'kun',
  добру: 'yaxshilikka',
  долгой: 'uzoq',
  дом: 'uy',
  домом: 'uy bilan',
  дружбу: 'do‘stlikni',
  друзьям: 'do‘stlarga',
  друзьями: 'do‘stlar bilan',
  друзьях: 'do‘stlar haqida',
  думаешь: 'o‘ylaysan',
  думал: 'o‘yladi',
  думали: 'o‘ylashdi',
  еду: 'ketaman',
  ездил: 'sayohat qildi',
  ездили: 'sayohat qilishdi',
  ели: 'yeyishdi',
  если: 'agar',
  еще: 'yana',
  ждал: 'kutdi',
  жду: 'kutaman',
  желаю: 'tilayman',
  желтые: 'sariq',
  живую: 'jonli',
  жизни: 'hayotda',
  за: 'uchun / ortidan',
  завтра: 'ertaga',
  задавал: 'berardi',
  заказали: 'buyurtma qilishdi',
  замечательные: 'ajoyib',
  занятия: 'mashg‘ulotlar',
  землю: 'zamini',
  знает: 'biladi',
  знаешь: 'bilasan',
  знакомый: 'tanish',
  значит: 'demak',
  знают: 'bilishadi',
  изменилась: 'o‘zgardi',
  или: 'yoki',
  им: 'ularga',
  интересной: 'qiziqarli',
  интересную: 'qiziqarli',
  интересные: 'qiziqarli',
  к: '…ga / …tomon',
  каждый: 'har bir',
  казанский: 'Qozon…',
  картин: 'tasvirlar',
  квартиру: 'kvartira',
  книгу: 'kitob',
  комнату: 'xonani',
  компьютер: 'kompyuter',
  конечно: 'albatta',
  красивые: 'chiroyli',
  красивый: 'chiroyli',
  кто: 'kim',
  купила: 'sotib oldi',
  легкий: 'engil',
  леса: 'o‘rmon',
  летит: 'uchadi',
  лимоном: 'limon bilan',
  листьев: 'barglar',
  лучшие: 'eng yaxshi',
  любил: 'sevgan',
  любите: 'sevasizmi',
  любишь: 'sevasan',
  любят: 'sevishadi',
  маленькие: 'kichkina',
  маленьким: 'kichkina',
  маленькую: 'kichkina',
  математики: 'matematika',
  машины: 'mashina',
  между: 'o‘rtasida',
  места: 'joylar',
  место: 'joy',
  месту: 'joyga',
  мимо: 'yo‘nalishdan o‘tib',
  минуту: 'daqiqa',
  мишка: 'mishka',
  многие: 'ko‘pchilik',
  могу: 'qila olaman',
  моим: 'meniki bilan',
  молодость: 'yoshlik',
  молоко: 'sut',
  момент: 'lahza',
  музыки: 'musiqa',
  музыку: 'musiqani',
  мыла: 'yuvdi',
  мысли: 'fikrlar',
  мыслями: 'fikrlar bilan',
  назад: 'orqaga',
  найти: 'topmoq',
  наказание: 'jazo',
  нам: 'bizga',
  нами: 'biz bilan',
  напиши: 'yoz',
  настоящая: 'haqiqiy',
  настоящие: 'haqiqiy',
  начал: 'boshladi',
  начали: 'boshlashdi',
  наша: 'bizning',
  наши: 'bizning',
  нашу: 'bizning',
  небольшой: 'kichik',
  невскому: 'Nevaga',
  неделе: 'haftada',
  нее: 'uni',
  ней: 'unda',
  ни: '…ham emas',
  никому: 'hech kimga',
  новой: 'yangi',
  новому: 'yangi',
  новую: 'yangi',
  новые: 'yangi',
  новых: 'yangi',
  о: '…haqida',
  обеда: 'tushlik',
  обещал: 'va’da berdi',
  обещаю: 'va’da beraman',
  окна: 'derazalar',
  они: 'ular',
  орех: 'yong‘oq',
  ответил: 'javob berdi',
  отвечаем: 'javob beramiz',
  открыл: 'ochdi',
  отличным: 'a’lo',
  отца: 'otasini',
  парк: 'park',
  парке: 'parkda',
  парковом: 'parkda',
  парку: 'parkka',
  первое: 'birinchi',
  первым: 'birinchi bo‘lib',
  петербург: 'Petersburg',
  петродворец: 'Petrodvorets',
  пикник: 'piknik',
  пирожное: 'shirin pishiriq',
  писал: 'yozgan',
  писали: 'yozishdi',
  пишу: 'yozaman',
  пловцом: 'suzuvchi',
  плюшевый: 'plyush (matoshyumshoq)',
  повторял: 'takrorlagan',
  подарке: 'sovg‘ada',
  подарок: 'sovg‘a',
  поддерживали: 'qo‘llab-quvvatlashdi',
  подключил: 'uladi',
  поднимаю: 'ko‘taraman',
  поезде: 'poezdda',
  поехал: 'ketdi',
  поехали: 'ketishdi',
  поехать: 'ketmoq',
  позвонил: 'qo‘ng‘iroq qildi',
  поздна: 'kech',
  пойти: 'bormoq',
  показать: 'ko‘rsatmoq',
  показываю: 'ko‘rsataman',
  покупаю: 'xarid qilaman',
  полетел: 'uchdi',
  полке: 'javonda',
  положили: 'qo‘yishdi',
  получаться: 'chiqqani',
  получится: 'bo‘ladi',
  полчаса: 'yarim soat',
  помнишь: 'esladingmi',
  помогал: 'yordam berdi',
  помогают: 'yordam berishadi',
  понимаю: 'tushunaman',
  понимают: 'tushunishadi',
  понравилась: 'yoqdi',
  понял: 'tushundi',
  попросил: 'so‘radi',
  поселился: 'joylashdi',
  после: 'keyin',
  посмотрел: 'ko‘rdi',
  посмотреть: 'ko‘rmoq',
  поставил: 'qo‘ydi',
  поставила: 'qo‘ydi',
  поставили: 'qo‘yishdi',
  потому: 'chunki',
  почему: 'nimaga',
  пошли: 'ketishdi',
  правильное: 'to‘g‘ri',
  прекрасное: 'go‘zal',
  прекрасный: 'go‘zal',
  прекрасными: 'go‘zal',
  преступление: 'jinoyat',
  пригласил: 'taklif qildi',
  приедет: 'keladi',
  приехали: 'kelishdi',
  прилетел: 'uchib keldi',
  прислать: 'yubormoq',
  пришла: 'keldi',
  провели: 'o‘tkazishdi',
  проговорили: 'gaplashishdi',
  продуктами: 'mahsulotlar bilan',
  простые: 'oddiy',
  прошлой: 'o‘tgan',
  прошлым: 'o‘tgan … bilan',
  птиц: 'qushlar',
  пятницу: 'jumaga',
  работают: 'ishlashadi',
  рабочие: 'ishchilar',
  рада: 'xursand',
  радоваться: 'xursand bo‘lmoq',
  разницу: 'farqni',
  рассказывал: 'gapirdi',
  ребенком: 'bola bo‘lib',
  результат: 'natija',
  решил: 'qaror qildi',
  решили: 'qaror qilishdi',
  родителей: 'ota-onalari',
  родителям: 'ota-onalariga',
  рождения: 'tug‘ilgan kun',
  россию: 'Rossiyaga',
  руках: 'qo‘llarda',
  русским: 'rus tilida',
  русского: 'rus tilining',
  русском: 'rus tilida',
  русскому: 'rus tiliga',
  рыб: 'baliqlar',
  сам: 'o‘zi',
  самолете: 'samolyotda',
  самые: 'eng',
  'санкт-петербург': 'Sankt-Peterburg',
  саша: 'Sasha',
  светило: 'nur sochar edi',
  свое: 'o‘zining',
  своего: 'o‘zining',
  своем: 'o‘zining',
  своему: 'o‘ziga',
  свои: 'o‘zining',
  своим: 'o‘zining',
  своими: 'o‘zlari bilan',
  своих: 'o‘zining',
  свой: 'o‘zining',
  своя: 'o‘zining',
  сдал: 'topshirdi',
  сделали: 'qilishdi',
  себе: 'o‘ziga',
  себя: 'o‘zini',
  сели: 'o‘tirishdi',
  семьей: 'oilasi bilan',
  семьи: 'oilasi',
  сережа: 'Seryoja',
  сережи: 'Seryojaning',
  сидела: 'o‘tirardi',
  сидит: 'o‘tiradi',
  сижу: 'o‘tiraman',
  сильный: 'kuchli',
  синий: 'ko‘k',
  сказала: 'dedi',
  слов: 'so‘zlar',
  слова: 'so‘zlar',
  слушали: 'tinglashdi',
  слышал: 'eshitdi',
  смех: 'kulgu',
  смотрел: 'qarardi',
  смотрели: 'qarashdi',
  смотрим: 'qaramiz',
  смотрит: 'qaraydi',
  смотрю: 'qaraman',
  сначала: 'avvalo',
  снова: 'yana',
  собор: 'sobor',
  собрал: 'yig‘di',
  собрали: 'yig‘ishdi',
  совета: 'maslahat',
  сожалению: 'afsuski',
  солнце: 'quyosh',
  сосед: 'qo‘shni',
  сочи: 'Sochi',
  'спас-на-крови': 'Spas na Krovi',
  спешили: 'shoshilishdi',
  спрашивали: 'so‘rashdi',
  спросили: 'so‘rashdi',
  ставили: 'qo‘yishdi',
  стал: 'bo‘ldi',
  стала: 'bo‘ldi',
  стало: 'bo‘ldi',
  старого: 'eski',
  старые: 'eski',
  старый: 'eski',
  стулья: 'stullar',
  сумкой: 'sumka bilan',
  сумку: 'sumkani',
  суп: 'sho‘rva',
  счастливы: 'baxtli',
  счастливым: 'baxtli',
  также: 'shuningdek',
  там: 'u yerda',
  твои: 'sening',
  твой: 'sening',
  тебе: 'senga',
  тексты: 'matnlar',
  телевизор: 'televizor',
  телефона: 'telefon',
  теплой: 'iliq',
  теплотой: 'iliqlik bilan',
  теплые: 'iliq',
  теплым: 'iliq',
  теста: 'test',
  только: 'faqat',
  том: 'u … da',
  третий: 'uchinchi',
  трудную: 'qiyin',
  туда: 'u yerga',
  тяжелую: 'og‘ir',
  увидел: 'ko‘rdi',
  удачным: 'omadli',
  удобная: 'qulay',
  уехал: 'ketdi',
  уже: 'allaqachon',
  ужина: 'kechki ovqat',
  узнать: 'bilmoq',
  улице: 'ko‘chada',
  улыбнулся: 'kulimsirdi',
  умываюсь: 'yuvinaman',
  урок: 'dars',
  урока: 'darsi',
  устали: 'charchashdi',
  утра: 'ertalabki',
  учил: 'o‘rgatdi',
  учила: 'o‘rgatdi',
  учили: 'o‘rgatishdi',
  учится: 'o‘qiydi',
  учу: 'o‘rganaman',
  фильмы: 'filmlar',
  фразы: 'iboralar',
  хлеб: 'non',
  ходили: 'yurishdi',
  ходите: 'yurasiz',
  хорошего: 'yaxshi',
  хотим: 'xohlaymiz',
  хочет: 'xohlaydi',
  цвет: 'rang',
  цели: 'maqsadlar',
  целую: 'bo‘sayman',
  чай: 'choy',
  часа: 'soat',
  часов: 'soat',
  чем: 'nima bilan',
  читала: 'o‘qidi',
  что: 'nima / kim',
  'что-то': 'nimadir',
  чтобы: '…uchun',
  чувствую: 'his qilaman',
  школу: 'maktabga',
  школьные: 'maktab…',
  шторы: 'pardalar',
  шум: 'shovqin',
  экскурсия: 'eksursiya',
  этим: 'bilan',
  этой: 'bu',
  эту: 'buni',
  язык: 'til',
  языка: 'tili',
  языке: 'tilida',
  языком: 'til bilan',
  языку: 'tiliga',
  ярко: 'yorqin',
};

const dir = path.join(__dirname, 'data');
fs.mkdirSync(dir, { recursive: true });
const target = path.join(dir, 'kunlik_lexeme_fallback_extra.json');
fs.writeFileSync(target, JSON.stringify(TR, null, 2), 'utf8');
console.log(`wrote ${target} (${Object.keys(TR).length} keys)`);
