/**
 * This file was generated by kysely-codegen.
 * Please do not edit it manually.
 */

import type { ColumnType } from "kysely";

export type Generated<T> = T extends ColumnType<infer S, infer I, infer U>
  ? ColumnType<S, I | undefined, U>
  : ColumnType<T, T | undefined, T>;

export type Int8 = ColumnType<string, bigint | number | string, bigint | number | string>;

export type Json = JsonValue;

export type JsonArray = JsonValue[];

export type JsonObject = {
  [x: string]: JsonValue | undefined;
};

export type JsonPrimitive = boolean | number | string | null;

export type JsonValue = JsonArray | JsonObject | JsonPrimitive;

export type Numeric = ColumnType<string, number | string, number | string>;

export type Timestamp = ColumnType<Date, Date | string, Date | string>;

export interface Admins {
  created_at: Generated<Timestamp>;
  email: string;
  id: Generated<Int8>;
  password_hash: string;
}

export interface CardTokens {
  created_at: Generated<Timestamp>;
  encrypted_card_token: string;
  id: Generated<Int8>;
  is_active: Generated<boolean>;
  masked_card: string | null;
  masked_phone: string | null;
  updated_at: Generated<Timestamp>;
  user_id: Int8;
}

export interface ChatMessages {
  content: string;
  created_at: Generated<Timestamp>;
  id: Generated<Int8>;
  match_id: number;
  sender_id: number;
}

export interface ClickPaymentLogs {
  click_payment_id: string | null;
  created_at: Generated<Timestamp>;
  error_code: number | null;
  error_note: string | null;
  id: Generated<Int8>;
  merchant_trans_id: string | null;
  operation: string;
  request_safe: Json | null;
  response_safe: Json | null;
  subscription_id: Int8 | null;
  user_id: Int8 | null;
}

export interface DailyGrammarMatches {
  block_sort_order: Generated<number>;
  created_at: Generated<Timestamp>;
  day_number: number;
  id: Generated<Int8>;
  left_text: string;
  pair_sort_order: Generated<number>;
  right_text: string;
}

export interface DailyGrammarMcqs {
  correct_index: number;
  created_at: Generated<Timestamp>;
  day_number: number;
  id: Generated<Int8>;
  option_a: string;
  option_b: string;
  option_c: string;
  option_d: string;
  question_text: string;
  quiz_kind: string;
  sort_order: Generated<number>;
}

export interface DailyGrammarSentenceArrange {
  answer_ru: string;
  created_at: Generated<Timestamp>;
  day_number: number;
  id: Generated<Int8>;
  prompt_lang: string;
  prompt_text: string;
  sort_order: Generated<number>;
  word_bank: Generated<string[]>;
}

export interface DailyGrammarTopics {
  day_number: number;
  theory_text: Generated<string>;
  title: Generated<string>;
  updated_at: Generated<Timestamp>;
}

export interface DailyPracticePrompts {
  created_at: Generated<Timestamp>;
  day_number: number;
  id: Generated<Int8>;
  ru_correct: string;
  sort_order: Generated<number>;
  uz_text: string;
}

export interface DailyReadingLexemes {
  audio_ru: string | null;
  id: Generated<Int8>;
  text_id: string;
  translation_uz: string;
  updated_at: Generated<Timestamp>;
  word_ru: string;
  word_ru_normalized: Generated<string>;
}

export interface DailyReadingPassages {
  body_ru: Generated<string>;
  day_number: number;
  text_id: string;
  title: Generated<string>;
}

export interface DailyVocabWords {
  created_at: Generated<Timestamp>;
  day_number: number;
  id: Generated<Int8>;
  sort_order: Generated<number>;
  word_ru: string;
  word_uz: string;
}

export interface PartnerMatches {
  ended_at: Timestamp | null;
  id: Generated<number>;
  matched_at: Generated<Timestamp>;
  status: Generated<string>;
  user1_id: number;
  user2_id: number;
}

export interface PartnerProfiles {
  about: Generated<string>;
  age: number;
  created_at: Generated<Timestamp>;
  display_name: string;
  gender: string;
  goal: string;
  language_level: string;
  seeking: Generated<string>;
  updated_at: Generated<Timestamp>;
  user_id: number;
}

export interface PartnerRequests {
  created_at: Generated<Timestamp>;
  id: Generated<number>;
  receiver_id: number;
  responded_at: Timestamp | null;
  sender_id: number;
  status: Generated<string>;
}

export interface PatentVariantResults {
  completed_at: Generated<Timestamp>;
  correct_count: number;
  created_at: Generated<Timestamp>;
  id: Generated<Int8>;
  passed: Generated<boolean>;
  score_percent: number;
  total_count: number;
  updated_at: Generated<Timestamp>;
  user_id: Int8;
  variant_number: number;
}

export interface PaymentMethods {
  bank_name: string;
  card_holder_name: string;
  card_number: string;
  created_at: Generated<Timestamp>;
  currency: string;
  id: Generated<Int8>;
  phone_number: string | null;
  status: Generated<string>;
  updated_at: Generated<Timestamp>;
}

export interface Payments {
  admin_id: Int8 | null;
  amount: Numeric;
  approved_at: Timestamp | null;
  base_amount: Numeric | null;
  click_merchant_payment_id: string | null;
  click_refund_raw: Json | null;
  created_at: Generated<Timestamp>;
  currency: string | null;
  discount_amount: Generated<Numeric | null>;
  discount_meta: Json | null;
  fiscal_attempt_count: Generated<number>;
  fiscal_error: string | null;
  fiscal_raw_response: Json | null;
  fiscal_receipt_id: string | null;
  fiscal_status: string | null;
  id: Generated<Int8>;
  multicard_invoice_uuid: string | null;
  original_amount: Numeric | null;
  payment_channel: string | null;
  payment_proof_url: string | null;
  payment_time: Generated<Timestamp | null>;
  referral_discount_used: Generated<boolean | null>;
  refunded_at: Timestamp | null;
  status: Generated<string>;
  tariff_type: string | null;
  user_id: Int8;
}

export interface Referrals {
  created_at: Generated<Timestamp>;
  discount_used: Generated<boolean>;
  id: Generated<Int8>;
  payment_id: Int8 | null;
  referred_user_id: Int8;
  referrer_id: Int8;
  reward_amount: Numeric | null;
  rewarded_at: Timestamp | null;
  status: Generated<string>;
}

export interface ReferralWithdrawals {
  admin_receipt: string | null;
  amount: Numeric;
  card_number: string | null;
  created_at: Generated<Timestamp>;
  full_name: string | null;
  id: Generated<Int8>;
  phone: string | null;
  processed_at: Timestamp | null;
  status: Generated<string>;
  user_id: Int8;
}

export interface Subscriptions {
  auto_payment_enabled: Generated<boolean>;
  auto_payment_last_error: string | null;
  auto_payment_retry_count: Generated<number>;
  card_token_id: Int8 | null;
  expires_at: Timestamp;
  id: Generated<Int8>;
  next_payment_date: Timestamp | null;
  plan_type: string;
  started_at: Generated<Timestamp>;
  status: Generated<string>;
  user_id: Int8;
}

export interface SupportChatMessages {
  chat_id: Int8;
  content: string;
  created_at: Generated<Timestamp>;
  id: Generated<Int8>;
  sender_type: string;
  sender_user_id: Int8 | null;
}

export interface SupportChats {
  admin_last_read_at: Timestamp | null;
  created_at: Generated<Timestamp>;
  id: Generated<Int8>;
  last_message_at: Timestamp | null;
  status: Generated<string>;
  updated_at: Generated<Timestamp>;
  user_id: Int8;
  user_last_read_at: Timestamp | null;
}

export interface TariffPrices {
  created_at: Generated<Timestamp>;
  currency: string;
  id: Generated<Int8>;
  price: Numeric;
  tariff_type: string;
  updated_at: Generated<Timestamp>;
}

export interface UserActivityDates {
  activity_date: Timestamp;
  user_id: Int8;
}

export interface UserKunlikDayProgress {
  day_number: number;
  grammar_1: Generated<boolean>;
  grammar_2: Generated<boolean>;
  grammar_3: Generated<boolean>;
  oqish_done: Generated<boolean>;
  speaking_level: Generated<number>;
  updated_at: Generated<Timestamp>;
  user_id: Int8;
  words_correct: Generated<number>;
  words_learned: Generated<number>;
  words_match: Generated<boolean>;
}

export interface Users {
  avatar_url: string | null;
  gender: string | null;
  billing_notice_uz: string | null;
  /**
   * ISO 3166-1 alpha-2 country derived from normalized number.
   */
  country_code: string | null;
  created_at: Generated<Timestamp | null>;
  email: string | null;
  first_name: string | null;
  id: Generated<Int8>;
  last_name: string | null;
  level: Generated<string | null>;
  onboarded: Generated<number | null>;
  password: string;
  phone: string | null;
  /**
   * True when legacy value could not be normalized (manual cleanup).
   */
  phone_invalid: Generated<boolean>;
  /**
   * E.164 including leading + (UZ/KZ/RU/TJ/TJ subset enforced in app).
   */
  phone_normalized: string | null;
  /**
   * Original phone input at registration or last manual edit.
   */
  phone_raw: string | null;
  /**
   * OTP verification reserved for future use.
   */
  phone_verified: Generated<boolean>;
  plan_expires_at: Timestamp | null;
  plan_name: string | null;
  progress: Generated<number | null>;
  referral_balance: Generated<Numeric>;
  referral_code: string | null;
  referred_by: Int8 | null;
  russian_promo_expires_at: Timestamp | null;
  russian_promo_started_at: Timestamp | null;
  total_referral_earned: Generated<Numeric>;
}

export interface DB {
  admins: Admins;
  card_tokens: CardTokens;
  chat_messages: ChatMessages;
  click_payment_logs: ClickPaymentLogs;
  daily_grammar_matches: DailyGrammarMatches;
  daily_grammar_mcqs: DailyGrammarMcqs;
  daily_grammar_sentence_arrange: DailyGrammarSentenceArrange;
  daily_grammar_topics: DailyGrammarTopics;
  daily_practice_prompts: DailyPracticePrompts;
  daily_reading_lexemes: DailyReadingLexemes;
  daily_reading_passages: DailyReadingPassages;
  daily_vocab_words: DailyVocabWords;
  partner_matches: PartnerMatches;
  partner_profiles: PartnerProfiles;
  partner_requests: PartnerRequests;
  patent_variant_results: PatentVariantResults;
  payment_methods: PaymentMethods;
  payments: Payments;
  referral_withdrawals: ReferralWithdrawals;
  referrals: Referrals;
  subscriptions: Subscriptions;
  support_chat_messages: SupportChatMessages;
  support_chats: SupportChats;
  tariff_prices: TariffPrices;
  user_activity_dates: UserActivityDates;
  user_kunlik_day_progress: UserKunlikDayProgress;
  users: Users;
}
