/** Loopback-only real WhisperX QA; separate storage and ephemeral admin auth. Never mounted in production. */
import 'dotenv/config';
import express from 'express';
import { randomBytes } from 'node:crypto';
import path from 'node:path';
import jwt from 'jsonwebtoken';
import { createServer } from 'vite';
import react from '@vitejs/plugin-react';
import tailwindcss from '@tailwindcss/vite';
import type { DbClient } from '../../server/types/dbClient';
process.env.ADMIN_JWT_SECRET=randomBytes(32).toString('hex');
const {createAdminAuthMiddleware}=await import('../../server/middleware/adminAuth.js');
const {VideoLessonService}=await import('../../server/videoLessons/service.js');
const {LessonStore}=await import('../../server/videoLessons/store.js');
const {createAdminVideoLessonRoutes,createPublicVideoLessonRoutes}=await import('../../server/routes/videoLessonRoutes.js');
const root=process.env.VIDEO_LESSONS_TEST_DIR;
if(!root)throw Error('VIDEO_LESSONS_TEST_DIR is required');
const service=new VideoLessonService(new LessonStore(path.resolve(root)));
const authDb={from:()=>({select:()=>({eq:(_key:string,id:number)=>({maybeSingle:async()=>({data:id===1?{id:1}:null,error:null})})})})} as unknown as DbClient;
const token=jwt.sign({adminId:1,role:'admin'},process.env.ADMIN_JWT_SECRET,{expiresIn:'2h'});
const app=express();app.use(express.json({limit:'2mb'}));
app.get('/preview-admin',(_req,res)=>res.type('html').send(`<script>localStorage.setItem('adminToken',${JSON.stringify(token)});location.replace('/secure-admin-a9k7x4p2/video-lessons')</script>`));
app.use('/api/video-lessons',createPublicVideoLessonRoutes(service));
app.use('/api/admin',createAdminAuthMiddleware(authDb));
app.use('/api/admin/video-lessons',createAdminVideoLessonRoutes(service));
app.get('/api/admin/dashboard',(_req,res)=>res.json({}));
app.get('/api/admin/help-chats',(_req,res)=>res.json([]));
app.use('/api',(_req,res)=>res.status(404).json({error:'Outside isolated preview'}));
const vite=await createServer({configFile:false,root:process.cwd(),envDir:'/tmp/video-lesson-preview-env',plugins:[react(),tailwindcss()],define:{'import.meta.env.VITE_API_URL':'""','import.meta.env.VITE_ADMIN_PATH':'"/secure-admin-a9k7x4p2"'},server:{middlewareMode:true,hmr:{port:24683,host:'127.0.0.1'}},appType:'spa'});
app.use(vite.middlewares);app.listen(4183,'127.0.0.1',()=>console.log('Isolated video lesson QA listening on 127.0.0.1:4183'));
