-- Full speaking tasks seed for A1/A2/B1/B2
-- Generated from user-approved curriculum text

DELETE FROM public.speaking_tasks WHERE topic IN ('tanishuv', 'oila', 'uy_joy', 'shahar', 'xarid', 'ovqat_ichimlik', 'ish_sodda', 'kun_vaqt', 'kundalik_harakatlar', 'qongiroqlar', 'ish_batafsil', 'ofis', 'transport', 'sogliq', 'xarid_batafsil', 'restoran', 'sayohat', 'mehmonxona', 'xizmatlar', 'bosh_vaqt', 'muloqot', 'muammolar', 'ish_tajriba_b1', 'karyera_b1', 'talim_b1', 'fikr_va_dalil_b1', 'muloqot_odamlar_b1', 'muammo_yechim_b1', 'kochish_b1', 'hujjatlar_b1', 'pul_xarajat_b1', 'media_b1', 'dostlar_munosabat_b1', 'kundalik_muammo_b1', 'munozara_fikr_b2', 'taqqoslash_tahlil_b2', 'biznes_b2', 'jamiyat_b2', 'iqtisod_b2', 'argument_b2', 'muammo_chuqur_b2', 'maqsad_reja_b2', 'debat_b2', 'rivojlanish_b2', 'madaniyat_b2', 'texnologiya_b2');

INSERT INTO public.speaking_tasks (topic, level, sort_order, uz_text, ru_correct) VALUES
('tanishuv', 'A1', 1, 'Mening ismim Ali.', 'Меня зовут Али.'),
('tanishuv', 'A1', 2, 'Men O‘zbekistondan kelganman.', 'Я приехал из Узбекистана.'),
('tanishuv', 'A1', 3, 'Siz bilan tanishganimdan xursandman.', 'Рад с вами познакомиться.'),
('tanishuv', 'A1', 4, 'Bu mening do‘stim Jamshid.', 'Это мой друг Жамшид.'),
('tanishuv', 'A1', 5, 'Qayerliksiz?', 'Откуда вы?'),
('tanishuv', 'A1', 6, 'Men 25 yoshdaman.', 'Мне 25 лет.'),
('tanishuv', 'A1', 7, 'Men talabaman.', 'Я студент.'),
('tanishuv', 'A1', 8, 'U mening ukam.', 'Это мой младший брат.'),
('tanishuv', 'A1', 9, 'Sizning ismingiz nima?', 'Как вас зовут?'),
('tanishuv', 'A1', 10, 'Men rus tilini o‘rganyapman.', 'Я учу русский язык.'),
('tanishuv', 'A1', 11, 'Qandaysiz?', 'Как дела?'),
('tanishuv', 'A1', 12, 'Yaxshi, rahmat.', 'Хорошо, спасибо.'),
('tanishuv', 'A1', 13, 'U qayerda ishlaydi?', 'Где он работает?'),
('tanishuv', 'A1', 14, 'Bu mening sinfdoshim.', 'Это мой одноклассник.'),
('tanishuv', 'A1', 15, 'Men Toshkentda yashayman.', 'Я живу в Ташкенте.'),
('tanishuv', 'A1', 16, 'Siz bilan tanishganimdan baxtiyorman.', 'Счастлив познакомиться с вами.'),
('tanishuv', 'A1', 17, 'U kelgan mamlakat – Rossiya. – Страна, откуда он приехал', 'Россия.'),
('tanishuv', 'A1', 18, 'Biz bir guruhdamiz.', 'Мы в одной группе.'),
('tanishuv', 'A1', 19, 'Kechirasiz, sizni tushunmadim.', 'Извините, я вас не понял.'),
('tanishuv', 'A1', 20, 'Yana ko‘rishguncha!', 'До свидания!'),
('oila', 'A1', 1, 'Mening oilam katta.', 'Моя семья большая.'),
('oila', 'A1', 2, 'Onam shifokor.', 'Моя мама врач.'),
('oila', 'A1', 3, 'Akam muhandis.', 'Мой старший брат инженер.'),
('oila', 'A1', 4, 'Biz bir uyda yashaymiz.', 'Мы живём в одном доме.'),
('oila', 'A1', 5, 'Mening singlim bor.', 'У меня есть младшая сестра.'),
('oila', 'A1', 6, 'Otam ishlaydi.', 'Мой папа работает.'),
('oila', 'A1', 7, 'Bobom va buvim qishloqda yashaydi.', 'Дедушка и бабушка живут в деревне.'),
('oila', 'A1', 8, 'Mening ikki akam bor.', 'У меня два брата.'),
('oila', 'A1', 9, 'Opam universitetda o‘qiydi.', 'Моя старшая сестра учится в университете.'),
('oila', 'A1', 10, 'Biz har yakshanba birga ovqatlanamiz.', 'Каждое воскресенье мы едим вместе.'),
('oila', 'A1', 11, 'Mening katta oilam bor.', 'У меня большая семья.'),
('oila', 'A1', 12, 'U mening amakivachcham.', 'Это мой двоюродный брат.'),
('oila', 'A1', 13, 'Qaynonam mehribon.', 'Моя свекровь добрая.'),
('oila', 'A1', 14, 'Kuyovim muhandis.', 'Мой зять инженер.'),
('oila', 'A1', 15, 'Kelinim chiroyli.', 'Моя невестка красивая.'),
('oila', 'A1', 16, 'Farzandlarim maktabda o‘qiydi.', 'Мои дети учатся в школе.'),
('oila', 'A1', 17, 'Erim kecha ishdan kech keldi.', 'Мой муж вчера пришёл с работы поздно.'),
('oila', 'A1', 18, 'Xotinim non pishirdi.', 'Моя жена испекла хлеб.'),
('oila', 'A1', 19, 'Oilam men uchun eng muhimi.', 'Семья для меня самое важное.'),
('oila', 'A1', 20, 'Biz bir-birimizni sevamiz.', 'Мы любим друг друга.'),
('uy_joy', 'A1', 1, 'Uyimiz kichik, lekin qulay.', 'Наш дом маленький, но уютный.'),
('uy_joy', 'A1', 2, 'Xonamda stol va kompyuter bor.', 'В моей комнате есть стол и компьютер.'),
('uy_joy', 'A1', 3, 'Oshxona toza.', 'Кухня чистая.'),
('uy_joy', 'A1', 4, 'Hovlida gulzor bor.', 'Во дворе есть цветник.'),
('uy_joy', 'A1', 5, 'Qo‘shnilarim yaxshi odamlar.', 'Мои соседи хорошие люди.'),
('uy_joy', 'A1', 6, 'Yotoqxonamda katta karavot bor.', 'В моей спальне большая кровать.'),
('uy_joy', 'A1', 7, 'Tom ostidagi xona – bolalar xonasi. – Комната под крышей', 'детская.'),
('uy_joy', 'A1', 8, 'Bizning uyda uch xona bor.', 'В нашем доме три комнаты.'),
('uy_joy', 'A1', 9, 'Hammom va hojatxona alohida.', 'Ванная и туалет раздельные.'),
('uy_joy', 'A1', 10, 'Derazadan bog‘ ko‘rinadi.', 'Из окна виден сад.'),
('uy_joy', 'A1', 11, 'Uyning yonida garaj bor.', 'Рядом с домом есть гараж.'),
('uy_joy', 'A1', 12, 'Kiraverishda katta yo‘lak bor.', 'У входа есть большой коридор.'),
('uy_joy', 'A1', 13, 'Mehmonxona yorug‘ va keng.', 'Гостиная светлая и просторная.'),
('uy_joy', 'A1', 14, 'Mening uyim shaharning markazida.', 'Мой дом в центре города.'),
('uy_joy', 'A1', 15, 'Ijarada yashayman.', 'Я живу в арендованной квартире.'),
('uy_joy', 'A1', 16, 'Kommunal to‘lovlar qimmat.', 'Коммунальные платежи дорогие.'),
('uy_joy', 'A1', 17, 'Eshik qulflanganmi?', 'Дверь заперта?'),
('uy_joy', 'A1', 18, 'Kalitni stol ustiga qo‘ying.', 'Положите ключ на стол.'),
('uy_joy', 'A1', 19, 'Uyda muzlatgich va kir yuvish mashinasi bor.', 'Дома есть холодильник и стиральная машина.'),
('uy_joy', 'A1', 20, 'Biz yangi uy sotib oldik.', 'Мы купили новый дом.'),
('shahar', 'A1', 1, 'Shahrimiz go‘zal.', 'Наш город красивый.'),
('shahar', 'A1', 2, 'Sariq taksi bu yerda arzon.', 'Жёлтое такси здесь дешёвое.'),
('shahar', 'A1', 3, 'Metro bekati uzoq emas.', 'Станция метро недалеко.'),
('shahar', 'A1', 4, 'Ko‘chada ko‘p odam bor.', 'На улице много людей.'),
('shahar', 'A1', 5, 'Men adashib qoldim.', 'Я заблудился.'),
('shahar', 'A1', 6, 'Bu maydon juda katta.', 'Эта площадь очень большая.'),
('shahar', 'A1', 7, 'Favvora kechasi yoritilgan.', 'Фонтан подсвечен ночью.'),
('shahar', 'A1', 8, 'Shaharda bog‘lar va istirohat bog‘lari bor.', 'В городе есть парки и скверы.'),
('shahar', 'A1', 9, 'Kecha biz kinoteatrga bordik.', 'Вчера мы ходили в кинотеатр.'),
('shahar', 'A1', 10, 'Sirk yaqinida ko‘prik bor.', 'Возле цирка есть мост.'),
('shahar', 'A1', 11, 'Ko‘chani kesib o‘tishdan oldin svetoforga qarang.', 'Прежде чем перейти улицу, посмотрите на светофор.'),
('shahar', 'A1', 12, 'Piyodalar yo‘lagi qayerda?', 'Где пешеходная дорожка?'),
('shahar', 'A1', 13, 'Bu yerda to‘xtash mumkin emas.', 'Здесь нельзя останавливаться.'),
('shahar', 'A1', 14, 'Eng yaqin dorixona qayerda?', 'Где ближайшая аптека?'),
('shahar', 'A1', 15, 'Shahar markaziga avtobusda borish mumkin.', 'В центр города можно доехать на автобусе.'),
('shahar', 'A1', 16, 'Kechqurun ko‘chalar yorug‘.', 'Вечером улицы освещены.'),
('shahar', 'A1', 17, 'Men bu shaharda o‘sganman.', 'Я вырос в этом городе.'),
('shahar', 'A1', 18, 'Bu joy juda shovqinli.', 'Это место очень шумное.'),
('shahar', 'A1', 19, 'Shaharda iflos havo muammosi bor.', 'В городе есть проблема грязного воздуха.'),
('shahar', 'A1', 20, 'Men shahar hayotini yaxshi ko‘raman.', 'Мне нравится городская жизнь.'),
('xarid', 'A1', 1, 'Bir kilogramm olma bering.', 'Дайте один килограмм яблок.'),
('xarid', 'A1', 2, 'Qancha turadi?', 'Сколько стоит?'),
('xarid', 'A1', 3, 'Bu juda qimmat.', 'Это слишком дорого.'),
('xarid', 'A1', 4, 'Karta bilan to‘layman.', 'Я заплачу картой.'),
('xarid', 'A1', 5, 'Sizda non bormi?', 'У вас есть хлеб?'),
('xarid', 'A1', 6, 'Menga bir litr sut kerak.', 'Мне нужен один литр молока.'),
('xarid', 'A1', 7, 'Bu kiyimni sinab ko‘rish mumkinmi?', 'Можно примерить эту одежду?'),
('xarid', 'A1', 8, 'Sizda mayda pul bormi?', 'У вас есть мелкие деньги?'),
('xarid', 'A1', 9, 'Chekni olishim mumkinmi?', 'Могу я получить чек?'),
('xarid', 'A1', 10, 'Bu mahsulot chegirmadami?', 'Этот товар со скидкой?'),
('xarid', 'A1', 11, 'Qayerda go‘sht bo‘limi?', 'Где мясной отдел?'),
('xarid', 'A1', 12, 'Sabzavotlar yangimi?', 'Овощи свежие?'),
('xarid', 'A1', 13, 'Men faqat ko‘rish uchun keldim.', 'Я пришёл просто посмотреть.'),
('xarid', 'A1', 14, 'Sizda o‘lcham 38 bormi?', 'У вас есть размер 38?'),
('xarid', 'A1', 15, 'Rang yoqmay qoldi.', 'Цвет не понравился.'),
('xarid', 'A1', 16, 'Bu sovg‘a uchun qadoqlanganmi?', 'Это упаковано для подарка?'),
('xarid', 'A1', 17, 'Sotuvchi juda muloyim.', 'Продавец очень вежливый.'),
('xarid', 'A1', 18, 'Do‘kon soat 9 da yopiladi.', 'Магазин закрывается в 9 часов.'),
('xarid', 'A1', 19, 'Kechirasiz, navbat kimda?', 'Извините, чья очередь?'),
('xarid', 'A1', 20, 'Bugun katta savdo bor.', 'Сегодня большая распродажа.'),
('ovqat_ichimlik', 'A1', 1, 'Men choy ichaman.', 'Я пью чай.'),
('ovqat_ichimlik', 'A1', 2, 'Osh juda mazali.', 'Плов очень вкусный.'),
('ovqat_ichimlik', 'A1', 3, 'Non va qaymoq bering.', 'Дайте хлеб и сметану.'),
('ovqat_ichimlik', 'A1', 4, 'Men go‘sht yemayman.', 'Я не ем мясо.'),
('ovqat_ichimlik', 'A1', 5, 'Suv sovuq.', 'Вода холодная.'),
('ovqat_ichimlik', 'A1', 6, 'Nonushtaga nima yeysiz?', 'Что вы едите на завтрак?'),
('ovqat_ichimlik', 'A1', 7, 'Men tuxum va pishloqni yaxshi ko‘raman.', 'Я люблю яйца и сыр.'),
('ovqat_ichimlik', 'A1', 8, 'Sho‘rva issiq.', 'Суп горячий.'),
('ovqat_ichimlik', 'A1', 9, 'Kofe shakarsiz, iltimos.', 'Кофе без сахара, пожалуйста.'),
('ovqat_ichimlik', 'A1', 10, 'Sizda vegetarian taomlari bormi?', 'У вас есть вегетарианские блюда?'),
('ovqat_ichimlik', 'A1', 11, 'Men olma sharbatini xohlayman.', 'Я хочу яблочный сок.'),
('ovqat_ichimlik', 'A1', 12, 'Kek juda shirin.', 'Пирожное слишком сладкое.'),
('ovqat_ichimlik', 'A1', 13, 'Tuzni uzating.', 'Передайте соль.'),
('ovqat_ichimlik', 'A1', 14, 'Baliq yangi emas.', 'Рыба несвежая.'),
('ovqat_ichimlik', 'A1', 15, 'Men to‘ymadim.', 'Я не наелся.'),
('ovqat_ichimlik', 'A1', 16, 'Yana bir bo‘lak non olaman.', 'Возьму ещё кусок хлеба.'),
('ovqat_ichimlik', 'A1', 17, 'Ovqat tayyor.', 'Еда готова.'),
('ovqat_ichimlik', 'A1', 18, 'Kechki ovqatga makaron qaynatamiz.', 'На ужин сварим макароны.'),
('ovqat_ichimlik', 'A1', 19, 'Muzqaymoqni yoqtiraman.', 'Я люблю мороженое.'),
('ovqat_ichimlik', 'A1', 20, 'Meva-sabzavotlarni yuvish kerak.', 'Фрукты и овощи нужно мыть.'),
('ish_sodda', 'A1', 1, 'Men o‘qituvchiman.', 'Я учитель.'),
('ish_sodda', 'A1', 2, 'U haydovchi bo‘lib ishlaydi.', 'Он работает водителем.'),
('ish_sodda', 'A1', 3, 'Ish soat 9 da boshlanadi.', 'Работа начинается в 9 часов.'),
('ish_sodda', 'A1', 4, 'Mening maoshim yaxshi.', 'У меня хорошая зарплата.'),
('ish_sodda', 'A1', 5, 'Bugun ishga bormayman.', 'Сегодня я не иду на работу.'),
('ish_sodda', 'A1', 6, 'U shifoxonada hamshira.', 'Она медсестра в больнице.'),
('ish_sodda', 'A1', 7, 'Mening ishim juda qiziq.', 'Моя работа очень интересная.'),
('ish_sodda', 'A1', 8, 'Dam olish kunlari ishlamayman.', 'В выходные я не работаю.'),
('ish_sodda', 'A1', 9, 'Ishimga mashinada boraman.', 'Я езжу на работу на машине.'),
('ish_sodda', 'A1', 10, 'Ishxonada ko‘p odam bor.', 'В офисе много людей.'),
('ish_sodda', 'A1', 11, 'Rahbarim yaxshi odam.', 'Мой начальник хороший человек.'),
('ish_sodda', 'A1', 12, 'Ish joyim uyimga yaqin.', 'Моя работа близко к дому.'),
('ish_sodda', 'A1', 13, 'Men kechki smenada ishlayman.', 'Я работаю в вечернюю смену.'),
('ish_sodda', 'A1', 14, 'Ish haftasida 5 kun. – Рабочая неделя', '5 дней.'),
('ish_sodda', 'A1', 15, 'Men kasal bo‘lganim uchun ishga chiqmadim.', 'Я не вышел на работу, потому что заболел.'),
('ish_sodda', 'A1', 16, 'Ishdan keyin do‘stlarim bilan uchrashaman.', 'После работы встречаюсь с друзьями.'),
('ish_sodda', 'A1', 17, 'Ish stajim 2 yil.', 'Мой стаж работы 2 года.'),
('ish_sodda', 'A1', 18, 'U ofisda kompyuterda ishlaydi.', 'Он работает в офисе за компьютером.'),
('ish_sodda', 'A1', 19, 'Men ish qidiryapman.', 'Я ищу работу.'),
('ish_sodda', 'A1', 20, 'Vaqtinchalik ish topdim.', 'Я нашёл временную работу.'),
('kun_vaqt', 'A1', 1, 'Hozir soat 10.', 'Сейчас 10 часов.'),
('kun_vaqt', 'A1', 2, 'Men ertalab turaman.', 'Я встаю утром.'),
('kun_vaqt', 'A1', 3, 'Dushanba kuni ish bor.', 'В понедельник работа есть.'),
('kun_vaqt', 'A1', 4, 'Kechqurun kitob o‘qiyman.', 'Вечером я читаю книгу.'),
('kun_vaqt', 'A1', 5, 'Tushlik vaqti soat 13 da.', 'Время обеда в 13 часов.'),
('kun_vaqt', 'A1', 6, 'Soat nechida uxlaysiz?', 'Во сколько вы ложитесь спать?'),
('kun_vaqt', 'A1', 7, 'Bugun seshanba, ertaga chorshanba.', 'Сегодня вторник, завтра среда.'),
('kun_vaqt', 'A1', 8, 'Men soat 6 da uyg‘onaman.', 'Я просыпаюсь в 6 часов.'),
('kun_vaqt', 'A1', 9, 'Kecha juma edi.', 'Вчера была пятница.'),
('kun_vaqt', 'A1', 10, 'Bir soatdan keyin uchrashamiz.', 'Встретимся через час.'),
('kun_vaqt', 'A1', 11, 'U yarim soat kechikdi.', 'Он опоздал на полчаса.'),
('kun_vaqt', 'A1', 12, 'Ertalab soat 7 dan 9 gacha ishga boraman.', 'Утром с 7 до 9 я еду на работу.'),
('kun_vaqt', 'A1', 13, 'Kechki soat 11 da uyga qaytaman.', 'Возвращаюсь домой в 11 часов вечера.'),
('kun_vaqt', 'A1', 14, 'Yilning eng qisqa kuni – 21 dekabr. – Самый короткий день в году', '21 декабря.'),
('kun_vaqt', 'A1', 15, 'Men har kuni 8 soat uxlayman.', 'Я сплю каждый день по 8 часов.'),
('kun_vaqt', 'A1', 16, 'Bugun hafta oxiri.', 'Сегодня выходной.'),
('kun_vaqt', 'A1', 17, 'Men vaqtimni yaxshi rejalashtiraman.', 'Я хорошо планирую своё время.'),
('kun_vaqt', 'A1', 18, 'Soat to‘rtlar choy ichamiz.', 'В четыре часа пьём чай.'),
('kun_vaqt', 'A1', 19, 'Uch oydan keyin yoz keladi.', 'Через три месяца наступит лето.'),
('kun_vaqt', 'A1', 20, 'Sizga qulay vaqt qachon?', 'Когда вам удобно?'),
('kundalik_harakatlar', 'A1', 1, 'Men har kuni yuvinaman.', 'Я каждый день умываюсь.'),
('kundalik_harakatlar', 'A1', 2, 'Nonushtaga non va tuxum yeyman.', 'На завтрак я ем хлеб и яйца.'),
('kundalik_harakatlar', 'A1', 3, 'Keyin ishga boraman.', 'Потом я иду на работу.'),
('kundalik_harakatlar', 'A1', 4, 'Kechqurun televizor ko‘raman.', 'Вечером я смотрю телевизор.'),
('kundalik_harakatlar', 'A1', 5, 'Soat 23 da uxlayman.', 'В 23 часа я ложусь спать.'),
('kundalik_harakatlar', 'A1', 6, 'Tishlarimni yuvaman.', 'Чищу зубы.'),
('kundalik_harakatlar', 'A1', 7, 'Kiyinaman va ishga tayyorlanaman.', 'Одеваюсь и готовлюсь на работу.'),
('kundalik_harakatlar', 'A1', 8, 'Avtobusga chiqaman.', 'Сажусь в автобус.'),
('kundalik_harakatlar', 'A1', 9, 'Ishda kompyuterda yozaman.', 'На работе печатаю на компьютере.'),
('kundalik_harakatlar', 'A1', 10, 'Tushlikda oshxonada ovqatlanaman.', 'В обед ем в столовой.'),
('kundalik_harakatlar', 'A1', 11, 'Uyga qaytib, qo‘l yuvaman.', 'Возвращаюсь домой и мою руки.'),
('kundalik_harakatlar', 'A1', 12, 'Telefonda onam bilan gaplashaman.', 'Разговариваю с мамой по телефону.'),
('kundalik_harakatlar', 'A1', 13, 'Xonamni tozalayman.', 'Убираю свою комнату.'),
('kundalik_harakatlar', 'A1', 14, 'Dush qabul qilaman.', 'Принимаю душ.'),
('kundalik_harakatlar', 'A1', 15, 'Gazeta o‘qiyman.', 'Читаю газету.'),
('kundalik_harakatlar', 'A1', 16, 'Do‘stimga xabar yozaman.', 'Пишу сообщение другу.'),
('kundalik_harakatlar', 'A1', 17, 'Nonushta tayyorlayman.', 'Готовлю завтрак.'),
('kundalik_harakatlar', 'A1', 18, 'Kechki ovqatdan keyin idish yuvaman.', 'После ужина мою посуду.'),
('kundalik_harakatlar', 'A1', 19, 'Ertangi kunga reja tuzaman.', 'Составляю план на завтра.'),
('kundalik_harakatlar', 'A1', 20, 'Har payshanba sport bilan shug‘ullanaman.', 'Каждый четверг занимаюсь спортом.'),
('qongiroqlar', 'A1', 1, 'Assalomu alaykum, Alini so‘rayapman.', 'Здравствуйте, мне нужен Али.'),
('qongiroqlar', 'A1', 2, 'U uyda emas.', 'Его нет дома.'),
('qongiroqlar', 'A1', 3, 'Unga nima deb aytay?', 'Что ему передать?'),
('qongiroqlar', 'A1', 4, 'Qayta qo‘ng‘iroq qiling.', 'Перезвоните, пожалуйста.'),
('qongiroqlar', 'A1', 5, 'Raqamingizni yozib qo‘ying.', 'Запишите ваш номер.'),
('qongiroqlar', 'A1', 6, 'Siz noto‘g‘ri raqam terdingiz.', 'Вы набрали неверный номер.'),
('qongiroqlar', 'A1', 7, 'Kechirasiz, hozir gaplasha olmayman.', 'Извините, сейчас не могу говорить.'),
('qongiroqlar', 'A1', 8, 'Sizga keyin qo‘ng‘iroq qilaman.', 'Я позвоню вам позже.'),
('qongiroqlar', 'A1', 9, 'Ovozingiz yaxshi eshitilmayapti.', 'Вас плохо слышно.'),
('qongiroqlar', 'A1', 10, 'Tomosha qiling, aloqani uzmay.', 'Не вешайте трубку.'),
('qongiroqlar', 'A1', 11, 'Men sizga bir daqiqadan keyin qayta qo‘ng‘iroq qilaman.', 'Я перезвоню вам через минуту.'),
('qongiroqlar', 'A1', 12, 'Telefoningizni jim rejimga qo‘ying.', 'Поставьте телефон на беззвучный режим.'),
('qongiroqlar', 'A1', 13, 'Qabul qila olmay qoldim, band edi.', 'Не смог принять, было занято.'),
('qongiroqlar', 'A1', 14, 'Iltimos, ovozli xabar qoldiring.', 'Пожалуйста, оставьте голосовое сообщение.'),
('qongiroqlar', 'A1', 15, 'Sizga kim qo‘ng‘iroq qilgan?', 'Кто вам звонил?'),
('qongiroqlar', 'A1', 16, 'Qo‘ng‘iroqni kutib turing.', 'Ожидайте звонок.'),
('qongiroqlar', 'A1', 17, 'Telefonimning batareyasi tugayapti.', 'У моего телефона разряжается батарея.'),
('qongiroqlar', 'A1', 18, 'Qisqa xabar yuboring.', 'Отправьте короткое сообщение.'),
('qongiroqlar', 'A1', 19, 'Men sizning raqamingizni yo‘qotib qo‘ydim.', 'Я потерял ваш номер.'),
('qongiroqlar', 'A1', 20, 'Qo‘ng‘iroq uchun rahmat.', 'Спасибо за звонок.'),
('ish_batafsil', 'A2', 1, 'Men ofisda loyiha menejeri bo‘lib ishlayman.', 'Я работаю в офисе менеджером проектов.'),
('ish_batafsil', 'A2', 2, 'Ish kunim soat 9 dan 18 gacha.', 'Мой рабочий день с 9 до 18.'),
('ish_batafsil', 'A2', 3, 'Haftada ikki marta uydan ishlayman.', 'Два раза в неделю я работаю из дома.'),
('ish_batafsil', 'A2', 4, 'Mening vazifam hisobot tayyorlash. – Моя задача', 'готовить отчёты.'),
('ish_batafsil', 'A2', 5, 'Ish haqim oyiga 1000 dollar. – Моя зарплата', '1000 долларов в месяц.'),
('ish_batafsil', 'A2', 6, 'Mijozlar bilan muzokaralar olib boraman.', 'Провожу переговоры с клиентами.'),
('ish_batafsil', 'A2', 7, 'Ishga qabul qilishdan oldin suhbatdan o‘tdim.', 'Перед приёмом на работу я прошёл собеседование.'),
('ish_batafsil', 'A2', 8, 'Jamoada ishlashni yaxshi ko‘raman.', 'Люблю работать в команде.'),
('ish_batafsil', 'A2', 9, 'Mening xo‘jayinim talabchan.', 'Мой начальник требовательный.'),
('ish_batafsil', 'A2', 10, 'Ish vaqtida shaxsiy ishlar bilan shug‘ullanmaslik kerak.', 'В рабочее время нельзя заниматься личными делами.'),
('ish_batafsil', 'A2', 11, 'Oylik mukofot olaman.', 'Получаю ежемесячную премию.'),
('ish_batafsil', 'A2', 12, 'Ish stolim har doim tartibli.', 'Мой рабочий стол всегда в порядке.'),
('ish_batafsil', 'A2', 13, 'Kechki soat 20 dan keyin ishlamayman.', 'После 20 часов вечера не работаю.'),
('ish_batafsil', 'A2', 14, 'Ishdan bo‘shash uchun ariza yozdim.', 'Написал заявление на увольнение.'),
('ish_batafsil', 'A2', 15, 'Yangi xodimni o‘rgatyapman.', 'Обучаю нового сотрудника.'),
('ish_batafsil', 'A2', 16, 'Ish joyimda ingliz tili kerak.', 'На моей работе нужен английский язык.'),
('ish_batafsil', 'A2', 17, 'Ish safari bilan boshqa shaharga bordim.', 'Ездил в командировку в другой город.'),
('ish_batafsil', 'A2', 18, 'Mehnat shartnomasini imzoladim.', 'Подписал трудовой договор.'),
('ish_batafsil', 'A2', 19, 'Kasallik ta’tilini oldim.', 'Взял больничный.'),
('ish_batafsil', 'A2', 20, 'Ishdan keyin charchab qaytaman.', 'После работы возвращаюсь уставшим.'),
('ofis', 'A2', 1, 'Ofisimiz markazda joylashgan.', 'Наш офис находится в центре.'),
('ofis', 'A2', 2, 'Xodimlar uchun oshxona bor.', 'Для сотрудников есть кухня.'),
('ofis', 'A2', 3, 'Har payshanba yig‘ilish bo‘ladi.', 'Каждый четверг бывает собрание.'),
('ofis', 'A2', 4, 'Men printerdan foydalana olaman.', 'Я умею пользоваться принтером.'),
('ofis', 'A2', 5, 'Ish joyimda kompyuter va telefon bor.', 'На моём рабочем месте есть компьютер и телефон.'),
('ofis', 'A2', 6, 'Ofisda konditsioner ishlaydi.', 'В офисе работает кондиционер.'),
('ofis', 'A2', 7, 'Kofe mashinasi bepul.', 'Кофемашина бесплатная.'),
('ofis', 'A2', 8, 'Yig‘ilish xonasida proyektor bor.', 'В переговорной комнате есть проектор.'),
('ofis', 'A2', 9, 'Har bir xodimning shkafi bor.', 'У каждого сотрудника есть шкаф.'),
('ofis', 'A2', 10, 'Ofisga kech qolmaslikka harakat qilaman.', 'Стараюсь не опаздывать в офис.'),
('ofis', 'A2', 11, 'Xodimlar bir-biriga yordam berishadi.', 'Сотрудники помогают друг другу.'),
('ofis', 'A2', 12, 'Ofisda Wi-Fi tez.', 'В офисе быстрый Wi-Fi.'),
('ofis', 'A2', 13, 'Kirishda elektron kalit ishlatiladi.', 'На входе используется электронный ключ.'),
('ofis', 'A2', 14, 'Kechqurun ofis tozalanadi.', 'Вечером офис убирают.'),
('ofis', 'A2', 15, 'Ish stulim qulay.', 'Мой рабочий стул удобный.'),
('ofis', 'A2', 16, 'Ofisda o‘simliklar bor.', 'В офисе есть растения.'),
('ofis', 'A2', 17, 'Biz bir-birimizga tug‘ilgan kun uchun tabriklar yozamiz.', 'Мы пишем друг другу поздравления с днём рождения.'),
('ofis', 'A2', 18, 'Ish xonasi keng va yorug‘.', 'Рабочий кабинет просторный и светлый.'),
('ofis', 'A2', 19, 'Ofisda suv sovutgichi bor.', 'В офисе есть кулер с водой.'),
('ofis', 'A2', 20, 'Ish vaqtida telefonlarni jim rejimga qo‘yish kerak.', 'В рабочее время телефоны нужно ставить на беззвучный режим.'),
('transport', 'A2', 1, 'Metro eng tez transport turi. – Метро', 'самый быстрый вид транспорта.'),
('transport', 'A2', 2, 'Avtobus bekatiga piyoda 5 minut.', 'До автобусной остановки 5 минут пешком.'),
('transport', 'A2', 3, 'Taksiga buyurtma berish kerak.', 'Нужно заказать такси.'),
('transport', 'A2', 4, 'Chiptani kassadan oling.', 'Возьмите билет в кассе.'),
('transport', 'A2', 5, 'Kechga yaqin transport kam ishlaydi.', 'Ближе к вечеру транспорт ходит редко.'),
('transport', 'A2', 6, 'Qayerda troleybus bekati?', 'Где остановка троллейбуса?'),
('transport', 'A2', 7, 'Metro eskalatoridan ehtiyot bo‘ling.', 'Будьте осторожны на эскалаторе в метро.'),
('transport', 'A2', 8, 'Poyezd 5 daqiqadan keyin keladi.', 'Поезд придёт через 5 минут.'),
('transport', 'A2', 9, 'Chiptani komposterda teshish kerak.', 'Билет нужно прокомпостировать.'),
('transport', 'A2', 10, 'Haydovchiga «to‘xtang» deb aytdim.', 'Сказал водителю «остановите».'),
('transport', 'A2', 11, 'Jamoat transportida katta sumka bilan yurish noqulay.', 'В общественном транспорте неудобно ходить с большой сумкой.'),
('transport', 'A2', 12, 'Men velosipedda ishga boraman.', 'Я езжу на работу на велосипеде.'),
('transport', 'A2', 13, 'Poyezdda bo‘sh joy bormi?', 'Есть ли в поезде свободное место?'),
('transport', 'A2', 14, 'Uch soatlik yo‘l.', 'Трёхчасовая дорога.'),
('transport', 'A2', 15, 'Transportda karta bilan to‘lash mumkin.', 'В транспорте можно оплатить картой.'),
('transport', 'A2', 16, 'Kechirasiz, bu avtobus markazga boradimi?', 'Извините, этот автобус идёт в центр?'),
('transport', 'A2', 17, 'Men keyingi bekatda tushaman.', 'Я выхожу на следующей остановке.'),
('transport', 'A2', 18, 'Yomg‘ir yog‘ayotganda taksi chaqirish yaxshiroq.', 'Когда идёт дождь, лучше вызвать такси.'),
('transport', 'A2', 19, 'Samolyotda qo‘l yukining og‘irligi cheklangan.', 'В самолёте ограничен вес ручной клади.'),
('transport', 'A2', 20, 'Poyezd chiptasini internetda oldindan sotib olish mumkin.', 'Билет на поезд можно купить заранее в интернете.'),
('sogliq', 'A2', 1, 'Boshim og‘riyapti.', 'У меня болит голова.'),
('sogliq', 'A2', 2, 'Shifokorni chaqiring.', 'Вызовите врача.'),
('sogliq', 'A2', 3, 'Men kasal bo‘lib qoldim.', 'Я заболел.'),
('sogliq', 'A2', 4, 'Dorixonadan dori sotib oling.', 'Купите лекарство в аптеке.'),
('sogliq', 'A2', 5, 'Har kuni ertalab mashq qilish foydali.', 'Каждый день утром полезно делать зарядку.'),
('sogliq', 'A2', 6, 'Mening isitmam bor.', 'У меня температура.'),
('sogliq', 'A2', 7, 'Tomog‘im og‘riyapti.', 'У меня болит горло.'),
('sogliq', 'A2', 8, 'Allergiyam bor.', 'У меня аллергия.'),
('sogliq', 'A2', 9, 'Shifokor dam olishni tavsiya qildi.', 'Врач рекомендовал отдых.'),
('sogliq', 'A2', 10, 'Operatsiyadan keyin tez tuzalib ketdim.', 'После операции я быстро поправился.'),
('sogliq', 'A2', 11, 'Dori-darmonlarni ovqatdan keyin iching.', 'Принимайте лекарства после еды.'),
('sogliq', 'A2', 12, 'Tez yordam raqami 103.', 'Номер скорой помощи 103.'),
('sogliq', 'A2', 13, 'Men shamollab qoldim.', 'Я простудился.'),
('sogliq', 'A2', 14, 'Qon bosimim ko‘tarilib ketdi.', 'У меня поднялось давление.'),
('sogliq', 'A2', 15, 'Shifokor ko‘rikdan o‘tkazdi.', 'Врач провёл осмотр.'),
('sogliq', 'A2', 16, 'Sog‘lom ovqatlanish muhim.', 'Важно правильно питаться.'),
('sogliq', 'A2', 17, 'Men har yili tibbiy ko‘rikdan o‘taman.', 'Я каждый год прохожу медосмотр.'),
('sogliq', 'A2', 18, 'Tishim og‘riyapti, stomatologga borishim kerak.', 'У меня болит зуб, нужно пойти к стоматологу.'),
('sogliq', 'A2', 19, 'Ehtiyot bo‘ling, gripp epidemiyasi boshlandi.', 'Будьте осторожны, началась эпидемия гриппа.'),
('sogliq', 'A2', 20, 'Men sog‘lom hayot tarziga rioya qilaman.', 'Я придерживаюсь здорового образа жизни.'),
('xarid_batafsil', 'A2', 1, 'Menga qora kostyum kerak.', 'Мне нужен чёрный костюм.'),
('xarid_batafsil', 'A2', 2, 'Sizda 42 o‘lcham bormi?', 'У вас есть 42 размер?'),
('xarid_batafsil', 'A2', 3, 'Boshqa rang bormi?', 'Есть другой цвет?'),
('xarid_batafsil', 'A2', 4, 'Men bu mahsulotni qaytarib bera olamanmi?', 'Могу ли я вернуть этот товар?'),
('xarid_batafsil', 'A2', 5, 'Kvitansiyani saqlang.', 'Сохраните чек.'),
('xarid_batafsil', 'A2', 6, 'Chegirma karta bormi?', 'Есть ли дисконтная карта?'),
('xarid_batafsil', 'A2', 7, 'Bu qo‘l terisidan tayyorlangan.', 'Это сделано из натуральной кожи.'),
('xarid_batafsil', 'A2', 8, 'Men o‘lchamni sinab ko‘rmoqchiman.', 'Я хочу примерить размер.'),
('xarid_batafsil', 'A2', 9, 'Juda keng, kichikroq bormi?', 'Слишком широко, есть ли поменьше?'),
('xarid_batafsil', 'A2', 10, 'To‘lovni bo‘lib-bo‘lib to‘lash mumkinmi?', 'Можно ли оплатить в рассрочку?'),
('xarid_batafsil', 'A2', 11, 'Xaridni onlayn qilish qulay.', 'Делать покупки онлайн удобно.'),
('xarid_batafsil', 'A2', 12, 'Yetkazib berish bepulmi?', 'Доставка бесплатная?'),
('xarid_batafsil', 'A2', 13, 'Bu modelning zaxirada bormi?', 'Эта модель есть в наличии?'),
('xarid_batafsil', 'A2', 14, 'Men kassada kutaman.', 'Я подожду у кассы.'),
('xarid_batafsil', 'A2', 15, 'Sotuvchi menga maslahat berdi.', 'Продавец посоветовал мне.'),
('xarid_batafsil', 'A2', 16, 'Sifat juda yaxshi.', 'Качество очень хорошее.'),
('xarid_batafsil', 'A2', 17, 'Men pulni qaytarib olishni xohlayman.', 'Я хочу вернуть деньги.'),
('xarid_batafsil', 'A2', 18, 'Ayirboshlash muddati 14 kun. – Срок обмена', '14 дней.'),
('xarid_batafsil', 'A2', 19, 'Bugun supermarketda aksiya bor.', 'Сегодня в супермаркете акция.'),
('xarid_batafsil', 'A2', 20, 'Men odatda karta bilan to‘layman.', 'Я обычно плачу картой.'),
('restoran', 'A2', 1, 'Stolni ikki kishiga band qiling.', 'Забронируйте столик на двоих.'),
('restoran', 'A2', 2, 'Menga menyuni bering.', 'Дайте мне меню.'),
('restoran', 'A2', 3, 'Sizning imzo taomingiz nima?', 'Какое у вас фирменное блюдо?'),
('restoran', 'A2', 4, 'Qancha vaqt kutish kerak?', 'Сколько времени ждать?'),
('restoran', 'A2', 5, 'Hisobni keltiring, iltimos.', 'Принесите счёт, пожалуйста.'),
('restoran', 'A2', 6, 'Men steakni o‘rta qovurilgan istayman.', 'Я хочу стейк средней прожарки.'),
('restoran', 'A2', 7, 'Iltimos, tuzsiz.', 'Пожалуйста, без соли.'),
('restoran', 'A2', 8, 'Qo‘shimcha sous bering.', 'Дайте дополнительный соус.'),
('restoran', 'A2', 9, 'Bolalar uchun maxsus menyu bormi?', 'Есть ли специальное меню для детей?'),
('restoran', 'A2', 10, 'Ofitsiant juda muloyim edi.', 'Официант был очень вежливым.'),
('restoran', 'A2', 11, 'Biz tez ovqatlanish shoxobchasiga bordik.', 'Мы пошли в заведение быстрого питания.'),
('restoran', 'A2', 12, 'Kofe juda issiq, salqinlashini kuting.', 'Кофе очень горячий, подождите, пока остынет.'),
('restoran', 'A2', 13, 'Pishiriqlar yangi pishirilgan.', 'Пирожные свежеиспечённые.'),
('restoran', 'A2', 14, 'Men buyurtmani o‘zgartirmoqchiman.', 'Я хочу изменить заказ.'),
('restoran', 'A2', 15, 'Sizda alkogolsiz pivolar bormi?', 'У вас есть безалкогольное пиво?'),
('restoran', 'A2', 16, 'Kechki ovqat uchun stolni oldindan bron qildim.', 'Я заранее забронировал столик на ужин.'),
('restoran', 'A2', 17, 'Ovqat sovib qolgan, qizdiring.', 'Еда остыла, подогрейте.'),
('restoran', 'A2', 18, 'Muzlatilgan desertni yoqtirmayman.', 'Не люблю замороженный десерт.'),
('restoran', 'A2', 19, 'Hisobni bo‘lib to‘laymiz.', 'Мы платим отдельно.'),
('restoran', 'A2', 20, 'Restoranning manzilini yuboring.', 'Пришлите адрес ресторана.'),
('sayohat', 'A2', 1, 'Men Toshkentga sayohat qilmoqchiman.', 'Я хочу поехать в Ташкент.'),
('sayohat', 'A2', 2, 'Samolyot chiptasini oldindan sotib oling.', 'Купите авиабилет заранее.'),
('sayohat', 'A2', 3, 'Menda faqat qo‘l yuki bor.', 'У меня только ручная кладь.'),
('sayohat', 'A2', 4, 'Mehmonxonada nonushta bormi?', 'В гостинице есть завтрак?'),
('sayohat', 'A2', 5, 'Pasportingizni ko‘rsating.', 'Покажите ваш паспорт.'),
('sayohat', 'A2', 6, 'Chegara nazoratida navbat bor.', 'На паспортном контроле очередь.'),
('sayohat', 'A2', 7, 'Samolyot uchishi kechiktirildi.', 'Вылет самолёта задержали.'),
('sayohat', 'A2', 8, 'Bagajim yo‘qolib qoldi.', 'Мой багаж потерялся.'),
('sayohat', 'A2', 9, 'Sayohat sug‘urtasini olish kerak.', 'Нужно оформить туристическую страховку.'),
('sayohat', 'A2', 10, 'Ekskursiyalarga yozilish mumkin.', 'Можно записаться на экскурсии.'),
('sayohat', 'A2', 11, 'Dengiz bo‘yida dam olishni yaxshi ko‘raman.', 'Люблю отдыхать на море.'),
('sayohat', 'A2', 12, 'Tog‘larga sayohat qilish xavfli.', 'Путешествовать в горы опасно.'),
('sayohat', 'A2', 13, 'Biz bir haftalik tur paketini sotib oldik.', 'Мы купили недельный турпакет.'),
('sayohat', 'A2', 14, 'Mehmonxonada basseyn va sport zali bor.', 'В гостинице есть бассейн и тренажёрный зал.'),
('sayohat', 'A2', 15, 'Aeroportga qanday borsam bo‘ladi?', 'Как мне добраться до аэропорта?'),
('sayohat', 'A2', 16, 'Yotoqli poyezdda ketaylik.', 'Поедем на поезде с местами для лежания.'),
('sayohat', 'A2', 17, 'Yo‘lda ovqat olish uchun to‘xtadik.', 'Остановились, чтобы купить еду в дорогу.'),
('sayohat', 'A2', 18, 'Sayohat hujjatlarini tekshiring.', 'Проверьте документы для поездки.'),
('sayohat', 'A2', 19, 'Bepul shaharlar ro‘yxatiga kirmaydi.', 'Не входит в список безвизовых стран.'),
('sayohat', 'A2', 20, 'Sizga yoqimli sayohat tilayman!', 'Желаю вам приятного путешествия!'),
('mehmonxona', 'A2', 1, 'Bir kishilik xona bormi?', 'Есть одноместный номер?'),
('mehmonxona', 'A2', 2, 'Xonada konditsioner bormi?', 'В номере есть кондиционер?'),
('mehmonxona', 'A2', 3, 'Men ertaga chiqib ketaman.', 'Я выезжаю завтра.'),
('mehmonxona', 'A2', 4, 'Soat 12 da bo‘shatish kerak.', 'Нужно освободить номер в 12 часов.'),
('mehmonxona', 'A2', 5, 'Qo‘shimcha sochiq bering.', 'Дайте дополнительное полотенце.'),
('mehmonxona', 'A2', 6, 'Nonushta soat nechada?', 'Во сколько завтрак?'),
('mehmonxona', 'A2', 7, 'Xona raqamini unutib qo‘ydim.', 'Я забыл номер комнаты.'),
('mehmonxona', 'A2', 8, 'Wi-Fi parolini bera olasizmi?', 'Можете дать пароль от Wi-Fi?'),
('mehmonxona', 'A2', 9, 'Mehmonxonada avtoturargoh bormi?', 'В гостинице есть парковка?'),
('mehmonxona', 'A2', 10, 'Kechki ovqat mehmonxonada bo‘ladi.', 'Ужин будет в гостинице.'),
('mehmonxona', 'A2', 11, 'Men xonani yerto‘lada emas, yuqori qavatda xohlayman.', 'Я хочу номер не в подвале, а на верхнем этаже.'),
('mehmonxona', 'A2', 12, 'Xonangizda nonushta bilan bron qilmoqchiman.', 'Хочу забронировать номер с завтраком.'),
('mehmonxona', 'A2', 13, 'Kechirasiz, hammom oqmayapti.', 'Извините, в ванной не сливается вода.'),
('mehmonxona', 'A2', 14, 'Qo‘shimcha karavot bering.', 'Дайте дополнительную кровать.'),
('mehmonxona', 'A2', 15, 'Mehmonxona xodimlari yordam berishadi.', 'Сотрудники гостиницы помогают.'),
('mehmonxona', 'A2', 16, 'Eng yaqin metro qayerda?', 'Где ближайшее метро?'),
('mehmonxona', 'A2', 17, 'Xonani tozalashni so‘radim.', 'Я попросил убрать номер.'),
('mehmonxona', 'A2', 18, 'Kechiktirib chiqish uchun qancha to‘lash kerak?', 'Сколько нужно доплатить за поздний выезд?'),
('mehmonxona', 'A2', 19, 'Mehmonxonadagi nonushta juda xilma-xil.', 'Завтрак в гостинице очень разнообразный.'),
('mehmonxona', 'A2', 20, 'Men boshqa mehmonxonaga o‘tishni xohlayman.', 'Я хочу переехать в другую гостиницу.'),
('xizmatlar', 'A2', 1, 'Men karta ochmoqchiman.', 'Я хочу открыть карту.'),
('xizmatlar', 'A2', 2, 'Valyuta ayirboshlash kursi qancha?', 'Какой курс обмена валюты?'),
('xizmatlar', 'A2', 3, 'Posilkani qayerdan olish mumkin?', 'Где можно получить посылку?'),
('xizmatlar', 'A2', 4, 'Bu yerga zamonaviy xat qoldirmoqchiman.', 'Я хочу оставить заказное письмо.'),
('xizmatlar', 'A2', 5, 'Mening hisobimga pul tushdimi?', 'Деньги поступили на мой счёт?'),
('xizmatlar', 'A2', 6, 'Bankda navbat juda uzun.', 'В банке очень длинная очередь.'),
('xizmatlar', 'A2', 7, 'Kredit olish uchun qanday hujjatlar kerak?', 'Какие документы нужны для получения кредита?'),
('xizmatlar', 'A2', 8, 'Pul o‘tkazmasini amalga oshirish mumkinmi?', 'Можно сделать денежный перевод?'),
('xizmatlar', 'A2', 9, 'Posilkaning og‘irligini o‘lchab bering.', 'Взвесьте посылку.'),
('xizmatlar', 'A2', 10, 'Xalqaro pochta jo‘natmasi qancha vaqt ketadi?', 'Сколько времени идёт международное почтовое отправление?'),
('xizmatlar', 'A2', 11, 'Men onlayn bankdan foydalanaman.', 'Я пользуюсь интернет-банком.'),
('xizmatlar', 'A2', 12, 'Bank kartam bloklandi.', 'Моя банковская карта заблокирована.'),
('xizmatlar', 'A2', 13, 'To‘lovni terminal orqali amalga oshiring.', 'Оплатите через терминал.'),
('xizmatlar', 'A2', 14, 'Depozit ochish uchun foiz stavkasi qanday?', 'Какова процентная ставка для открытия вклада?'),
('xizmatlar', 'A2', 15, 'Bankomat yaqinidami?', 'Банкомат рядом?'),
('xizmatlar', 'A2', 16, 'Pochta markasini sotib olmoqchiman.', 'Хочу купить почтовую марку.'),
('xizmatlar', 'A2', 17, 'Mening manzilimga xat kelib tushdi.', 'На мой адрес пришло письмо.'),
('xizmatlar', 'A2', 18, 'Sizga bankdan qisqa xabar keladimi?', 'Вам приходит смс от банка?'),
('xizmatlar', 'A2', 19, 'Kechirasiz, bank soat 5 da yopiladi.', 'Извините, банк закрывается в 5 часов.'),
('xizmatlar', 'A2', 20, 'Men posilkani kuzatish raqamini so‘radim.', 'Я попросил трек-номер посылки.'),
('bosh_vaqt', 'A2', 1, 'Dam olish kunlari nima qilasiz?', 'Что вы делаете в выходные?'),
('bosh_vaqt', 'A2', 2, 'Men futbol o‘ynashni yaxshi ko‘raman.', 'Я люблю играть в футбол.'),
('bosh_vaqt', 'A2', 3, 'Kino tomosha qilaylikmi?', 'Давайте посмотрим кино?'),
('bosh_vaqt', 'A2', 4, 'Kechqurun sayrga chiqamiz.', 'Вечером идём гулять.'),
('bosh_vaqt', 'A2', 5, 'Sizga qanday musiqa yoqadi?', 'Какая музыка вам нравится?'),
('bosh_vaqt', 'A2', 6, 'Men kitob o‘qishni xush ko‘raman.', 'Я люблю читать книги.'),
('bosh_vaqt', 'A2', 7, 'Televizorda serial tomosha qilaman.', 'Смотрю сериал по телевизору.'),
('bosh_vaqt', 'A2', 8, 'Do‘stlarim bilan kafelarda uchrashamiz.', 'Встречаемся с друзьями в кафе.'),
('bosh_vaqt', 'A2', 9, 'Rasm chizish mening sevimli mashg‘ulotim. – Рисование', 'моё любимое занятие.'),
('bosh_vaqt', 'A2', 10, 'Kecha konsertda edim.', 'Вчера я был на концерте.'),
('bosh_vaqt', 'A2', 11, 'Haftada uch marta sport zaliga boraman.', 'Три раза в неделю хожу в спортзал.'),
('bosh_vaqt', 'A2', 12, 'Ochiq havoda piknik qilish yoqadi.', 'Нравится устраивать пикник на свежем воздухе.'),
('bosh_vaqt', 'A2', 13, 'Kompyuter o‘yinlarini o‘ynayman.', 'Играю в компьютерные игры.'),
('bosh_vaqt', 'A2', 14, 'Yozda ko‘l bo‘yiga sayohat qilamiz.', 'Летом ездим на озеро.'),
('bosh_vaqt', 'A2', 15, 'Kechqurun pianino chalishni o‘rganyapman.', 'Вечером учусь играть на пианино.'),
('bosh_vaqt', 'A2', 16, 'Sevimli serialimning yangi qismi chiqdi.', 'Вышла новая серия моего любимого сериала.'),
('bosh_vaqt', 'A2', 17, 'Men raqsga tushishni yaxshi ko‘raman.', 'Я люблю танцевать.'),
('bosh_vaqt', 'A2', 18, 'Dam olish kunlari uyda ovqat pishiraman.', 'В выходные готовлю еду дома.'),
('bosh_vaqt', 'A2', 19, 'Ko‘ngilochar parkka borish qiziq.', 'Интересно сходить в парк аттракционов.'),
('bosh_vaqt', 'A2', 20, 'Bo‘sh vaqtimda ingliz tilini o‘rganaman.', 'В свободное время учу английский.'),
('muloqot', 'A2', 1, 'Menga Telegramda xabar yuboring.', 'Напишите мне в Telegram.'),
('muloqot', 'A2', 2, 'Sizning qo‘ng‘iroq signalingizga javob bermadim.', 'Я не ответил на ваш звонок.'),
('muloqot', 'A2', 3, 'Rasmni qayerda yuklab olsam bo‘ladi?', 'Где можно скачать фото?'),
('muloqot', 'A2', 4, 'Kechirasiz, kech ko‘rdim.', 'Извините, поздно увидел.'),
('muloqot', 'A2', 5, 'Guruhga qanday qo‘shilish mumkin?', 'Как присоединиться к группе?'),
('muloqot', 'A2', 6, 'Iltimos, menga ovozli xabar yubormang.', 'Пожалуйста, не присылайте мне голосовые сообщения.'),
('muloqot', 'A2', 7, 'Sizni do‘stlar ro‘yxatiga qo‘shdim.', 'Я добавил вас в друзья.'),
('muloqot', 'A2', 8, 'Postingizga layk bosdim.', 'Я поставил лайк на ваш пост.'),
('muloqot', 'A2', 9, 'Sizning profilingiz maxfiy.', 'Ваш профиль закрытый.'),
('muloqot', 'A2', 10, 'Kecha sizga xabar yozdim, o‘qidingizmi?', 'Вчера я написал вам сообщение, вы прочитали?'),
('muloqot', 'A2', 11, 'Ijtimoiy tarmoqlarda juda ko‘p vaqt o‘tkazaman.', 'Я провожу много времени в соцсетях.'),
('muloqot', 'A2', 12, 'Bu xabar spamga o‘xshaydi.', 'Это сообщение похоже на спам.'),
('muloqot', 'A2', 13, 'Siz bilan shaxsiy xabarlarda gaplashaylik.', 'Давайте поговорим в личных сообщениях.'),
('muloqot', 'A2', 14, 'Ertaga jonli efir bo‘ladi.', 'Завтра будет прямой эфир.'),
('muloqot', 'A2', 15, 'Suratni tagiga izoh qoldiring.', 'Оставьте комментарий под фото.'),
('muloqot', 'A2', 16, 'Kanalga obuna bo‘ling.', 'Подпишитесь на канал.'),
('muloqot', 'A2', 17, 'Men sizni bloklamoqchi emasman.', 'Я не хочу вас блокировать.'),
('muloqot', 'A2', 18, 'Ushbu xabarni hammaga yuboring.', 'Перешлите это сообщение всем.'),
('muloqot', 'A2', 19, 'Nega onlayn ko‘rinasiz, lekin javob bermaysiz?', 'Почему вы в сети, но не отвечаете?'),
('muloqot', 'A2', 20, 'Iltimos, shaxsiy ma’lumotlarni tarmoqda e’lon qilmang.', 'Пожалуйста, не публикуйте личную информацию в сети.'),
('muammolar', 'A2', 1, 'Kechirasiz, men kechikdim.', 'Извините, я опоздал.'),
('muammolar', 'A2', 2, 'Kalitimni uyda unutib qo‘ydim.', 'Я забыл ключи дома.'),
('muammolar', 'A2', 3, 'Telefonim o‘chib qoldi.', 'У меня разрядился телефон.'),
('muammolar', 'A2', 4, 'Manzilni topa olmayapman.', 'Не могу найти адрес.'),
('muammolar', 'A2', 5, 'Yordam kerak.', 'Нужна помощь.'),
('muammolar', 'A2', 6, 'Hamyonimni yo‘qotib qo‘ydim.', 'Я потерял кошелёк.'),
('muammolar', 'A2', 7, 'Mashinam ishga tushmayapti.', 'Моя машина не заводится.'),
('muammolar', 'A2', 8, 'Vaqtni noto‘g‘ri eshitibman.', 'Я неправильно расслышал время.'),
('muammolar', 'A2', 9, 'Internet aloqasi uzilib qoldi.', 'Соединение с интернетом прервалось.'),
('muammolar', 'A2', 10, 'Men o‘zimni yomon his qilyapman.', 'Я плохо себя чувствую.'),
('muammolar', 'A2', 11, 'Chiptani uyda qoldirib kelibman.', 'Я оставил билет дома.'),
('muammolar', 'A2', 12, 'Avtobusni kutib charchadim.', 'Устал ждать автобус.'),
('muammolar', 'A2', 13, 'Do‘stim va’dasida turmadi.', 'Мой друг не сдержал обещание.'),
('muammolar', 'A2', 14, 'Ishga kech qolmaslik uchun erta chiqdim.', 'Чтобы не опоздать на работу, вышел пораньше.'),
('muammolar', 'A2', 15, 'Telefonimni tushirib sindirib qo‘ydim.', 'Уронил телефон и разбил.'),
('muammolar', 'A2', 16, 'Karta bilan to‘lov o‘tmadi.', 'Оплата картой не прошла.'),
('muammolar', 'A2', 17, 'Bugun juda charchadim.', 'Сегодня очень устал.'),
('muammolar', 'A2', 18, 'Muzlatgich ishlamayapti, ovqat buzilib ketdi.', 'Холодильник не работает, еда испортилась.'),
('muammolar', 'A2', 19, 'Kechirasiz, sizni eslay olmayman.', 'Извините, я вас не помню.'),
('muammolar', 'A2', 20, 'Yana bir marta takrorlaysizmi?', 'Вы не повторите ещё раз?'),
('ish_tajriba_b1', 'B1', 1, 'Mening vazifalarimga mijozlar bilan muzokaralar kiradi.', 'Мои обязанности включают переговоры с клиентами.'),
('ish_tajriba_b1', 'B1', 2, 'Uch yillik tajribaga egaman.', 'У меня трёхлетний опыт.'),
('ish_tajriba_b1', 'B1', 3, 'Loyiha ustida jamoa bo‘lib ishlaymiz.', 'Мы работаем над проектом командой.'),
('ish_tajriba_b1', 'B1', 4, 'Ishdan keyin qo‘shimcha mashg‘ulotlar bor.', 'После работы есть дополнительные занятия.'),
('ish_tajriba_b1', 'B1', 5, 'Menejer mening hisobotimni ma’qulladi.', 'Менеджер одобрил мой отчёт.'),
('ish_tajriba_b1', 'B1', 6, 'Men bir vaqtning o‘zida bir nechta vazifani bajaraman.', 'Я выполняю несколько задач одновременно.'),
('ish_tajriba_b1', 'B1', 7, 'Ish joyimda avtonom ishlay olish muhim.', 'На моей работе важно уметь работать автономно.'),
('ish_tajriba_b1', 'B1', 8, 'Men o‘tgan yili muvaffaqiyatli loyihani yakunladim.', 'В прошлом году я успешно завершил проект.'),
('ish_tajriba_b1', 'B1', 9, 'Xodimlar o‘rtasida mas’uliyatni taqsimlaymiz.', 'Распределяем ответственность между сотрудниками.'),
('ish_tajriba_b1', 'B1', 10, 'Mening ishim stressli, lekin qiziq.', 'Моя работа стрессовая, но интересная.'),
('ish_tajriba_b1', 'B1', 11, 'Ishga kirishda tavsiya xati kerak edi.', 'При приёме на работу требовалось рекомендательное письмо.'),
('ish_tajriba_b1', 'B1', 12, 'Men vaqtinchalik loyihada ishlayapman.', 'Я работаю над временным проектом.'),
('ish_tajriba_b1', 'B1', 13, 'Ish beruvchi tajriba va malakaga qaraydi.', 'Работодатель смотрит на опыт и квалификацию.'),
('ish_tajriba_b1', 'B1', 14, 'Men ko‘pincha qo‘shimcha ish vaqtida qolaman.', 'Я часто задерживаюсь на сверхурочную работу.'),
('ish_tajriba_b1', 'B1', 15, 'Ish haqim har oyning 10-sanasida keladi.', 'Моя зарплата приходит 10-го числа каждого месяца.'),
('ish_tajriba_b1', 'B1', 16, 'Men ishdan ketish sababimni tushuntirdim.', 'Я объяснил причину своего ухода с работы.'),
('ish_tajriba_b1', 'B1', 17, 'Ish joyida doimiy ravishda yangi narsalarni o‘rganaman.', 'На работе постоянно учусь новому.'),
('ish_tajriba_b1', 'B1', 18, 'Mening birinchi ishim juda oddiy edi.', 'Моя первая работа была очень простой.'),
('ish_tajriba_b1', 'B1', 19, 'Xodimlarni baholash har chorakda o‘tkaziladi.', 'Оценка сотрудников проводится каждый квартал.'),
('ish_tajriba_b1', 'B1', 20, 'Men ishda halol va mas’uliyatli bo‘lishga harakat qilaman.', 'Я стараюсь быть честным и ответственным в работе.'),
('karyera_b1', 'B1', 1, 'Men kelajakda o‘z biznesimni ochmoqchiman.', 'В будущем я хочу открыть свой бизнес.'),
('karyera_b1', 'B1', 2, 'Ish joyimni o‘zgartirish haqida o‘ylayapman.', 'Я думаю о смене работы.'),
('karyera_b1', 'B1', 3, 'Bu kompaniyada o‘sish imkoniyati bor.', 'В этой компании есть возможность роста.'),
('karyera_b1', 'B1', 4, 'Malaka oshirish kurslariga borish foydali.', 'Полезно ходить на курсы повышения квалификации.'),
('karyera_b1', 'B1', 5, 'Mening kasbim juda talabga ega.', 'Моя профессия очень востребована.'),
('karyera_b1', 'B1', 6, 'Men uzoq muddatli martaba rejasini tuzdim.', 'Я составил долгосрочный карьерный план.'),
('karyera_b1', 'B1', 7, 'Menejerlik lavozimiga ko‘tarilishni xohlayman.', 'Хочу повышения до должности менеджера.'),
('karyera_b1', 'B1', 8, 'U karerasini butunlay o‘zgartirdi.', 'Он полностью сменил карьеру.'),
('karyera_b1', 'B1', 9, 'Ko‘pchilik yaxshi maosh uchun emas, balki o‘sish uchun ishlaydi.', 'Многие работают не ради высокой зарплаты, а ради роста.'),
('karyera_b1', 'B1', 10, 'Men o‘z sohamda mutaxassis bo‘lishni maqsad qilganman.', 'Я поставил цель стать экспертом в своей области.'),
('karyera_b1', 'B1', 11, 'Ish intervyusida kuchli va zaif tomonlarim haqida so‘rashdi.', 'На собеседовании спросили о моих сильных и слабых сторонах.'),
('karyera_b1', 'B1', 12, 'Uning martaba zinapoyasi tez ko‘tarildi.', 'Его карьерная лестница быстро поднялась.'),
('karyera_b1', 'B1', 13, 'Men ikkinchi oliy ma’lumot olishni rejalashtiryapman.', 'Я планирую получить второе высшее образование.'),
('karyera_b1', 'B1', 14, 'Ish joyini almashtirish har doim xavf bilan bog‘liq.', 'Смена работы всегда связана с риском.'),
('karyera_b1', 'B1', 15, 'Bizning kompaniyada ichki ko‘tarilish imkoniyati bor.', 'В нашей компании есть возможность внутреннего повышения.'),
('karyera_b1', 'B1', 16, 'Men tarmoq aloqalarini (networking) rivojlantirishga harakat qilaman.', 'Я стараюсь развивать деловые связи.'),
('karyera_b1', 'B1', 17, 'U o‘z biznesini yuritishda muvaffaqiyatga erishdi.', 'Он добился успеха в ведении своего бизнеса.'),
('karyera_b1', 'B1', 18, 'Kasbiy rivojlanish hech qachon to‘xtamasligi kerak.', 'Профессиональное развитие никогда не должно останавливаться.'),
('karyera_b1', 'B1', 19, 'Men bir nechta kompaniyalarda stajirovkadan o‘tdim.', 'Я прошёл стажировку в нескольких компаниях.'),
('karyera_b1', 'B1', 20, 'Kelajakda men rahbar bo‘lishni istayman.', 'В будущем я хочу стать руководителем.'),
('talim_b1', 'B1', 1, 'Universitetda ikkinchi kursda o‘qiyman.', 'Я учусь на втором курсе университета.'),
('talim_b1', 'B1', 2, 'Imtihonga tayyorgarlik ko‘rish qiyin.', 'Готовиться к экзамену трудно.'),
('talim_b1', 'B1', 3, 'Grant asosida o‘qish imkoniyati bor.', 'Есть возможность учиться на гранте.'),
('talim_b1', 'B1', 4, 'Diplom himoyasidan keyin ishga joylashaman.', 'После защиты диплома я устроюсь на работу.'),
('talim_b1', 'B1', 5, 'Kutubxonada ko‘p vaqt o‘tkazaman.', 'Я провожу много времени в библиотеке.'),
('talim_b1', 'B1', 6, 'Men masofaviy ta’limni tanladim.', 'Я выбрал дистанционное обучение.'),
('talim_b1', 'B1', 7, 'O‘qituvchi juda qattiq, lekin bilimli.', 'Учитель очень строгий, но знающий.'),
('talim_b1', 'B1', 8, 'Magistraturaga kirish uchun imtihon topshirdim.', 'Сдал экзамен для поступления в магистратуру.'),
('talim_b1', 'B1', 9, 'Men ilm-fan sohasida tadqiqot qilmoqchiman.', 'Я хочу заниматься исследованиями в области науки.'),
('talim_b1', 'B1', 10, 'Kurs ishini muddatida topshirish kerak.', 'Нужно сдать курсовую работу в срок.'),
('talim_b1', 'B1', 11, 'Maktabda men matematikani yaxshi ko‘rardim.', 'В школе я любил математику.'),
('talim_b1', 'B1', 12, 'O‘qishni tamomlagach, chet elda ishlashni rejalashtiryapman.', 'После окончания учёбы планирую работать за границей.'),
('talim_b1', 'B1', 13, 'Talabalar uchun stipendiya yetarli emas.', 'Стипендии для студентов недостаточно.'),
('talim_b1', 'B1', 14, 'Universitetda tanlov fanlari mavjud.', 'В университете есть предметы по выбору.'),
('talim_b1', 'B1', 15, 'Men o‘qish va ishni birlashtiraman.', 'Я совмещаю учёбу и работу.'),
('talim_b1', 'B1', 16, 'Imtihonda yuqori ball oldim.', 'Я получил высокий балл на экзамене.'),
('talim_b1', 'B1', 17, 'O‘qituvchi meni imtihonga qayta topshirishga ruxsat berdi.', 'Учитель разрешил мне пересдать экзамен.'),
('talim_b1', 'B1', 18, 'Mening diplomim xalqaro sertifikat bilan tasdiqlangan.', 'Мой диплом подтверждён международным сертификатом.'),
('talim_b1', 'B1', 19, 'O‘qish jarayonida ko‘plab yangi do‘stlar orttirdim.', 'За время учёбы приобрёл много новых друзей.'),
('talim_b1', 'B1', 20, 'Ta’lim – hayotdagi eng katta boylik. – Образование', 'величайшее богатство в жизни.'),
('fikr_va_dalil_b1', 'B1', 1, 'Menimcha, bu to‘g‘ri emas.', 'По-моему, это неправильно.'),
('fikr_va_dalil_b1', 'B1', 2, 'Bir tomondan, bu yaxshi, lekin…', 'С одной стороны, это хорошо, но…'),
('fikr_va_dalil_b1', 'B1', 3, 'Boshqa fikrlar ham bor.', 'Есть и другие мнения.'),
('fikr_va_dalil_b1', 'B1', 4, 'Men sizga qo‘shilaman, chunki…', 'Я согласен с вами, потому что…'),
('fikr_va_dalil_b1', 'B1', 5, 'Aniq dalillar keltirish kerak.', 'Нужно привести чёткие доказательства.'),
('fikr_va_dalil_b1', 'B1', 6, 'Men bunga qat’iy qarshi.', 'Я категорически против этого.'),
('fikr_va_dalil_b1', 'B1', 7, 'Hech kim meni ishontira olmadi.', 'Никто не смог меня убедить.'),
('fikr_va_dalil_b1', 'B1', 8, 'Sizning fikringiz qiziq, ammo men boshqacha o‘ylayman.', 'Ваше мнение интересно, но я думаю иначе.'),
('fikr_va_dalil_b1', 'B1', 9, 'Keling, faktlarga asoslanaylik.', 'Давайте опираться на факты.'),
('fikr_va_dalil_b1', 'B1', 10, 'Men bu masalada betarafman.', 'Я нейтрален в этом вопросе.'),
('fikr_va_dalil_b1', 'B1', 11, 'Ko‘pchilik shunday deb o‘ylaydi, lekin xato.', 'Многие так думают, но ошибаются.'),
('fikr_va_dalil_b1', 'B1', 12, 'Sizning argumentlaringiz mantiqqa to‘g‘ri kelmaydi.', 'Ваши аргументы нелогичны.'),
('fikr_va_dalil_b1', 'B1', 13, 'Men shaxsiy tajribamga asoslanib gapiryapman.', 'Я говорю, основываясь на личном опыте.'),
('fikr_va_dalil_b1', 'B1', 14, 'Faraz qilaylik, siz haqsiz, keyin nima?', 'Предположим, вы правы, что дальше?'),
('fikr_va_dalil_b1', 'B1', 15, 'Bu masala bo‘yicha konsensusga erishish qiyin.', 'По этому вопросу трудно достичь консенсуса.'),
('fikr_va_dalil_b1', 'B1', 16, 'Men sizni hurmat qilaman, lekin fikringizga qo‘shilmayman.', 'Я вас уважаю, но не согласен с вашим мнением.'),
('fikr_va_dalil_b1', 'B1', 17, 'Statistik ma’lumotlar aksini ko‘rsatadi.', 'Статистические данные показывают обратное.'),
('fikr_va_dalil_b1', 'B1', 18, 'Insonlar ko‘pincha his-tuyg‘ulariga asoslanib qaror qabul qilishadi.', 'Люди часто принимают решения, основываясь на эмоциях.'),
('fikr_va_dalil_b1', 'B1', 19, 'Men o‘z fikrimni himoya qilishga tayyorman.', 'Я готов защищать своё мнение.'),
('fikr_va_dalil_b1', 'B1', 20, 'Ob’ektiv bo‘lishga harakat qiling.', 'Постарайтесь быть объективным.'),
('muloqot_odamlar_b1', 'B1', 1, 'Odamlar bilan umumiy til topish muhim.', 'Важно находить общий язык с людьми.'),
('muloqot_odamlar_b1', 'B1', 2, 'U juda xushmuomala va yordamga tayyor.', 'Он очень вежливый и готов помочь.'),
('muloqot_odamlar_b1', 'B1', 3, 'Kechirim so‘rashdan uyalmang.', 'Не стесняйтесь извиняться.'),
('muloqot_odamlar_b1', 'B1', 4, 'U bilan gaplashish yoqimli.', 'С ним приятно разговаривать.'),
('muloqot_odamlar_b1', 'B1', 5, 'Konfliktni tinch yo‘l bilan hal qilish kerak.', 'Конфликт нужно решать мирным путём.'),
('muloqot_odamlar_b1', 'B1', 6, 'Yaxshi tinglovchi bo‘lish – san’at. – Быть хорошим слушателем', 'искусство.'),
('muloqot_odamlar_b1', 'B1', 7, 'U har doim gapni bo‘lib qo‘yadi.', 'Он всегда перебивает.'),
('muloqot_odamlar_b1', 'B1', 8, 'Begona odam bilan suhbatni qanday boshlash kerak?', 'Как начать разговор с незнакомцем?'),
('muloqot_odamlar_b1', 'B1', 9, 'U menga sovuq muomala qilmoqda.', 'Он ведёт себя со мной холодно.'),
('muloqot_odamlar_b1', 'B1', 10, 'Men odamlarning kayfiyatini his qilaman.', 'Я чувствую настроение людей.'),
('muloqot_odamlar_b1', 'B1', 11, 'Yolg‘on gapirish munosabatlarga putur yetkazadi.', 'Ложь вредит отношениям.'),
('muloqot_odamlar_b1', 'B1', 12, 'U juda kamtar va ochiq.', 'Он очень скромный и открытый.'),
('muloqot_odamlar_b1', 'B1', 13, 'Katta guruhda gaplashish menga qiyin.', 'Мне трудно говорить в большой группе.'),
('muloqot_odamlar_b1', 'B1', 14, 'Siz bilan gaplashish menga yoqadi.', 'Мне нравится с вами разговаривать.'),
('muloqot_odamlar_b1', 'B1', 15, 'Biz bir-birimizga hazil qilamiz.', 'Мы шутим друг над другом.'),
('muloqot_odamlar_b1', 'B1', 16, 'U doim yordam taklif qiladi.', 'Он всегда предлагает помощь.'),
('muloqot_odamlar_b1', 'B1', 17, 'Men odamlarning ko‘ziga qarab gapirishga harakat qilaman.', 'Стараюсь говорить людям в глаза.'),
('muloqot_odamlar_b1', 'B1', 18, 'Yomon kayfiyatingizni boshqalarga chiqarmang.', 'Не вымещайте плохое настроение на других.'),
('muloqot_odamlar_b1', 'B1', 19, 'Biz muntazam ravishda telefon orqali gaplashib turamiz.', 'Мы регулярно разговариваем по телефону.'),
('muloqot_odamlar_b1', 'B1', 20, 'Ijtimoiy tarmoqlarda muloqot jonli muloqot o‘rnini bosa olmaydi.', 'Общение в соцсетях не заменит живого общения.'),
('muammo_yechim_b1', 'B1', 1, 'Mening kompyuterim ishlamayapti.', 'Мой компьютер не работает.'),
('muammo_yechim_b1', 'B1', 2, 'Elektr uzilib qoldi.', 'Отключили электричество.'),
('muammo_yechim_b1', 'B1', 3, 'Internet tezligi juda past.', 'Скорость интернета очень низкая.'),
('muammo_yechim_b1', 'B1', 4, 'Buning bir necha yechimi bor.', 'Есть несколько решений этого.'),
('muammo_yechim_b1', 'B1', 5, 'Mutaxassisni chaqirish kerak.', 'Нужно вызвать специалиста.'),
('muammo_yechim_b1', 'B1', 6, 'Muzlatgichdan suv oqmoqda.', 'Из холодильника течёт вода.'),
('muammo_yechim_b1', 'B1', 7, 'Viza muddati tugayapti, uzaytirish kerak.', 'Заканчивается виза, нужно продлить.'),
('muammo_yechim_b1', 'B1', 8, 'Biznesda muammolar yuzaga keldi.', 'В бизнесе возникли проблемы.'),
('muammo_yechim_b1', 'B1', 9, 'Qisqa vaqt ichida qaror qabul qilishim kerak.', 'Мне нужно принять решение за короткое время.'),
('muammo_yechim_b1', 'B1', 10, 'Muammoni e’tiborsiz qoldirish mumkin emas.', 'Нельзя игнорировать проблему.'),
('muammo_yechim_b1', 'B1', 11, 'Birgalikda yechim topish osonroq.', 'Вместе легче найти решение.'),
('muammo_yechim_b1', 'B1', 12, 'Eng yomoni shundaki, biz hech narsa qilmaymiz.', 'Хуже всего то, что мы ничего не делаем.'),
('muammo_yechim_b1', 'B1', 13, 'U har qanday muammodan chiqish yo‘lini topadi.', 'Он находит выход из любой проблемы.'),
('muammo_yechim_b1', 'B1', 14, 'Moliyaviy qiyinchiliklar bizni to‘xtata olmaydi.', 'Финансовые трудности не могут нас остановить.'),
('muammo_yechim_b1', 'B1', 15, 'Kechirasiz, bu sizning muammoingiz emas.', 'Извините, это не ваша проблема.'),
('muammo_yechim_b1', 'B1', 16, 'Qarama-qarshilikni konstruktiv hal qilish mumkin.', 'Противопоставление можно решить конструктивно.'),
('muammo_yechim_b1', 'B1', 17, 'Kechikishlar jiddiy muammoga aylandi.', 'Опоздания стали серьёзной проблемой.'),
('muammo_yechim_b1', 'B1', 18, 'Eng yaxshi yechim – oldini olish. – Лучшее решение', 'профилактика.'),
('muammo_yechim_b1', 'B1', 19, 'U o‘z muammolari haqida gapirishni yoqtirmaydi.', 'Он не любит говорить о своих проблемах.'),
('muammo_yechim_b1', 'B1', 20, 'Vaqt o‘tishi bilan muammo o‘z-o‘zidan hal bo‘ladi.', 'Со временем проблема решится сама собой.'),
('kochish_b1', 'B1', 1, 'Men boshqa shaharga ko‘chib o‘tdim.', 'Я переехал в другой город.'),
('kochish_b1', 'B1', 2, 'Yangi joyga moslashish qiyin.', 'Трудно привыкнуть к новому месту.'),
('kochish_b1', 'B1', 3, 'Mahalliy tilni o‘rganish kerak.', 'Нужно выучить местный язык.'),
('kochish_b1', 'B1', 4, 'Viza muddatini uzaytirish mumkinmi?', 'Можно продлить визу?'),
('kochish_b1', 'B1', 5, 'Vatanimni sog‘indim.', 'Я скучаю по родине.'),
('kochish_b1', 'B1', 6, 'Boshqa mamlakatda yashash dunyoqarashni kengaytiradi.', 'Жизнь в другой стране расширяет кругозор.'),
('kochish_b1', 'B1', 7, 'Men hujjatlarni rasmiylashtirish uchun ko‘p vaqt sarfladim.', 'Я потратил много времени на оформление документов.'),
('kochish_b1', 'B1', 8, 'Yashash joyini tanlashda maktab va infratuzilma muhim.', 'При выборе места жительства важны школа и инфраструктура.'),
('kochish_b1', 'B1', 9, 'U chet elda ishlash taklifini qabul qildi.', 'Он принял предложение работать за границей.'),
('kochish_b1', 'B1', 10, 'Madaniy farqlar tufayli tushunmovchiliklar yuz berdi.', 'Из-за культурных различий возникло недопонимание.'),
('kochish_b1', 'B1', 11, 'Men ijara haqini to‘lashga qiynalayapman.', 'Мне трудно платить арендную плату.'),
('kochish_b1', 'B1', 12, 'Qo‘shnilar bilan til topishish ba’zan qiyin.', 'С соседями иногда трудно найти общий язык.'),
('kochish_b1', 'B1', 13, 'Chet elda o‘qishga grant yutib oldim.', 'Я выиграл грант на учёбу за границей.'),
('kochish_b1', 'B1', 14, 'Vaqt o‘tishi bilan yangi joyni o‘z uyimdek his qila boshladim.', 'Со временем я начал чувствовать новое место как свой дом.'),
('kochish_b1', 'B1', 15, 'Ko‘chib o‘tish stressli, lekin qiziqarli tajriba. – Переезд', 'это стрессовый, но интересный опыт.'),
('kochish_b1', 'B1', 16, 'Men har yili vatanimga qaytib boraman.', 'Я каждый год возвращаюсь на родину.'),
('kochish_b1', 'B1', 17, 'Chet ellik sifatida mahalliy qonunlarni bilishim kerak.', 'Как иностранец, я должен знать местные законы.'),
('kochish_b1', 'B1', 18, 'Dastlab til bilmaslik katta muammo edi.', 'Сначала незнание языка было большой проблемой.'),
('kochish_b1', 'B1', 19, 'Biz yangi mamlakatda o‘z biznesimizni ochdik.', 'Мы открыли свой бизнес в новой стране.'),
('kochish_b1', 'B1', 20, 'Ko‘chib o‘tishdan oldin batafsil tadqiqot qilish kerak.', 'Перед переездом нужно провести детальное исследование.'),
('hujjatlar_b1', 'B1', 1, 'Pasportim muddati tugagan.', 'У меня истёк срок паспорта.'),
('hujjatlar_b1', 'B1', 2, 'Anketa to‘ldirish kerak.', 'Нужно заполнить анкету.'),
('hujjatlar_b1', 'B1', 3, 'Sertifikatning nusxasini oling.', 'Сделайте копию сертификата.'),
('hujjatlar_b1', 'B1', 4, 'Hujjatlar notariusda tasdiqlanishi kerak.', 'Документы должны быть заверены нотариусом.'),
('hujjatlar_b1', 'B1', 5, 'Fuqarolikni olish jarayoni uzoq.', 'Процесс получения гражданства долгий.'),
('hujjatlar_b1', 'B1', 6, 'Men tug‘ilganlik haqidagi guvohnomani yo‘qotib qo‘ydim.', 'Я потерял свидетельство о рождении.'),
('hujjatlar_b1', 'B1', 7, 'Ariza ikki nusxada topshiriladi.', 'Заявление подаётся в двух экземплярах.'),
('hujjatlar_b1', 'B1', 8, 'Mening diplomim nostrifikatsiyadan o‘tishi kerak.', 'Мой диплом должен пройти нострификацию.'),
('hujjatlar_b1', 'B1', 9, 'Chet el pasporti uchun fotosurat kerak.', 'Для загранпаспорта нужна фотография.'),
('hujjatlar_b1', 'B1', 10, 'Hujjatlarni topshirishdan oldin tekshiring.', 'Перед подачей проверьте документы.'),
('hujjatlar_b1', 'B1', 11, 'Ko‘p funktsiyali markazga murojaat qiling.', 'Обратитесь в многофункциональный центр.'),
('hujjatlar_b1', 'B1', 12, 'Men soliq identifikatsiya raqamini oldim.', 'Я получил идентификационный номер налогоплательщика.'),
('hujjatlar_b1', 'B1', 13, 'Tibbiy ma’lumotnoma talab qilinadi.', 'Требуется медицинская справка.'),
('hujjatlar_b1', 'B1', 14, 'Hujjatlarni qabul qilish muddati bir oy. – Срок приёма документов', 'один месяц.'),
('hujjatlar_b1', 'B1', 15, 'Men elektron raqamli imzoga ega bo‘ldim.', 'Я получил электронную цифровую подпись.'),
('hujjatlar_b1', 'B1', 16, 'Notarius hujjatni tasdiqlashdan oldin shaxsimni tekshirdi.', 'Нотариус проверил мою личность перед заверением документа.'),
('hujjatlar_b1', 'B1', 17, 'Sud qarorining nusxasini olish kerak.', 'Нужно получить копию судебного решения.'),
('hujjatlar_b1', 'B1', 18, 'Hujjatlarni pochta orqali yuborish mumkin.', 'Документы можно отправить по почте.'),
('hujjatlar_b1', 'B1', 19, 'Mening arizam rad etildi, sababi noto‘liq ma’lumot.', 'Моё заявление отклонили из-за неполной информации.'),
('hujjatlar_b1', 'B1', 20, 'Shartnomani diqqat bilan o‘qing, imzolashdan oldin.', 'Внимательно прочитайте договор перед подписанием.'),
('pul_xarajat_b1', 'B1', 1, 'Oyiga qancha pul sarflaysiz?', 'Сколько денег вы тратите в месяц?'),
('pul_xarajat_b1', 'B1', 2, 'Tejamkorlik qilish muhim.', 'Важно экономить.'),
('pul_xarajat_b1', 'B1', 3, 'Kredit olishdan oldin o‘ylab ko‘ring.', 'Прежде чем брать кредит, подумайте.'),
('pul_xarajat_b1', 'B1', 4, 'Nima uchun bu qadar qimmat?', 'Почему это так дорого?'),
('pul_xarajat_b1', 'B1', 5, 'Men byudjetni rejalashtiraman.', 'Я планирую бюджет.'),
('pul_xarajat_b1', 'B1', 6, 'Oylik daromadim xarajatlarimni qoplaydi.', 'Мой месячный доход покрывает расходы.'),
('pul_xarajat_b1', 'B1', 7, 'Men har oy jamg‘arma hisobiga pul qo‘yaman.', 'Каждый месяц кладу деньги на сберегательный счёт.'),
('pul_xarajat_b1', 'B1', 8, 'Kutilmagan xarajatlar byudjetni buzdi.', 'Непредвиденные расходы нарушили бюджет.'),
('pul_xarajat_b1', 'B1', 9, 'Men pulni uch qismga ajrataman: majburiy, ixtiyoriy, jamg‘arma.', 'Я делю деньги на три части: обязательную, произвольную, сбережения.'),
('pul_xarajat_b1', 'B1', 10, 'Kredit kartadan foydalanish qulay, lekin qarzdorlikka olib kelishi mumkin.', 'Пользоваться кредитной картой удобно, но это может привести к задолженности.'),
('pul_xarajat_b1', 'B1', 11, 'Men naqd pulni afzal ko‘raman, karta emas.', 'Я предпочитаю наличные, а не карту.'),
('pul_xarajat_b1', 'B1', 12, 'Inflyatsiya tufayli pul qadrsizlanmoqda.', 'Из-за инфляции деньги обесцениваются.'),
('pul_xarajat_b1', 'B1', 13, 'U juda isrofgarchilik qiladi.', 'Он очень расточителен.'),
('pul_xarajat_b1', 'B1', 14, 'Oziq-ovqat eng katta xarajat moddasi. – Продукты питания', 'самая большая статья расходов.'),
('pul_xarajat_b1', 'B1', 15, 'Biz umumiy byudjetni yuritamiz.', 'Мы ведём общий бюджет.'),
('pul_xarajat_b1', 'B1', 16, 'Qarz berishdan oldin odamni yaxshi bilish kerak.', 'Прежде чем давать в долг, нужно хорошо знать человека.'),
('pul_xarajat_b1', 'B1', 17, 'Pulni qanday qilib oqilona sarflashni bilaman.', 'Я умею разумно тратить деньги.'),
('pul_xarajat_b1', 'B1', 18, 'Men bir yil ichida mashina sotib olish uchun pul yig‘moqchiman.', 'Хочу накопить деньги на покупку машины в течение года.'),
('pul_xarajat_b1', 'B1', 19, 'Moliyaviy maslahatchiga murojaat qilish foydali.', 'Полезно обратиться к финансовому консультанту.'),
('pul_xarajat_b1', 'B1', 20, 'Kambag‘allik va boylik – bu ko‘pincha odatlar masalasi. – Бедность и богатство', 'это часто вопрос привычек.'),
('media_b1', 'B1', 1, 'Siz qaysi yangilik kanalini tomosha qilasiz?', 'Какой новостной канал вы смотрите?'),
('media_b1', 'B1', 2, 'Internetda ko‘p yolg‘on ma’lumotlar bor.', 'В интернете много ложной информации.'),
('media_b1', 'B1', 3, 'Bu video juda ko‘p ko‘rilgan.', 'Это видео набрало много просмотров.'),
('media_b1', 'B1', 4, 'Gazetaga obuna bo‘lish arzon.', 'Подписка на газету дешёвая.'),
('media_b1', 'B1', 5, 'Men faqat ishonchli manbalarni o‘qiyman.', 'Я читаю только надёжные источники.'),
('media_b1', 'B1', 6, 'Haftalik jurnal chiqariladi.', 'Выпускается еженедельный журнал.'),
('media_b1', 'B1', 7, 'Yangiliklar ko‘pincha salbiy bo‘ladi.', 'Новости часто бывают негативными.'),
('media_b1', 'B1', 8, 'Men ertalab radio tinglayman.', 'Я слушаю радио утром.'),
('media_b1', 'B1', 9, 'U televidenieda ishlaydi.', 'Он работает на телевидении.'),
('media_b1', 'B1', 10, 'Siyosiy yangiliklar meni charchatadi.', 'Политические новости меня утомляют.'),
('media_b1', 'B1', 11, 'Ijtimoiy tarmoqlarda tezkor yangiliklar tarqaladi.', 'В соцсетях быстро распространяются новости.'),
('media_b1', 'B1', 12, 'Men kanalga obuna bo‘ldim va bildirishnomalarni yoqdim.', 'Я подписался на канал и включил уведомления.'),
('media_b1', 'B1', 13, 'Ushbu xabar hali tasdiqlanmagan.', 'Это сообщение ещё не подтверждено.'),
('media_b1', 'B1', 14, 'Ko‘plab odamlar sarlavhani o‘qib, mazmuniga e’tibor bermaydi.', 'Многие люди читают заголовок, не обращая внимания на содержание.'),
('media_b1', 'B1', 15, 'Men hujjatli filmlarni tomosha qilishni yaxshi ko‘raman.', 'Я люблю смотреть документальные фильмы.'),
('media_b1', 'B1', 16, 'Bugungi gazetada qiziqarli maqola bor.', 'В сегодняшней газете есть интересная статья.'),
('media_b1', 'B1', 17, 'Yangiliklar yig‘ilishida asosiy mavzular muhokama qilinadi.', 'На планерке обсуждаются главные темы.'),
('media_b1', 'B1', 18, 'U yangiliklarni har kuni ertalab ko‘rib chiqadi.', 'Он просматривает новости каждое утро.'),
('media_b1', 'B1', 19, 'Media savodxonlikni rivojlantirish kerak.', 'Нужно развивать медиаграмотность.'),
('media_b1', 'B1', 20, 'Bu telekanal xolis deb hisoblanadi.', 'Этот телеканал считается объективным.'),
('dostlar_munosabat_b1', 'B1', 1, 'Haqiqiy do‘st qiyin paytda yordam beradi.', 'Настоящий друг помогает в трудную минуту.'),
('dostlar_munosabat_b1', 'B1', 2, 'Biz bolalikdan do‘stmiz.', 'Мы дружим с детства.'),
('dostlar_munosabat_b1', 'B1', 3, 'U bilan har hafta uchrashamiz.', 'Мы встречаемся с ним каждую неделю.'),
('dostlar_munosabat_b1', 'B1', 4, 'Do‘stlikka vaqt kerak.', 'Для дружбы нужно время.'),
('dostlar_munosabat_b1', 'B1', 5, 'Kechirimlilik munosabatlarni saqlaydi.', 'Умение прощать сохраняет отношения.'),
('dostlar_munosabat_b1', 'B1', 6, 'Do‘stlarimga ishonaman.', 'Я доверяю своим друзьям.'),
('dostlar_munosabat_b1', 'B1', 7, 'U yaxshi do‘st, lekin ba’zida xudbin.', 'Он хороший друг, но иногда эгоистичен.'),
('dostlar_munosabat_b1', 'B1', 8, 'Biz bir-birimizga sirlarimizni aytamiz.', 'Мы рассказываем друг другу свои секреты.'),
('dostlar_munosabat_b1', 'B1', 9, 'Uzoq masofali do‘stlikni saqlash qiyin.', 'Трудно поддерживать дружбу на расстоянии.'),
('dostlar_munosabat_b1', 'B1', 10, 'Men yangi do‘stlar orttirishga ochiqman.', 'Я открыт для приобретения новых друзей.'),
('dostlar_munosabat_b1', 'B1', 11, 'U do‘stlari oldida meni kamsitdi.', 'Он унизил меня перед друзьями.'),
('dostlar_munosabat_b1', 'B1', 12, 'Do‘stlar bilan vaqt o‘tkazish meni quvontiradi.', 'Время с друзьями меня радует.'),
('dostlar_munosabat_b1', 'B1', 13, 'U meni hech qachon tushunmaydi.', 'Он никогда меня не понимает.'),
('dostlar_munosabat_b1', 'B1', 14, 'Ishonch buzilganda munosabatlarni tiklash mushkul.', 'Когда доверие нарушено, восстановить отношения трудно.'),
('dostlar_munosabat_b1', 'B1', 15, 'Eng yaxshi do‘stim – onam. – Мой лучший друг', 'мама.'),
('dostlar_munosabat_b1', 'B1', 16, 'U bilan birga ishlaymiz, shuning uchun ko‘p vaqt birgamiz.', 'Мы работаем вместе, поэтому много времени проводим вместе.'),
('dostlar_munosabat_b1', 'B1', 17, 'Men do‘stlarimga yordam berishdan mamnunman.', 'Я рад помогать своим друзьям.'),
('dostlar_munosabat_b1', 'B1', 18, 'Ba’zi do‘stliklar faqat bir mavsumga mo‘ljallangan.', 'Некоторые дружбы длятся только один сезон.'),
('dostlar_munosabat_b1', 'B1', 19, 'U doim sodiq va ishonchli.', 'Он всегда верный и надёжный.'),
('dostlar_munosabat_b1', 'B1', 20, 'Do‘stsiz hayot zerikarli.', 'Жизнь без друзей скучна.'),
('kundalik_muammo_b1', 'B1', 1, 'Iltimos, ovozingizni pasaytiring.', 'Пожалуйста, сделайте потише.'),
('kundalik_muammo_b1', 'B1', 2, 'Menga bir daqiqa vaqt bera olasizmi?', 'Можете уделить мне минуту?'),
('kundalik_muammo_b1', 'B1', 3, 'Siz bilan gaplashishim kerak.', 'Мне нужно поговорить с вами.'),
('kundalik_muammo_b1', 'B1', 4, 'Noto‘g‘ri tushunmovchilik yuz berdi.', 'Произошло недоразумение.'),
('kundalik_muammo_b1', 'B1', 5, 'Kechirasiz, sizni bezovta qilmoqchi emasdim.', 'Извините, не хотел вас беспокоить.'),
('kundalik_muammo_b1', 'B1', 6, 'Siz juda baland ovozda gapiryapsiz.', 'Вы говорите слишком громко.'),
('kundalik_muammo_b1', 'B1', 7, 'Men sizning fikringizni hurmat qilaman, lekin qoidani buzish mumkin emas.', 'Я уважаю ваше мнение, но нарушать правило нельзя.'),
('kundalik_muammo_b1', 'B1', 8, 'Keling, tinchlanaylik va gaplashaylik.', 'Давайте успокоимся и поговорим.'),
('kundalik_muammo_b1', 'B1', 9, 'Siz menga qo‘pol munosabatda bo‘lyapsiz.', 'Вы ведёте себя со мной грубо.'),
('kundalik_muammo_b1', 'B1', 10, 'Men sizdan kechirim so‘rayman, agar sizni xafa qilgan bo‘lsam.', 'Прошу прощения, если вас обидел.'),
('kundalik_muammo_b1', 'B1', 11, 'Iltimos, navbatni buzmaslik kerak.', 'Пожалуйста, не нарушайте очередь.'),
('kundalik_muammo_b1', 'B1', 12, 'Siz noto‘g‘ri tushunyapsiz.', 'Вы неправильно понимаете.'),
('kundalik_muammo_b1', 'B1', 13, 'Kechirasiz, siz bilan bahslashishni xohlamayman.', 'Извините, я не хочу с вами спорить.'),
('kundalik_muammo_b1', 'B1', 14, 'Sizning so‘rovingizni bajarolmayman.', 'Я не могу выполнить вашу просьбу.'),
('kundalik_muammo_b1', 'B1', 15, 'Iltimos, buni menga qarshi ishlatmang.', 'Пожалуйста, не используйте это против меня.'),
('kundalik_muammo_b1', 'B1', 16, 'Kechirasiz, sizga qanday yordam bera olaman?', 'Извините, чем я могу вам помочь?'),
('kundalik_muammo_b1', 'B1', 17, 'Sizning xatti-harakatingiz noo‘rin.', 'Ваше поведение неуместно.'),
('kundalik_muammo_b1', 'B1', 18, 'Keling, bu masalani birga hal qilaylik.', 'Давайте решим этот вопрос вместе.'),
('kundalik_muammo_b1', 'B1', 19, 'Siz meni tinglamayapsiz.', 'Вы меня не слушаете.'),
('kundalik_muammo_b1', 'B1', 20, 'Men sizga nisbatan hech qanday yomon niyatim yo‘q.', 'У меня нет никаких плохих намерений по отношению к вам.'),
('munozara_fikr_b2', 'B2', 1, 'Men sizning nuqtai nazaringizni tushunaman, lekin…', 'Я понимаю вашу точку зрения, но…'),
('munozara_fikr_b2', 'B2', 2, 'Statistik ma’lumotlar buni tasdiqlaydi.', 'Статистические данные это подтверждают.'),
('munozara_fikr_b2', 'B2', 3, 'Bu masala bo‘yicha turli xil qarashlar mavjud.', 'По этому вопросу существуют разные взгляды.'),
('munozara_fikr_b2', 'B2', 4, 'Men o‘z fikrimni asoslab bera olaman.', 'Я могу обосновать своё мнение.'),
('munozara_fikr_b2', 'B2', 5, 'Sizning dalillaringiz ishonarli emas.', 'Ваши доводы неубедительны.'),
('munozara_fikr_b2', 'B2', 6, 'Men ushbu gipotezani qabul qilmayman.', 'Я не принимаю эту гипотезу.'),
('munozara_fikr_b2', 'B2', 7, 'Bu borada ilmiy konsensus mavjud.', 'В этом вопросе существует научный консенсус.'),
('munozara_fikr_b2', 'B2', 8, 'Siz haddan tashqari soddalashtiryapsiz.', 'Вы чрезмерно упрощаете.'),
('munozara_fikr_b2', 'B2', 9, 'Keling, ushbu masalani bir necha burchakdan ko‘rib chiqaylik.', 'Давайте рассмотрим этот вопрос с нескольких сторон.'),
('munozara_fikr_b2', 'B2', 10, 'Men o‘z pozitsiyamni o‘zgartirishga tayyorman, agar ishonchli dalillar keltirsangiz.', 'Я готов изменить свою позицию, если вы приведёте убедительные доказательства.'),
('munozara_fikr_b2', 'B2', 11, 'Sizning mulohazalaringizda mantiqiy xatolik bor.', 'В ваших рассуждениях есть логическая ошибка.'),
('munozara_fikr_b2', 'B2', 12, 'Axloqiy jihatdan bu to‘g‘rimi yoki yo‘qmi?', 'Этически это правильно или нет?'),
('munozara_fikr_b2', 'B2', 13, 'Ko‘pchilik tomonidan qabul qilingan fikr har doim ham to‘g‘ri emas.', 'Мнение, принятое большинством, не всегда верно.'),
('munozara_fikr_b2', 'B2', 14, 'Men shaxsan o‘zim boshqacha tajribaga egaman.', 'Лично у меня другой опыт.'),
('munozara_fikr_b2', 'B2', 15, 'Ushbu masala bo‘yicha chuqurroq tahlil kerak.', 'По этому вопросу нужен более глубокий анализ.'),
('munozara_fikr_b2', 'B2', 16, 'Sizning fikringiz qisman to‘g‘ri, lekin istisnolar bor.', 'Ваше мнение частично верно, но есть исключения.'),
('munozara_fikr_b2', 'B2', 17, 'Men hech qanday taraf tutmayman.', 'Я не занимаю ничью сторону.'),
('munozara_fikr_b2', 'B2', 18, 'Bu faqat sizning sub’ektiv bahongiz.', 'Это лишь ваша субъективная оценка.'),
('munozara_fikr_b2', 'B2', 19, 'Keling, fakt va fikrni ajrataylik.', 'Давайте отделим факты от мнений.'),
('munozara_fikr_b2', 'B2', 20, 'Men sizni ishontira olmasam ham, sizning fikringizni hurmat qilaman.', 'Даже если я не могу вас убедить, я уважаю ваше мнение.'),
('taqqoslash_tahlil_b2', 'B2', 1, 'Ikkala variantni solishtirsak, birinchisi afzalroq.', 'Если сравнить оба варианта, первый предпочтительнее.'),
('taqqoslash_tahlil_b2', 'B2', 2, 'O‘xshash jihatlari ko‘p, ammo farqlari ham bor.', 'Сходств много, но есть и различия.'),
('taqqoslash_tahlil_b2', 'B2', 3, 'Bu hodisaning sabablarini tahlil qilaylik.', 'Давайте проанализируем причины этого явления.'),
('taqqoslash_tahlil_b2', 'B2', 4, 'Narx va sifat nisbati muhim.', 'Соотношение цены и качества важно.'),
('taqqoslash_tahlil_b2', 'B2', 5, 'Statistikaga ko‘ra, talab ortib bormoqda.', 'Согласно статистике, спрос растёт.'),
('taqqoslash_tahlil_b2', 'B2', 6, 'Ushbu ikki strategiyaning samaradorligini taqqoslash kerak.', 'Нужно сравнить эффективность этих двух стратегий.'),
('taqqoslash_tahlil_b2', 'B2', 7, 'Afzalliklari kamchiliklaridan ustun.', 'Преимущества перевешивают недостатки.'),
('taqqoslash_tahlil_b2', 'B2', 8, 'Tarixiy tahlil shuni ko‘rsatadiki…', 'Исторический анализ показывает, что…'),
('taqqoslash_tahlil_b2', 'B2', 9, 'Ushbu modelning cheklovlarini hisobga olish lozim.', 'Следует учитывать ограничения этой модели.'),
('taqqoslash_tahlil_b2', 'B2', 10, 'Miqdoriy va sifat jihatlarini farqlang.', 'Различайте количественные и качественные аспекты.'),
('taqqoslash_tahlil_b2', 'B2', 11, 'Korrelyatsiya sababiy bog‘liqlikni anglatmaydi.', 'Корреляция не означает причинно-следственную связь.'),
('taqqoslash_tahlil_b2', 'B2', 12, 'Ushbu ikki tushunchani bir-biridan ajratish muhim.', 'Важно различать эти два понятия.'),
('taqqoslash_tahlil_b2', 'B2', 13, 'Dinamikada qanday o‘zgarishlar kuzatilmoqda?', 'Какие изменения наблюдаются в динамике?'),
('taqqoslash_tahlil_b2', 'B2', 14, 'Indikatorlarni solishtirish asosida xulosa chiqarish mumkin.', 'На основе сравнения показателей можно сделать вывод.'),
('taqqoslash_tahlil_b2', 'B2', 15, 'Ushbu yondashuvning kuchli va zaif tomonlarini ko‘rib chiqamiz.', 'Рассмотрим сильные и слабые стороны этого подхода.'),
('taqqoslash_tahlil_b2', 'B2', 16, 'Benchmarking – raqobatchilar bilan solishtirish usuli. – Бенчмаркинг', 'метод сравнения с конкурентами.'),
('taqqoslash_tahlil_b2', 'B2', 17, 'Klaster tahlili guruhlarni aniqlashga yordam beradi.', 'Кластерный анализ помогает выявить группы.'),
('taqqoslash_tahlil_b2', 'B2', 18, 'Ushbu hodisani tushuntiruvchi bir necha omillar mavjud.', 'Существует несколько факторов, объясняющих это явление.'),
('taqqoslash_tahlil_b2', 'B2', 19, 'Natijalarni standartlashtirish kerak.', 'Нужно стандартизировать результаты.'),
('taqqoslash_tahlil_b2', 'B2', 20, 'Har qanday tahlil ob’ektiv ma’lumotlarga asoslanishi lozim.', 'Любой анализ должен основываться на объективных данных.'),
('biznes_b2', 'B2', 1, 'Bizning kompaniya bozor ulushini oshirmoqda.', 'Наша компания увеличивает долю рынка.'),
('biznes_b2', 'B2', 2, 'Strategik rejalashtirish muvaffaqiyat kaliti. – Стратегическое планирование', 'ключ к успеху.'),
('biznes_b2', 'B2', 3, 'Investitsiyalarni jalb qilish kerak.', 'Нужно привлечь инвестиции.'),
('biznes_b2', 'B2', 4, 'Xodimlarning motivatsiyasi yuqori bo‘lishi lozim.', 'Мотивация сотрудников должна быть высокой.'),
('biznes_b2', 'B2', 5, 'Biz raqobatchilardan oldinda boramiz.', 'Мы опережаем конкурентов.'),
('biznes_b2', 'B2', 6, 'KPI (asosiy samaradorlik ko‘rsatkichlari) muntazam kuzatiladi.', 'KPI (ключевые показатели эффективности) регулярно отслеживаются.'),
('biznes_b2', 'B2', 7, 'Byudjetni qat’iy bajarish talab etiladi.', 'Требуется строгое соблюдение бюджета.'),
('biznes_b2', 'B2', 8, 'Biznes jarayonlarini optimallashtirish orqali xarajatlarni kamaytirdik.', 'Мы снизили расходы за счёт оптимизации бизнес-процессов.'),
('biznes_b2', 'B2', 9, 'Risklarni boshqarish tizimi joriy etilgan.', 'Внедрена система управления рисками.'),
('biznes_b2', 'B2', 10, 'Kompaniyamizda vertikal boshqaruv tuzilmasi mavjud.', 'В нашей компании существует вертикальная структура управления.'),
('biznes_b2', 'B2', 11, 'Startap bosqichida eng muhimi tez moslashish. – На стадии стартапа самое главное', 'быстро адаптироваться.'),
('biznes_b2', 'B2', 12, 'Mijozlarning qoniqish darajasini oshirish maqsad qilingan.', 'Поставлена цель повысить уровень удовлетворённости клиентов.'),
('biznes_b2', 'B2', 13, 'Uchrashuvda kelgusi chorak uchun rejalar muhokama qilindi.', 'На встрече обсуждались планы на следующий квартал.'),
('biznes_b2', 'B2', 14, 'Moliyaviy hisobot har oy tayyorlanadi.', 'Финансовый отчёт готовится каждый месяц.'),
('biznes_b2', 'B2', 15, 'Biznes-modelni o‘zgartirish vaqti keldi.', 'Пришло время изменить бизнес-модель.'),
('biznes_b2', 'B2', 16, 'Xodimlarning malakasini oshirishga sarmoya kiritilmoqda.', 'Инвестируется в повышение квалификации сотрудников.'),
('biznes_b2', 'B2', 17, 'Yirik shartnoma imzolash arafasida turibmiz.', 'Мы стоим на пороге подписания крупного контракта.'),
('biznes_b2', 'B2', 18, 'Raqamli transformatsiya barcha bo‘limlarni qamrab oladi.', 'Цифровая трансформация охватывает все отделы.'),
('biznes_b2', 'B2', 19, 'Menejment qarorlarini ma’lumotlarga asoslanib qabul qiladi.', 'Менеджмент принимает решения на основе данных.'),
('biznes_b2', 'B2', 20, 'Korporativ madaniyat kompaniyaning yuzidir. – Корпоративная культура', 'это лицо компании.'),
('jamiyat_b2', 'B2', 1, 'Ijtimoiy tengsizlik jiddiy muammo. – Социальное неравенство', 'серьёзная проблема.'),
('jamiyat_b2', 'B2', 2, 'Fuqarolik jamiyati rivojlanishi kerak.', 'Гражданское общество должно развиваться.'),
('jamiyat_b2', 'B2', 3, 'Ekologik muammolar hammamizga ta’sir qiladi.', 'Экологические проблемы влияют на всех нас.'),
('jamiyat_b2', 'B2', 4, 'Ko‘ngillilik harakatlari muhim rol o‘ynaydi.', 'Волонтёрские движения играют важную роль.'),
('jamiyat_b2', 'B2', 5, 'Inson huquqlari himoyasi zarur.', 'Защита прав человека необходима.'),
('jamiyat_b2', 'B2', 6, 'Demografik o‘zgarishlar iqtisodiyotga ta’sir qiladi.', 'Демографические изменения влияют на экономику.'),
('jamiyat_b2', 'B2', 7, 'Korrupsiyaga qarshi kurash jamiyatning ustuvor vazifasi. – Борьба с коррупцией', 'приоритетная задача общества.'),
('jamiyat_b2', 'B2', 8, 'Gender tengligi hali to‘liq erishilmagan.', 'Гендерное равенство ещё не достигнуто полностью.'),
('jamiyat_b2', 'B2', 9, 'Migratsiya oqimi mehnat bozorini o‘zgartirmoqda.', 'Миграционные потоки меняют рынок труда.'),
('jamiyat_b2', 'B2', 10, 'Ta’lim tizimi islohoti zarur.', 'Необходима реформа системы образования.'),
('jamiyat_b2', 'B2', 11, 'Sog‘liqni saqlash tizimi byudjetdan katta mablag‘ talab qiladi.', 'Система здравоохранения требует больших бюджетных средств.'),
('jamiyat_b2', 'B2', 12, 'Ijtimoiy himoya aholining zaif qatlamlarini qo‘llab-quvvatlaydi.', 'Социальная защита поддерживает уязвимые слои населения.'),
('jamiyat_b2', 'B2', 13, 'Ommaviy axborot vositalari jamoatchilik fikrini shakllantiradi.', 'Средства массовой информации формируют общественное мнение.'),
('jamiyat_b2', 'B2', 14, 'Mahalliy hokimiyat organlari fuqarolarga yaqin bo‘lishi kerak.', 'Органы местной власти должны быть близки к гражданам.'),
('jamiyat_b2', 'B2', 15, 'Fuqarolarning siyosiy faolligi muhim.', 'Важна политическая активность граждан.'),
('jamiyat_b2', 'B2', 16, 'Etnik va diniy bag‘rikenglik jamiyat barqarorligi uchun asosdir. – Этническая и религиозная толерантность', 'основа стабильности общества.'),
('jamiyat_b2', 'B2', 17, 'Raqamli bo‘linish (digital divide) kuchaymoqda.', 'Цифровое неравенство усиливается.'),
('jamiyat_b2', 'B2', 18, 'Ijtimoiy tadqiqotlar siyosatni shakllantirishga yordam beradi.', 'Социальные исследования помогают формировать политику.'),
('jamiyat_b2', 'B2', 19, 'Jamiyatdagi o‘zgarishlar ko‘pincha avloddan avlodga sekin sodir bo‘ladi.', 'Изменения в обществе часто происходят медленно от поколения к поколению.'),
('jamiyat_b2', 'B2', 20, 'Barqaror rivojlanish maqsadlariga erishish uchun hamkorlik kerak.', 'Для достижения целей устойчивого развития необходимо сотрудничество.'),
('iqtisod_b2', 'B2', 1, 'Inflyatsiya xarid qobiliyatini pasaytiradi.', 'Инфляция снижает покупательную способность.'),
('iqtisod_b2', 'B2', 2, 'YaIM o‘sishi iqtisodiyotning sog‘lig‘ini ko‘rsatadi.', 'Рост ВВП показывает здоровье экономики.'),
('iqtisod_b2', 'B2', 3, 'Soliq tizimi shaffof bo‘lishi kerak.', 'Налоговая система должна быть прозрачной.'),
('iqtisod_b2', 'B2', 4, 'Kichik biznesga davlat tomonidan yordam kerak.', 'Малому бизнесу нужна государственная поддержка.'),
('iqtisod_b2', 'B2', 5, 'Bozor iqtisodiyotida talab va taklif muvozanati muhim.', 'В рыночной экономике важен баланс спроса и предложения.'),
('iqtisod_b2', 'B2', 6, 'Markaziy bank asosiy foiz stavkasini oshirdi.', 'Центральный банк повысил ключевую ставку.'),
('iqtisod_b2', 'B2', 7, 'Tashqi savdo defitsiti kamaydi.', 'Дефицит внешней торговли сократился.'),
('iqtisod_b2', 'B2', 8, 'Valyuta kursining o‘zgarishi eksport va importga ta’sir qiladi.', 'Изменение валютного курса влияет на экспорт и импорт.'),
('iqtisod_b2', 'B2', 9, 'Iqtisodiy o‘sish ishsizlikni kamaytiradi.', 'Экономический рост снижает безработицу.'),
('iqtisod_b2', 'B2', 10, 'Byudjet taqchilligini qoplash uchun qarz olinadi.', 'Для покрытия бюджетного дефицита берутся займы.'),
('iqtisod_b2', 'B2', 11, 'Monopoliyaga qarshi qonunchilik raqobatni himoya qiladi.', 'Антимонопольное законодательство защищает конкуренцию.'),
('iqtisod_b2', 'B2', 12, 'Shtatlik iqtisodchi iqtisodiy tsikllarni tahlil qiladi.', 'Экономист анализирует экономические циклы.'),
('iqtisod_b2', 'B2', 13, 'Iqtisodiyotning real sektori – ishlab chiqarish va qurilish. – Реальный сектор экономики', 'производство и строительство.'),
('iqtisod_b2', 'B2', 14, 'Xizmatlar sohasining ulushi ortib bormoqda.', 'Доля сферы услуг растёт.'),
('iqtisod_b2', 'B2', 15, 'Inflyatsion kutilmalar narxlarga ta’sir qiladi.', 'Инфляционные ожидания влияют на цены.'),
('iqtisod_b2', 'B2', 16, 'Mehnat unumdorligi oshsa, iqtisodiyot rivojlanadi.', 'Если растёт производительность труда, развивается экономика.'),
('iqtisod_b2', 'B2', 17, 'Iqtisodiy pasayish davrida iste’mol kamayadi.', 'В период экономического спада потребление снижается.'),
('iqtisod_b2', 'B2', 18, 'Shtat tomonidan subsidiya beriladi.', 'Государством предоставляется субсидия.'),
('iqtisod_b2', 'B2', 19, 'Iqtisodiy modellar real hayotni soddalashtirib ko‘rsatadi.', 'Экономические модели упрощённо отражают реальную жизнь.'),
('iqtisod_b2', 'B2', 20, 'Moliyaviy savodxonlik iqtisodiy farovonlikka olib keladi.', 'Финансовая грамотность ведёт к экономическому благополучию.'),
('argument_b2', 'B2', 1, 'Birinchidan, ikkinchidan, uchinchidan…', 'Во-первых, во-вторых, в-третьих…'),
('argument_b2', 'B2', 2, 'Keling, bunga boshqa tomondan qaraylik.', 'Давайте посмотрим на это с другой стороны.'),
('argument_b2', 'B2', 3, 'Misollar bilan tushuntirish osonroq.', 'Объяснять на примерах легче.'),
('argument_b2', 'B2', 4, 'Bu fikrga qarshi dalil keltiraman.', 'Приведу контраргумент к этому мнению.'),
('argument_b2', 'B2', 5, 'Xulosa qilib aytganda, men quyidagini taklif qilaman.', 'Подводя итог, я предлагаю следующее.'),
('argument_b2', 'B2', 6, 'Agar shart bajarilsa, unda natija…', 'Если условие выполнено, то результат…'),
('argument_b2', 'B2', 7, 'Buning aksi ham to‘g‘ri.', 'Верно и обратное.'),
('argument_b2', 'B2', 8, 'Sabab-oqibat zanjirini tahlil qilaylik.', 'Проанализируем причинно-следственную цепочку.'),
('argument_b2', 'B2', 9, 'Ushbu tezisni isbotlash uchun yetarli asoslar mavjud.', 'Для доказательства этого тезиса есть достаточные основания.'),
('argument_b2', 'B2', 10, 'Hech kim bu borada aniq javob bera olmaydi.', 'Никто не может дать точный ответ на этот счёт.'),
('argument_b2', 'B2', 11, 'Sizning argumentingiz o‘rinli, lekin yetarli emas.', 'Ваш аргумент уместен, но недостаточен.'),
('argument_b2', 'B2', 12, 'Keling, analogiyadan foydalanaylik.', 'Давайте воспользуемся аналогией.'),
('argument_b2', 'B2', 13, 'Bu deduksiya yoki induksiya usuli bilan isbotlanishi mumkin.', 'Это можно доказать методом дедукции или индукции.'),
('argument_b2', 'B2', 14, 'Bahsli jihatlarini alohida ko‘rib chiqish kerak.', 'Спорные аспекты нужно рассмотреть отдельно.'),
('argument_b2', 'B2', 15, 'Men sizning mantiqingizni kuzatib bormoqdaman.', 'Я слежу за вашей логикой.'),
('argument_b2', 'B2', 16, 'Ushbu dalilni rad etish mumkin, chunki…', 'Этот довод можно опровергнуть, потому что…'),
('argument_b2', 'B2', 17, 'Siz o‘zingizga zid gapiryapsiz.', 'Вы говорите противоречиво.'),
('argument_b2', 'B2', 18, 'Eng ishonchli dalil – bu amaliyot. – Самый убедительный довод', 'это практика.'),
('argument_b2', 'B2', 19, 'Keling, umumlashtirishdan saqlanaylik.', 'Давайте избегать обобщений.'),
('argument_b2', 'B2', 20, 'Mantiqiy xulosaga kelish uchun barcha omillarni hisobga olish kerak.', 'Чтобы прийти к логическому выводу, нужно учесть все факторы.'),
('muammo_chuqur_b2', 'B2', 1, 'Muammoning ildiziga borish kerak.', 'Нужно добраться до корня проблемы.'),
('muammo_chuqur_b2', 'B2', 2, 'Qisqa muddatli va uzoq muddatli choralar farqlanadi.', 'Краткосрочные и долгосрочные меры различаются.'),
('muammo_chuqur_b2', 'B2', 3, 'Hech qanday yechim mukammal emas.', 'Ни одно решение не идеально.'),
('muammo_chuqur_b2', 'B2', 4, 'Oldini olish bartaraf qilishdan yaxshiroq.', 'Предотвращение лучше, чем устранение.'),
('muammo_chuqur_b2', 'B2', 5, 'Hamkorlikda ishlash samaraliroq.', 'Работать в сотрудничестве эффективнее.'),
('muammo_chuqur_b2', 'B2', 6, 'Tizimli muammo tizimli yechim talab qiladi.', 'Системная проблема требует системного решения.'),
('muammo_chuqur_b2', 'B2', 7, 'Inson omili ko‘pincha asosiy to‘siq bo‘ladi.', 'Человеческий фактор часто является основным препятствием.'),
('muammo_chuqur_b2', 'B2', 8, 'Biz muammoni qayta tavsiflashimiz kerak.', 'Нам нужно переформулировать проблему.'),
('muammo_chuqur_b2', 'B2', 9, 'Resurslar cheklangan, shuning uchun ustuvorliklarni belgilang.', 'Ресурсы ограничены, поэтому определите приоритеты.'),
('muammo_chuqur_b2', 'B2', 10, 'Keng qamrovli tahlildan so‘ng harakat rejasini tuzish mumkin.', 'После всестороннего анализа можно составить план действий.'),
('muammo_chuqur_b2', 'B2', 11, 'Ba’zida eng yaxshi yechim – hech narsa qilmaslik. – Иногда лучшее решение', 'ничего не делать.'),
('muammo_chuqur_b2', 'B2', 12, 'Ehtimollarni baholash va risklarni minimallashtirish lozim.', 'Нужно оценить вероятности и минимизировать риски.'),
('muammo_chuqur_b2', 'B2', 13, 'Muammoning salbiy ta’sirini kvantifikatsiya qilish mumkinmi?', 'Можно ли квантифицировать негативное влияние проблемы?'),
('muammo_chuqur_b2', 'B2', 14, 'Yechimlarni sinovdan o‘tkazish uchun pilot loyiha boshlang.', 'Запустите пилотный проект для тестирования решений.'),
('muammo_chuqur_b2', 'B2', 15, 'Qaror qabul qilishda axloqiy jihatlarni hisobga oling.', 'При принятии решения учитывайте этические аспекты.'),
('muammo_chuqur_b2', 'B2', 16, 'Muvaffaqiyatsiz yechimlar ham qimmatli saboq beradi.', 'Неудачные решения тоже дают ценный урок.'),
('muammo_chuqur_b2', 'B2', 17, 'Monokauzal fikrlashdan uzoqlashing.', 'Отойдите от монокаузального мышления.'),
('muammo_chuqur_b2', 'B2', 18, 'Teskari aloqa mexanizmini o‘rnatish muhim.', 'Важно настроить механизм обратной связи.'),
('muammo_chuqur_b2', 'B2', 19, 'Vaqt o‘tishi bilan yechimni qayta ko‘rib chiqish kerak bo‘lishi mumkin.', 'Со временем решение может потребовать пересмотра.'),
('muammo_chuqur_b2', 'B2', 20, 'Eng qiyin muammolar ko‘pincha eng oddiy yechimlarga ega.', 'Самые сложные проблемы часто имеют самые простые решения.'),
('maqsad_reja_b2', 'B2', 1, 'Men aniq va o‘lchovli maqsadlarni qo‘yaman.', 'Я ставлю конкретные и измеримые цели.'),
('maqsad_reja_b2', 'B2', 2, 'Kelgusi besh yil ichida uy sotib olmoqchiman.', 'В ближайшие пять лет я хочу купить квартиру.'),
('maqsad_reja_b2', 'B2', 3, 'Rejani bosqichma-bosqich amalga oshirish kerak.', 'План нужно выполнять поэтапно.'),
('maqsad_reja_b2', 'B2', 4, 'To‘siqlarga qaramay, maqsadimdan qaytmayman.', 'Несмотря на препятствия, я не отступлю от цели.'),
('maqsad_reja_b2', 'B2', 5, 'Muvaffaqiyatga erishish uchun intizim zarur.', 'Для достижения успеха необходима дисциплина.'),
('maqsad_reja_b2', 'B2', 6, 'Men har kuni kichik qadamlar bilan maqsadimga yaqinlashaman.', 'Каждый день маленькими шагами приближаюсь к своей цели.'),
('maqsad_reja_b2', 'B2', 7, 'Uzoq muddatli maqsadlarni qisqa muddatli vazifalarga bo‘lish mumkin.', 'Долгосрочные цели можно разбить на краткосрочные задачи.'),
('maqsad_reja_b2', 'B2', 8, 'Men o‘z maqsadlarimni yozib qo‘yaman va ularni muntazam ko‘rib chiqaman.', 'Я записываю свои цели и регулярно их пересматриваю.'),
('maqsad_reja_b2', 'B2', 9, 'Ba’zida maqsadlarni o‘zgartirish yoki kechiktirish kerak bo‘ladi.', 'Иногда цели нужно менять или откладывать.'),
('maqsad_reja_b2', 'B2', 10, 'Motivatsiya pasayganda, kichik yutuqlarni nishonlang.', 'Когда мотивация падает, отмечайте маленькие достижения.'),
('maqsad_reja_b2', 'B2', 11, 'Muvaffaqiyatga erishganlardan o‘rganish foydali.', 'Полезно учиться у тех, кто достиг успеха.'),
('maqsad_reja_b2', 'B2', 12, 'Men o‘zimning kuchli tomonlarimga tayanib maqsad qo‘yaman.', 'Я ставлю цели, опираясь на свои сильные стороны.'),
('maqsad_reja_b2', 'B2', 13, 'Rejani amalga oshirishda vaqtni boshqarish muhim.', 'При выполнении плана важно тайм-менеджмент.'),
('maqsad_reja_b2', 'B2', 14, 'Kutilmagan holatlar uchun zaxira reja tuzish kerak.', 'Нужно составить запасной план на случай непредвиденных обстоятельств.'),
('maqsad_reja_b2', 'B2', 15, 'Maqsadlar nafaqat moddiy, balki ma’naviy ham bo‘lishi mumkin.', 'Цели могут быть не только материальными, но и духовными.'),
('maqsad_reja_b2', 'B2', 16, 'Men har oy maqsadlarimga erishish darajasini baholayman.', 'Каждый месяц я оцениваю степень достижения своих целей.'),
('maqsad_reja_b2', 'B2', 17, 'Yomon odatlar maqsadlarga erishishga to‘sqinlik qiladi.', 'Вредные привычки мешают достижению целей.'),
('maqsad_reja_b2', 'B2', 18, 'Maqsadsiz hayot kemasiz dengizda suzishga o‘xshaydi.', 'Жизнь без цели похожа на плавание в море без корабля.'),
('maqsad_reja_b2', 'B2', 19, 'Men o‘z maqsadlarimni boshqalar bilan baham ko‘raman, bu meni mas’uliyatli qiladi.', 'Я делюсь своими целями с другими, это делает меня ответственным.'),
('maqsad_reja_b2', 'B2', 20, 'Eng muhimi – harakatni boshlash. – Самое главное', 'начать действовать.'),
('debat_b2', 'B2', 1, 'Sizning fikringiz bilan bahslashishga majburman.', 'Я вынужден не согласиться с вашим мнением.'),
('debat_b2', 'B2', 2, 'Iltimos, fikringizni isbotlovchi misol keltiring.', 'Пожалуйста, приведите пример, доказывающий вашу мысль.'),
('debat_b2', 'B2', 3, 'Bu mantiqiy xatolik.', 'Это логическая ошибка.'),
('debat_b2', 'B2', 4, 'Keling, mavzuga qaytaylik.', 'Давайте вернёмся к теме.'),
('debat_b2', 'B2', 5, 'Sizni tushunaman, lekin siz bir faktni e’tiborsiz qoldiryapsiz.', 'Я вас понимаю, но вы упускаете один факт.'),
('debat_b2', 'B2', 6, 'Sizning asosiy tezisingiz nimaga asoslangan?', 'На чём основан ваш основной тезис?'),
('debat_b2', 'B2', 7, 'Bu strawman argumenti (qo‘g‘irchoq) – siz mening pozitsiyamni buzib ko‘rsatyapsiz. – Это соломенное чучело', 'вы искажаете мою позицию.'),
('debat_b2', 'B2', 8, 'Keling, so‘z o‘yinlaridan emas, dalillarga tayanaylik.', 'Давайте опираться на факты, а не на игру слов.'),
('debat_b2', 'B2', 9, 'Men sizning fikringizni qabul qilishdan oldin qo‘shimcha dalillarni kutaman.', 'Прежде чем принять ваше мнение, я жду дополнительных доказательств.'),
('debat_b2', 'B2', 10, 'Sizning argumentingizda noaniqlik bor.', 'В вашем аргументе есть неясность.'),
('debat_b2', 'B2', 11, 'Keling, bir-birimizni tinglaylik, faqat gapirmaylik.', 'Давайте слушать друг друга, а не только говорить.'),
('debat_b2', 'B2', 12, 'Siz juda emotsional munosabat bildiryapsiz.', 'Вы реагируете слишком эмоционально.'),
('debat_b2', 'B2', 13, 'Men sizning nuqtai nazaringizni qabul qilaman, ammo xulosa chiqarishga shoshilmang.', 'Я принимаю вашу точку зрения, но не торопитесь с выводами.'),
('debat_b2', 'B2', 14, 'Bu false dilemma (noto‘g‘ri ikkilamchilik) – boshqa variantlar ham bor. – Это ложная дилемма', 'есть и другие варианты.'),
('debat_b2', 'B2', 15, 'Sizning dalilingiz statistik jihatdan ahamiyatsiz.', 'Ваш довод статистически незначим.'),
('debat_b2', 'B2', 16, 'Men rais sifatida so‘zni boshqa ishtirokchiga beraman.', 'Как председатель, я передаю слово другому участнику.'),
('debat_b2', 'B2', 17, 'Vaqtimiz cheklangan, keling, eng muhim nuqtalarga e’tibor qarataylik.', 'Время ограничено, давайте сосредоточимся на самых важных пунктах.'),
('debat_b2', 'B2', 18, 'Sizning pozitsiyangizda bir qancha zaif tomonlar bor.', 'В вашей позиции есть несколько слабых мест.'),
('debat_b2', 'B2', 19, 'Men siz bilan to‘liq bahslashmayman, lekin kichik bir tafsilotda farqimiz bor.', 'Я не полностью спорю с вами, но у нас есть различие в одной детали.'),
('debat_b2', 'B2', 20, 'Bahs davomida shaxsiyatga emas, mavzuga e’tibor qarataylik.', 'В ходе дискуссии давайте сосредоточимся на теме, а не на личности.'),
('rivojlanish_b2', 'B2', 1, 'Uzluksiz ta’lim zamon talabi. – Непрерывное образование', 'требование времени.'),
('rivojlanish_b2', 'B2', 2, 'O‘z ustida ishlash hech qachon to‘xtamasligi kerak.', 'Работа над собой не должна прекращаться.'),
('rivojlanish_b2', 'B2', 3, 'Mentor yoki murabbiy topish foydali.', 'Полезно найти наставника или тренера.'),
('rivojlanish_b2', 'B2', 4, 'Xatolardan o‘rganish rivojlanishning bir qismi. – Учиться на ошибках', 'часть развития.'),
('rivojlanish_b2', 'B2', 5, 'Bugun juda ko‘p bepul ta’lim resurslari bor.', 'Сегодня есть много бесплатных образовательных ресурсов.'),
('rivojlanish_b2', 'B2', 6, 'Men har kuni kamida 30 daqiqa o‘qishga ajrataman.', 'Я выделяю на чтение минимум 30 минут каждый день.'),
('rivojlanish_b2', 'B2', 7, 'Onlayn kurslar orqali yangi kasb o‘rganish mumkin.', 'Через онлайн-курсы можно освоить новую профессию.'),
('rivojlanish_b2', 'B2', 8, 'Tez o‘zgaruvchan dunyoda moslashuvchanlik muhim.', 'В быстро меняющемся мире важна адаптивность.'),
('rivojlanish_b2', 'B2', 9, 'Men o‘rganish uslubimni (vizual, eshitish, kinestetik) bilaman.', 'Я знаю свой стиль обучения (визуальный, аудиальный, кинестетический).'),
('rivojlanish_b2', 'B2', 10, 'Kechqurun o‘rganilgan materialni takrorlash yaxshi esda qoladi.', 'Повторение изученного материала вечером помогает лучше запомнить.'),
('rivojlanish_b2', 'B2', 11, 'O‘z-o‘zini baholash rivojlanishning muhim qismi. – Самооценка', 'важная часть развития.'),
('rivojlanish_b2', 'B2', 12, 'Men maqsadli ravishda zaif tomonlarimni kuchaytiryapman.', 'Я целенаправленно усиливаю свои слабые стороны.'),
('rivojlanish_b2', 'B2', 13, 'Guruhda o‘rganish individual o‘rganishdan farq qiladi.', 'Обучение в группе отличается от индивидуального.'),
('rivojlanish_b2', 'B2', 14, 'Chet tilini o‘rganishda muntazamlik muhim.', 'В изучении иностранного языка важна регулярность.'),
('rivojlanish_b2', 'B2', 15, 'Men o‘qiganlarimni amalda qo‘llashga harakat qilaman.', 'Стараюсь применять изученное на практике.'),
('rivojlanish_b2', 'B2', 16, 'Kreativ fikrlashni rivojlantirish mumkin.', 'Креативное мышление можно развить.'),
('rivojlanish_b2', 'B2', 17, 'O‘rganish motivatsiyasi tashqi va ichki omillarga bog‘liq.', 'Мотивация к обучению зависит от внешних и внутренних факторов.'),
('rivojlanish_b2', 'B2', 18, 'Men o‘z bilimlarimni boshqalarga o‘rgatish orqali mustahkamlayman.', 'Я укрепляю свои знания, обучая других.'),
('rivojlanish_b2', 'B2', 19, 'Rivojlanish uchun qulay muhit yaratish kerak.', 'Для развития нужно создать благоприятную среду.'),
('rivojlanish_b2', 'B2', 20, 'Eng yaxshi sarmoya – bu o‘zingizga qilgan sarmoya. – Лучшая инвестиция', 'это инвестиция в себя.'),
('madaniyat_b2', 'B2', 1, 'Har bir millatning o‘ziga xos urf-odatlari bor.', 'У каждого народа есть свои обычаи.'),
('madaniyat_b2', 'B2', 2, 'An’analarni saqlash kelajak avlod uchun muhim.', 'Сохранять традиции важно для будущих поколений.'),
('madaniyat_b2', 'B2', 3, 'Bayramlar odamlarni birlashtiradi.', 'Праздники объединяют людей.'),
('madaniyat_b2', 'B2', 4, 'Madaniyatlararo muloqot dunyoqarashni kengaytiradi.', 'Межкультурное общение расширяет кругозор.'),
('madaniyat_b2', 'B2', 5, 'Biz o‘zbek mehmondo‘stligi bilan faxrlanamiz.', 'Мы гордимся узбекским гостеприимством.'),
('madaniyat_b2', 'B2', 6, 'Navro‘z – bahor bayrami va yangi yil boshlanishi. – Навруз', 'весенний праздник и начало нового года.'),
('madaniyat_b2', 'B2', 7, 'To‘ylarda ko‘plab milliy taomlar tortiladi.', 'На свадьбах подают много национальных блюд.'),
('madaniyat_b2', 'B2', 8, 'Katta yoshlilarni hurmat qilish – bizning an’anamiz. – Уважение к старшим', 'наша традиция.'),
('madaniyat_b2', 'B2', 9, 'Turli madaniyatlarda bir xil imo-ishoralar turlicha ma’noni anglatishi mumkin.', 'В разных культурах одни и те же жесты могут иметь разное значение.'),
('madaniyat_b2', 'B2', 10, 'Men o‘z madaniyatimni boshqalarga tanishtirishni yaxshi ko‘raman.', 'Мне нравится знакомить других со своей культурой.'),
('madaniyat_b2', 'B2', 11, 'Globalizatsiya ba’zi an’analarni yo‘qolish xavfiga olib keladi.', 'Глобализация приводит к риску исчезновения некоторых традиций.'),
('madaniyat_b2', 'B2', 12, 'Milliy liboslar – madaniy merosning bir qismi. – Национальные костюмы', 'часть культурного наследия.'),
('madaniyat_b2', 'B2', 13, 'Har bir mintaqaning o‘ziga xos qo‘shiq va raqslari bor.', 'У каждого региона есть свои песни и танцы.'),
('madaniyat_b2', 'B2', 14, 'Diniy urf-odatlar ham madaniyatning muhim tarkibiy qismi.', 'Религиозные обычаи также важная составляющая культуры.'),
('madaniyat_b2', 'B2', 15, 'Madaniy merosni saqlash uchun muzeylar va kutubxonalar muhim rol o‘ynaydi.', 'Для сохранения культурного наследия важную роль играют музеи и библиотеки.'),
('madaniyat_b2', 'B2', 16, 'Men boshqa madaniyat vakillari bilan suhbatlashishdan zavqlanaman.', 'Я получаю удовольствие от общения с представителями других культур.'),
('madaniyat_b2', 'B2', 17, 'An’analarni buzmaslik kerak, lekin ularni yangi davrga moslashtirish mumkin.', 'Нельзя нарушать традиции, но их можно адаптировать к новой эпохе.'),
('madaniyat_b2', 'B2', 18, 'Ota-ona va bobokalonlarning hayotiy hikmatlari avloddan-avlodga o‘tadi.', 'Житейская мудрость родителей и предков передаётся из поколения в поколение.'),
('madaniyat_b2', 'B2', 19, 'Madaniyat – bu jamiyatning ruhi. – Культура', 'это душа общества.'),
('madaniyat_b2', 'B2', 20, 'Turizm orqali boshqa madaniyatlarni yaqindan o‘rganish mumkin.', 'Через туризм можно ближе познакомиться с другими культурами.'),
('texnologiya_b2', 'B2', 1, 'Sun’iy intellekt kundalik hayotimizga kirib keldi.', 'Искусственный интеллект вошёл в нашу повседневную жизнь.'),
('texnologiya_b2', 'B2', 2, 'Ma’lumotlar xavfsizligi juda muhim.', 'Безопасность данных очень важна.'),
('texnologiya_b2', 'B2', 3, 'Masofaviy ish texnologiyalar tufayli mumkin bo‘ldi.', 'Удалённая работа стала возможной благодаря технологиям.'),
('texnologiya_b2', 'B2', 4, 'Texnologik taraqqiyot ikki qirrali qilich. – Технологический прогресс', 'обоюдоострый меч.'),
('texnologiya_b2', 'B2', 5, 'Raqamli savodxonlik har bir insonga kerak.', 'Цифровая грамотность нужна каждому человеку.'),
('texnologiya_b2', 'B2', 6, 'Bulutli texnologiyalar ma’lumotlarni saqlashni osonlashtirdi.', 'Облачные технологии упростили хранение данных.'),
('texnologiya_b2', 'B2', 7, 'Internet of Things (IoT) uylarimizni aqlli qilmoqda.', 'Интернет вещей делает наши дома умными.'),
('texnologiya_b2', 'B2', 8, 'Kiberhujumlar xavfi ortib bormoqda.', 'Риск кибератак растёт.'),
('texnologiya_b2', 'B2', 9, 'Men ijtimoiy tarmoqlarda kuniga qancha vaqt o‘tkazayotganimni kuzataman.', 'Я отслеживаю, сколько времени провожу в соцсетях в день.'),
('texnologiya_b2', 'B2', 10, '5G tarmog‘i yangi imkoniyatlar ochadi.', 'Сеть 5G открывает новые возможности.'),
('texnologiya_b2', 'B2', 11, 'Blokcheyn nafaqat kriptovalyutalar, balki boshqa sohalarda ham qo‘llaniladi.', 'Блокчейн используется не только в криптовалютах, но и в других сферах.'),
('texnologiya_b2', 'B2', 12, 'Virtual va kengaytirilgan reallik o‘qitishda qo‘llanilmoqda.', 'Виртуальная и дополненная реальность применяются в обучении.'),
('texnologiya_b2', 'B2', 13, 'Texnologiyalar tufayli uzoq masofalarga bemalol muloqot qilish mumkin.', 'Благодаря технологиям можно легко общаться на больших расстояниях.'),
('texnologiya_b2', 'B2', 14, 'Yordamchi texnologiyalar nogironlar hayotini yengillashtiradi.', 'Вспомогательные технологии облегчают жизнь инвалидов.'),
('texnologiya_b2', 'B2', 15, 'Elektron hukumat xizmatlari vaqtni tejaydi.', 'Электронные правительственные услуги экономят время.'),
('texnologiya_b2', 'B2', 16, 'Men yangi gadjetlarni sinab ko‘rishni yaxshi ko‘raman.', 'Я люблю тестировать новые гаджеты.'),
('texnologiya_b2', 'B2', 17, 'Texnologik qaramlik – zamonaviy muammo. – Технологическая зависимость', 'современная проблема.'),
('texnologiya_b2', 'B2', 18, 'Dasturlashni o‘rganish mantiqiy fikrlashni rivojlantiradi.', 'Изучение программирования развивает логическое мышление.'),
('texnologiya_b2', 'B2', 19, 'Ehtimol, kelajakda ko‘plab kasblar avtomatlashtiriladi.', 'Возможно, в будущем многие профессии будут автоматизированы.'),
('texnologiya_b2', 'B2', 20, 'Texnologiyalar insoniyatning katta muammolarini hal qilishga yordam berishi mumkin.', 'Технологии могут помочь решить большие проблемы человечества.');