-- Kunlik o‘qish 14–40: matnda uchraydi, lekin leksikon+lug‘atda yo‘q bo‘lgan tokenlar uchun qo‘shimcha lexemalar.
-- Offline generator: scripts/offlineGenerate076ReadingLexemeFill.ts

-- UNIQUE indeks — `ON CONFLICT (text_id, word_ru_normalized)` uchun majburiy (`054` da indeks olib tashlangan edi).
DELETE FROM public.daily_reading_lexemes l
WHERE COALESCE(trim(l.text_id), '') <> ''
  AND EXISTS (
    SELECT 1
    FROM public.daily_reading_lexemes l2
    WHERE l2.text_id = l.text_id
      AND l2.word_ru_normalized = l.word_ru_normalized
      AND l2.id < l.id
  );

CREATE UNIQUE INDEX IF NOT EXISTS uq_daily_reading_lexemes_text_word_norm
  ON public.daily_reading_lexemes (text_id, word_ru_normalized);

INSERT INTO public.daily_reading_lexemes (text_id, word_ru, word_ru_normalized, translation_uz, audio_ru)
VALUES
  ('kunlik-oqish-14', 'А', 'а', 'Esa, va (qarama-qarshilik)', NULL),
  ('kunlik-oqish-14', 'в', 'в', '...da', NULL),
  ('kunlik-oqish-14', 'всегда', 'всегда', 'Har doim', NULL),
  ('kunlik-oqish-14', 'вы', 'вы', 'Siz', NULL),
  ('kunlik-oqish-14', 'говорили', 'говорили', 'Gaplashdik', NULL),
  ('kunlik-oqish-14', 'долго', 'долго', 'uzoq', NULL),
  ('kunlik-oqish-14', 'друзья', 'друзья', 'Do‘stlar', NULL),
  ('kunlik-oqish-14', 'думаю', 'думаю', 'O‘ylayapman', NULL),
  ('kunlik-oqish-14', 'его', 'его', 'Uni (erkak)', NULL),
  ('kunlik-oqish-14', 'живёт', 'живет', 'Yashaydi', NULL),
  ('kunlik-oqish-14', 'к', 'к', '…ga / …tomon', NULL),
  ('kunlik-oqish-14', 'лето', 'лето', 'Yoz', NULL),
  ('kunlik-oqish-14', 'любите', 'любите', 'sevasizmi', NULL),
  ('kunlik-oqish-14', 'меня', 'меня', 'Meni', NULL),
  ('kunlik-oqish-14', 'Моя', 'моя', 'Mening (ayol otl.)', NULL),
  ('kunlik-oqish-14', 'мы', 'мы', 'Biz', NULL),
  ('kunlik-oqish-14', 'на', 'на', 'Ustida / yo‘nalish', NULL),
  ('kunlik-oqish-14', 'написал', 'написал', 'yozdim', NULL),
  ('kunlik-oqish-14', 'не', 'не', 'Emas', NULL),
  ('kunlik-oqish-14', 'ней', 'ней', 'unda', NULL),
  ('kunlik-oqish-14', 'никогда', 'никогда', 'Hech qachon', NULL),
  ('kunlik-oqish-14', 'новых', 'новых', 'yangi', NULL),
  ('kunlik-oqish-14', 'о', 'о', '…haqida', NULL),
  ('kunlik-oqish-14', 'Он', 'он', 'U (erkak)', NULL),
  ('kunlik-oqish-14', 'Она', 'она', 'U (ayol)', NULL),
  ('kunlik-oqish-14', 'ответил', 'ответил', 'javob berdi', NULL),
  ('kunlik-oqish-14', 'писали', 'писали', 'yozishdi', NULL),
  ('kunlik-oqish-14', 'После', 'после', 'keyin', NULL),
  ('kunlik-oqish-14', 'Потом', 'потом', 'Keyin', NULL),
  ('kunlik-oqish-14', 'преподаватель', 'преподаватель', 'O‘qituvchi', NULL),
  ('kunlik-oqish-14', 'работа', 'работа', 'Ish', NULL),
  ('kunlik-oqish-14', 'разных', 'разных', 'Har xil (род.)', NULL),
  ('kunlik-oqish-14', 'рассказал', 'рассказал', 'Aytib berdi', NULL),
  ('kunlik-oqish-14', 'своём', 'своем', 'o‘zining', NULL),
  ('kunlik-oqish-14', 'своих', 'своих', 'o‘zining', NULL),
  ('kunlik-oqish-14', 'сказал', 'сказал', 'dedim', NULL),
  ('kunlik-oqish-14', 'Сначала', 'сначала', 'avvalo', NULL),
  ('kunlik-oqish-14', 'спрашивали', 'спрашивали', 'so‘rashdi', NULL),
  ('kunlik-oqish-14', 'спросили', 'спросили', 'so‘rashdi', NULL),
  ('kunlik-oqish-14', 'узнать', 'узнать', 'bilmoq', NULL),
  ('kunlik-oqish-14', 'урока', 'урока', 'darsi', NULL),
  ('kunlik-oqish-14', 'уроке', 'уроке', 'Darsda', NULL),
  ('kunlik-oqish-14', 'хочу', 'хочу', 'Xohlayman', NULL),
  ('kunlik-oqish-14', 'чём', 'чем', 'nima bilan', NULL),
  ('kunlik-oqish-14', 'что', 'что', 'nima / kim', NULL),
  ('kunlik-oqish-14', 'это', 'это', 'Bu (o‘rta)', NULL),
  ('kunlik-oqish-14', 'Я', 'я', 'Men', NULL),
  ('kunlik-oqish-15', 'А', 'а', 'Esa, va (qarama-qarshilik)', NULL),
  ('kunlik-oqish-15', 'автобусе', 'автобусе', 'Avtobusda', NULL),
  ('kunlik-oqish-15', 'в', 'в', '...da', NULL),
  ('kunlik-oqish-15', 'вы', 'вы', 'Siz', NULL),
  ('kunlik-oqish-15', 'говорили', 'говорили', 'Gaplashdik', NULL),
  ('kunlik-oqish-15', 'году', 'году', 'yilda', NULL),
  ('kunlik-oqish-15', 'города', 'города', 'shaharlar', NULL),
  ('kunlik-oqish-15', 'городе', 'городе', 'Shaharda', NULL),
  ('kunlik-oqish-15', 'думали', 'думали', 'o‘ylashdi', NULL),
  ('kunlik-oqish-15', 'ездили', 'ездили', 'sayohat qilishdi', NULL),
  ('kunlik-oqish-15', 'езжу', 'езжу', 'Boraman (takroriy)', NULL),
  ('kunlik-oqish-15', 'живу', 'живу', 'Yashayman', NULL),
  ('kunlik-oqish-15', 'Здравствуйте', 'здравствуйте', 'Assalomu alaykum', NULL),
  ('kunlik-oqish-15', 'зовут', 'зовут', 'Chaqirishadi', NULL),
  ('kunlik-oqish-15', 'и', 'и', 'Va', NULL),
  ('kunlik-oqish-15', 'Каждое', 'каждое', 'Har bir', NULL),
  ('kunlik-oqish-15', 'любите', 'любите', 'sevasizmi', NULL),
  ('kunlik-oqish-15', 'Меня', 'меня', 'Meni', NULL),
  ('kunlik-oqish-15', 'метро', 'метро', 'Metro', NULL),
  ('kunlik-oqish-15', 'много', 'много', 'Ko‘p', NULL),
  ('kunlik-oqish-15', 'Мой', 'мой', 'Mening', NULL),
  ('kunlik-oqish-15', 'Москве', 'москве', 'Moskvada', NULL),
  ('kunlik-oqish-15', 'мы', 'мы', 'Biz', NULL),
  ('kunlik-oqish-15', 'на', 'на', 'Ustida / yo‘nalish', NULL),
  ('kunlik-oqish-15', 'находится', 'находится', 'Joylashgan', NULL),
  ('kunlik-oqish-15', 'небольшой', 'небольшой', 'kichik', NULL),
  ('kunlik-oqish-15', 'о', 'о', '…haqida', NULL),
  ('kunlik-oqish-15', 'пишу', 'пишу', 'yozaman', NULL),
  ('kunlik-oqish-15', 'по', 'по', 'yo‘nalish/harakat bo‘ylab («по дороге» → yo‘l bo‘ylab)', NULL),
  ('kunlik-oqish-15', 'поезде', 'поезде', 'poezdda', NULL),
  ('kunlik-oqish-15', 'поехали', 'поехали', 'ketishdi', NULL),
  ('kunlik-oqish-15', 'прошлом', 'прошлом', 'O‘tgan', NULL),
  ('kunlik-oqish-15', 'России', 'россии', 'Rossiyaning', NULL),
  ('kunlik-oqish-15', 'с', 'с', 'birga bilan («с другом»)', NULL),
  ('kunlik-oqish-15', 'своей', 'своей', 'O‘zimning (ayol rod.)', NULL),
  ('kunlik-oqish-15', 'своих', 'своих', 'o‘zining', NULL),
  ('kunlik-oqish-15', 'Сейчас', 'сейчас', 'Hozir', NULL),
  ('kunlik-oqish-15', 'семьёй', 'семьей', 'oilasi bilan', NULL),
  ('kunlik-oqish-15', 'сижу', 'сижу', 'o‘tiraman', NULL),
  ('kunlik-oqish-15', 'утро', 'утро', 'Tong', NULL),
  ('kunlik-oqish-15', 'центре', 'центре', 'Markazda', NULL),
  ('kunlik-oqish-15', 'часто', 'часто', 'Tez-tez', NULL),
  ('kunlik-oqish-15', 'чём', 'чем', 'nima bilan', NULL),
  ('kunlik-oqish-15', 'Этим', 'этим', 'bilan', NULL),
  ('kunlik-oqish-15', 'этот', 'этот', 'Bu (erkak)', NULL),
  ('kunlik-oqish-15', 'Я', 'я', 'Men', NULL),
  ('kunlik-oqish-16', 'в', 'в', '...da', NULL),
  ('kunlik-oqish-16', 'Вечером', 'вечером', 'Kechqurun', NULL),
  ('kunlik-oqish-16', 'вопросы', 'вопросы', 'savollar', NULL),
  ('kunlik-oqish-16', 'всегда', 'всегда', 'Har doim', NULL),
  ('kunlik-oqish-16', 'делаем', 'делаем', 'qilamiz', NULL),
  ('kunlik-oqish-16', 'делаю', 'делаю', 'qilaman', NULL),
  ('kunlik-oqish-16', 'до', 'до', 'Ko‘rishguncha tuzilmasi (до)', NULL),
  ('kunlik-oqish-16', 'друг', 'друг', 'Do‘st', NULL),
  ('kunlik-oqish-16', 'задание', 'задание', 'Vazifa', NULL),
  ('kunlik-oqish-16', 'и', 'и', 'Va', NULL),
  ('kunlik-oqish-16', 'иду', 'иду', 'Ketyapman', NULL),
  ('kunlik-oqish-16', 'или', 'или', 'yoki', NULL),
  ('kunlik-oqish-16', 'Каждое', 'каждое', 'Har bir', NULL),
  ('kunlik-oqish-16', 'мне', 'мне', 'Menga', NULL),
  ('kunlik-oqish-16', 'Мои', 'мои', 'Mening (ko‘plik)', NULL),
  ('kunlik-oqish-16', 'Мой', 'мой', 'Mening', NULL),
  ('kunlik-oqish-16', 'Мы', 'мы', 'Biz', NULL),
  ('kunlik-oqish-16', 'на', 'на', 'Ustida / yo‘nalish', NULL),
  ('kunlik-oqish-16', 'нашем', 'нашем', 'Bizning (predlog bilan)', NULL),
  ('kunlik-oqish-16', 'не', 'не', 'Emas', NULL),
  ('kunlik-oqish-16', 'никогда', 'никогда', 'Hech qachon', NULL),
  ('kunlik-oqish-16', 'но', 'но', 'Lekin', NULL),
  ('kunlik-oqish-16', 'Он', 'он', 'U (erkak)', NULL),
  ('kunlik-oqish-16', 'Они', 'они', 'ular', NULL),
  ('kunlik-oqish-16', 'очень', 'очень', 'Juda', NULL),
  ('kunlik-oqish-16', 'парке', 'парке', 'parkda', NULL),
  ('kunlik-oqish-16', 'пишу', 'пишу', 'yozaman', NULL),
  ('kunlik-oqish-16', 'поздна', 'поздна', 'kech', NULL),
  ('kunlik-oqish-16', 'Потом', 'потом', 'Keyin', NULL),
  ('kunlik-oqish-16', 'работают', 'работают', 'ishlashadi', NULL),
  ('kunlik-oqish-16', 'русским', 'русским', 'rus tilida', NULL),
  ('kunlik-oqish-16', 'с', 'с', 'birga bilan («с другом»)', NULL),
  ('kunlik-oqish-16', 'свою', 'свою', 'O‘zimizning (ayol/vin.)', NULL),
  ('kunlik-oqish-16', 'смотрю', 'смотрю', 'qaraman', NULL),
  ('kunlik-oqish-16', 'тексты', 'тексты', 'matnlar', NULL),
  ('kunlik-oqish-16', 'телевизор', 'телевизор', 'televizor', NULL),
  ('kunlik-oqish-16', 'тоже', 'тоже', 'Ham', NULL),
  ('kunlik-oqish-16', 'умываюсь', 'умываюсь', 'yuvinaman', NULL),
  ('kunlik-oqish-16', 'университете', 'университете', 'Universitetda', NULL),
  ('kunlik-oqish-16', 'утро', 'утро', 'Tong', NULL),
  ('kunlik-oqish-16', 'учится', 'учится', 'o‘qiydi', NULL),
  ('kunlik-oqish-16', 'часов', 'часов', 'soat', NULL),
  ('kunlik-oqish-16', 'я', 'я', 'Men', NULL),
  ('kunlik-oqish-16', 'языком', 'языком', 'til bilan', NULL),
  ('kunlik-oqish-17', 'Анна', 'анна', 'Anna (ism)', NULL),
  ('kunlik-oqish-17', 'аудитории', 'аудитории', 'Auditoriyada', NULL),
  ('kunlik-oqish-17', 'в', 'в', '...da', NULL),
  ('kunlik-oqish-17', 'говорит', 'говорит', 'Gapiradi', NULL),
  ('kunlik-oqish-17', 'её', 'ее', 'Uni (ayol)', NULL),
  ('kunlik-oqish-17', 'ещё', 'еще', 'yana', NULL),
  ('kunlik-oqish-17', 'и', 'и', 'Va', NULL),
  ('kunlik-oqish-17', 'Кто', 'кто', 'kim', NULL),
  ('kunlik-oqish-17', 'Моя', 'моя', 'Mening (ayol otl.)', NULL),
  ('kunlik-oqish-17', 'на', 'на', 'Ustida / yo‘nalish', NULL),
  ('kunlik-oqish-17', 'но', 'но', 'Lekin', NULL),
  ('kunlik-oqish-17', 'новую', 'новую', 'yangi', NULL),
  ('kunlik-oqish-17', 'он', 'он', 'U (erkak)', NULL),
  ('kunlik-oqish-17', 'Она', 'она', 'U (ayol)', NULL),
  ('kunlik-oqish-17', 'отвечает', 'отвечает', 'Javob beradi', NULL),
  ('kunlik-oqish-17', 'отвечаю', 'отвечаю', 'Javob beraman', NULL),
  ('kunlik-oqish-17', 'Отлично', 'отлично', 'Ajoyib', NULL),
  ('kunlik-oqish-17', 'поднимаю', 'поднимаю', 'ko‘taraman', NULL),
  ('kunlik-oqish-17', 'подруга', 'подруга', 'Qiz do‘st', NULL),
  ('kunlik-oqish-17', 'Потом', 'потом', 'Keyin', NULL),
  ('kunlik-oqish-17', 'правильное', 'правильное', 'to‘g‘ri', NULL),
  ('kunlik-oqish-17', 'Преподаватель', 'преподаватель', 'O‘qituvchi', NULL),
  ('kunlik-oqish-17', 'преподавателя', 'преподавателя', 'O‘qituvchining', NULL),
  ('kunlik-oqish-17', 'русского', 'русского', 'rus tilining', NULL),
  ('kunlik-oqish-17', 'Сейчас', 'сейчас', 'Hozir', NULL),
  ('kunlik-oqish-17', 'сижу', 'сижу', 'o‘tiraman', NULL),
  ('kunlik-oqish-17', 'слово', 'слово', 'So‘z', NULL),
  ('kunlik-oqish-17', 'тоже', 'тоже', 'Ham', NULL),
  ('kunlik-oqish-17', 'Ты', 'ты', 'Sen', NULL),
  ('kunlik-oqish-17', 'урок', 'урок', 'dars', NULL),
  ('kunlik-oqish-17', 'хорошо', 'хорошо', 'Yaxshi', NULL),
  ('kunlik-oqish-17', 'хочет', 'хочет', 'xohlaydi', NULL),
  ('kunlik-oqish-17', 'хочу', 'хочу', 'Xohlayman', NULL),
  ('kunlik-oqish-17', 'Я', 'я', 'Men', NULL),
  ('kunlik-oqish-17', 'языка', 'языка', 'tili', NULL),
  ('kunlik-oqish-18', 'буду', 'буду', 'bo‘laman', NULL),
  ('kunlik-oqish-18', 'говорить', 'говорить', 'Gapirmoq', NULL),
  ('kunlik-oqish-18', 'год', 'год', 'Yil', NULL),
  ('kunlik-oqish-18', 'до', 'до', 'Ko‘rishguncha tuzilmasi (до)', NULL),
  ('kunlik-oqish-18', 'друг', 'друг', 'Do‘st', NULL),
  ('kunlik-oqish-18', 'думаю', 'думаю', 'O‘ylayapman', NULL),
  ('kunlik-oqish-18', 'его', 'его', 'Uni (erkak)', NULL),
  ('kunlik-oqish-18', 'есть', 'есть', 'Bor', NULL),
  ('kunlik-oqish-18', 'здравствуйте', 'здравствуйте', 'Assalomu alaykum', NULL),
  ('kunlik-oqish-18', 'знает', 'знает', 'biladi', NULL),
  ('kunlik-oqish-18', 'знают', 'знают', 'bilishadi', NULL),
  ('kunlik-oqish-18', 'интересно', 'интересно', 'Qiziqarli', NULL),
  ('kunlik-oqish-18', 'их', 'их', 'Ularni', NULL),
  ('kunlik-oqish-18', 'меня', 'меня', 'Meni', NULL),
  ('kunlik-oqish-18', 'мне', 'мне', 'Menga', NULL),
  ('kunlik-oqish-18', 'Мои', 'мои', 'Mening (ko‘plik)', NULL),
  ('kunlik-oqish-18', 'Мой', 'мой', 'Mening', NULL),
  ('kunlik-oqish-18', 'моя', 'моя', 'Mening (ayol otl.)', NULL),
  ('kunlik-oqish-18', 'не', 'не', 'Emas', NULL),
  ('kunlik-oqish-18', 'но', 'но', 'Lekin', NULL),
  ('kunlik-oqish-18', 'Он', 'он', 'U (erkak)', NULL),
  ('kunlik-oqish-18', 'Они', 'они', 'ular', NULL),
  ('kunlik-oqish-18', 'очень', 'очень', 'Juda', NULL),
  ('kunlik-oqish-18', 'по-русски', 'по-русски', 'Ruscha', NULL),
  ('kunlik-oqish-18', 'помогает', 'помогает', 'Yordam beradi', NULL),
  ('kunlik-oqish-18', 'понимаю', 'понимаю', 'tushunaman', NULL),
  ('kunlik-oqish-18', 'понимают', 'понимают', 'tushunishadi', NULL),
  ('kunlik-oqish-18', 'преподавателя', 'преподавателя', 'O‘qituvchining', NULL),
  ('kunlik-oqish-18', 'родители', 'родители', 'Ota-ona', NULL),
  ('kunlik-oqish-18', 'русский', 'русский', 'Rus', NULL),
  ('kunlik-oqish-18', 'русского', 'русского', 'rus tilining', NULL),
  ('kunlik-oqish-18', 'русскому', 'русскому', 'rus tiliga', NULL),
  ('kunlik-oqish-18', 'свидания', 'свидания', 'Ko‘rishish', NULL),
  ('kunlik-oqish-18', 'Сейчас', 'сейчас', 'Hozir', NULL),
  ('kunlik-oqish-18', 'слов', 'слов', 'so‘zlar', NULL),
  ('kunlik-oqish-18', 'спасибо', 'спасибо', 'Rahmat', NULL),
  ('kunlik-oqish-18', 'только', 'только', 'faqat', NULL),
  ('kunlik-oqish-18', 'уже', 'уже', 'allaqachon', NULL),
  ('kunlik-oqish-18', 'хочу', 'хочу', 'Xohlayman', NULL),
  ('kunlik-oqish-18', 'что', 'что', 'nima / kim', NULL),
  ('kunlik-oqish-18', 'это', 'это', 'Bu (o‘rta)', NULL),
  ('kunlik-oqish-18', 'Я', 'я', 'Men', NULL),
  ('kunlik-oqish-18', 'язык', 'язык', 'til', NULL),
  ('kunlik-oqish-18', 'языка', 'языка', 'tili', NULL),
  ('kunlik-oqish-18', 'языку', 'языку', 'tiliga', NULL),
  ('kunlik-oqish-19', 'А', 'а', 'Esa, va (qarama-qarshilik)', NULL),
  ('kunlik-oqish-19', 'Анна', 'анна', 'Anna (ism)', NULL),
  ('kunlik-oqish-19', 'брат', 'брат', 'Aka / uka', NULL),
  ('kunlik-oqish-19', 'был', 'был', 'Edi (erkak)', NULL),
  ('kunlik-oqish-19', 'в', 'в', '...da', NULL),
  ('kunlik-oqish-19', 'где', 'где', 'qayerda', NULL),
  ('kunlik-oqish-19', 'да', 'да', 'Ha', NULL),
  ('kunlik-oqish-19', 'делаешь', 'делаешь', 'qilasan', NULL),
  ('kunlik-oqish-19', 'думаешь', 'думаешь', 'o‘ylaysan', NULL),
  ('kunlik-oqish-19', 'думаю', 'думаю', 'O‘ylayapman', NULL),
  ('kunlik-oqish-19', 'за', 'за', 'uchun / ortidan', NULL),
  ('kunlik-oqish-19', 'знаешь', 'знаешь', 'bilasan', NULL),
  ('kunlik-oqish-19', 'иду', 'иду', 'Ketyapman', NULL),
  ('kunlik-oqish-19', 'интересную', 'интересную', 'qiziqarli', NULL),
  ('kunlik-oqish-19', 'Как', 'как', 'Qanday', NULL),
  ('kunlik-oqish-19', 'книги', 'книги', 'Kitoblar', NULL),
  ('kunlik-oqish-19', 'книгу', 'книгу', 'kitob', NULL),
  ('kunlik-oqish-19', 'любишь', 'любишь', 'sevasan', NULL),
  ('kunlik-oqish-19', 'мне', 'мне', 'Menga', NULL),
  ('kunlik-oqish-19', 'на', 'на', 'Ustida / yo‘nalish', NULL),
  ('kunlik-oqish-19', 'найти', 'найти', 'topmoq', NULL),
  ('kunlik-oqish-19', 'не', 'не', 'Emas', NULL),
  ('kunlik-oqish-19', 'Он', 'он', 'U (erkak)', NULL),
  ('kunlik-oqish-19', 'по', 'по', 'yo‘nalish/harakat bo‘ylab («по дороге» → yo‘l bo‘ylab)', NULL),
  ('kunlik-oqish-19', 'Пока', 'пока', 'Xayr', NULL),
  ('kunlik-oqish-19', 'помогает', 'помогает', 'Yordam beradi', NULL),
  ('kunlik-oqish-19', 'Потому', 'потому', 'chunki', NULL),
  ('kunlik-oqish-19', 'почему', 'почему', 'nimaga', NULL),
  ('kunlik-oqish-19', 'Привет', 'привет', 'Salom', NULL),
  ('kunlik-oqish-19', 'работает', 'работает', 'Ishlaydi', NULL),
  ('kunlik-oqish-19', 'Саша', 'саша', 'Sasha', NULL),
  ('kunlik-oqish-19', 'Сейчас', 'сейчас', 'Hozir', NULL),
  ('kunlik-oqish-19', 'Спасибо', 'спасибо', 'Rahmat', NULL),
  ('kunlik-oqish-19', 'твой', 'твой', 'sening', NULL),
  ('kunlik-oqish-19', 'тебя', 'тебя', 'Seni', NULL),
  ('kunlik-oqish-19', 'ты', 'ты', 'Sen', NULL),
  ('kunlik-oqish-19', 'Хорошего', 'хорошего', 'yaxshi', NULL),
  ('kunlik-oqish-19', 'читаю', 'читаю', 'O‘qiyman', NULL),
  ('kunlik-oqish-19', 'Что', 'что', 'nima / kim', NULL),
  ('kunlik-oqish-19', 'этот', 'этот', 'Bu (erkak)', NULL),
  ('kunlik-oqish-19', 'Я', 'я', 'Men', NULL),
  ('kunlik-oqish-20', 'А', 'а', 'Esa, va (qarama-qarshilik)', NULL),
  ('kunlik-oqish-20', 'Анна', 'анна', 'Anna (ism)', NULL),
  ('kunlik-oqish-20', 'буду', 'буду', 'bo‘laman', NULL),
  ('kunlik-oqish-20', 'в', 'в', '...da', NULL),
  ('kunlik-oqish-20', 'вместе', 'вместе', 'Birga', NULL),
  ('kunlik-oqish-20', 'вопросы', 'вопросы', 'savollar', NULL),
  ('kunlik-oqish-20', 'встаю', 'встаю', 'Turaman', NULL),
  ('kunlik-oqish-20', 'говорить', 'говорить', 'Gapirmoq', NULL),
  ('kunlik-oqish-20', 'городу', 'городу', 'shaharga', NULL),
  ('kunlik-oqish-20', 'гуляем', 'гуляем', 'sayr qilamiz', NULL),
  ('kunlik-oqish-20', 'два', 'два', 'Ikki', NULL),
  ('kunlik-oqish-20', 'делаешь', 'делаешь', 'qilasan', NULL),
  ('kunlik-oqish-20', 'делаю', 'делаю', 'qilaman', NULL),
  ('kunlik-oqish-20', 'день', 'день', 'Kun', NULL),
  ('kunlik-oqish-20', 'думаю', 'думаю', 'O‘ylayapman', NULL),
  ('kunlik-oqish-20', 'еду', 'еду', 'ketaman', NULL),
  ('kunlik-oqish-20', 'Жду', 'жду', 'kutaman', NULL),
  ('kunlik-oqish-20', 'живу', 'живу', 'Yashayman', NULL),
  ('kunlik-oqish-20', 'завтракаю', 'завтракаю', 'Nonushta qilaman', NULL),
  ('kunlik-oqish-20', 'и', 'и', 'Va', NULL),
  ('kunlik-oqish-20', 'иногда', 'иногда', 'Ba’zida', NULL),
  ('kunlik-oqish-20', 'Каждый', 'каждый', 'har bir', NULL),
  ('kunlik-oqish-20', 'Как', 'как', 'Qanday', NULL),
  ('kunlik-oqish-20', 'Мне', 'мне', 'Menga', NULL),
  ('kunlik-oqish-20', 'много', 'много', 'Ko‘p', NULL),
  ('kunlik-oqish-20', 'Мои', 'мои', 'Mening (ko‘plik)', NULL),
  ('kunlik-oqish-20', 'мой', 'мой', 'Mening', NULL),
  ('kunlik-oqish-20', 'Москве', 'москве', 'Moskvada', NULL),
  ('kunlik-oqish-20', 'Мы', 'мы', 'Biz', NULL),
  ('kunlik-oqish-20', 'на', 'на', 'Ustida / yo‘nalish', NULL),
  ('kunlik-oqish-20', 'Напиши', 'напиши', 'yoz', NULL),
  ('kunlik-oqish-20', 'но', 'но', 'Lekin', NULL),
  ('kunlik-oqish-20', 'новые', 'новые', 'yangi', NULL),
  ('kunlik-oqish-20', 'отвечаю', 'отвечаю', 'Javob beraman', NULL),
  ('kunlik-oqish-20', 'очень', 'очень', 'Juda', NULL),
  ('kunlik-oqish-20', 'ошибки', 'ошибки', 'Xatolar', NULL),
  ('kunlik-oqish-20', 'пишу', 'пишу', 'yozaman', NULL),
  ('kunlik-oqish-20', 'по', 'по', 'yo‘nalish/harakat bo‘ylab («по дороге» → yo‘l bo‘ylab)', NULL),
  ('kunlik-oqish-20', 'Пока', 'пока', 'Xayr', NULL),
  ('kunlik-oqish-20', 'помогают', 'помогают', 'yordam berishadi', NULL),
  ('kunlik-oqish-20', 'понимаю', 'понимаю', 'tushunaman', NULL),
  ('kunlik-oqish-20', 'преподавателя', 'преподавателя', 'O‘qituvchining', NULL),
  ('kunlik-oqish-20', 'Привет', 'привет', 'Salom', NULL),
  ('kunlik-oqish-20', 'русский', 'русский', 'Rus', NULL),
  ('kunlik-oqish-20', 'русском', 'русском', 'rus tilida', NULL),
  ('kunlik-oqish-20', 'с', 'с', 'birga bilan («с другом»)', NULL),
  ('kunlik-oqish-20', 'свободно', 'свободно', 'Erkin', NULL),
  ('kunlik-oqish-20', 'сейчас', 'сейчас', 'Hozir', NULL),
  ('kunlik-oqish-20', 'смотрим', 'смотрим', 'qaramiz', NULL),
  ('kunlik-oqish-20', 'твои', 'твои', 'sening', NULL),
  ('kunlik-oqish-20', 'твой', 'твой', 'sening', NULL),
  ('kunlik-oqish-20', 'ты', 'ты', 'Sen', NULL),
  ('kunlik-oqish-20', 'уже', 'уже', 'allaqachon', NULL),
  ('kunlik-oqish-20', 'университет', 'университет', 'Universitet', NULL),
  ('kunlik-oqish-20', 'университете', 'университете', 'Universitetda', NULL),
  ('kunlik-oqish-20', 'утра', 'утра', 'ertalabki', NULL),
  ('kunlik-oqish-20', 'часов', 'часов', 'soat', NULL),
  ('kunlik-oqish-20', 'читаю', 'читаю', 'O‘qiyman', NULL),
  ('kunlik-oqish-20', 'что', 'что', 'nima / kim', NULL),
  ('kunlik-oqish-20', 'Я', 'я', 'Men', NULL),
  ('kunlik-oqish-20', 'язык', 'язык', 'til', NULL),
  ('kunlik-oqish-20', 'языке', 'языке', 'tilida', NULL),
  ('kunlik-oqish-21', 'активным', 'активным', 'faol (korinish)', NULL),
  ('kunlik-oqish-21', 'Алишера', 'алишера', 'Alisherning', NULL),
  ('kunlik-oqish-21', 'быть', 'быть', 'Bo‘lmoq (vaziyatda)', NULL),
  ('kunlik-oqish-21', 'вопросы', 'вопросы', 'savollar', NULL),
  ('kunlik-oqish-21', 'всегда', 'всегда', 'Har doim', NULL),
  ('kunlik-oqish-21', 'говорю', 'говорю', 'Aytaman', NULL),
  ('kunlik-oqish-21', 'день', 'день', 'Kun', NULL),
  ('kunlik-oqish-21', 'друг', 'друг', 'Do‘st', NULL),
  ('kunlik-oqish-21', 'и', 'и', 'Va', NULL),
  ('kunlik-oqish-21', 'Каждый', 'каждый', 'har bir', NULL),
  ('kunlik-oqish-21', 'когда', 'когда', 'qachon', NULL),
  ('kunlik-oqish-21', 'лучше', 'лучше', 'Yaxshiroq', NULL),
  ('kunlik-oqish-21', 'люблю', 'люблю', 'Sevaman / yaxshi ko‘raman', NULL),
  ('kunlik-oqish-21', 'Младшая', 'младшая', 'Kichik', NULL),
  ('kunlik-oqish-21', 'Мой', 'мой', 'Mening', NULL),
  ('kunlik-oqish-21', 'мы', 'мы', 'Biz', NULL),
  ('kunlik-oqish-21', 'На', 'на', 'Ustida / yo‘nalish', NULL),
  ('kunlik-oqish-21', 'не', 'не', 'Emas', NULL),
  ('kunlik-oqish-21', 'но', 'но', 'Lekin', NULL),
  ('kunlik-oqish-21', 'новые', 'новые', 'yangi', NULL),
  ('kunlik-oqish-21', 'он', 'он', 'U (erkak)', NULL),
  ('kunlik-oqish-21', 'Она', 'она', 'U (ayol)', NULL),
  ('kunlik-oqish-21', 'отвечаем', 'отвечаем', 'javob beramiz', NULL),
  ('kunlik-oqish-21', 'отвечает', 'отвечает', 'Javob beradi', NULL),
  ('kunlik-oqish-21', 'очень', 'очень', 'Juda', NULL),
  ('kunlik-oqish-21', 'по-русски', 'по-русски', 'Ruscha', NULL),
  ('kunlik-oqish-21', 'пока', 'пока', 'Xayr', NULL),
  ('kunlik-oqish-21', 'Преподаватель', 'преподаватель', 'O‘qituvchi', NULL),
  ('kunlik-oqish-21', 'преподавателя', 'преподавателя', 'O‘qituvchining', NULL),
  ('kunlik-oqish-21', 'работают', 'работают', 'ishlashadi', NULL),
  ('kunlik-oqish-21', 'руку', 'руку', 'Qo‘lni', NULL),
  ('kunlik-oqish-21', 'русский', 'русский', 'Rus', NULL),
  ('kunlik-oqish-21', 'Сейчас', 'сейчас', 'Hozir', NULL),
  ('kunlik-oqish-21', 'сестра', 'сестра', 'Opa / singil', NULL),
  ('kunlik-oqish-21', 'слова', 'слова', 'so‘zlar', NULL),
  ('kunlik-oqish-21', 'студенты', 'студенты', 'Talabalar', NULL),
  ('kunlik-oqish-21', 'тоже', 'тоже', 'Ham', NULL),
  ('kunlik-oqish-21', 'только', 'только', 'faqat', NULL),
  ('kunlik-oqish-21', 'уроке', 'уроке', 'Darsda', NULL),
  ('kunlik-oqish-21', 'учу', 'учу', 'o‘rganaman', NULL),
  ('kunlik-oqish-21', 'хорошо', 'хорошо', 'Yaxshi', NULL),
  ('kunlik-oqish-21', 'хочу', 'хочу', 'Xohlayman', NULL),
  ('kunlik-oqish-21', 'часто', 'часто', 'Tez-tez', NULL),
  ('kunlik-oqish-21', 'Я', 'я', 'Men', NULL),
  ('kunlik-oqish-21', 'язык', 'язык', 'til', NULL),
  ('kunlik-oqish-22', 'быстро', 'быстро', 'Tez', NULL),
  ('kunlik-oqish-22', 'в', 'в', '...da', NULL),
  ('kunlik-oqish-22', 'вижу', 'вижу', 'ko‘raman', NULL),
  ('kunlik-oqish-22', 'Вокруг', 'вокруг', 'atrofida', NULL),
  ('kunlik-oqish-22', 'время', 'время', 'Vaqt', NULL),
  ('kunlik-oqish-22', 'глубоко', 'глубоко', 'chuqur', NULL),
  ('kunlik-oqish-22', 'года', 'года', 'Yosh (22 года)', NULL),
  ('kunlik-oqish-22', 'голоса', 'голоса', 'ovozlar', NULL),
  ('kunlik-oqish-22', 'гуляю', 'гуляю', 'Sayr qilaman', NULL),
  ('kunlik-oqish-22', 'держит', 'держит', 'ushlab turadi', NULL),
  ('kunlik-oqish-22', 'детей', 'детей', 'bolalar', NULL),
  ('kunlik-oqish-22', 'думаю', 'думаю', 'O‘ylayapman', NULL),
  ('kunlik-oqish-22', 'жёлтые', 'желтые', 'sariq', NULL),
  ('kunlik-oqish-22', 'землю', 'землю', 'zamini', NULL),
  ('kunlik-oqish-22', 'и', 'и', 'Va', NULL),
  ('kunlik-oqish-22', 'каждый', 'каждый', 'har bir', NULL),
  ('kunlik-oqish-22', 'как', 'как', 'Qanday', NULL),
  ('kunlik-oqish-22', 'летит', 'летит', 'uchadi', NULL),
  ('kunlik-oqish-22', 'листьев', 'листьев', 'barglar', NULL),
  ('kunlik-oqish-22', 'людей', 'людей', 'Odamlar (род.)', NULL),
  ('kunlik-oqish-22', 'медленно', 'медленно', 'Sekin', NULL),
  ('kunlik-oqish-22', 'много', 'много', 'Ko‘p', NULL),
  ('kunlik-oqish-22', 'молодость', 'молодость', 'yoshlik', NULL),
  ('kunlik-oqish-22', 'момент', 'момент', 'lahza', NULL),
  ('kunlik-oqish-22', 'на', 'на', 'Ustida / yo‘nalish', NULL),
  ('kunlik-oqish-22', 'Нужно', 'нужно', 'Kerak', NULL),
  ('kunlik-oqish-22', 'о', 'о', '…haqida', NULL),
  ('kunlik-oqish-22', 'Она', 'она', 'U (ayol)', NULL),
  ('kunlik-oqish-22', 'они', 'они', 'ular', NULL),
  ('kunlik-oqish-22', 'парке', 'парке', 'parkda', NULL),
  ('kunlik-oqish-22', 'прекрасное', 'прекрасное', 'go‘zal', NULL),
  ('kunlik-oqish-22', 'птиц', 'птиц', 'qushlar', NULL),
  ('kunlik-oqish-22', 'руках', 'руках', 'qo‘llarda', NULL),
  ('kunlik-oqish-22', 'свою', 'свою', 'O‘zimizning (ayol/vin.)', NULL),
  ('kunlik-oqish-22', 'себя', 'себя', 'o‘zini', NULL),
  ('kunlik-oqish-22', 'Сегодня', 'сегодня', 'Bugun', NULL),
  ('kunlik-oqish-22', 'сидит', 'сидит', 'o‘tiradi', NULL),
  ('kunlik-oqish-22', 'смех', 'смех', 'kulgu', NULL),
  ('kunlik-oqish-22', 'смотрит', 'смотрит', 'qaraydi', NULL),
  ('kunlik-oqish-22', 'смотрю', 'смотрю', 'qaraman', NULL),
  ('kunlik-oqish-22', 'счастливым', 'счастливым', 'baxtli', NULL),
  ('kunlik-oqish-22', 'том', 'том', 'u … da', NULL),
  ('kunlik-oqish-22', 'чувствую', 'чувствую', 'his qilaman', NULL),
  ('kunlik-oqish-22', 'шум', 'шум', 'shovqin', NULL),
  ('kunlik-oqish-22', 'я', 'я', 'Men', NULL),
  ('kunlik-oqish-23', 'благодарю', 'благодарю', 'rahmat', NULL),
  ('kunlik-oqish-23', 'большой', 'большой', 'katta', NULL),
  ('kunlik-oqish-23', 'было', 'было', 'Edi (o‘rta rod)', NULL),
  ('kunlik-oqish-23', 'быть', 'быть', 'Bo‘lmoq (vaziyatda)', NULL),
  ('kunlik-oqish-23', 'в', 'в', '...da', NULL),
  ('kunlik-oqish-23', 'Вечером', 'вечером', 'Kechqurun', NULL),
  ('kunlik-oqish-23', 'внимательным', 'внимательным', 'diqqatli', NULL),
  ('kunlik-oqish-23', 'возле', 'возле', 'yonida', NULL),
  ('kunlik-oqish-23', 'говорит', 'говорит', 'Gapiradi', NULL),
  ('kunlik-oqish-23', 'день', 'день', 'Kun', NULL),
  ('kunlik-oqish-23', 'дом', 'дом', 'uy', NULL),
  ('kunlik-oqish-23', 'его', 'его', 'Uni (erkak)', NULL),
  ('kunlik-oqish-23', 'живёт', 'живет', 'Yashaydi', NULL),
  ('kunlik-oqish-23', 'здесь', 'здесь', 'Bu yerda', NULL),
  ('kunlik-oqish-23', 'и', 'и', 'Va', NULL),
  ('kunlik-oqish-23', 'Инженер', 'инженер', 'Muhandis', NULL),
  ('kunlik-oqish-23', 'Каждый', 'каждый', 'har bir', NULL),
  ('kunlik-oqish-23', 'любим', 'любим', 'Sevamiz', NULL),
  ('kunlik-oqish-23', 'людей', 'людей', 'Odamlar (род.)', NULL),
  ('kunlik-oqish-23', 'Мама', 'мама', 'Ona', NULL),
  ('kunlik-oqish-23', 'меня', 'меня', 'Meni', NULL),
  ('kunlik-oqish-23', 'мимо', 'мимо', 'yo‘nalishdan o‘tib', NULL),
  ('kunlik-oqish-23', 'Мы', 'мы', 'Biz', NULL),
  ('kunlik-oqish-23', 'На', 'на', 'Ustida / yo‘nalish', NULL),
  ('kunlik-oqish-23', 'нам', 'нам', 'bizga', NULL),
  ('kunlik-oqish-23', 'наш', 'наш', 'Bizning', NULL),
  ('kunlik-oqish-23', 'Наша', 'наша', 'bizning', NULL),
  ('kunlik-oqish-23', 'Не', 'не', 'Emas', NULL),
  ('kunlik-oqish-23', 'обещаю', 'обещаю', 'va’da beraman', NULL),
  ('kunlik-oqish-23', 'Она', 'она', 'U (ayol)', NULL),
  ('kunlik-oqish-23', 'парк', 'парк', 'park', NULL),
  ('kunlik-oqish-23', 'поле', 'поле', 'Dala', NULL),
  ('kunlik-oqish-23', 'помочь', 'помочь', 'Yordam bermoq', NULL),
  ('kunlik-oqish-23', 'продуктами', 'продуктами', 'mahsulotlar bilan', NULL),
  ('kunlik-oqish-23', 'Рабочие', 'рабочие', 'ishchilar', NULL),
  ('kunlik-oqish-23', 'район', 'район', 'Tuman', NULL),
  ('kunlik-oqish-23', 'с', 'с', 'birga bilan («с другом»)', NULL),
  ('kunlik-oqish-23', 'сегодня', 'сегодня', 'Bugun', NULL),
  ('kunlik-oqish-23', 'семья', 'семья', 'Oila', NULL),
  ('kunlik-oqish-23', 'сильный', 'сильный', 'kuchli', NULL),
  ('kunlik-oqish-23', 'сосед', 'сосед', 'qo‘shni', NULL),
  ('kunlik-oqish-23', 'сумку', 'сумку', 'sumkani', NULL),
  ('kunlik-oqish-23', 'тяжёлую', 'тяжелую', 'og‘ir', NULL),
  ('kunlik-oqish-23', 'ходите', 'ходите', 'yurasiz', NULL),
  ('kunlik-oqish-23', 'хотим', 'хотим', 'xohlaymiz', NULL),
  ('kunlik-oqish-23', 'чтобы', 'чтобы', '…uchun', NULL),
  ('kunlik-oqish-23', 'школу', 'школу', 'maktabga', NULL),
  ('kunlik-oqish-23', 'я', 'я', 'Men', NULL),
  ('kunlik-oqish-24', 'А', 'а', 'Esa, va (qarama-qarshilik)', NULL),
  ('kunlik-oqish-24', 'Брат', 'брат', 'Aka / uka', NULL),
  ('kunlik-oqish-24', 'будет', 'будет', 'bo‘ladi', NULL),
  ('kunlik-oqish-24', 'в', 'в', '...da', NULL),
  ('kunlik-oqish-24', 'Вечером', 'вечером', 'Kechqurun', NULL),
  ('kunlik-oqish-24', 'Всё', 'все', 'Barcha', NULL),
  ('kunlik-oqish-24', 'входа', 'входа', 'Kirish joyi', NULL),
  ('kunlik-oqish-24', 'дел', 'дел', 'ishlar', NULL),
  ('kunlik-oqish-24', 'друзьями', 'друзьями', 'do‘stlar bilan', NULL),
  ('kunlik-oqish-24', 'думаю', 'думаю', 'O‘ylayapman', NULL),
  ('kunlik-oqish-24', 'если', 'если', 'agar', NULL),
  ('kunlik-oqish-24', 'Завтра', 'завтра', 'ertaga', NULL),
  ('kunlik-oqish-24', 'и', 'и', 'Va', NULL),
  ('kunlik-oqish-24', 'кафе', 'кафе', 'Kafe', NULL),
  ('kunlik-oqish-24', 'книгу', 'книгу', 'kitob', NULL),
  ('kunlik-oqish-24', 'лёгкий', 'легкий', 'engil', NULL),
  ('kunlik-oqish-24', 'магазине', 'магазине', 'Do‘konda', NULL),
  ('kunlik-oqish-24', 'Мама', 'мама', 'Ona', NULL),
  ('kunlik-oqish-24', 'меня', 'меня', 'Meni', NULL),
  ('kunlik-oqish-24', 'много', 'много', 'Ko‘p', NULL),
  ('kunlik-oqish-24', 'молоко', 'молоко', 'sut', NULL),
  ('kunlik-oqish-24', 'мы', 'мы', 'Biz', NULL),
  ('kunlik-oqish-24', 'на', 'на', 'Ustida / yo‘nalish', NULL),
  ('kunlik-oqish-24', 'не', 'не', 'Emas', NULL),
  ('kunlik-oqish-24', 'о', 'о', '…haqida', NULL),
  ('kunlik-oqish-24', 'обеда', 'обеда', 'tushlik', NULL),
  ('kunlik-oqish-24', 'обещал', 'обещал', 'va’da berdi', NULL),
  ('kunlik-oqish-24', 'планах', 'планах', 'Rejalar', NULL),
  ('kunlik-oqish-24', 'После', 'после', 'keyin', NULL),
  ('kunlik-oqish-24', 'прислать', 'прислать', 'yubormoq', NULL),
  ('kunlik-oqish-24', 'с', 'с', 'birga bilan («с другом»)', NULL),
  ('kunlik-oqish-24', 'сейчас', 'сейчас', 'Hozir', NULL),
  ('kunlik-oqish-24', 'сказала', 'сказала', 'dedi', NULL),
  ('kunlik-oqish-24', 'у', 'у', '...da borlik', NULL),
  ('kunlik-oqish-24', 'Утром', 'утром', 'Ertalab', NULL),
  ('kunlik-oqish-24', 'хлеб', 'хлеб', 'non', NULL),
  ('kunlik-oqish-24', 'хорошо', 'хорошо', 'Yaxshi', NULL),
  ('kunlik-oqish-24', 'что', 'что', 'nima / kim', NULL),
  ('kunlik-oqish-24', 'я', 'я', 'Men', NULL),
  ('kunlik-oqish-25', 'будем', 'будем', 'bo‘lamiz', NULL),
  ('kunlik-oqish-25', 'в', 'в', '...da', NULL),
  ('kunlik-oqish-25', 'важные', 'важные', 'muhim', NULL),
  ('kunlik-oqish-25', 'вместе', 'вместе', 'Birga', NULL),
  ('kunlik-oqish-25', 'всё', 'все', 'Barcha', NULL),
  ('kunlik-oqish-25', 'второе', 'второе', 'ikkinchi', NULL),
  ('kunlik-oqish-25', 'Главное', 'главное', 'asosiysi', NULL),
  ('kunlik-oqish-25', 'говорили', 'говорили', 'Gaplashdik', NULL),
  ('kunlik-oqish-25', 'голове', 'голове', 'Boshda', NULL),
  ('kunlik-oqish-25', 'готовить', 'готовить', 'Tayyorlamoq', NULL),
  ('kunlik-oqish-25', 'день', 'день', 'Kun', NULL),
  ('kunlik-oqish-25', 'держали', 'держали', 'ushlab turishdi', NULL),
  ('kunlik-oqish-25', 'другу', 'другу', 'Do‘stimga', NULL),
  ('kunlik-oqish-25', 'дышать', 'дышать', 'Nafas olmoq', NULL),
  ('kunlik-oqish-25', 'Если', 'если', 'agar', NULL),
  ('kunlik-oqish-25', 'Завтра', 'завтра', 'ertaga', NULL),
  ('kunlik-oqish-25', 'занятия', 'занятия', 'mashg‘ulotlar', NULL),
  ('kunlik-oqish-25', 'звонить', 'звонить', 'Qo‘ng‘iroq qilmoq', NULL),
  ('kunlik-oqish-25', 'и', 'и', 'Va', NULL),
  ('kunlik-oqish-25', 'каждый', 'каждый', 'har bir', NULL),
  ('kunlik-oqish-25', 'как', 'как', 'Qanday', NULL),
  ('kunlik-oqish-25', 'любить', 'любить', 'Sevmoq', NULL),
  ('kunlik-oqish-25', 'маленькие', 'маленькие', 'kichkina', NULL),
  ('kunlik-oqish-25', 'между', 'между', 'o‘rtasida', NULL),
  ('kunlik-oqish-25', 'мы', 'мы', 'Biz', NULL),
  ('kunlik-oqish-25', 'На', 'на', 'Ustida / yo‘nalish', NULL),
  ('kunlik-oqish-25', 'не', 'не', 'Emas', NULL),
  ('kunlik-oqish-25', 'неделе', 'неделе', 'haftada', NULL),
  ('kunlik-oqish-25', 'получится', 'получится', 'bo‘ladi', NULL),
  ('kunlik-oqish-25', 'просить', 'просить', 'So‘ramoq', NULL),
  ('kunlik-oqish-25', 'простые', 'простые', 'oddiy', NULL),
  ('kunlik-oqish-25', 'радоваться', 'радоваться', 'xursand bo‘lmoq', NULL),
  ('kunlik-oqish-25', 'разницу', 'разницу', 'farqni', NULL),
  ('kunlik-oqish-25', 'результат', 'результат', 'natija', NULL),
  ('kunlik-oqish-25', 'свободно', 'свободно', 'Erkin', NULL),
  ('kunlik-oqish-25', 'себе', 'себе', 'o‘ziga', NULL),
  ('kunlik-oqish-25', 'себя', 'себя', 'o‘zini', NULL),
  ('kunlik-oqish-25', 'слышать', 'слышать', 'Eshitmoq', NULL),
  ('kunlik-oqish-25', 'смотреть', 'смотреть', 'Qaramoq', NULL),
  ('kunlik-oqish-25', 'совета', 'совета', 'maslahat', NULL),
  ('kunlik-oqish-25', 'спешили', 'спешили', 'shoshilishdi', NULL),
  ('kunlik-oqish-25', 'ставили', 'ставили', 'qo‘yishdi', NULL),
  ('kunlik-oqish-25', 'теста', 'теста', 'test', NULL),
  ('kunlik-oqish-25', 'учили', 'учили', 'o‘rgatishdi', NULL),
  ('kunlik-oqish-25', 'фразы', 'фразы', 'iboralar', NULL),
  ('kunlik-oqish-25', 'ходили', 'ходили', 'yurishdi', NULL),
  ('kunlik-oqish-25', 'цели', 'цели', 'maqsadlar', NULL),
  ('kunlik-oqish-25', 'этой', 'этой', 'bu', NULL),
  ('kunlik-oqish-25', 'я', 'я', 'Men', NULL),
  ('kunlik-oqish-26', 'а', 'а', 'Esa, va (qarama-qarshilik)', NULL),
  ('kunlik-oqish-26', 'Антон', 'антон', 'Anton', NULL),
  ('kunlik-oqish-26', 'Антона', 'антона', 'Antonning', NULL),
  ('kunlik-oqish-26', 'Бабушка', 'бабушка', 'Buvi', NULL),
  ('kunlik-oqish-26', 'в', 'в', '...da', NULL),
  ('kunlik-oqish-26', 'видеть', 'видеть', 'Ko‘rmoq (sezgi)', NULL),
  ('kunlik-oqish-26', 'вместе', 'вместе', 'Birga', NULL),
  ('kunlik-oqish-26', 'день', 'день', 'Kun', NULL),
  ('kunlik-oqish-26', 'долгой', 'долгой', 'uzoq', NULL),
  ('kunlik-oqish-26', 'друга', 'друга', 'Do‘st (род.; 2 uchun)', NULL),
  ('kunlik-oqish-26', 'заказал', 'заказал', 'Buyurtdim', NULL),
  ('kunlik-oqish-26', 'интересной', 'интересной', 'qiziqarli', NULL),
  ('kunlik-oqish-26', 'интересный', 'интересный', 'qiziqarli', NULL),
  ('kunlik-oqish-26', 'кафе', 'кафе', 'Kafe', NULL),
  ('kunlik-oqish-26', 'кофе', 'кофе', 'Kofe', NULL),
  ('kunlik-oqish-26', 'любимый', 'любимый', 'Sevimli', NULL),
  ('kunlik-oqish-26', 'меня', 'меня', 'Meni', NULL),
  ('kunlik-oqish-26', 'много', 'много', 'Ko‘p', NULL),
  ('kunlik-oqish-26', 'мой', 'мой', 'Mening', NULL),
  ('kunlik-oqish-26', 'Мы', 'мы', 'Biz', NULL),
  ('kunlik-oqish-26', 'На', 'на', 'Ustida / yo‘nalish', NULL),
  ('kunlik-oqish-26', 'нас', 'нас', 'Bizni', NULL),
  ('kunlik-oqish-26', 'но', 'но', 'Lekin', NULL),
  ('kunlik-oqish-26', 'Он', 'он', 'U (erkak)', NULL),
  ('kunlik-oqish-26', 'Она', 'она', 'U (ayol)', NULL),
  ('kunlik-oqish-26', 'очень', 'очень', 'Juda', NULL),
  ('kunlik-oqish-26', 'пирог', 'пирог', 'Pirog', NULL),
  ('kunlik-oqish-26', 'по', 'по', 'yo‘nalish/harakat bo‘ylab («по дороге» → yo‘l bo‘ylab)', NULL),
  ('kunlik-oqish-26', 'Потом', 'потом', 'Keyin', NULL),
  ('kunlik-oqish-26', 'пошли', 'пошли', 'ketishdi', NULL),
  ('kunlik-oqish-26', 'рада', 'рада', 'xursand', NULL),
  ('kunlik-oqish-26', 'светило', 'светило', 'nur sochar edi', NULL),
  ('kunlik-oqish-26', 'своего', 'своего', 'o‘zining', NULL),
  ('kunlik-oqish-26', 'Солнце', 'солнце', 'quyosh', NULL),
  ('kunlik-oqish-26', 'Там', 'там', 'u yerda', NULL),
  ('kunlik-oqish-26', 'У', 'у', '...da borlik', NULL),
  ('kunlik-oqish-26', 'удачным', 'удачным', 'omadli', NULL),
  ('kunlik-oqish-26', 'улице', 'улице', 'ko‘chada', NULL),
  ('kunlik-oqish-26', 'университете', 'университете', 'Universitetda', NULL),
  ('kunlik-oqish-26', 'чай', 'чай', 'choy', NULL),
  ('kunlik-oqish-26', 'я', 'я', 'Men', NULL),
  ('kunlik-oqish-26', 'ярко', 'ярко', 'yorqin', NULL),
  ('kunlik-oqish-27', 'брат', 'брат', 'Aka / uka', NULL),
  ('kunlik-oqish-27', 'буду', 'буду', 'bo‘laman', NULL),
  ('kunlik-oqish-27', 'был', 'был', 'Edi (erkak)', NULL),
  ('kunlik-oqish-27', 'были', 'были', 'Edilar', NULL),
  ('kunlik-oqish-27', 'было', 'было', 'Edi (o‘rta rod)', NULL),
  ('kunlik-oqish-27', 'в', 'в', '...da', NULL),
  ('kunlik-oqish-27', 'вечерам', 'вечерам', 'kechquruqlar', NULL),
  ('kunlik-oqish-27', 'воде', 'воде', 'suvda', NULL),
  ('kunlik-oqish-27', 'все', 'все', 'Barcha', NULL),
  ('kunlik-oqish-27', 'всегда', 'всегда', 'Har doim', NULL),
  ('kunlik-oqish-27', 'горы', 'горы', 'Tog‘lar', NULL),
  ('kunlik-oqish-27', 'ели', 'ели', 'yeyishdi', NULL),
  ('kunlik-oqish-27', 'живую', 'живую', 'jonli', NULL),
  ('kunlik-oqish-27', 'жизни', 'жизни', 'hayotda', NULL),
  ('kunlik-oqish-27', 'и', 'и', 'Va', NULL),
  ('kunlik-oqish-27', 'их', 'их', 'Ularni', NULL),
  ('kunlik-oqish-27', 'Каждое', 'каждое', 'Har bir', NULL),
  ('kunlik-oqish-27', 'кафе', 'кафе', 'Kafe', NULL),
  ('kunlik-oqish-27', 'летом', 'летом', 'Yozda', NULL),
  ('kunlik-oqish-27', 'лучшие', 'лучшие', 'eng yaxshi', NULL),
  ('kunlik-oqish-27', 'много', 'много', 'Ko‘p', NULL),
  ('kunlik-oqish-27', 'моей', 'моей', 'Mening ...ga (я)', NULL),
  ('kunlik-oqish-27', 'Мои', 'мои', 'Mening (ko‘plik)', NULL),
  ('kunlik-oqish-27', 'Мой', 'мой', 'Mening', NULL),
  ('kunlik-oqish-27', 'Море', 'море', 'Dengiz', NULL),
  ('kunlik-oqish-27', 'музыки', 'музыки', 'musiqa', NULL),
  ('kunlik-oqish-27', 'музыку', 'музыку', 'musiqani', NULL),
  ('kunlik-oqish-27', 'мы', 'мы', 'Biz', NULL),
  ('kunlik-oqish-27', 'на', 'на', 'Ustida / yo‘nalish', NULL),
  ('kunlik-oqish-27', 'нами', 'нами', 'biz bilan', NULL),
  ('kunlik-oqish-27', 'Он', 'он', 'U (erkak)', NULL),
  ('kunlik-oqish-27', 'отличным', 'отличным', 'a’lo', NULL),
  ('kunlik-oqish-27', 'очень', 'очень', 'Juda', NULL),
  ('kunlik-oqish-27', 'первым', 'первым', 'birinchi bo‘lib', NULL),
  ('kunlik-oqish-27', 'пловцом', 'пловцом', 'suzuvchi', NULL),
  ('kunlik-oqish-27', 'По', 'по', 'yo‘nalish/harakat bo‘ylab («по дороге» → yo‘l bo‘ylab)', NULL),
  ('kunlik-oqish-27', 'Прошлым', 'прошлым', 'o‘tgan … bilan', NULL),
  ('kunlik-oqish-27', 'рыб', 'рыб', 'baliqlar', NULL),
  ('kunlik-oqish-27', 'с', 'с', 'birga bilan («с другом»)', NULL),
  ('kunlik-oqish-27', 'самые', 'самые', 'eng', NULL),
  ('kunlik-oqish-27', 'сделали', 'сделали', 'qilishdi', NULL),
  ('kunlik-oqish-27', 'слушали', 'слушали', 'tinglashdi', NULL),
  ('kunlik-oqish-27', 'Сочи', 'сочи', 'Sochi', NULL),
  ('kunlik-oqish-27', 'счастливы', 'счастливы', 'baxtli', NULL),
  ('kunlik-oqish-27', 'Там', 'там', 'u yerda', NULL),
  ('kunlik-oqish-27', 'теплотой', 'теплотой', 'iliqlik bilan', NULL),
  ('kunlik-oqish-27', 'тёплым', 'теплым', 'iliq', NULL),
  ('kunlik-oqish-27', 'тоже', 'тоже', 'Ham', NULL),
  ('kunlik-oqish-27', 'утро', 'утро', 'Tong', NULL),
  ('kunlik-oqish-27', 'Эти', 'эти', 'Bular', NULL),
  ('kunlik-oqish-27', 'Это', 'это', 'Bu (o‘rta)', NULL),
  ('kunlik-oqish-27', 'Я', 'я', 'Men', NULL),
  ('kunlik-oqish-28', 'а', 'а', 'Esa, va (qarama-qarshilik)', NULL),
  ('kunlik-oqish-28', 'большой', 'большой', 'katta', NULL),
  ('kunlik-oqish-28', 'был', 'был', 'Edi (erkak)', NULL),
  ('kunlik-oqish-28', 'была', 'была', 'Edi (ayol)', NULL),
  ('kunlik-oqish-28', 'были', 'были', 'Edilar', NULL),
  ('kunlik-oqish-28', 'было', 'было', 'Edi (o‘rta rod)', NULL),
  ('kunlik-oqish-28', 'В', 'в', '...da', NULL),
  ('kunlik-oqish-28', 'вместе', 'вместе', 'Birga', NULL),
  ('kunlik-oqish-28', 'Вот', 'вот', 'Mana', NULL),
  ('kunlik-oqish-28', 'всегда', 'всегда', 'Har doim', NULL),
  ('kunlik-oqish-28', 'Главное', 'главное', 'asosiysi', NULL),
  ('kunlik-oqish-28', 'город', 'город', 'Shahar', NULL),
  ('kunlik-oqish-28', 'Дима', 'дима', 'Dima', NULL),
  ('kunlik-oqish-28', 'Димы', 'димы', 'Dimaning', NULL),
  ('kunlik-oqish-28', 'друзья', 'друзья', 'Do‘stlar', NULL),
  ('kunlik-oqish-28', 'его', 'его', 'Uni (erkak)', NULL),
  ('kunlik-oqish-28', 'ездили', 'ездили', 'sayohat qilishdi', NULL),
  ('kunlik-oqish-28', 'за', 'за', 'uchun / ortidan', NULL),
  ('kunlik-oqish-28', 'замечательные', 'замечательные', 'ajoyib', NULL),
  ('kunlik-oqish-28', 'и', 'и', 'Va', NULL),
  ('kunlik-oqish-28', 'Когда', 'когда', 'qachon', NULL),
  ('kunlik-oqish-28', 'комнате', 'комнате', 'Xonada', NULL),
  ('kunlik-oqish-28', 'Конечно', 'конечно', 'albatta', NULL),
  ('kunlik-oqish-28', 'любил', 'любил', 'sevgan', NULL),
  ('kunlik-oqish-28', 'маленьким', 'маленьким', 'kichkina', NULL),
  ('kunlik-oqish-28', 'машина', 'машина', 'Mashina', NULL),
  ('kunlik-oqish-28', 'меня', 'меня', 'Meni', NULL),
  ('kunlik-oqish-28', 'мишка', 'мишка', 'mishka', NULL),
  ('kunlik-oqish-28', 'мне', 'мне', 'Menga', NULL),
  ('kunlik-oqish-28', 'много', 'много', 'Ko‘p', NULL),
  ('kunlik-oqish-28', 'моего', 'моего', 'Mening (rod.)', NULL),
  ('kunlik-oqish-28', 'моей', 'моей', 'Mening ...ga (я)', NULL),
  ('kunlik-oqish-28', 'Мы', 'мы', 'Biz', NULL),
  ('kunlik-oqish-28', 'на', 'на', 'Ustida / yo‘nalish', NULL),
  ('kunlik-oqish-28', 'нас', 'нас', 'Bizni', NULL),
  ('kunlik-oqish-28', 'настоящие', 'настоящие', 'haqiqiy', NULL),
  ('kunlik-oqish-28', 'не', 'не', 'Emas', NULL),
  ('kunlik-oqish-28', 'никогда', 'никогда', 'Hech qachon', NULL),
  ('kunlik-oqish-28', 'но', 'но', 'Lekin', NULL),
  ('kunlik-oqish-28', 'новый', 'новый', 'Yangi', NULL),
  ('kunlik-oqish-28', 'отца', 'отца', 'otasini', NULL),
  ('kunlik-oqish-28', 'очень', 'очень', 'Juda', NULL),
  ('kunlik-oqish-28', 'пикник', 'пикник', 'piknik', NULL),
  ('kunlik-oqish-28', 'плюшевый', 'плюшевый', 'plyush (matoshyumshoq)', NULL),
  ('kunlik-oqish-28', 'своя', 'своя', 'o‘zining', NULL),
  ('kunlik-oqish-28', 'семья', 'семья', 'Oila', NULL),
  ('kunlik-oqish-28', 'Серёжа', 'сережа', 'Seryoja', NULL),
  ('kunlik-oqish-28', 'Серёжи', 'сережи', 'Seryojaning', NULL),
  ('kunlik-oqish-28', 'телефона', 'телефона', 'telefon', NULL),
  ('kunlik-oqish-28', 'у', 'у', '...da borlik', NULL),
  ('kunlik-oqish-28', 'часто', 'часто', 'Tez-tez', NULL),
  ('kunlik-oqish-28', 'что', 'что', 'nima / kim', NULL),
  ('kunlik-oqish-28', 'я', 'я', 'Men', NULL),
  ('kunlik-oqish-29', 'была', 'была', 'Edi (ayol)', NULL),
  ('kunlik-oqish-29', 'были', 'были', 'Edilar', NULL),
  ('kunlik-oqish-29', 'было', 'было', 'Edi (o‘rta rod)', NULL),
  ('kunlik-oqish-29', 'В', 'в', '...da', NULL),
  ('kunlik-oqish-29', 'видел', 'видел', 'Ko‘rdim', NULL),
  ('kunlik-oqish-29', 'времени', 'времени', 'Vaqt (род.)', NULL),
  ('kunlik-oqish-29', 'всё', 'все', 'Barcha', NULL),
  ('kunlik-oqish-29', 'второй', 'второй', 'Ikkinchi', NULL),
  ('kunlik-oqish-29', 'выглянуло', 'выглянуло', 'ko‘rindi', NULL),
  ('kunlik-oqish-29', 'году', 'году', 'yilda', NULL),
  ('kunlik-oqish-29', 'город', 'город', 'Shahar', NULL),
  ('kunlik-oqish-29', 'города', 'города', 'shaharlar', NULL),
  ('kunlik-oqish-29', 'гулял', 'гулял', 'sayr qildi', NULL),
  ('kunlik-oqish-29', 'день', 'день', 'Kun', NULL),
  ('kunlik-oqish-29', 'дня', 'дня', 'kun', NULL),
  ('kunlik-oqish-29', 'ездил', 'ездил', 'sayohat qildi', NULL),
  ('kunlik-oqish-29', 'и', 'и', 'Va', NULL),
  ('kunlik-oqish-29', 'изменилась', 'изменилась', 'o‘zgardi', NULL),
  ('kunlik-oqish-29', 'К', 'к', '…ga / …tomon', NULL),
  ('kunlik-oqish-29', 'Казанский', 'казанский', 'Qozon…', NULL),
  ('kunlik-oqish-29', 'картин', 'картин', 'tasvirlar', NULL),
  ('kunlik-oqish-29', 'Когда', 'когда', 'qachon', NULL),
  ('kunlik-oqish-29', 'меня', 'меня', 'Meni', NULL),
  ('kunlik-oqish-29', 'Мне', 'мне', 'Menga', NULL),
  ('kunlik-oqish-29', 'много', 'много', 'Ko‘p', NULL),
  ('kunlik-oqish-29', 'моё', 'мое', 'Mening (o‘rta otl.)', NULL),
  ('kunlik-oqish-29', 'на', 'на', 'Ustida / yo‘nalish', NULL),
  ('kunlik-oqish-29', 'не', 'не', 'Emas', NULL),
  ('kunlik-oqish-29', 'небольшой', 'небольшой', 'kichik', NULL),
  ('kunlik-oqish-29', 'Невскому', 'невскому', 'Nevaga', NULL),
  ('kunlik-oqish-29', 'Но', 'но', 'Lekin', NULL),
  ('kunlik-oqish-29', 'очень', 'очень', 'Juda', NULL),
  ('kunlik-oqish-29', 'первое', 'первое', 'birinchi', NULL),
  ('kunlik-oqish-29', 'первый', 'первый', 'Birinchi', NULL),
  ('kunlik-oqish-29', 'Петербург', 'петербург', 'Petersburg', NULL),
  ('kunlik-oqish-29', 'Петродворец', 'петродворец', 'Petrodvorets', NULL),
  ('kunlik-oqish-29', 'по', 'по', 'yo‘nalish/harakat bo‘ylab («по дороге» → yo‘l bo‘ylab)', NULL),
  ('kunlik-oqish-29', 'погода', 'погода', 'Ob-havo', NULL),
  ('kunlik-oqish-29', 'поехал', 'поехал', 'ketdi', NULL),
  ('kunlik-oqish-29', 'полетел', 'полетел', 'uchdi', NULL),
  ('kunlik-oqish-29', 'понравилась', 'понравилась', 'yoqdi', NULL),
  ('kunlik-oqish-29', 'поселился', 'поселился', 'joylashdi', NULL),
  ('kunlik-oqish-29', 'посмотреть', 'посмотреть', 'ko‘rmoq', NULL),
  ('kunlik-oqish-29', 'Потом', 'потом', 'Keyin', NULL),
  ('kunlik-oqish-29', 'пошёл', 'пошел', 'Bordim (erkak)', NULL),
  ('kunlik-oqish-29', 'прекрасными', 'прекрасными', 'go‘zal', NULL),
  ('kunlik-oqish-29', 'прилетел', 'прилетел', 'uchib keldi', NULL),
  ('kunlik-oqish-29', 'прошлом', 'прошлом', 'O‘tgan', NULL),
  ('kunlik-oqish-29', 'самолёте', 'самолете', 'samolyotda', NULL),
  ('kunlik-oqish-29', 'Санкт-Петербург', 'санкт-петербург', 'Sankt-Peterburg', NULL),
  ('kunlik-oqish-29', 'Сначала', 'сначала', 'avvalo', NULL),
  ('kunlik-oqish-29', 'снова', 'снова', 'yana', NULL),
  ('kunlik-oqish-29', 'собор', 'собор', 'sobor', NULL),
  ('kunlik-oqish-29', 'сожалению', 'сожалению', 'afsuski', NULL),
  ('kunlik-oqish-29', 'солнце', 'солнце', 'quyosh', NULL),
  ('kunlik-oqish-29', 'Спас-на-Крови', 'спас-на-крови', 'Spas na Krovi', NULL),
  ('kunlik-oqish-29', 'Там', 'там', 'u yerda', NULL),
  ('kunlik-oqish-29', 'третий', 'третий', 'uchinchi', NULL),
  ('kunlik-oqish-29', 'три', 'три', 'Uch', NULL),
  ('kunlik-oqish-29', 'туда', 'туда', 'u yerga', NULL),
  ('kunlik-oqish-29', 'У', 'у', '...da borlik', NULL),
  ('kunlik-oqish-29', 'центре', 'центре', 'Markazda', NULL),
  ('kunlik-oqish-29', 'чтобы', 'чтобы', '…uchun', NULL),
  ('kunlik-oqish-29', 'экскурсия', 'экскурсия', 'eksursiya', NULL),
  ('kunlik-oqish-29', 'эта', 'эта', 'Bu (ayol)', NULL),
  ('kunlik-oqish-29', 'Это', 'это', 'Bu (o‘rta)', NULL),
  ('kunlik-oqish-29', 'этот', 'этот', 'Bu (erkak)', NULL),
  ('kunlik-oqish-29', 'я', 'я', 'Men', NULL),
  ('kunlik-oqish-30', 'Анна', 'анна', 'Anna (ism)', NULL),
  ('kunlik-oqish-30', 'без', 'без', '…siz', NULL),
  ('kunlik-oqish-30', 'бояться', 'бояться', 'qo‘rqmoq', NULL),
  ('kunlik-oqish-30', 'был', 'был', 'Edi (erkak)', NULL),
  ('kunlik-oqish-30', 'были', 'были', 'Edilar', NULL),
  ('kunlik-oqish-30', 'было', 'было', 'Edi (o‘rta rod)', NULL),
  ('kunlik-oqish-30', 'в', 'в', '...da', NULL),
  ('kunlik-oqish-30', 'всё', 'все', 'Barcha', NULL),
  ('kunlik-oqish-30', 'всегда', 'всегда', 'Har doim', NULL),
  ('kunlik-oqish-30', 'всем', 'всем', 'hammaga', NULL),
  ('kunlik-oqish-30', 'главное', 'главное', 'asosiysi', NULL),
  ('kunlik-oqish-30', 'говорил', 'говорил', 'aytdim', NULL),
  ('kunlik-oqish-30', 'говорю', 'говорю', 'Aytaman', NULL),
  ('kunlik-oqish-30', 'года', 'года', 'Yosh (22 года)', NULL),
  ('kunlik-oqish-30', 'готовы', 'готовы', 'tayyor', NULL),
  ('kunlik-oqish-30', 'Два', 'два', 'Ikki', NULL),
  ('kunlik-oqish-30', 'день', 'день', 'Kun', NULL),
  ('kunlik-oqish-30', 'домом', 'домом', 'uy bilan', NULL),
  ('kunlik-oqish-30', 'друзей', 'друзей', 'Do‘stlar (род.)', NULL),
  ('kunlik-oqish-30', 'друзья', 'друзья', 'Do‘stlar', NULL),
  ('kunlik-oqish-30', 'Желаю', 'желаю', 'tilayman', NULL),
  ('kunlik-oqish-30', 'и', 'и', 'Va', NULL),
  ('kunlik-oqish-30', 'Каждый', 'каждый', 'har bir', NULL),
  ('kunlik-oqish-30', 'книги', 'книги', 'Kitoblar', NULL),
  ('kunlik-oqish-30', 'меня', 'меня', 'Meni', NULL),
  ('kunlik-oqish-30', 'много', 'много', 'Ko‘p', NULL),
  ('kunlik-oqish-30', 'моим', 'моим', 'meniki bilan', NULL),
  ('kunlik-oqish-30', 'мой', 'мой', 'Mening', NULL),
  ('kunlik-oqish-30', 'На', 'на', 'Ustida / yo‘nalish', NULL),
  ('kunlik-oqish-30', 'назад', 'назад', 'orqaga', NULL),
  ('kunlik-oqish-30', 'не', 'не', 'Emas', NULL),
  ('kunlik-oqish-30', 'неделе', 'неделе', 'haftada', NULL),
  ('kunlik-oqish-30', 'Но', 'но', 'Lekin', NULL),
  ('kunlik-oqish-30', 'новые', 'новые', 'yangi', NULL),
  ('kunlik-oqish-30', 'Они', 'они', 'ular', NULL),
  ('kunlik-oqish-30', 'очень', 'очень', 'Juda', NULL),
  ('kunlik-oqish-30', 'первый', 'первый', 'Birinchi', NULL),
  ('kunlik-oqish-30', 'плохо', 'плохо', 'Yomon', NULL),
  ('kunlik-oqish-30', 'по', 'по', 'yo‘nalish/harakat bo‘ylab («по дороге» → yo‘l bo‘ylab)', NULL),
  ('kunlik-oqish-30', 'по-русски', 'по-русски', 'Ruscha', NULL),
  ('kunlik-oqish-30', 'повторял', 'повторял', 'takrorlagan', NULL),
  ('kunlik-oqish-30', 'получаться', 'получаться', 'chiqqani', NULL),
  ('kunlik-oqish-30', 'понял', 'понял', 'tushundi', NULL),
  ('kunlik-oqish-30', 'прошлой', 'прошлой', 'o‘tgan', NULL),
  ('kunlik-oqish-30', 'работать', 'работать', 'Ishlamoq', NULL),
  ('kunlik-oqish-30', 'рад', 'рад', 'Xursand', NULL),
  ('kunlik-oqish-30', 'Россию', 'россию', 'Rossiyaga', NULL),
  ('kunlik-oqish-30', 'Россия', 'россия', 'Rossiya', NULL),
  ('kunlik-oqish-30', 'русскому', 'русскому', 'rus tiliga', NULL),
  ('kunlik-oqish-30', 'сдал', 'сдал', 'topshirdi', NULL),
  ('kunlik-oqish-30', 'Сейчас', 'сейчас', 'Hozir', NULL),
  ('kunlik-oqish-30', 'Сергей', 'сергей', 'Sergey', NULL),
  ('kunlik-oqish-30', 'слова', 'слова', 'so‘zlar', NULL),
  ('kunlik-oqish-30', 'смотрю', 'смотрю', 'qaraman', NULL),
  ('kunlik-oqish-30', 'Сначала', 'сначала', 'avvalo', NULL),
  ('kunlik-oqish-30', 'стала', 'стала', 'bo‘ldi', NULL),
  ('kunlik-oqish-30', 'стало', 'стало', 'bo‘ldi', NULL),
  ('kunlik-oqish-30', 'счастлив', 'счастлив', 'Baxtli', NULL),
  ('kunlik-oqish-30', 'У', 'у', '...da borlik', NULL),
  ('kunlik-oqish-30', 'уже', 'уже', 'allaqachon', NULL),
  ('kunlik-oqish-30', 'учил', 'учил', 'o‘rgatdi', NULL),
  ('kunlik-oqish-30', 'фильмы', 'фильмы', 'filmlar', NULL),
  ('kunlik-oqish-30', 'хорошо', 'хорошо', 'Yaxshi', NULL),
  ('kunlik-oqish-30', 'читаю', 'читаю', 'O‘qiyman', NULL),
  ('kunlik-oqish-30', 'что', 'что', 'nima / kim', NULL),
  ('kunlik-oqish-30', 'Это', 'это', 'Bu (o‘rta)', NULL),
  ('kunlik-oqish-30', 'этот', 'этот', 'Bu (erkak)', NULL),
  ('kunlik-oqish-30', 'я', 'я', 'Men', NULL),
  ('kunlik-oqish-30', 'языку', 'языку', 'tiliga', NULL),
  ('kunlik-oqish-31', 'А', 'а', 'Esa, va (qarama-qarshilik)', NULL),
  ('kunlik-oqish-31', 'была', 'была', 'Edi (ayol)', NULL),
  ('kunlik-oqish-31', 'в', 'в', '...da', NULL),
  ('kunlik-oqish-31', 'вкусный', 'вкусный', 'ta’mli', NULL),
  ('kunlik-oqish-31', 'время', 'время', 'Vaqt', NULL),
  ('kunlik-oqish-31', 'Вчера', 'вчера', 'Kecha', NULL),
  ('kunlik-oqish-31', 'вы', 'вы', 'Siz', NULL),
  ('kunlik-oqish-31', 'говорит', 'говорит', 'Gapiradi', NULL),
  ('kunlik-oqish-31', 'готовлю', 'готовлю', 'Tayyorlayapman', NULL),
  ('kunlik-oqish-31', 'делать', 'делать', 'Qilmoq', NULL),
  ('kunlik-oqish-31', 'делаю', 'делаю', 'qilaman', NULL),
  ('kunlik-oqish-31', 'для', 'для', 'uchun', NULL),
  ('kunlik-oqish-31', 'есть', 'есть', 'Bor', NULL),
  ('kunlik-oqish-31', 'и', 'и', 'Va', NULL),
  ('kunlik-oqish-31', 'Иногда', 'иногда', 'Ba’zida', NULL),
  ('kunlik-oqish-31', 'интересный', 'интересный', 'qiziqarli', NULL),
  ('kunlik-oqish-31', 'их', 'их', 'Ularni', NULL),
  ('kunlik-oqish-31', 'книги', 'книги', 'Kitoblar', NULL),
  ('kunlik-oqish-31', 'Когда', 'когда', 'qachon', NULL),
  ('kunlik-oqish-31', 'любите', 'любите', 'sevasizmi', NULL),
  ('kunlik-oqish-31', 'люблю', 'люблю', 'Sevaman / yaxshi ko‘raman', NULL),
  ('kunlik-oqish-31', 'мама', 'мама', 'Ona', NULL),
  ('kunlik-oqish-31', 'меня', 'меня', 'Meni', NULL),
  ('kunlik-oqish-31', 'мои', 'мои', 'Mening (ko‘plik)', NULL),
  ('kunlik-oqish-31', 'Моя', 'моя', 'Mening (ayol otl.)', NULL),
  ('kunlik-oqish-31', 'мысли', 'мысли', 'fikrlar', NULL),
  ('kunlik-oqish-31', 'мясо', 'мясо', 'Go‘sht', NULL),
  ('kunlik-oqish-31', 'наказание', 'наказание', 'jazo', NULL),
  ('kunlik-oqish-31', 'не', 'не', 'Emas', NULL),
  ('kunlik-oqish-31', 'никому', 'никому', 'hech kimga', NULL),
  ('kunlik-oqish-31', 'новую', 'новую', 'yangi', NULL),
  ('kunlik-oqish-31', 'Он', 'он', 'U (erkak)', NULL),
  ('kunlik-oqish-31', 'Она', 'она', 'U (ayol)', NULL),
  ('kunlik-oqish-31', 'очень', 'очень', 'Juda', NULL),
  ('kunlik-oqish-31', 'пишу', 'пишу', 'yozaman', NULL),
  ('kunlik-oqish-31', 'По', 'по', 'yo‘nalish/harakat bo‘ylab («по дороге» → yo‘l bo‘ylab)', NULL),
  ('kunlik-oqish-31', 'показываю', 'показываю', 'ko‘rsataman', NULL),
  ('kunlik-oqish-31', 'покупаю', 'покупаю', 'xarid qilaman', NULL),
  ('kunlik-oqish-31', 'посмотрел', 'посмотрел', 'ko‘rdi', NULL),
  ('kunlik-oqish-31', 'потому', 'потому', 'chunki', NULL),
  ('kunlik-oqish-31', 'Преступление', 'преступление', 'jinoyat', NULL),
  ('kunlik-oqish-31', 'Сейчас', 'сейчас', 'Hozir', NULL),
  ('kunlik-oqish-31', 'семьи', 'семьи', 'oilasi', NULL),
  ('kunlik-oqish-31', 'смотреть', 'смотреть', 'Qaramoq', NULL),
  ('kunlik-oqish-31', 'суп', 'суп', 'shoʻrva', NULL),
  ('kunlik-oqish-31', 'Также', 'также', 'shuningdek', NULL),
  ('kunlik-oqish-31', 'то', 'то', 'O‘sha (o‘rta)', NULL),
  ('kunlik-oqish-31', 'у', 'у', '...da borlik', NULL),
  ('kunlik-oqish-31', 'ужин', 'ужин', 'Kechki ovqat', NULL),
  ('kunlik-oqish-31', 'фильмы', 'фильмы', 'filmlar', NULL),
  ('kunlik-oqish-31', 'хорошо', 'хорошо', 'Yaxshi', NULL),
  ('kunlik-oqish-31', 'часто', 'часто', 'Tez-tez', NULL),
  ('kunlik-oqish-31', 'читаю', 'читаю', 'O‘qiyman', NULL),
  ('kunlik-oqish-31', 'что', 'что', 'nima / kim', NULL),
  ('kunlik-oqish-31', 'это', 'это', 'Bu (o‘rta)', NULL),
  ('kunlik-oqish-31', 'я', 'я', 'Men', NULL),
  ('kunlik-oqish-32', 'Антон', 'антон', 'Anton', NULL),
  ('kunlik-oqish-32', 'Антона', 'антона', 'Antonning', NULL),
  ('kunlik-oqish-32', 'в', 'в', '...da', NULL),
  ('kunlik-oqish-32', 'весело', 'весело', 'shodiyona', NULL),
  ('kunlik-oqish-32', 'вечер', 'вечер', 'Kech', NULL),
  ('kunlik-oqish-32', 'видел', 'видел', 'Ko‘rdim', NULL),
  ('kunlik-oqish-32', 'Вчера', 'вчера', 'Kecha', NULL),
  ('kunlik-oqish-32', 'давно', 'давно', 'uzoqdan beri', NULL),
  ('kunlik-oqish-32', 'дороге', 'дороге', 'yo‘lda', NULL),
  ('kunlik-oqish-32', 'друга', 'друга', 'Do‘st (род.; 2 uchun)', NULL),
  ('kunlik-oqish-32', 'его', 'его', 'Uni (erkak)', NULL),
  ('kunlik-oqish-32', 'её', 'ее', 'Uni (ayol)', NULL),
  ('kunlik-oqish-32', 'жизни', 'жизни', 'hayotda', NULL),
  ('kunlik-oqish-32', 'за', 'за', 'uchun / ortidan', NULL),
  ('kunlik-oqish-32', 'заказали', 'заказали', 'buyurtma qilishdi', NULL),
  ('kunlik-oqish-32', 'и', 'и', 'Va', NULL),
  ('kunlik-oqish-32', 'их', 'их', 'Ularni', NULL),
  ('kunlik-oqish-32', 'к', 'к', '…ga / …tomon', NULL),
  ('kunlik-oqish-32', 'кафе', 'кафе', 'Kafe', NULL),
  ('kunlik-oqish-32', 'Когда', 'когда', 'qachon', NULL),
  ('kunlik-oqish-32', 'Конечно', 'конечно', 'albatta', NULL),
  ('kunlik-oqish-32', 'кофе', 'кофе', 'Kofe', NULL),
  ('kunlik-oqish-32', 'математики', 'математики', 'matematika', NULL),
  ('kunlik-oqish-32', 'меня', 'меня', 'Meni', NULL),
  ('kunlik-oqish-32', 'мне', 'мне', 'Menga', NULL),
  ('kunlik-oqish-32', 'Мы', 'мы', 'Biz', NULL),
  ('kunlik-oqish-32', 'нам', 'нам', 'bizga', NULL),
  ('kunlik-oqish-32', 'нашу', 'нашу', 'bizning', NULL),
  ('kunlik-oqish-32', 'не', 'не', 'Emas', NULL),
  ('kunlik-oqish-32', 'никогда', 'никогда', 'Hech qachon', NULL),
  ('kunlik-oqish-32', 'о', 'о', '…haqida', NULL),
  ('kunlik-oqish-32', 'Он', 'он', 'U (erkak)', NULL),
  ('kunlik-oqish-32', 'она', 'она', 'U (ayol)', NULL),
  ('kunlik-oqish-32', 'По', 'по', 'yo‘nalish/harakat bo‘ylab («по дороге» → yo‘l bo‘ylab)', NULL),
  ('kunlik-oqish-32', 'позвонил', 'позвонил', 'qo‘ng‘iroq qildi', NULL),
  ('kunlik-oqish-32', 'пойти', 'пойти', 'bormoq', NULL),
  ('kunlik-oqish-32', 'полчаса', 'полчаса', 'yarim soat', NULL),
  ('kunlik-oqish-32', 'помнишь', 'помнишь', 'esladingmi', NULL),
  ('kunlik-oqish-32', 'Потом', 'потом', 'Keyin', NULL),
  ('kunlik-oqish-32', 'прекрасный', 'прекрасный', 'go‘zal', NULL),
  ('kunlik-oqish-32', 'пришла', 'пришла', 'keldi', NULL),
  ('kunlik-oqish-32', 'провели', 'провели', 'o‘tkazishdi', NULL),
  ('kunlik-oqish-32', 'рассказал', 'рассказал', 'Aytib berdi', NULL),
  ('kunlik-oqish-32', 'решили', 'решили', 'qaror qilishdi', NULL),
  ('kunlik-oqish-32', 'своего', 'своего', 'o‘zining', NULL),
  ('kunlik-oqish-32', 'своей', 'своей', 'O‘zimning (ayol rod.)', NULL),
  ('kunlik-oqish-32', 'семье', 'семье', 'Oilada', NULL),
  ('kunlik-oqish-32', 'сестре', 'сестре', 'Singlim haqida', NULL),
  ('kunlik-oqish-32', 'сестру', 'сестру', 'Singilni', NULL),
  ('kunlik-oqish-32', 'сказал', 'сказал', 'dedim', NULL),
  ('kunlik-oqish-32', 'спросил', 'спросил', 'So‘radi', NULL),
  ('kunlik-oqish-32', 'старого', 'старого', 'eski', NULL),
  ('kunlik-oqish-32', 'то', 'то', 'O‘sha (o‘rta)', NULL),
  ('kunlik-oqish-32', 'тоже', 'тоже', 'Ham', NULL),
  ('kunlik-oqish-32', 'Ты', 'ты', 'Sen', NULL),
  ('kunlik-oqish-32', 'улыбнулся', 'улыбнулся', 'kulimsirdi', NULL),
  ('kunlik-oqish-32', 'Через', 'через', 'Orqali / keyin', NULL),
  ('kunlik-oqish-32', 'я', 'я', 'Men', NULL),
  ('kunlik-oqish-33', 'большое', 'большое', 'katta', NULL),
  ('kunlik-oqish-33', 'большой', 'большой', 'katta', NULL),
  ('kunlik-oqish-33', 'были', 'были', 'Edilar', NULL),
  ('kunlik-oqish-33', 'вечеру', 'вечеру', 'kechgacha', NULL),
  ('kunlik-oqish-33', 'вещи', 'вещи', 'Narsalar', NULL),
  ('kunlik-oqish-33', 'Вчера', 'вчера', 'Kecha', NULL),
  ('kunlik-oqish-33', 'ему', 'ему', 'Unga (erkak)', NULL),
  ('kunlik-oqish-33', 'есть', 'есть', 'Bor', NULL),
  ('kunlik-oqish-33', 'и', 'и', 'Va', NULL),
  ('kunlik-oqish-33', 'К', 'к', '…ga / …tomon', NULL),
  ('kunlik-oqish-33', 'квартиру', 'квартиру', 'kvartira', NULL),
  ('kunlik-oqish-33', 'книги', 'книги', 'Kitoblar', NULL),
  ('kunlik-oqish-33', 'комнату', 'комнату', 'xonani', NULL),
  ('kunlik-oqish-33', 'компьютер', 'компьютер', 'kompyuter', NULL),
  ('kunlik-oqish-33', 'купила', 'купила', 'sotib oldi', NULL),
  ('kunlik-oqish-33', 'люблю', 'люблю', 'Sevaman / yaxshi ko‘raman', NULL),
  ('kunlik-oqish-33', 'Мама', 'мама', 'Ona', NULL),
  ('kunlik-oqish-33', 'месту', 'месту', 'joyga', NULL),
  ('kunlik-oqish-33', 'моя', 'моя', 'Mening (ayol otl.)', NULL),
  ('kunlik-oqish-33', 'мы', 'мы', 'Biz', NULL),
  ('kunlik-oqish-33', 'мыла', 'мыла', 'yuvdi', NULL),
  ('kunlik-oqish-33', 'На', 'на', 'Ustida / yo‘nalish', NULL),
  ('kunlik-oqish-33', 'начали', 'начали', 'boshlashdi', NULL),
  ('kunlik-oqish-33', 'неделе', 'неделе', 'haftada', NULL),
  ('kunlik-oqish-33', 'но', 'но', 'Lekin', NULL),
  ('kunlik-oqish-33', 'новому', 'новому', 'yangi', NULL),
  ('kunlik-oqish-33', 'новую', 'новую', 'yangi', NULL),
  ('kunlik-oqish-33', 'обеда', 'обеда', 'tushlik', NULL),
  ('kunlik-oqish-33', 'окна', 'окна', 'derazalar', NULL),
  ('kunlik-oqish-33', 'окно', 'окно', 'Deraza', NULL),
  ('kunlik-oqish-33', 'очень', 'очень', 'Juda', NULL),
  ('kunlik-oqish-33', 'Папа', 'папа', 'Ota (erkak)', NULL),
  ('kunlik-oqish-33', 'подключил', 'подключил', 'uladi', NULL),
  ('kunlik-oqish-33', 'полке', 'полке', 'javonda', NULL),
  ('kunlik-oqish-33', 'помогал', 'помогал', 'yordam berdi', NULL),
  ('kunlik-oqish-33', 'После', 'после', 'keyin', NULL),
  ('kunlik-oqish-33', 'прошлой', 'прошлой', 'o‘tgan', NULL),
  ('kunlik-oqish-33', 'с', 'с', 'birga bilan («с другом»)', NULL),
  ('kunlik-oqish-33', 'свои', 'свои', 'o‘zining', NULL),
  ('kunlik-oqish-33', 'свою', 'свою', 'O‘zimizning (ayol/vin.)', NULL),
  ('kunlik-oqish-33', 'семья', 'семья', 'Oila', NULL),
  ('kunlik-oqish-33', 'Сестра', 'сестра', 'Opa / singil', NULL),
  ('kunlik-oqish-33', 'Сначала', 'сначала', 'avvalo', NULL),
  ('kunlik-oqish-33', 'собрал', 'собрал', 'yig‘di', NULL),
  ('kunlik-oqish-33', 'стала', 'стала', 'bo‘ldi', NULL),
  ('kunlik-oqish-33', 'стол', 'стол', 'Stol', NULL),
  ('kunlik-oqish-33', 'счастливы', 'счастливы', 'baxtli', NULL),
  ('kunlik-oqish-33', 'Там', 'там', 'u yerda', NULL),
  ('kunlik-oqish-33', 'телевизор', 'телевизор', 'televizor', NULL),
  ('kunlik-oqish-33', 'удобная', 'удобная', 'qulay', NULL),
  ('kunlik-oqish-33', 'уже', 'уже', 'allaqachon', NULL),
  ('kunlik-oqish-33', 'устали', 'устали', 'charchashdi', NULL),
  ('kunlik-oqish-33', 'шторы', 'шторы', 'pardalar', NULL),
  ('kunlik-oqish-33', 'Я', 'я', 'Men', NULL),
  ('kunlik-oqish-34', 'а', 'а', 'Esa, va (qarama-qarshilik)', NULL),
  ('kunlik-oqish-34', 'Анна', 'анна', 'Anna (ism)', NULL),
  ('kunlik-oqish-34', 'будущее', 'будущее', 'Kelajak', NULL),
  ('kunlik-oqish-34', 'Вечером', 'вечером', 'Kechqurun', NULL),
  ('kunlik-oqish-34', 'внимательно', 'внимательно', 'Diqqat bilan', NULL),
  ('kunlik-oqish-34', 'Вот', 'вот', 'Mana', NULL),
  ('kunlik-oqish-34', 'всегда', 'всегда', 'Har doim', NULL),
  ('kunlik-oqish-34', 'городу', 'городу', 'shaharga', NULL),
  ('kunlik-oqish-34', 'гуляли', 'гуляли', 'Sayr qildik', NULL),
  ('kunlik-oqish-34', 'два', 'два', 'Ikki', NULL),
  ('kunlik-oqish-34', 'день', 'день', 'Kun', NULL),
  ('kunlik-oqish-34', 'диск', 'диск', 'disk', NULL),
  ('kunlik-oqish-34', 'друга', 'друга', 'Do‘st (род.; 2 uchun)', NULL),
  ('kunlik-oqish-34', 'ему', 'ему', 'Unga (erkak)', NULL),
  ('kunlik-oqish-34', 'есть', 'есть', 'Bor', NULL),
  ('kunlik-oqish-34', 'значит', 'значит', 'demak', NULL),
  ('kunlik-oqish-34', 'и', 'и', 'Va', NULL),
  ('kunlik-oqish-34', 'им', 'им', 'ularga', NULL),
  ('kunlik-oqish-34', 'книгу', 'книгу', 'kitob', NULL),
  ('kunlik-oqish-34', 'Когда', 'когда', 'qachon', NULL),
  ('kunlik-oqish-34', 'лучших', 'лучших', 'Eng yaxshi (род. мн.)', NULL),
  ('kunlik-oqish-34', 'люблю', 'люблю', 'Sevaman / yaxshi ko‘raman', NULL),
  ('kunlik-oqish-34', 'мне', 'мне', 'Menga', NULL),
  ('kunlik-oqish-34', 'могу', 'могу', 'qila olaman', NULL),
  ('kunlik-oqish-34', 'мои', 'мои', 'Mening (ko‘plik)', NULL),
  ('kunlik-oqish-34', 'мы', 'мы', 'Biz', NULL),
  ('kunlik-oqish-34', 'На', 'на', 'Ustida / yo‘nalish', NULL),
  ('kunlik-oqish-34', 'настоящая', 'настоящая', 'haqiqiy', NULL),
  ('kunlik-oqish-34', 'не', 'не', 'Emas', NULL),
  ('kunlik-oqish-34', 'неделе', 'неделе', 'haftada', NULL),
  ('kunlik-oqish-34', 'никогда', 'никогда', 'Hech qachon', NULL),
  ('kunlik-oqish-34', 'новый', 'новый', 'Yangi', NULL),
  ('kunlik-oqish-34', 'о', 'о', '…haqida', NULL),
  ('kunlik-oqish-34', 'обнял', 'обнял', 'Quchoqladi', NULL),
  ('kunlik-oqish-34', 'она', 'она', 'U (ayol)', NULL),
  ('kunlik-oqish-34', 'Они', 'они', 'ular', NULL),
  ('kunlik-oqish-34', 'очень', 'очень', 'Juda', NULL),
  ('kunlik-oqish-34', 'планах', 'планах', 'Rejalar', NULL),
  ('kunlik-oqish-34', 'по', 'по', 'yo‘nalish/harakat bo‘ylab («по дороге» → yo‘l bo‘ylab)', NULL),
  ('kunlik-oqish-34', 'пригласил', 'пригласил', 'taklif qildi', NULL),
  ('kunlik-oqish-34', 'прошлой', 'прошлой', 'o‘tgan', NULL),
  ('kunlik-oqish-34', 'рассказывал', 'рассказывал', 'gapirdi', NULL),
  ('kunlik-oqish-34', 'рождения', 'рождения', 'tug‘ilgan kun', NULL),
  ('kunlik-oqish-34', 'своих', 'своих', 'o‘zining', NULL),
  ('kunlik-oqish-34', 'свой', 'свой', 'o‘zining', NULL),
  ('kunlik-oqish-34', 'Сергей', 'сергей', 'Sergey', NULL),
  ('kunlik-oqish-34', 'сказал', 'сказал', 'dedim', NULL),
  ('kunlik-oqish-34', 'слушали', 'слушали', 'tinglashdi', NULL),
  ('kunlik-oqish-34', 'Спасибо', 'спасибо', 'Rahmat', NULL),
  ('kunlik-oqish-34', 'У', 'у', '...da borlik', NULL),
  ('kunlik-oqish-34', 'что', 'что', 'nima / kim', NULL),
  ('kunlik-oqish-34', 'Я', 'я', 'Men', NULL),
  ('kunlik-oqish-35', 'брата', 'брата', 'Akani', NULL),
  ('kunlik-oqish-35', 'брату', 'брату', 'akanga / ukanga', NULL),
  ('kunlik-oqish-35', 'был', 'был', 'Edi (erkak)', NULL),
  ('kunlik-oqish-35', 'В', 'в', '...da', NULL),
  ('kunlik-oqish-35', 'день', 'день', 'Kun', NULL),
  ('kunlik-oqish-35', 'долго', 'долго', 'uzoq', NULL),
  ('kunlik-oqish-35', 'думал', 'думал', 'o‘yladi', NULL),
  ('kunlik-oqish-35', 'его', 'его', 'Uni (erkak)', NULL),
  ('kunlik-oqish-35', 'ему', 'ему', 'Unga (erkak)', NULL),
  ('kunlik-oqish-35', 'и', 'и', 'Va', NULL),
  ('kunlik-oqish-35', 'красивый', 'красивый', 'chiroyli', NULL),
  ('kunlik-oqish-35', 'купил', 'купил', 'Sotib oldim', NULL),
  ('kunlik-oqish-35', 'купить', 'купить', 'Xarid qilmoq', NULL),
  ('kunlik-oqish-35', 'магазине', 'магазине', 'Do‘konda', NULL),
  ('kunlik-oqish-35', 'мне', 'мне', 'Menga', NULL),
  ('kunlik-oqish-35', 'моего', 'моего', 'Mening (rod.)', NULL),
  ('kunlik-oqish-35', 'мы', 'мы', 'Biz', NULL),
  ('kunlik-oqish-35', 'На', 'на', 'Ustida / yo‘nalish', NULL),
  ('kunlik-oqish-35', 'Наконец', 'наконец', 'Nihoyat', NULL),
  ('kunlik-oqish-35', 'неделе', 'неделе', 'haftada', NULL),
  ('kunlik-oqish-35', 'новый', 'новый', 'Yangi', NULL),
  ('kunlik-oqish-35', 'о', 'о', '…haqida', NULL),
  ('kunlik-oqish-35', 'обнял', 'обнял', 'Quchoqladi', NULL),
  ('kunlik-oqish-35', 'Он', 'он', 'U (erkak)', NULL),
  ('kunlik-oqish-35', 'открыл', 'открыл', 'ochdi', NULL),
  ('kunlik-oqish-35', 'очень', 'очень', 'Juda', NULL),
  ('kunlik-oqish-35', 'подарке', 'подарке', 'sovg‘ada', NULL),
  ('kunlik-oqish-35', 'подарок', 'подарок', 'sovg‘a', NULL),
  ('kunlik-oqish-35', 'показать', 'показать', 'ko‘rsatmoq', NULL),
  ('kunlik-oqish-35', 'попросил', 'попросил', 'so‘radi', NULL),
  ('kunlik-oqish-35', 'прошлой', 'прошлой', 'o‘tgan', NULL),
  ('kunlik-oqish-35', 'рад', 'рад', 'Xursand', NULL),
  ('kunlik-oqish-35', 'решил', 'решил', 'qaror qildi', NULL),
  ('kunlik-oqish-35', 'рождения', 'рождения', 'tug‘ilgan kun', NULL),
  ('kunlik-oqish-35', 'своего', 'своего', 'o‘zining', NULL),
  ('kunlik-oqish-35', 'синий', 'синий', 'ko‘k', NULL),
  ('kunlik-oqish-35', 'сказал', 'сказал', 'dedim', NULL),
  ('kunlik-oqish-35', 'Спасибо', 'спасибо', 'Rahmat', NULL),
  ('kunlik-oqish-35', 'тебе', 'тебе', 'senga', NULL),
  ('kunlik-oqish-35', 'у', 'у', '...da borlik', NULL),
  ('kunlik-oqish-35', 'увидел', 'увидел', 'ko‘rdi', NULL),
  ('kunlik-oqish-35', 'улыбнулся', 'улыбнулся', 'kulimsirdi', NULL),
  ('kunlik-oqish-35', 'цвет', 'цвет', 'rang', NULL),
  ('kunlik-oqish-35', 'что', 'что', 'nima / kim', NULL),
  ('kunlik-oqish-35', 'эту', 'эту', 'buni', NULL),
  ('kunlik-oqish-35', 'Я', 'я', 'Men', NULL),
  ('kunlik-oqish-36', 'а', 'а', 'Esa, va (qarama-qarshilik)', NULL),
  ('kunlik-oqish-36', 'Антон', 'антон', 'Anton', NULL),
  ('kunlik-oqish-36', 'был', 'был', 'Edi (erkak)', NULL),
  ('kunlik-oqish-36', 'была', 'была', 'Edi (ayol)', NULL),
  ('kunlik-oqish-36', 'в', 'в', '...da', NULL),
  ('kunlik-oqish-36', 'вечность', 'вечность', 'abadiyat', NULL),
  ('kunlik-oqish-36', 'видел', 'видел', 'Ko‘rdim', NULL),
  ('kunlik-oqish-36', 'внимательно', 'внимательно', 'Diqqat bilan', NULL),
  ('kunlik-oqish-36', 'выпить', 'выпить', 'ichmoq', NULL),
  ('kunlik-oqish-36', 'годы', 'годы', 'yillar', NULL),
  ('kunlik-oqish-36', 'голос', 'голос', 'ovoz', NULL),
  ('kunlik-oqish-36', 'гулял', 'гулял', 'sayr qildi', NULL),
  ('kunlik-oqish-36', 'дереве', 'дереве', 'daraxtda', NULL),
  ('kunlik-oqish-36', 'долго', 'долго', 'uzoq', NULL),
  ('kunlik-oqish-36', 'друг', 'друг', 'Do‘st', NULL),
  ('kunlik-oqish-36', 'дружбу', 'дружбу', 'do‘stlikni', NULL),
  ('kunlik-oqish-36', 'его', 'его', 'Uni (erkak)', NULL),
  ('kunlik-oqish-36', 'знакомый', 'знакомый', 'tanish', NULL),
  ('kunlik-oqish-36', 'и', 'и', 'Va', NULL),
  ('kunlik-oqish-36', 'кафе', 'кафе', 'Kafe', NULL),
  ('kunlik-oqish-36', 'кофе', 'кофе', 'Kofe', NULL),
  ('kunlik-oqish-36', 'лимоном', 'лимоном', 'limon bilan', NULL),
  ('kunlik-oqish-36', 'маленькую', 'маленькую', 'kichkina', NULL),
  ('kunlik-oqish-36', 'мне', 'мне', 'Menga', NULL),
  ('kunlik-oqish-36', 'мой', 'мой', 'Mening', NULL),
  ('kunlik-oqish-36', 'Мы', 'мы', 'Biz', NULL),
  ('kunlik-oqish-36', 'на', 'на', 'Ustida / yo‘nalish', NULL),
  ('kunlik-oqish-36', 'наши', 'наши', 'bizning', NULL),
  ('kunlik-oqish-36', 'нашу', 'нашу', 'bizning', NULL),
  ('kunlik-oqish-36', 'не', 'не', 'Emas', NULL),
  ('kunlik-oqish-36', 'неё', 'нее', 'uni', NULL),
  ('kunlik-oqish-36', 'новой', 'новой', 'yangi', NULL),
  ('kunlik-oqish-36', 'о', 'о', '…haqida', NULL),
  ('kunlik-oqish-36', 'Он', 'он', 'U (erkak)', NULL),
  ('kunlik-oqish-36', 'Она', 'она', 'U (ayol)', NULL),
  ('kunlik-oqish-36', 'орех', 'орех', 'yong‘oq', NULL),
  ('kunlik-oqish-36', 'очень', 'очень', 'Juda', NULL),
  ('kunlik-oqish-36', 'парк', 'парк', 'park', NULL),
  ('kunlik-oqish-36', 'парковом', 'парковом', 'parkda', NULL),
  ('kunlik-oqish-36', 'парку', 'парку', 'parkka', NULL),
  ('kunlik-oqish-36', 'пирожное', 'пирожное', 'shirin pishiriq', NULL),
  ('kunlik-oqish-36', 'по', 'по', 'yo‘nalish/harakat bo‘ylab («по дороге» → yo‘l bo‘ylab)', NULL),
  ('kunlik-oqish-36', 'Погода', 'погода', 'Ob-havo', NULL),
  ('kunlik-oqish-36', 'После', 'после', 'keyin', NULL),
  ('kunlik-oqish-36', 'Потом', 'потом', 'Keyin', NULL),
  ('kunlik-oqish-36', 'пошёл', 'пошел', 'Bordim (erkak)', NULL),
  ('kunlik-oqish-36', 'прекрасная', 'прекрасная', 'Ajoyib', NULL),
  ('kunlik-oqish-36', 'Привет', 'привет', 'Salom', NULL),
  ('kunlik-oqish-36', 'птиц', 'птиц', 'qushlar', NULL),
  ('kunlik-oqish-36', 'работе', 'работе', 'Ish haqida', NULL),
  ('kunlik-oqish-36', 'рад', 'рад', 'Xursand', NULL),
  ('kunlik-oqish-36', 'разговаривали', 'разговаривали', 'gaplashdik', NULL),
  ('kunlik-oqish-36', 'решили', 'решили', 'qaror qilishdi', NULL),
  ('kunlik-oqish-36', 'с', 'с', 'birga bilan («с другом»)', NULL),
  ('kunlik-oqish-36', 'своей', 'своей', 'O‘zimning (ayol rod.)', NULL),
  ('kunlik-oqish-36', 'Сегодня', 'сегодня', 'Bugun', NULL),
  ('kunlik-oqish-36', 'сидела', 'сидела', 'o‘tirardi', NULL),
  ('kunlik-oqish-36', 'слышал', 'слышал', 'eshitdi', NULL),
  ('kunlik-oqish-36', 'смотрел', 'смотрел', 'qarardi', NULL),
  ('kunlik-oqish-36', 'старый', 'старый', 'eski', NULL),
  ('kunlik-oqish-36', 'тебя', 'тебя', 'Seni', NULL),
  ('kunlik-oqish-36', 'тоже', 'тоже', 'Ham', NULL),
  ('kunlik-oqish-36', 'утром', 'утром', 'Ertalab', NULL),
  ('kunlik-oqish-36', 'целую', 'целую', 'bo‘sayman', NULL),
  ('kunlik-oqish-36', 'чай', 'чай', 'choy', NULL),
  ('kunlik-oqish-36', 'школьные', 'школьные', 'maktab…', NULL),
  ('kunlik-oqish-36', 'Это', 'это', 'Bu (o‘rta)', NULL),
  ('kunlik-oqish-36', 'я', 'я', 'Men', NULL),
  ('kunlik-oqish-37', 'Бабушка', 'бабушка', 'Buvi', NULL),
  ('kunlik-oqish-37', 'бабушке', 'бабушке', 'Buvimga', NULL),
  ('kunlik-oqish-37', 'был', 'был', 'Edi (erkak)', NULL),
  ('kunlik-oqish-37', 'была', 'была', 'Edi (ayol)', NULL),
  ('kunlik-oqish-37', 'в', 'в', '...da', NULL),
  ('kunlik-oqish-37', 'вещи', 'вещи', 'Narsalar', NULL),
  ('kunlik-oqish-37', 'видели', 'видели', 'ko‘rdik', NULL),
  ('kunlik-oqish-37', 'вкусный', 'вкусный', 'ta’mli', NULL),
  ('kunlik-oqish-37', 'Вода', 'вода', 'suv', NULL),
  ('kunlik-oqish-37', 'воскресенье', 'воскресенье', 'yakshanba', NULL),
  ('kunlik-oqish-37', 'встретила', 'встретила', 'uchrashdi', NULL),
  ('kunlik-oqish-37', 'день', 'день', 'Kun', NULL),
  ('kunlik-oqish-37', 'деревню', 'деревню', 'qishloqqa', NULL),
  ('kunlik-oqish-37', 'дом', 'дом', 'uy', NULL),
  ('kunlik-oqish-37', 'дороге', 'дороге', 'yo‘lda', NULL),
  ('kunlik-oqish-37', 'и', 'и', 'Va', NULL),
  ('kunlik-oqish-37', 'их', 'их', 'Ularni', NULL),
  ('kunlik-oqish-37', 'к', 'к', '…ga / …tomon', NULL),
  ('kunlik-oqish-37', 'комнату', 'комнату', 'xonani', NULL),
  ('kunlik-oqish-37', 'красивые', 'красивые', 'chiroyli', NULL),
  ('kunlik-oqish-37', 'леса', 'леса', 'o‘rmon', NULL),
  ('kunlik-oqish-37', 'Летом', 'летом', 'Yozda', NULL),
  ('kunlik-oqish-37', 'машину', 'машину', 'Mashina (vin.)', NULL),
  ('kunlik-oqish-37', 'машины', 'машины', 'mashina', NULL),
  ('kunlik-oqish-37', 'мы', 'мы', 'Biz', NULL),
  ('kunlik-oqish-37', 'на', 'на', 'Ustida / yo‘nalish', NULL),
  ('kunlik-oqish-37', 'нас', 'нас', 'Bizni', NULL),
  ('kunlik-oqish-37', 'начали', 'начали', 'boshlashdi', NULL),
  ('kunlik-oqish-37', 'окно', 'окно', 'Deraza', NULL),
  ('kunlik-oqish-37', 'Папа', 'папа', 'Ota (erkak)', NULL),
  ('kunlik-oqish-37', 'По', 'по', 'yo‘nalish/harakat bo‘ylab («по дороге» → yo‘l bo‘ylab)', NULL),
  ('kunlik-oqish-37', 'поехали', 'поехали', 'ketishdi', NULL),
  ('kunlik-oqish-37', 'поехать', 'поехать', 'ketmoq', NULL),
  ('kunlik-oqish-37', 'положили', 'положили', 'qo‘yishdi', NULL),
  ('kunlik-oqish-37', 'После', 'после', 'keyin', NULL),
  ('kunlik-oqish-37', 'поставил', 'поставил', 'qo‘ydi', NULL),
  ('kunlik-oqish-37', 'поставила', 'поставила', 'qo‘ydi', NULL),
  ('kunlik-oqish-37', 'поставили', 'поставили', 'qo‘yishdi', NULL),
  ('kunlik-oqish-37', 'пошли', 'пошли', 'ketishdi', NULL),
  ('kunlik-oqish-37', 'приехали', 'приехали', 'kelishdi', NULL),
  ('kunlik-oqish-37', 'решили', 'решили', 'qaror qilishdi', NULL),
  ('kunlik-oqish-37', 'сели', 'сели', 'o‘tirishdi', NULL),
  ('kunlik-oqish-37', 'смотрели', 'смотрели', 'qarashdi', NULL),
  ('kunlik-oqish-37', 'собрали', 'собрали', 'yig‘ishdi', NULL),
  ('kunlik-oqish-37', 'стол', 'стол', 'Stol', NULL),
  ('kunlik-oqish-37', 'стулья', 'стулья', 'stullar', NULL),
  ('kunlik-oqish-37', 'тёплой', 'теплой', 'iliq', NULL),
  ('kunlik-oqish-37', 'три', 'три', 'Uch', NULL),
  ('kunlik-oqish-37', 'у', 'у', '...da borlik', NULL),
  ('kunlik-oqish-37', 'ужина', 'ужина', 'kechki ovqat', NULL),
  ('kunlik-oqish-37', 'утром', 'утром', 'Ertalab', NULL),
  ('kunlik-oqish-37', 'чай', 'чай', 'choy', NULL),
  ('kunlik-oqish-37', 'часа', 'часа', 'soat', NULL),
  ('kunlik-oqish-37', 'Через', 'через', 'Orqali / keyin', NULL),
  ('kunlik-oqish-37', 'Этот', 'этот', 'Bu (erkak)', NULL),
  ('kunlik-oqish-38', 'брат', 'брат', 'Aka / uka', NULL),
  ('kunlik-oqish-38', 'в', 'в', '...da', NULL),
  ('kunlik-oqish-38', 'Во-первых', 'во-первых', 'birinchidan', NULL),
  ('kunlik-oqish-38', 'Все', 'все', 'Barcha', NULL),
  ('kunlik-oqish-38', 'всегда', 'всегда', 'Har doim', NULL),
  ('kunlik-oqish-38', 'встречать', 'встречать', 'Kutib olmoq', NULL),
  ('kunlik-oqish-38', 'главное', 'главное', 'asosiysi', NULL),
  ('kunlik-oqish-38', 'город', 'город', 'Shahar', NULL),
  ('kunlik-oqish-38', 'гулять', 'гулять', 'Sayr qilmoq', NULL),
  ('kunlik-oqish-38', 'для', 'для', 'uchun', NULL),
  ('kunlik-oqish-38', 'друзей', 'друзей', 'Do‘stlar (род.)', NULL),
  ('kunlik-oqish-38', 'его', 'его', 'Uni (erkak)', NULL),
  ('kunlik-oqish-38', 'еду', 'еду', 'ketaman', NULL),
  ('kunlik-oqish-38', 'Ещё', 'еще', 'yana', NULL),
  ('kunlik-oqish-38', 'и', 'и', 'Va', NULL),
  ('kunlik-oqish-38', 'интересные', 'интересные', 'qiziqarli', NULL),
  ('kunlik-oqish-38', 'книги', 'книги', 'Kitoblar', NULL),
  ('kunlik-oqish-38', 'Конечно', 'конечно', 'albatta', NULL),
  ('kunlik-oqish-38', 'люблю', 'люблю', 'Sevaman / yaxshi ko‘raman', NULL),
  ('kunlik-oqish-38', 'любят', 'любят', 'sevishadi', NULL),
  ('kunlik-oqish-38', 'людей', 'людей', 'Odamlar (род.)', NULL),
  ('kunlik-oqish-38', 'люди', 'люди', 'Odamlar', NULL),
  ('kunlik-oqish-38', 'меня', 'меня', 'Meni', NULL),
  ('kunlik-oqish-38', 'места', 'места', 'joylar', NULL),
  ('kunlik-oqish-38', 'место', 'место', 'joy', NULL),
  ('kunlik-oqish-38', 'минуту', 'минуту', 'daqiqa', NULL),
  ('kunlik-oqish-38', 'многие', 'многие', 'ko‘pchilik', NULL),
  ('kunlik-oqish-38', 'Мои', 'мои', 'Mening (ko‘plik)', NULL),
  ('kunlik-oqish-38', 'моя', 'моя', 'Mening (ayol otl.)', NULL),
  ('kunlik-oqish-38', 'музыку', 'музыку', 'musiqani', NULL),
  ('kunlik-oqish-38', 'на', 'на', 'Ustida / yo‘nalish', NULL),
  ('kunlik-oqish-38', 'Но', 'но', 'Lekin', NULL),
  ('kunlik-oqish-38', 'новую', 'новую', 'yangi', NULL),
  ('kunlik-oqish-38', 'новые', 'новые', 'yangi', NULL),
  ('kunlik-oqish-38', 'новых', 'новых', 'yangi', NULL),
  ('kunlik-oqish-38', 'Они', 'они', 'ular', NULL),
  ('kunlik-oqish-38', 'очень', 'очень', 'Juda', NULL),
  ('kunlik-oqish-38', 'по', 'по', 'yo‘nalish/harakat bo‘ylab («по дороге» → yo‘l bo‘ylab)', NULL),
  ('kunlik-oqish-38', 'родители', 'родители', 'Ota-ona', NULL),
  ('kunlik-oqish-38', 'самые', 'самые', 'eng', NULL),
  ('kunlik-oqish-38', 'своё', 'свое', 'o‘zining', NULL),
  ('kunlik-oqish-38', 'своих', 'своих', 'o‘zining', NULL),
  ('kunlik-oqish-38', 'свой', 'свой', 'o‘zining', NULL),
  ('kunlik-oqish-38', 'свою', 'свою', 'O‘zimizning (ayol/vin.)', NULL),
  ('kunlik-oqish-38', 'семью', 'семью', 'Oilamni', NULL),
  ('kunlik-oqish-38', 'слушать', 'слушать', 'Tinglamoq', NULL),
  ('kunlik-oqish-38', 'смотреть', 'смотреть', 'Qaramoq', NULL),
  ('kunlik-oqish-38', 'старые', 'старые', 'eski', NULL),
  ('kunlik-oqish-38', 'тоже', 'тоже', 'Ham', NULL),
  ('kunlik-oqish-38', 'трудную', 'трудную', 'qiyin', NULL),
  ('kunlik-oqish-38', 'Узнавать', 'узнавать', 'Tanimoq', NULL),
  ('kunlik-oqish-38', 'улицам', 'улицам', 'Ko‘chalarga', NULL),
  ('kunlik-oqish-38', 'фильмы', 'фильмы', 'filmlar', NULL),
  ('kunlik-oqish-38', 'читать', 'читать', 'O‘qimoq', NULL),
  ('kunlik-oqish-38', 'что-то', 'что-то', 'nimadir', NULL),
  ('kunlik-oqish-38', 'это', 'это', 'Bu (o‘rta)', NULL),
  ('kunlik-oqish-38', 'Я', 'я', 'Men', NULL),
  ('kunlik-oqish-39', 'боится', 'боится', 'qo‘rqadi', NULL),
  ('kunlik-oqish-39', 'большой', 'большой', 'katta', NULL),
  ('kunlik-oqish-39', 'будущее', 'будущее', 'Kelajak', NULL),
  ('kunlik-oqish-39', 'в', 'в', '...da', NULL),
  ('kunlik-oqish-39', 'вагона', 'вагона', 'vagon', NULL),
  ('kunlik-oqish-39', 'вечером', 'вечером', 'Kechqurun', NULL),
  ('kunlik-oqish-39', 'внимательно', 'внимательно', 'Diqqat bilan', NULL),
  ('kunlik-oqish-39', 'вокзал', 'вокзал', 'vokzal', NULL),
  ('kunlik-oqish-39', 'вопросы', 'вопросы', 'savollar', NULL),
  ('kunlik-oqish-39', 'времени', 'времени', 'Vaqt (род.)', NULL),
  ('kunlik-oqish-39', 'встрече', 'встрече', 'uchrashuvda', NULL),
  ('kunlik-oqish-39', 'вышел', 'вышел', 'chiqdi', NULL),
  ('kunlik-oqish-39', 'город', 'город', 'Shahar', NULL),
  ('kunlik-oqish-39', 'гостиницы', 'гостиницы', 'mehmonxona', NULL),
  ('kunlik-oqish-39', 'делился', 'делился', 'bo‘lishdi', NULL),
  ('kunlik-oqish-39', 'до', 'до', 'Ko‘rishguncha tuzilmasi (до)', NULL),
  ('kunlik-oqish-39', 'долго', 'долго', 'uzoq', NULL),
  ('kunlik-oqish-39', 'Друг', 'друг', 'Do‘st', NULL),
  ('kunlik-oqish-39', 'друга', 'друга', 'Do‘st (род.; 2 uchun)', NULL),
  ('kunlik-oqish-39', 'дружба', 'дружба', 'Do‘stlik', NULL),
  ('kunlik-oqish-39', 'его', 'его', 'Uni (erkak)', NULL),
  ('kunlik-oqish-39', 'ждал', 'ждал', 'kutdi', NULL),
  ('kunlik-oqish-39', 'жизни', 'жизни', 'hayotda', NULL),
  ('kunlik-oqish-39', 'задавал', 'задавал', 'berardi', NULL),
  ('kunlik-oqish-39', 'и', 'и', 'Va', NULL),
  ('kunlik-oqish-39', 'из', 'из', '...dan', NULL),
  ('kunlik-oqish-39', 'к', 'к', '…ga / …tomon', NULL),
  ('kunlik-oqish-39', 'кафе', 'кафе', 'Kafe', NULL),
  ('kunlik-oqish-39', 'Когда', 'когда', 'qachon', NULL),
  ('kunlik-oqish-39', 'мне', 'мне', 'Menga', NULL),
  ('kunlik-oqish-39', 'Мы', 'мы', 'Biz', NULL),
  ('kunlik-oqish-39', 'мыслями', 'мыслями', 'fikrlar bilan', NULL),
  ('kunlik-oqish-39', 'На', 'на', 'Ustida / yo‘nalish', NULL),
  ('kunlik-oqish-39', 'Наконец', 'наконец', 'Nihoyat', NULL),
  ('kunlik-oqish-39', 'настоящая', 'настоящая', 'haqiqiy', NULL),
  ('kunlik-oqish-39', 'начал', 'начал', 'boshladi', NULL),
  ('kunlik-oqish-39', 'наш', 'наш', 'Bizning', NULL),
  ('kunlik-oqish-39', 'не', 'не', 'Emas', NULL),
  ('kunlik-oqish-39', 'неделе', 'неделе', 'haftada', NULL),
  ('kunlik-oqish-39', 'ни', 'ни', '…ham emas', NULL),
  ('kunlik-oqish-39', 'новых', 'новых', 'yangi', NULL),
  ('kunlik-oqish-39', 'о', 'о', '…haqida', NULL),
  ('kunlik-oqish-39', 'обрадовался', 'обрадовался', 'Xursand bo‘ldi', NULL),
  ('kunlik-oqish-39', 'Он', 'он', 'U (erkak)', NULL),
  ('kunlik-oqish-39', 'от', 'от', '...dan', NULL),
  ('kunlik-oqish-39', 'очень', 'очень', 'Juda', NULL),
  ('kunlik-oqish-39', 'писал', 'писал', 'yozgan', NULL),
  ('kunlik-oqish-39', 'планах', 'планах', 'Rejalar', NULL),
  ('kunlik-oqish-39', 'поехал', 'поехал', 'ketdi', NULL),
  ('kunlik-oqish-39', 'понял', 'понял', 'tushundi', NULL),
  ('kunlik-oqish-39', 'пошли', 'пошли', 'ketishdi', NULL),
  ('kunlik-oqish-39', 'приедет', 'приедет', 'keladi', NULL),
  ('kunlik-oqish-39', 'провожал', 'провожал', 'Kuzatib qo‘ydim', NULL),
  ('kunlik-oqish-39', 'проговорили', 'проговорили', 'gaplashishdi', NULL),
  ('kunlik-oqish-39', 'прошлой', 'прошлой', 'o‘tgan', NULL),
  ('kunlik-oqish-39', 'пятницу', 'пятницу', 'jumaga', NULL),
  ('kunlik-oqish-39', 'рассказал', 'рассказал', 'Aytib berdi', NULL),
  ('kunlik-oqish-39', 'с', 'с', 'birga bilan («с другом»)', NULL),
  ('kunlik-oqish-39', 'своего', 'своего', 'o‘zining', NULL),
  ('kunlik-oqish-39', 'своей', 'своей', 'O‘zimning (ayol rod.)', NULL),
  ('kunlik-oqish-39', 'своими', 'своими', 'o‘zlari bilan', NULL),
  ('kunlik-oqish-39', 'своих', 'своих', 'o‘zining', NULL),
  ('kunlik-oqish-39', 'слушал', 'слушал', 'Tingladim', NULL),
  ('kunlik-oqish-39', 'среди', 'среди', 'Orasida', NULL),
  ('kunlik-oqish-39', 'старого', 'старого', 'eski', NULL),
  ('kunlik-oqish-39', 'сумкой', 'сумкой', 'sumka bilan', NULL),
  ('kunlik-oqish-39', 'то', 'то', 'O‘sha (o‘rta)', NULL),
  ('kunlik-oqish-39', 'у', 'у', '...da borlik', NULL),
  ('kunlik-oqish-39', 'увидел', 'увидел', 'ko‘rdi', NULL),
  ('kunlik-oqish-39', 'что', 'что', 'nima / kim', NULL),
  ('kunlik-oqish-39', 'я', 'я', 'Men', NULL),
  ('kunlik-oqish-40', 'бабушка', 'бабушка', 'Buvi', NULL),
  ('kunlik-oqish-40', 'большой', 'большой', 'katta', NULL),
  ('kunlik-oqish-40', 'был', 'был', 'Edi (erkak)', NULL),
  ('kunlik-oqish-40', 'в', 'в', '...da', NULL),
  ('kunlik-oqish-40', 'вечер', 'вечер', 'Kech', NULL),
  ('kunlik-oqish-40', 'вечера', 'вечера', 'Kechning', NULL),
  ('kunlik-oqish-40', 'воскресенье', 'воскресенье', 'yakshanba', NULL),
  ('kunlik-oqish-40', 'всё', 'все', 'Barcha', NULL),
  ('kunlik-oqish-40', 'всегда', 'всегда', 'Har doim', NULL),
  ('kunlik-oqish-40', 'город', 'город', 'Shahar', NULL),
  ('kunlik-oqish-40', 'городу', 'городу', 'shaharga', NULL),
  ('kunlik-oqish-40', 'дала', 'дала', 'berdi', NULL),
  ('kunlik-oqish-40', 'детей', 'детей', 'bolalar', NULL),
  ('kunlik-oqish-40', 'добру', 'добру', 'yaxshilikka', NULL),
  ('kunlik-oqish-40', 'домой', 'домой', 'uyga', NULL),
  ('kunlik-oqish-40', 'друзьям', 'друзьям', 'do‘stlarga', NULL),
  ('kunlik-oqish-40', 'друзьях', 'друзьях', 'do‘stlar haqida', NULL),
  ('kunlik-oqish-40', 'забуду', 'забуду', 'Unutmayman', NULL),
  ('kunlik-oqish-40', 'и', 'и', 'Va', NULL),
  ('kunlik-oqish-40', 'им', 'им', 'ularga', NULL),
  ('kunlik-oqish-40', 'интересные', 'интересные', 'qiziqarli', NULL),
  ('kunlik-oqish-40', 'Каждое', 'каждое', 'Har bir', NULL),
  ('kunlik-oqish-40', 'каждый', 'каждый', 'har bir', NULL),
  ('kunlik-oqish-40', 'как', 'как', 'Qanday', NULL),
  ('kunlik-oqish-40', 'Когда', 'когда', 'qachon', NULL),
  ('kunlik-oqish-40', 'любил', 'любил', 'sevgan', NULL),
  ('kunlik-oqish-40', 'любить', 'любить', 'Sevmoq', NULL),
  ('kunlik-oqish-40', 'меня', 'меня', 'Meni', NULL),
  ('kunlik-oqish-40', 'мне', 'мне', 'Menga', NULL),
  ('kunlik-oqish-40', 'Моя', 'моя', 'Mening (ayol otl.)', NULL),
  ('kunlik-oqish-40', 'не', 'не', 'Emas', NULL),
  ('kunlik-oqish-40', 'никогда', 'никогда', 'Hech qachon', NULL),
  ('kunlik-oqish-40', 'новых', 'новых', 'yangi', NULL),
  ('kunlik-oqish-40', 'о', 'о', '…haqida', NULL),
  ('kunlik-oqish-40', 'Она', 'она', 'U (ayol)', NULL),
  ('kunlik-oqish-40', 'Они', 'они', 'ular', NULL),
  ('kunlik-oqish-40', 'очень', 'очень', 'Juda', NULL),
  ('kunlik-oqish-40', 'планах', 'планах', 'Rejalar', NULL),
  ('kunlik-oqish-40', 'по', 'по', 'yo‘nalish/harakat bo‘ylab («по дороге» → yo‘l bo‘ylab)', NULL),
  ('kunlik-oqish-40', 'поддерживали', 'поддерживали', 'qo‘llab-quvvatlashdi', NULL),
  ('kunlik-oqish-40', 'понимаю', 'понимаю', 'tushunaman', NULL),
  ('kunlik-oqish-40', 'рассказывал', 'рассказывал', 'gapirdi', NULL),
  ('kunlik-oqish-40', 'ребёнком', 'ребенком', 'bola bo‘lib', NULL),
  ('kunlik-oqish-40', 'родителей', 'родителей', 'ota-onalari', NULL),
  ('kunlik-oqish-40', 'родителям', 'родителям', 'ota-onalariga', NULL),
  ('kunlik-oqish-40', 'сам', 'сам', 'o‘zi', NULL),
  ('kunlik-oqish-40', 'своей', 'своей', 'O‘zimning (ayol rod.)', NULL),
  ('kunlik-oqish-40', 'своему', 'своему', 'o‘ziga', NULL),
  ('kunlik-oqish-40', 'своим', 'своим', 'o‘zining', NULL),
  ('kunlik-oqish-40', 'своих', 'своих', 'o‘zining', NULL),
  ('kunlik-oqish-40', 'Сейчас', 'сейчас', 'Hozir', NULL),
  ('kunlik-oqish-40', 'семье', 'семье', 'Oilada', NULL),
  ('kunlik-oqish-40', 'семья', 'семья', 'Oila', NULL),
  ('kunlik-oqish-40', 'слушать', 'слушать', 'Tinglamoq', NULL),
  ('kunlik-oqish-40', 'стал', 'стал', 'bo‘ldi', NULL),
  ('kunlik-oqish-40', 'стараюсь', 'стараюсь', 'Harakat qilaman', NULL),
  ('kunlik-oqish-40', 'тёплые', 'теплые', 'iliq', NULL),
  ('kunlik-oqish-40', 'то', 'то', 'O‘sha (o‘rta)', NULL),
  ('kunlik-oqish-40', 'уважать', 'уважать', 'Hurmat qilmoq', NULL),
  ('kunlik-oqish-40', 'уехал', 'уехал', 'ketdi', NULL),
  ('kunlik-oqish-40', 'учила', 'учила', 'o‘rgatdi', NULL),
  ('kunlik-oqish-40', 'учиться', 'учиться', 'O‘qimoq', NULL),
  ('kunlik-oqish-40', 'хорошее', 'хорошее', 'yaxshi', NULL),
  ('kunlik-oqish-40', 'читала', 'читала', 'o‘qidi', NULL),
  ('kunlik-oqish-40', 'что', 'что', 'nima / kim', NULL),
  ('kunlik-oqish-40', 'эти', 'эти', 'Bular', NULL),
  ('kunlik-oqish-40', 'я', 'я', 'Men', NULL)
ON CONFLICT (text_id, word_ru_normalized) DO NOTHING;
