import { useCallback, useEffect, useRef, useState } from 'react';
import { ArrowDownToLine, ArrowUpRight, CheckCircle2, ChevronLeft, ChevronRight, ClipboardList, Gift, LoaderCircle, RefreshCw, Save, Search, Settings2, Ticket, Users, X } from 'lucide-react';
import { KIOSK_AUDIENCE_LABELS, type KioskAudience } from '../../../shared/kiosk';
import { adminApi } from '../../lib/adminApi';
import type { KioskConfig, KioskDashboard, KioskParticipant } from '../../../shared/kiosk';
import '../../components/kiosk/admin-kiosk.css';

const date=(s:string)=>new Date(s).toLocaleString('ru-RU',{timeZone:'Asia/Tashkent',day:'2-digit',month:'short',hour:'2-digit',minute:'2-digit'});
const csvCell=(v:unknown)=>`"${String(v??'').replace(/^\s*[=+@\-\t\r]/,"'$&").replace(/"/g,'""')}"`;
export default function AdminKioskPage(){
  const [data,setData]=useState<KioskDashboard|null>(null);const [config,setConfig]=useState<KioskConfig|null>(null);
  const [audience,setAudience]=useState<KioskAudience|'all'>('all');
  const [days,setDays]=useState(30);const [page,setPage]=useState(1);const [search,setSearch]=useState('');const [query,setQuery]=useState('');const [status,setStatus]=useState('all');
  const [tab,setTab]=useState<'participants'|'settings'>('participants');const [loading,setLoading]=useState(true);const [busy,setBusy]=useState(false);const [exporting,setExporting]=useState(false);const [error,setError]=useState('');const [message,setMessage]=useState('');
  const [redeem,setRedeem]=useState<KioskParticipant|null>(null);const [note,setNote]=useState('');const dialog=useRef<HTMLDialogElement>(null);const requestId=useRef(0);
  useEffect(()=>{const id=setTimeout(()=>{setPage(1);setQuery(search);},350);return()=>clearTimeout(id);},[search]);
  const params=useCallback((p=page)=>new URLSearchParams({days:String(days),page:String(p),search:query,status,audience}).toString(),[days,page,query,status,audience]);
  const refresh=useCallback(async()=>{const id=++requestId.current;setLoading(true);setError('');try{const result=await adminApi<KioskDashboard>(`/kiosk/stats?${params()}`);if(id===requestId.current)setData(result);}catch(e){if(id===requestId.current)setError((e as Error).message);}finally{if(id===requestId.current)setLoading(false);}},[params]);
  useEffect(()=>{void refresh();return()=>{requestId.current++;};},[refresh]);
  useEffect(()=>{void adminApi<KioskConfig>('/kiosk/config').then(setConfig).catch(e=>setError(e.message));},[]);
  useEffect(()=>{if(redeem){setNote('');dialog.current?.showModal();}else dialog.current?.close();},[redeem]);
  const save=async(e:React.FormEvent)=>{e.preventDefault();if(!config)return;setBusy(true);setError('');setMessage('');try{setConfig(await adminApi<KioskConfig>('/kiosk/config',{method:'PUT',body:JSON.stringify(config)}));setMessage('Условия сохранены. Они применяются к новым тестам.');}catch(e){setError((e as Error).message);}finally{setBusy(false);}};
  const confirmRedeem=async(e:React.FormEvent)=>{e.preventDefault();if(!redeem?.coupon_id)return;setBusy(true);setError('');try{await adminApi(`/kiosk/coupons/${redeem.coupon_id}/redeem`,{method:'POST',body:JSON.stringify({note})});setRedeem(null);setMessage('Использование купона подтверждено.');await refresh();}catch(e){setError((e as Error).message);}finally{setBusy(false);}};
  const exportCsv=async()=>{setExporting(true);setError('');try{
    let all:KioskParticipant[]=[];let current=1;let total=1;
    while(all.length<total){const result=await adminApi<KioskDashboard>(`/kiosk/stats?${params(current++)}`);all.push(...result.participants);total=result.total;if(!result.participants.length)break;if(total>10000)throw new Error('Слишком много строк. Выберите меньший период или уточните поиск.');}
    const rows=[['Имя','Группа','Телефон','Согласие на предложения','Дата','Источник','Язык','Статус','Баллы','Ответов','Купон','Скидка %','Действует до','Использован'],...all.map(r=>[r.name,KIOSK_AUDIENCE_LABELS[r.audience]?.ru??r.audience,r.phone,r.marketing_consent?'Да':'Нет',r.created_at,r.source,r.locale,r.status,r.correct_count,r.answer_count,r.coupon_code,r.discount_percent,r.expires_at,r.redeemed_at])];
    const url=URL.createObjectURL(new Blob(['\ufeff'+rows.map(r=>r.map(csvCell).join(';')).join('\r\n')],{type:'text/csv;charset=utf-8'}));const a=document.createElement('a');a.href=url;a.download=`falarus-test-${new Date().toISOString().slice(0,10)}.csv`;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);
  }catch(e){setError((e as Error).message);}finally{setExporting(false);}};
  const s=data?.summary;const percent=s?.started?Math.round(s.completed/s.started*100):0;
  const change=<K extends keyof KioskConfig>(key:K,value:KioskConfig[K])=>{setConfig(c=>c?{...c,[key]:value}:c);setMessage('');};
  return <div className="kiosk-admin">
    <header className="ka-heading"><div><div className="ka-eyebrow">FALARUS · АКЦИИ</div><h1>Тест и скидки</h1><p>От первого ответа до использования купона.</p></div><a className="ka-button" href="/test-russkogo" target="_blank" rel="noreferrer">Открыть тест <ArrowUpRight size={17}/></a></header>
    {error&&<div className="ka-alert error" role="alert">{error}</div>}{message&&<div className="ka-alert success" role="status"><CheckCircle2 size={18}/>{message}</div>}
    <div className="ka-toolbar"><div className="ka-tabs" aria-label="Раздел"><button className={tab==='participants'?'active':''} onClick={()=>setTab('participants')}><Users size={17}/>Статистика</button><button className={tab==='settings'?'active':''} onClick={()=>setTab('settings')}><Settings2 size={17}/>Условия акции</button></div>{tab==='participants'&&<div className="ka-toolbar-right"><select aria-label="Возрастная группа" value={audience} onChange={e=>{setAudience(e.target.value as KioskAudience|'all');setPage(1);}}><option value="all">Все группы</option>{Object.entries(KIOSK_AUDIENCE_LABELS).map(([key,label])=><option key={key} value={key}>{label.ru}</option>)}</select><select aria-label="Период статистики" value={days} onChange={e=>{setDays(Number(e.target.value));setPage(1);}}><option value={7}>За 7 дней</option><option value={30}>За 30 дней</option><option value={90}>За 90 дней</option><option value={365}>За год</option></select><button className="ka-button icon" aria-label="Обновить статистику" onClick={()=>void refresh()} disabled={loading}><RefreshCw size={17} className={loading?'ka-spin':''}/></button></div>}</div>
    {tab==='participants'&&<>
      <div className="ka-audience-summary">{Object.entries(KIOSK_AUDIENCE_LABELS).map(([key,label])=>{const group=data?.audiences.find(a=>a.audience===key);return <button key={key} className={audience===key?'active':''} onClick={()=>{setAudience(audience===key?'all':key as KioskAudience);setPage(1);}} aria-pressed={audience===key}><span>{label.ru}</span><strong>{group?.started??0}</strong><small>Завершили: {group?.completed??0}</small></button>;})}</div>
      <div className="ka-metrics">{[
        {label:'Начали тест',value:s?.started,icon:ClipboardList,note:'Все попытки за период'},
        {label:'Участники',value:s?.contacts,icon:Users,note:'Уникальные телефоны'},
        {label:'Завершили',value:s?.completed,icon:CheckCircle2,note:`${percent}% от начавших`},
        {label:'Средний результат',value:s?`${s.averageScore} / 10`:undefined,icon:Gift,note:'Среди завершивших тест'},
        {label:'Выдано скидок',value:s?.issued,icon:Ticket,note:'Новые купоны за период'},
        {label:'Использовано',value:s?.redeemed,icon:CheckCircle2,note:'Из выданных за период'},
      ].map(({label,value,icon:Icon,note})=><section className="ka-metric" key={label}><div><span>{label}</span><Icon size={18}/></div><strong>{value??'—'}</strong><small>{note}</small></section>)}</div>
      <div className="ka-charts"><section className="ka-panel"><div className="ka-panel-heading"><h2>Активность по дням</h2><span><i className="ka-dot"/> Начали <i className="ka-dot green"/> Завершили</span></div>{data?.daily.length?<div className="ka-chart-scroll"><div className="ka-chart">{data.daily.map(d=>{const max=Math.max(...data.daily.map(x=>x.started),1);return <div className="ka-bar-group" key={d.day} title={`${d.day}: начали ${d.started}, завершили ${d.completed}`}><span>{d.started}</span><div><i style={{height:`${Math.max(3,d.started/max*120)}px`}}/><i className="green" style={{height:`${d.completed?Math.max(3,d.completed/max*120):0}px`}}/></div><small>{d.day.slice(8)}.{d.day.slice(5,7)}</small></div>;})}</div></div>:<div className="ka-chart-empty">После первых прохождений здесь появится график.</div>}</section>
      <section className="ka-panel"><div className="ka-panel-heading"><h2>Результаты теста</h2><span>Правильных ответов</span></div><div className="ka-score-chart">{Array.from({length:11},(_,score)=>{const count=data?.scores.find(x=>x.score===score)?.count??0;const max=Math.max(...(data?.scores.map(x=>x.count)??[]),1);return <div key={score} title={`${score} из 10: ${count} участников`}><span>{count||''}</span><i style={{height:`${count?Math.max(4,count/max*120):3}px`}} className={count?'':'empty'}/><small>{score}</small></div>;})}</div></section></div>
      <section className="ka-panel ka-table-panel"><div className="ka-table-heading"><div><h2>Участники</h2><p>{data?.total??0} записей по выбранным фильтрам</p></div><button className="ka-button" onClick={()=>void exportCsv()} disabled={exporting||!data?.total}>{exporting?<LoaderCircle size={17} className="ka-spin"/>:<ArrowDownToLine size={17}/>}Скачать CSV</button></div>
        <div className="ka-filters"><label className="ka-search"><Search size={18}/><input placeholder="Имя, телефон или промокод" value={search} onChange={e=>setSearch(e.target.value)} aria-label="Поиск участников"/>{search&&<button aria-label="Очистить поиск" onClick={()=>setSearch('')}><X size={16}/></button>}</label><select aria-label="Статус участника" value={status} onChange={e=>{setStatus(e.target.value);setPage(1);}}><option value="all">Все участники</option><option value="started">Не завершили</option><option value="completed">Завершили тест</option><option value="issued">Получили скидку</option><option value="redeemed">Использовали скидку</option></select></div>
        <div className="ka-table-scroll" aria-busy={loading}><table><thead><tr><th>Участник</th><th>Дата / источник</th><th>Результат</th><th>Купон</th><th>Статус скидки</th><th><span className="sr-only">Действия</span></th></tr></thead><tbody>{data?.participants.map(r=>{const expired=r.expires_at&&new Date(r.expires_at).getTime()<=Date.now();return <tr key={r.id}><td><strong>{r.name}</strong><a href={`tel:${r.phone}`}>{r.phone}</a><small>{KIOSK_AUDIENCE_LABELS[r.audience]?.ru??r.audience}</small></td><td>{date(r.created_at)}<small>{r.source} · {r.locale.toUpperCase()}</small></td><td><span className={`ka-status ${r.status==='completed'?'good':'neutral'}`}>{r.status==='completed'?`${r.correct_count} / 10`:`${r.answer_count} / 10 ответов`}</span><small>{r.status==='completed'?'Завершён':'Не завершён'}</small></td><td>{r.coupon_code?<><code>{r.coupon_code}</code><small>Скидка {r.discount_percent}%</small></>:'—'}</td><td>{r.coupon_code?<><span className={`ka-status ${r.redeemed_at?'good':expired?'neutral':'gold'}`}>{r.redeemed_at?'Использован':expired?'Истёк':'Активен'}</span><small>{r.redeemed_at?date(r.redeemed_at):r.expires_at?`До ${date(r.expires_at)}`:''}</small></>:'—'}</td><td>{r.coupon_id&&!r.redeemed_at&&!expired&&<button className="ka-button small" onClick={()=>setRedeem(r)}>Подтвердить использование</button>}</td></tr>;})}</tbody></table>{!data?.participants.length&&<div className="ka-empty">{loading?<><LoaderCircle className="ka-spin"/>Загружаем участников…</>:<><Users size={30}/><strong>{query||status!=='all'?'Ничего не найдено':'Пока нет участников'}</strong><span>{query||status!=='all'?'Измените поиск или фильтр.':'Поделитесь ссылкой на тест — результаты появятся здесь.'}</span></>}</div>}</div>
        <div className="ka-pagination"><span>Страница {page} из {Math.max(1,Math.ceil((data?.total??0)/25))}</span><div><button className="ka-button icon" aria-label="Предыдущая страница" onClick={()=>setPage(p=>p-1)} disabled={page===1||loading}><ChevronLeft size={18}/></button><button className="ka-button icon" aria-label="Следующая страница" onClick={()=>setPage(p=>p+1)} disabled={loading||page*25>=(data?.total??0)}><ChevronRight size={18}/></button></div></div>
      </section><p className="ka-footnote">Даты: Ташкент (UTC+5). Использование купона подтверждается менеджером; это не автоматическое подтверждение оплаты.</p>
    </>}
    {tab==='settings'&&(config?<form className="ka-panel ka-settings" onSubmit={save}><div className="ka-settings-heading"><div><h2>Правила выдачи скидки</h2><p>Выданные купоны сохраняют условия, действовавшие при начале теста.</p></div><label className="ka-switch"><input type="checkbox" checked={config.enabled} onChange={e=>change('enabled',e.target.checked)}/><span>Тест включён</span></label></div>
      <div className="ka-settings-grid"><label>Название курса (RU)<input required maxLength={160} value={config.courseTitle} onChange={e=>change('courseTitle',e.target.value)}/></label><label>Название курса (UZ)<input required maxLength={160} value={config.courseTitleUz} onChange={e=>change('courseTitleUz',e.target.value)}/></label>
        <label>Скидка, %<input type="number" min={1} max={90} required value={config.discountPercent} onChange={e=>change('discountPercent',Number(e.target.value))}/></label><label>Правильных ответов для скидки<input type="number" min={0} max={10} required value={config.minimumCorrect} onChange={e=>change('minimumCorrect',Number(e.target.value))}/><small>0 — скидка за прохождение независимо от результата.</small></label>
        <label>Срок действия, часов<input type="number" min={1} max={720} required value={config.validityHours} onChange={e=>change('validityHours',Number(e.target.value))}/></label><label>Время на вопрос, секунд<input type="number" min={10} max={120} required value={config.questionSeconds} onChange={e=>change('questionSeconds',Number(e.target.value))}/></label>
        <label>Обычная цена курса<input type="number" min={1} max={1000000000} step="0.01" placeholder="Не показывать цену" value={config.originalPrice??''} onChange={e=>change('originalPrice',e.target.value===''?null:Number(e.target.value))}/><small>Без цены посетитель увидит только процент скидки.</small></label><label>Валюта<select value={config.currency} onChange={e=>change('currency',e.target.value as 'RUB'|'UZS')}><option value="RUB">Российский рубль (₽)</option><option value="UZS">Узбекский сум (so‘m)</option></select></label>
        <label className="ka-wide">Код акции<input required pattern="[a-z0-9_-]+" maxLength={60} value={config.campaignKey} onChange={e=>change('campaignKey',e.target.value)}/><small>Один купон на телефон в рамках акции. Новый код разрешает всем участвовать заново; старые купоны остаются действительными до своего срока.</small></label>
      </div><div className="ka-settings-footer"><span>10 вопросов · Проверка ответов на сервере</span><button className="ka-button primary" disabled={busy}>{busy?<LoaderCircle size={18} className="ka-spin"/>:<Save size={18}/>}Сохранить условия</button></div>
    </form>:<div className="ka-empty">Загружаем настройки…</div>)}
    <dialog className="ka-dialog" ref={dialog} onCancel={()=>{if(!busy)setRedeem(null);}}><form onSubmit={confirmRedeem}><div className="ka-dialog-heading"><h2>Использование купона</h2><button type="button" aria-label="Закрыть" onClick={()=>setRedeem(null)} disabled={busy}><X size={22}/></button></div><p>{redeem?.name} · {redeem?.phone}</p><code>{redeem?.coupon_code}</code><p>Подтвердите, что скидка {redeem?.discount_percent}% применена к заказу. Повторное использование будет недоступно.</p><label>Номер заказа или комментарий<textarea required minLength={3} maxLength={500} value={note} onChange={e=>setNote(e.target.value)} placeholder="Например: заказ 1245, курс 182 дня"/></label>{error&&<p className="ka-dialog-error" role="alert">{error}</p>}<div className="ka-dialog-actions"><button type="button" className="ka-button" onClick={()=>setRedeem(null)} disabled={busy}>Отмена</button><button className="ka-button primary" disabled={busy}>{busy?'Сохраняем…':'Подтвердить'}</button></div></form></dialog>
  </div>;
}
