/* eslint-disable */
// Generated by scripts/generate_patent_keywords.ts — edit manually or re-run the script.

export type PatentQuestionKeywordHints = {
  textKeyword?: string | null;
  optionKeywords?: (string | null)[] | null;
};

export const PATENT_QUESTION_KEYWORDS: Record<string, PatentQuestionKeywordHints> = {
  "P_1_1": {
    "optionKeywords": [
      null,
      null,
      "в центре тестирования"
    ]
  },
  "P_1_2": {
    "optionKeywords": [
      "миграционную карту",
      null,
      null
    ]
  },
  "P_1_3": {
    "optionKeywords": [
      "в торговом центре",
      null,
      null
    ]
  },
  "P_1_4": {
    "optionKeywords": [
      null,
      "у администратора",
      null
    ]
  },
  "P_1_5": {
    "optionKeywords": [
      null,
      "в автобусе",
      null
    ]
  },
  "P_1_6": {
    "optionKeywords": [
      "в 10 часов",
      null,
      null
    ]
  },
  "P_1_8": {
    "optionKeywords": [
      null,
      "в пятницу",
      null
    ]
  },
  "P_1_9": {
    "optionKeywords": [
      null,
      null,
      "телефон"
    ]
  },
  "P_1_10": {
    "optionKeywords": [
      null,
      "Меня",
      null
    ]
  },
  "P_1_11": {
    "optionKeywords": [
      "потому что",
      null,
      null
    ]
  },
  "P_1_12": {
    "optionKeywords": [
      null,
      "День народного единства",
      null
    ]
  },
  "P_1_13": {
    "optionKeywords": [
      "Москва",
      null,
      null
    ]
  },
  "P_1_14": {
    "optionKeywords": [
      null,
      "в 1945 г",
      null
    ]
  },
  "P_1_15": {
    "optionKeywords": [
      "распада СССР в 1991 г",
      null,
      null
    ]
  },
  "P_1_17": {
    "textKeyword": "Российской",
    "optionKeywords": [
      null,
      "иностранные граждане пользуются правами и несут обязанности наравне с гражданами Российской Федерации",
      null
    ]
  },
  "P_1_18": {
    "optionKeywords": [
      null,
      "записи актов гражданского состояния",
      null
    ]
  },
  "P_1_19": {
    "optionKeywords": [
      "в полицию",
      null,
      null
    ]
  },
  "P_1_20": {
    "optionKeywords": [
      null,
      null,
      "паспорт и миграционную карту"
    ]
  },
  "P_1_21": {
    "optionKeywords": [
      null,
      null,
      "административной"
    ]
  },
  "P_1_22": {
    "textKeyword": "Верно"
  },
  "P_2_1": {
    "optionKeywords": [
      null,
      null,
      "в автобусе"
    ]
  },
  "P_2_2": {
    "optionKeywords": [
      "через одну остановку",
      null,
      null
    ]
  },
  "P_2_3": {
    "optionKeywords": [
      "в торговом центре",
      null,
      null
    ]
  },
  "P_2_4": {
    "optionKeywords": [
      "взять свой потерянный телефон",
      null,
      null
    ]
  },
  "P_2_5": {
    "optionKeywords": [
      null,
      "о спорте",
      null
    ]
  },
  "P_2_6": {
    "optionKeywords": [
      "в парке",
      null,
      null
    ]
  },
  "P_2_8": {
    "optionKeywords": [
      null,
      null,
      "стол"
    ]
  },
  "P_2_9": {
    "optionKeywords": [
      null,
      null,
      "работает"
    ]
  },
  "P_2_10": {
    "optionKeywords": [
      null,
      "тебе",
      null
    ]
  },
  "P_2_12": {
    "optionKeywords": [
      null,
      null,
      "Рождество Христово"
    ]
  },
  "P_2_13": {
    "optionKeywords": [
      null,
      "Владивосток",
      null
    ]
  },
  "P_2_14": {
    "optionKeywords": [
      null,
      null,
      "Великобритания"
    ]
  },
  "P_2_15": {
    "optionKeywords": [
      null,
      "Жуков",
      null
    ]
  },
  "P_2_17": {
    "optionKeywords": [
      null,
      null,
      "пользоваться родным языком"
    ]
  },
  "P_2_18": {
    "optionKeywords": [
      "только в письменной",
      null,
      null
    ]
  },
  "P_2_19": {
    "optionKeywords": [
      "в полицию и консульство своей страны",
      null,
      null
    ]
  },
  "P_2_20": {
    "optionKeywords": [
      null,
      "7 рабочих дней",
      null
    ]
  },
  "P_2_21": {
    "optionKeywords": [
      null,
      "Кодекс Российской Федерации об административных правонарушениях",
      null
    ]
  },
  "P_2_22": {
    "textKeyword": "Верно"
  },
  "P_3_1": {
    "optionKeywords": [
      null,
      null,
      "в гостинице"
    ]
  },
  "P_3_2": {
    "optionKeywords": [
      null,
      "нет свободных номеров",
      null
    ]
  },
  "P_3_3": {
    "optionKeywords": [
      null,
      null,
      "изменил часы работы"
    ]
  },
  "P_3_4": {
    "optionKeywords": [
      "до 9 часов вечера",
      null,
      null
    ]
  },
  "P_3_5": {
    "optionKeywords": [
      null,
      "на стройке",
      null
    ]
  },
  "P_3_6": {
    "optionKeywords": [
      "вечером",
      null,
      null
    ]
  },
  "P_3_8": {
    "optionKeywords": [
      "6 июня",
      null,
      null
    ]
  },
  "P_3_9": {
    "optionKeywords": [
      null,
      "слушать",
      null
    ]
  },
  "P_3_10": {
    "optionKeywords": [
      null,
      null,
      "у вас"
    ]
  },
  "P_3_11": {
    "optionKeywords": [
      null,
      "потому что",
      null
    ]
  },
  "P_3_12": {
    "optionKeywords": [
      null,
      "День защитника Отечества",
      null
    ]
  },
  "P_3_13": {
    "optionKeywords": [
      null,
      null,
      "Санкт-Петербург"
    ]
  },
  "P_3_14": {
    "optionKeywords": [
      null,
      null,
      "в 1945 г"
    ]
  },
  "P_3_15": {
    "optionKeywords": [
      null,
      null,
      "в 1991 г"
    ]
  },
  "P_3_17": {
    "optionKeywords": [
      null,
      "выбирать род занятий",
      null
    ]
  },
  "P_3_18": {
    "textKeyword": "Имеет"
  },
  "P_3_20": {
    "optionKeywords": [
      null,
      "Работа",
      null
    ]
  },
  "P_3_21": {
    "optionKeywords": [
      "30 календарных дней",
      null,
      null
    ]
  },
  "P_3_22": {
    "textKeyword": "Верно"
  },
  "P_4_1": {
    "optionKeywords": [
      "друзей",
      null,
      null
    ]
  },
  "P_4_2": {
    "optionKeywords": [
      null,
      null,
      "Он дал мобильный телефон"
    ]
  },
  "P_4_3": {
    "optionKeywords": [
      null,
      "в магазине",
      null
    ]
  },
  "P_4_4": {
    "optionKeywords": [
      null,
      null,
      "принимают только наличные деньги"
    ]
  },
  "P_4_5": {
    "optionKeywords": [
      "в транспорте",
      null,
      null
    ]
  },
  "P_4_6": {
    "optionKeywords": [
      null,
      "строителем",
      null
    ]
  },
  "P_4_9": {
    "optionKeywords": [
      null,
      "врачом",
      null
    ]
  },
  "P_4_10": {
    "optionKeywords": [
      null,
      null,
      "ваши"
    ]
  },
  "P_4_12": {
    "optionKeywords": [
      null,
      "9 мая",
      null
    ]
  },
  "P_4_13": {
    "optionKeywords": [
      null,
      null,
      "Новосибирск"
    ]
  },
  "P_4_14": {
    "optionKeywords": [
      null,
      "Путин",
      null
    ]
  },
  "P_4_15": {
    "optionKeywords": [
      null,
      "Борис Ельцин",
      null
    ]
  },
  "P_4_17": {
    "optionKeywords": [
      null,
      null,
      "говорить на родном языке"
    ]
  },
  "P_4_18": {
    "optionKeywords": [
      "однократно пройти дактилоскопическую регистрацию и фотографирование при получении разрешения на работу",
      null,
      null
    ]
  },
  "P_4_19": {
    "optionKeywords": [
      "В полицию",
      null,
      null
    ]
  },
  "P_4_20": {
    "optionKeywords": [
      null,
      "миграционную карту",
      null
    ]
  },
  "P_4_21": {
    "textKeyword": "Российской",
    "optionKeywords": [
      "Уголовным кодексом Российской Федерации",
      null,
      null
    ]
  },
  "P_4_22": {
    "textKeyword": "Верно",
    "optionKeywords": [
      null,
      "Неверно"
    ]
  },
  "P_5_1": {
    "optionKeywords": [
      "в магазине",
      null,
      null
    ]
  },
  "P_5_2": {
    "optionKeywords": [
      null,
      null,
      "овощи"
    ]
  },
  "P_5_3": {
    "optionKeywords": [
      "в магазине",
      null,
      null
    ]
  },
  "P_5_4": {
    "optionKeywords": [
      null,
      "5 этаже",
      null
    ]
  },
  "P_5_5": {
    "optionKeywords": [
      null,
      "на вокзале",
      null
    ]
  },
  "P_5_6": {
    "optionKeywords": [
      "недавно",
      null,
      null
    ]
  },
  "P_5_8": {
    "optionKeywords": [
      null,
      "яблоки",
      null
    ]
  },
  "P_5_9": {
    "optionKeywords": [
      null,
      null,
      "отдыхали"
    ]
  },
  "P_5_10": {
    "optionKeywords": [
      null,
      null,
      "поваром"
    ]
  },
  "P_5_11": {
    "optionKeywords": [
      "какая",
      null,
      null
    ]
  },
  "P_5_12": {
    "optionKeywords": [
      null,
      null,
      "12 июня"
    ]
  },
  "P_5_13": {
    "optionKeywords": [
      "Самара",
      null,
      null
    ]
  },
  "P_5_14": {
    "optionKeywords": [
      "советские войска взяли Берлин",
      null,
      null
    ]
  },
  "P_5_15": {
    "optionKeywords": [
      "Гагарин",
      null,
      null
    ]
  },
  "P_5_17": {
    "optionKeywords": [
      "непосредственно затрагивающими его права и свободы",
      null,
      null
    ]
  },
  "P_5_18": {
    "optionKeywords": [
      null,
      null,
      "обеспечивается законодательством Российской Федерации"
    ]
  },
  "P_5_20": {
    "textKeyword": "временно",
    "optionKeywords": [
      null,
      null,
      "по истечении срока временного пребывания"
    ]
  },
  "P_5_21": {
    "optionKeywords": [
      null,
      null,
      "административной"
    ]
  },
  "P_5_22": {
    "textKeyword": "Верно"
  },
  "P_6_1": {
    "optionKeywords": [
      null,
      null,
      "в банке"
    ]
  },
  "P_6_2": {
    "optionKeywords": [
      "миграционную карту",
      null,
      null
    ]
  },
  "P_6_3": {
    "optionKeywords": [
      "для мужчин",
      null,
      null
    ]
  },
  "P_6_4": {
    "optionKeywords": [
      "в торговом центре",
      null,
      null
    ]
  },
  "P_6_5": {
    "optionKeywords": [
      null,
      "в гостинице",
      null
    ]
  },
  "P_6_6": {
    "optionKeywords": [
      "днём",
      null,
      null
    ]
  },
  "P_6_10": {
    "optionKeywords": [
      null,
      "в поликлинике",
      null
    ]
  },
  "P_6_11": {
    "optionKeywords": [
      "потому что",
      null,
      null
    ]
  },
  "P_6_12": {
    "optionKeywords": [
      null,
      "День защитника Отечества",
      null
    ]
  },
  "P_6_13": {
    "optionKeywords": [
      null,
      null,
      "Екатеринбург"
    ]
  },
  "P_6_14": {
    "optionKeywords": [
      null,
      null,
      "в 1993 г"
    ]
  },
  "P_6_15": {
    "optionKeywords": [
      "Берлин",
      null,
      null
    ]
  },
  "P_6_17": {
    "optionKeywords": [
      "заключение брака",
      null,
      null
    ]
  },
  "P_6_18": {
    "optionKeywords": [
      null,
      null,
      "не является правом"
    ]
  },
  "P_6_19": {
    "optionKeywords": [
      null,
      "в полицию",
      null
    ]
  },
  "P_6_20": {
    "optionKeywords": [
      null,
      null,
      "90 дней"
    ]
  },
  "P_6_21": {
    "optionKeywords": [
      "Депортация",
      null,
      null
    ]
  },
  "P_6_22": {
    "textKeyword": "Верно"
  },
  "P_7_1": {
    "optionKeywords": [
      "в аптеке",
      null,
      null
    ]
  },
  "P_7_2": {
    "optionKeywords": [
      "сто пятьдесят рублей",
      null,
      null
    ]
  },
  "P_7_3": {
    "optionKeywords": [
      "о работе",
      null,
      null
    ]
  },
  "P_7_4": {
    "optionKeywords": [
      null,
      "молодым людям",
      null
    ]
  },
  "P_7_5": {
    "optionKeywords": [
      null,
      "в детском саду",
      null
    ]
  },
  "P_7_6": {
    "optionKeywords": [
      "петь",
      null,
      null
    ]
  },
  "P_7_8": {
    "optionKeywords": [
      null,
      null,
      "пятница"
    ]
  },
  "P_7_9": {
    "optionKeywords": [
      "адрес",
      null,
      null
    ]
  },
  "P_7_11": {
    "optionKeywords": [
      "поэтому",
      null,
      null
    ]
  },
  "P_7_12": {
    "optionKeywords": [
      "Международный женский день",
      null,
      null
    ]
  },
  "P_7_13": {
    "optionKeywords": [
      null,
      "Ростов-на-Дону",
      null
    ]
  },
  "P_7_14": {
    "optionKeywords": [
      null,
      null,
      "в 2014 г"
    ]
  },
  "P_7_15": {
    "optionKeywords": [
      "Германии",
      null,
      null
    ]
  },
  "P_7_17": {
    "optionKeywords": [
      null,
      "свободный труд",
      null
    ]
  },
  "P_7_18": {
    "optionKeywords": [
      "Обязанность",
      null,
      null
    ]
  },
  "P_7_20": {
    "optionKeywords": [
      null,
      null,
      "при выдаче разрешения на работу"
    ]
  },
  "P_7_21": {
    "optionKeywords": [
      null,
      null,
      "при сообщении заведомо ложных сведений о себе"
    ]
  },
  "P_7_22": {
    "textKeyword": "Верно"
  },
  "P_8_1": {
    "optionKeywords": [
      null,
      "в магазине",
      null
    ]
  },
  "P_8_2": {
    "optionKeywords": [
      null,
      "триста рублей",
      null
    ]
  },
  "P_8_3": {
    "optionKeywords": [
      null,
      "из Екатеринбурга",
      null
    ]
  },
  "P_8_4": {
    "optionKeywords": [
      "в 17 часов",
      null,
      null
    ]
  },
  "P_8_5": {
    "optionKeywords": [
      null,
      "на вокзале",
      null
    ]
  },
  "P_8_6": {
    "optionKeywords": [
      "поваром",
      null,
      null
    ]
  },
  "P_8_8": {
    "optionKeywords": [
      "по-русски",
      null,
      null
    ]
  },
  "P_8_9": {
    "optionKeywords": [
      null,
      null,
      "часы"
    ]
  },
  "P_8_10": {
    "optionKeywords": [
      "на работу",
      null,
      null
    ]
  },
  "P_8_11": {
    "optionKeywords": [
      "сколько",
      null,
      null
    ]
  },
  "P_8_12": {
    "optionKeywords": [
      null,
      null,
      "4 ноября"
    ]
  },
  "P_8_13": {
    "optionKeywords": [
      null,
      "Омск",
      null
    ]
  },
  "P_8_14": {
    "optionKeywords": [
      null,
      null,
      "в 2014 г"
    ]
  },
  "P_8_15": {
    "optionKeywords": [
      "военачальник",
      null,
      null
    ]
  },
  "P_8_17": {
    "optionKeywords": [
      null,
      null,
      "равенство прав мужчин и женщин"
    ]
  },
  "P_8_18": {
    "optionKeywords": [
      null,
      "могут поступить на военную службу по контракту",
      null
    ]
  },
  "P_8_19": {
    "textKeyword": "работу",
    "optionKeywords": [
      "при наличии патента или разрешения на работу",
      null,
      null
    ]
  },
  "P_8_20": {
    "optionKeywords": [
      null,
      "Визой",
      null
    ]
  },
  "P_8_21": {
    "optionKeywords": [
      null,
      null,
      "задержание по подозрению в преступлении"
    ]
  },
  "P_8_22": {
    "textKeyword": "Верно"
  },
  "P_9_1": {
    "optionKeywords": [
      null,
      null,
      "на улице"
    ]
  },
  "P_9_2": {
    "optionKeywords": [
      "справа от белого здания",
      null,
      null
    ]
  },
  "P_9_3": {
    "optionKeywords": [
      "из Казани",
      null,
      null
    ]
  },
  "P_9_4": {
    "optionKeywords": [
      "в час дня",
      null,
      null
    ]
  },
  "P_9_5": {
    "optionKeywords": [
      null,
      "в автобусе",
      null
    ]
  },
  "P_9_6": {
    "optionKeywords": [
      "в поликлинике",
      null,
      null
    ]
  },
  "P_9_8": {
    "optionKeywords": [
      null,
      "смотреть",
      null
    ]
  },
  "P_9_9": {
    "optionKeywords": [
      null,
      null,
      "какой"
    ]
  },
  "P_9_10": {
    "optionKeywords": [
      null,
      "в марте",
      null
    ]
  },
  "P_9_12": {
    "optionKeywords": [
      null,
      "8 марта",
      null
    ]
  },
  "P_9_13": {
    "optionKeywords": [
      null,
      "Красноярск",
      null
    ]
  },
  "P_9_14": {
    "optionKeywords": [
      null,
      "в 1991 г",
      null
    ]
  },
  "P_9_15": {
    "optionKeywords": [
      "первый космонавт",
      null,
      null
    ]
  },
  "P_9_17": {
    "textKeyword": "осуществивших въезд в Российскую Федерацию",
    "optionKeywords": [
      null,
      null,
      "осуществивших въезд в Российскую Федерацию"
    ]
  },
  "P_9_18": {
    "optionKeywords": [
      "законно находящихся на территории Российской Федерации",
      null,
      null
    ]
  },
  "P_9_19": {
    "optionKeywords": [
      null,
      "на бесплатную медицинскую помощь",
      null
    ]
  },
  "P_9_20": {
    "textKeyword": "Российской",
    "optionKeywords": [
      null,
      "срок сокращается в случае неразрешения въезда на территорию Российской Федерации",
      null
    ]
  },
  "P_9_21": {
    "optionKeywords": [
      null,
      null,
      "предъявить действительные документы"
    ]
  },
  "P_9_22": {
    "textKeyword": "Верно"
  },
  "P_10_1": {
    "optionKeywords": [
      "в торговом центре",
      null,
      null
    ]
  },
  "P_10_2": {
    "optionKeywords": [
      null,
      "получить деньги",
      null
    ]
  },
  "P_10_3": {
    "optionKeywords": [
      "в торговом центре",
      null,
      null
    ]
  },
  "P_10_4": {
    "optionKeywords": [
      null,
      null,
      "для детей"
    ]
  },
  "P_10_5": {
    "optionKeywords": [
      null,
      "в школе",
      null
    ]
  },
  "P_10_6": {
    "optionKeywords": [
      "на велосипеде",
      null,
      null
    ]
  },
  "P_10_8": {
    "optionKeywords": [
      "телефон",
      null,
      null
    ]
  },
  "P_10_9": {
    "optionKeywords": [
      null,
      null,
      "гуляли"
    ]
  },
  "P_10_11": {
    "optionKeywords": [
      "куда",
      null,
      null
    ]
  },
  "P_10_12": {
    "optionKeywords": [
      null,
      "1 мая",
      null
    ]
  },
  "P_10_13": {
    "optionKeywords": [
      null,
      null,
      "Пермь"
    ]
  },
  "P_10_14": {
    "optionKeywords": [
      null,
      "состоялся первый в мире полёт человека в космос",
      null
    ]
  },
  "P_10_15": {
    "optionKeywords": [
      "Крым",
      null,
      null
    ]
  },
  "P_10_17": {
    "optionKeywords": [
      null,
      null,
      "обеспечивающие достойную жизнь и свободное развитие человека"
    ]
  },
  "P_10_18": {
    "optionKeywords": [
      null,
      "сохранять культурное наследие",
      null
    ]
  },
  "P_10_19": {
    "textKeyword": "документ",
    "optionKeywords": [
      null,
      "документ о медицинском освидетельствовании",
      null
    ]
  },
  "P_10_20": {
    "optionKeywords": [
      null,
      null,
      "выдаче патента"
    ]
  },
  "P_10_21": {
    "optionKeywords": [
      null,
      null,
      "административный штраф"
    ]
  },
  "P_10_22": {
    "textKeyword": "Верно",
    "optionKeywords": [
      null,
      "Неверно"
    ]
  },
  "P_11_1": {
    "optionKeywords": [
      null,
      "на улице",
      null
    ]
  },
  "P_11_2": {
    "optionKeywords": [
      "лекарство",
      null,
      null
    ]
  },
  "P_11_3": {
    "optionKeywords": [
      null,
      null,
      "в субботу"
    ]
  },
  "P_11_4": {
    "optionKeywords": [
      "праздник для детей",
      null,
      null
    ]
  },
  "P_11_5": {
    "optionKeywords": [
      null,
      "в поликлинике",
      null
    ]
  },
  "P_11_6": {
    "optionKeywords": [
      "была в зоопарке",
      null,
      null
    ]
  },
  "P_11_8": {
    "optionKeywords": [
      "делаешь",
      null,
      null
    ]
  },
  "P_11_9": {
    "optionKeywords": [
      "работала",
      null,
      null
    ]
  },
  "P_11_12": {
    "textKeyword": "России",
    "optionKeywords": [
      null,
      null,
      "День России"
    ]
  },
  "P_11_13": {
    "optionKeywords": [
      null,
      "Севастополь",
      null
    ]
  },
  "P_11_14": {
    "optionKeywords": [
      "военачальник",
      null,
      null
    ]
  },
  "P_11_15": {
    "optionKeywords": [
      null,
      null,
      "в 1993 г"
    ]
  },
  "P_11_17": {
    "optionKeywords": [
      null,
      "свободно передвигаться по территории страны",
      null
    ]
  },
  "P_11_18": {
    "optionKeywords": [
      null,
      "уплачивать налоги",
      null
    ]
  },
  "P_11_19": {
    "optionKeywords": [
      "Трудовой",
      null,
      null
    ]
  },
  "P_11_20": {
    "optionKeywords": [
      null,
      null,
      "фамилию и имя"
    ]
  },
  "P_11_21": {
    "optionKeywords": [
      "административный штраф",
      null,
      null
    ]
  },
  "P_11_22": {
    "textKeyword": "Верно"
  },
  "P_12_1": {
    "optionKeywords": [
      "друзей",
      null,
      null
    ]
  },
  "P_12_2": {
    "optionKeywords": [
      null,
      null,
      "осенью"
    ]
  },
  "P_12_3": {
    "optionKeywords": [
      null,
      null,
      "в метро"
    ]
  },
  "P_12_4": {
    "optionKeywords": [
      "Театральная",
      null,
      null
    ]
  },
  "P_12_5": {
    "optionKeywords": [
      null,
      "в кафе",
      null
    ]
  },
  "P_12_6": {
    "optionKeywords": [
      "в кафе",
      null,
      null
    ]
  },
  "P_12_8": {
    "optionKeywords": [
      "бесплатно",
      null,
      null
    ]
  },
  "P_12_9": {
    "optionKeywords": [
      null,
      "семейное",
      null
    ]
  },
  "P_12_10": {
    "optionKeywords": [
      null,
      null,
      "у тебя"
    ]
  },
  "P_12_11": {
    "optionKeywords": [
      null,
      "потому что",
      null
    ]
  },
  "P_12_12": {
    "textKeyword": "России",
    "optionKeywords": [
      null,
      null,
      "День России"
    ]
  },
  "P_12_13": {
    "optionKeywords": [
      "Севастополь",
      null,
      null
    ]
  },
  "P_12_14": {
    "optionKeywords": [
      null,
      "Германии",
      null
    ]
  },
  "P_12_15": {
    "optionKeywords": [
      null,
      "1612 г",
      null
    ]
  },
  "P_12_17": {
    "optionKeywords": [
      null,
      "выбирать место пребывания",
      null
    ]
  },
  "P_12_18": {
    "optionKeywords": [
      null,
      null,
      "платить законно установленные налоги и сборы"
    ]
  },
  "P_12_19": {
    "optionKeywords": [
      "свидетельство о рождении детей",
      null,
      null
    ]
  },
  "P_12_20": {
    "optionKeywords": [
      null,
      "факт въезда иностранного гражданина в РФ",
      null
    ]
  },
  "P_12_21": {
    "optionKeywords": [
      null,
      null,
      "административное выдворение за пределы РФ"
    ]
  },
  "P_12_22": {
    "textKeyword": "Верно",
    "optionKeywords": [
      null,
      "неверно"
    ]
  },
  "P_13_1": {
    "optionKeywords": [
      null,
      null,
      "на железнодорожном вокзале"
    ]
  },
  "P_13_2": {
    "optionKeywords": [
      null,
      null,
      "в 3 часа"
    ]
  },
  "P_13_3": {
    "optionKeywords": [
      null,
      "в торговом центре",
      null
    ]
  },
  "P_13_4": {
    "optionKeywords": [
      null,
      null,
      "осенью"
    ]
  },
  "P_13_5": {
    "optionKeywords": [
      null,
      "в поликлинике",
      null
    ]
  },
  "P_13_6": {
    "optionKeywords": [
      "на почте",
      null,
      null
    ]
  },
  "P_13_8": {
    "optionKeywords": [
      "кроссовки",
      null,
      null
    ]
  },
  "P_13_9": {
    "optionKeywords": [
      null,
      null,
      "приглашаю"
    ]
  },
  "P_13_10": {
    "optionKeywords": [
      null,
      "кассиром",
      null
    ]
  },
  "P_13_11": {
    "optionKeywords": [
      "поэтому",
      null,
      null
    ]
  },
  "P_13_12": {
    "optionKeywords": [
      null,
      "День Победы",
      null
    ]
  },
  "P_13_13": {
    "optionKeywords": [
      "Челябинск",
      null,
      null
    ]
  },
  "P_13_14": {
    "optionKeywords": [
      null,
      null,
      "1993 г"
    ]
  },
  "P_13_15": {
    "optionKeywords": [
      null,
      null,
      "Смута и интервенция"
    ]
  },
  "P_13_17": {
    "optionKeywords": [
      null,
      null,
      "пользоваться учреждениями культуры"
    ]
  },
  "P_13_18": {
    "optionKeywords": [
      null,
      "сохранять природу и окружающую среду",
      null
    ]
  },
  "P_13_19": {
    "optionKeywords": [
      null,
      null,
      "свидетельство о праве собственности"
    ]
  },
  "P_13_20": {
    "optionKeywords": [
      null,
      null,
      "факт въезда иностранного гражданина в РФ"
    ]
  },
  "P_13_21": {
    "optionKeywords": [
      null,
      null,
      "административный штраф"
    ]
  },
  "P_13_22": {
    "textKeyword": "Верно"
  },
  "P_14_1": {
    "optionKeywords": [
      null,
      null,
      "в поликлинике"
    ]
  },
  "P_14_2": {
    "optionKeywords": [
      "в кабинете 15",
      null,
      null
    ]
  },
  "P_14_3": {
    "optionKeywords": [
      "в торговом центре",
      null,
      null
    ]
  },
  "P_14_4": {
    "optionKeywords": [
      "на зимнюю одежду",
      null,
      null
    ]
  },
  "P_14_5": {
    "optionKeywords": [
      null,
      "на вокзале",
      null
    ]
  },
  "P_14_6": {
    "optionKeywords": [
      null,
      null,
      "в воскресенье"
    ]
  },
  "P_14_8": {
    "optionKeywords": [
      "рюкзак",
      null,
      null
    ]
  },
  "P_14_9": {
    "optionKeywords": [
      null,
      "посылку",
      null
    ]
  },
  "P_14_10": {
    "optionKeywords": [
      null,
      "Андрею",
      null
    ]
  },
  "P_14_12": {
    "optionKeywords": [
      null,
      "День защитника Отечества",
      null
    ]
  },
  "P_14_13": {
    "textKeyword": "город",
    "optionKeywords": [
      "Нижний Новгород",
      null,
      null
    ]
  },
  "P_14_14": {
    "optionKeywords": [
      "Российская революция",
      null,
      null
    ]
  },
  "P_14_15": {
    "optionKeywords": [
      null,
      null,
      "2014 г"
    ]
  },
  "P_14_17": {
    "optionKeywords": [
      null,
      null,
      "иметь имущество в собственности"
    ]
  },
  "P_14_18": {
    "optionKeywords": [
      "платить законно установленные налоги и сборы",
      null,
      null
    ]
  },
  "P_14_19": {
    "optionKeywords": [
      "договор социального найма",
      null,
      null
    ]
  },
  "P_14_20": {
    "optionKeywords": [
      null,
      null,
      "визой"
    ]
  },
  "P_14_21": {
    "optionKeywords": [
      "административное выдворение за пределы РФ",
      null,
      null
    ]
  },
  "P_14_22": {
    "textKeyword": "Верно",
    "optionKeywords": [
      null,
      "неверно"
    ]
  },
  "P_15_1": {
    "optionKeywords": [
      "на автовокзале",
      null,
      null
    ]
  },
  "P_15_2": {
    "optionKeywords": [
      null,
      null,
      "в кассе"
    ]
  },
  "P_15_3": {
    "optionKeywords": [
      "на железнодорожном вокзале",
      null,
      null
    ]
  },
  "P_15_4": {
    "optionKeywords": [
      null,
      null,
      "в 17"
    ]
  },
  "P_15_5": {
    "optionKeywords": [
      "в банке",
      null,
      null
    ]
  },
  "P_15_6": {
    "optionKeywords": [
      null,
      "в метро",
      null
    ]
  },
  "P_15_8": {
    "optionKeywords": [
      null,
      "в конце августа",
      null
    ]
  },
  "P_15_9": {
    "optionKeywords": [
      null,
      null,
      "рубашку"
    ]
  },
  "P_15_12": {
    "optionKeywords": [
      null,
      null,
      "4 ноября"
    ]
  },
  "P_15_13": {
    "optionKeywords": [
      null,
      "Омск",
      null
    ]
  },
  "P_15_14": {
    "optionKeywords": [
      null,
      null,
      "2022 г"
    ]
  },
  "P_15_15": {
    "optionKeywords": [
      null,
      "1961 г",
      null
    ]
  },
  "P_15_17": {
    "optionKeywords": [
      "свободно передвигаться",
      null,
      null
    ]
  },
  "P_15_18": {
    "optionKeywords": [
      null,
      "беречь памятники истории и культуры",
      null
    ]
  },
  "P_15_19": {
    "optionKeywords": [
      null,
      null,
      "документ о праве собственности на жильё"
    ]
  },
  "P_15_20": {
    "optionKeywords": [
      null,
      "по истечении срока действия визы",
      null
    ]
  },
  "P_15_21": {
    "optionKeywords": [
      "административное выдворение за пределы РФ",
      null,
      null
    ]
  },
  "P_15_22": {
    "textKeyword": "Верно",
    "optionKeywords": [
      null,
      "неверно"
    ]
  },
  "P_16_1": {
    "optionKeywords": [
      null,
      null,
      "в поликлинике"
    ]
  },
  "P_16_2": {
    "optionKeywords": [
      null,
      "на вторник",
      null
    ]
  },
  "P_16_3": {
    "optionKeywords": [
      "в поликлинике",
      null,
      null
    ]
  },
  "P_16_4": {
    "optionKeywords": [
      null,
      "паспорт",
      null
    ]
  },
  "P_16_5": {
    "optionKeywords": [
      null,
      "на улице",
      null
    ]
  },
  "P_16_6": {
    "optionKeywords": [
      "в музее",
      null,
      null
    ]
  },
  "P_16_8": {
    "optionKeywords": [
      null,
      null,
      "чашку"
    ]
  },
  "P_16_9": {
    "optionKeywords": [
      null,
      "Уважаемые",
      null
    ]
  },
  "P_16_10": {
    "optionKeywords": [
      null,
      "папы",
      null
    ]
  },
  "P_16_11": {
    "optionKeywords": [
      "потому что",
      null,
      null
    ]
  },
  "P_16_12": {
    "optionKeywords": [
      null,
      null,
      "Праздник Весны и Труда"
    ]
  },
  "P_16_13": {
    "optionKeywords": [
      null,
      null,
      "Екатеринбург"
    ]
  },
  "P_16_14": {
    "optionKeywords": [
      "22 июня 1941 г",
      null,
      null
    ]
  },
  "P_16_15": {
    "optionKeywords": [
      null,
      "космонавт",
      null
    ]
  },
  "P_16_17": {
    "optionKeywords": [
      "свободно распоряжаться своими способностями к труду",
      null,
      null
    ]
  },
  "P_16_18": {
    "optionKeywords": [
      null,
      "заботиться о сохранении исторического и культурного наследия",
      null
    ]
  },
  "P_16_19": {
    "optionKeywords": [
      null,
      "договор социального найма",
      null
    ]
  },
  "P_16_20": {
    "optionKeywords": [
      null,
      "по истечении срока действия визы",
      null
    ]
  },
  "P_16_21": {
    "optionKeywords": [
      "административный штраф",
      null,
      null
    ]
  },
  "P_16_22": {
    "textKeyword": "Верно",
    "optionKeywords": [
      null,
      "неверно"
    ]
  }
};
