/* eslint-disable */
// Generated by scripts/generate_patent_keywords.ts — edit manually or re-run the script.

export type PatentQuestionKeywordHints = {
  textKeyword?: string | null;
};

export const PATENT_QUESTION_KEYWORDS: Record<string, PatentQuestionKeywordHints> = {
  "P_1_1": {
    "textKeyword": "говорят"
  },
  "P_1_2": {
    "textKeyword": "необходимо"
  },
  "P_1_3": {
    "textKeyword": "услышать"
  },
  "P_1_4": {
    "textKeyword": "можно"
  },
  "P_1_5": {
    "textKeyword": "объявление"
  },
  "P_1_6": {
    "textKeyword": "Экскурсия"
  },
  "P_1_8": {
    "textKeyword": "приехала"
  },
  "P_1_9": {
    "textKeyword": "сотовой"
  },
  "P_1_10": {
    "textKeyword": "зовут"
  },
  "P_1_11": {
    "textKeyword": "приехали"
  },
  "P_1_12": {
    "textKeyword": "празднуют"
  },
  "P_1_13": {
    "textKeyword": "Российской"
  },
  "P_1_14": {
    "textKeyword": "Отечественная"
  },
  "P_1_15": {
    "textKeyword": "Содружество"
  },
  "P_1_16": {
    "textKeyword": "Российской"
  },
  "P_1_17": {
    "textKeyword": "Конституции"
  },
  "P_1_18": {
    "textKeyword": "регистрация"
  },
  "P_1_19": {
    "textKeyword": "иностранного"
  },
  "P_1_20": {
    "textKeyword": "иметь"
  },
  "P_1_21": {
    "textKeyword": "ответственности"
  },
  "P_1_22": {
    "textKeyword": "законодательством"
  },
  "P_2_1": {
    "textKeyword": "говорят"
  },
  "P_2_2": {
    "textKeyword": "выходит"
  },
  "P_2_3": {
    "textKeyword": "услышать"
  },
  "P_2_4": {
    "textKeyword": "можно"
  },
  "P_2_5": {
    "textKeyword": "Новый"
  },
  "P_2_6": {
    "textKeyword": "Вчера"
  },
  "P_2_8": {
    "textKeyword": "магазине"
  },
  "P_2_9": {
    "textKeyword": "магазине"
  },
  "P_2_10": {
    "textKeyword": "Сколько"
  },
  "P_2_11": {
    "textKeyword": "чувствуете"
  },
  "P_2_12": {
    "textKeyword": "празднуют"
  },
  "P_2_13": {
    "textKeyword": "Российской"
  },
  "P_2_14": {
    "textKeyword": "Отечественной"
  },
  "P_2_15": {
    "textKeyword": "Прославленный"
  },
  "P_2_16": {
    "textKeyword": "Российской"
  },
  "P_2_17": {
    "textKeyword": "иностранному"
  },
  "P_2_18": {
    "textKeyword": "заключается"
  },
  "P_2_19": {
    "textKeyword": "обратиться"
  },
  "P_2_20": {
    "textKeyword": "иностранного"
  },
  "P_2_21": {
    "textKeyword": "устанавливает"
  },
  "P_2_22": {
    "textKeyword": "законодательством"
  },
  "P_3_1": {
    "textKeyword": "говорят"
  },
  "P_3_2": {
    "textKeyword": "услышали"
  },
  "P_3_4": {
    "textKeyword": "работать"
  },
  "P_3_5": {
    "textKeyword": "объявление"
  },
  "P_3_6": {
    "textKeyword": "вернулась"
  },
  "P_3_8": {
    "textKeyword": "родился"
  },
  "P_3_9": {
    "textKeyword": "хорошую"
  },
  "P_3_10": {
    "textKeyword": "Скажите"
  },
  "P_3_11": {
    "textKeyword": "разрешение"
  },
  "P_3_12": {
    "textKeyword": "отмечают"
  },
  "P_3_13": {
    "textKeyword": "Российской"
  },
  "P_3_14": {
    "textKeyword": "Отечественная"
  },
  "P_3_15": {
    "textKeyword": "Содружество"
  },
  "P_3_16": {
    "textKeyword": "Российской"
  },
  "P_3_17": {
    "textKeyword": "иностранному"
  },
  "P_3_18": {
    "textKeyword": "иностранный"
  },
  "P_3_19": {
    "textKeyword": "иностранный"
  },
  "P_3_20": {
    "textKeyword": "миграционной"
  },
  "P_3_21": {
    "textKeyword": "уполномоченную"
  },
  "P_3_22": {
    "textKeyword": "установленный"
  },
  "P_4_1": {
    "textKeyword": "разговор"
  },
  "P_4_2": {
    "textKeyword": "сделал"
  },
  "P_4_3": {
    "textKeyword": "услышать"
  },
  "P_4_4": {
    "textKeyword": "Кассы"
  },
  "P_4_5": {
    "textKeyword": "объявление"
  },
  "P_4_6": {
    "textKeyword": "работать"
  },
  "P_4_8": {
    "textKeyword": "находится"
  },
  "P_4_9": {
    "textKeyword": "работает"
  },
  "P_4_10": {
    "textKeyword": "документы"
  },
  "P_4_11": {
    "textKeyword": "поликлиника"
  },
  "P_4_12": {
    "textKeyword": "отмечают"
  },
  "P_4_13": {
    "textKeyword": "находится"
  },
  "P_4_14": {
    "textKeyword": "Севастополя"
  },
  "P_4_15": {
    "textKeyword": "Содружества"
  },
  "P_4_16": {
    "textKeyword": "Российской"
  },
  "P_4_17": {
    "textKeyword": "Иностранный"
  },
  "P_4_18": {
    "textKeyword": "Иностранный"
  },
  "P_4_19": {
    "textKeyword": "обратиться"
  },
  "P_4_20": {
    "textKeyword": "необходимо"
  },
  "P_4_21": {
    "textKeyword": "ответственность"
  },
  "P_4_22": {
    "textKeyword": "депортирован"
  },
  "P_5_1": {
    "textKeyword": "говорят"
  },
  "P_5_2": {
    "textKeyword": "купить"
  },
  "P_5_3": {
    "textKeyword": "услышать"
  },
  "P_5_4": {
    "textKeyword": "можно"
  },
  "P_5_5": {
    "textKeyword": "объявление"
  },
  "P_5_6": {
    "textKeyword": "работает"
  },
  "P_5_8": {
    "textKeyword": "магазине"
  },
  "P_5_9": {
    "textKeyword": "Вчера"
  },
  "P_5_10": {
    "textKeyword": "подруга"
  },
  "P_5_11": {
    "textKeyword": "смотрел"
  },
  "P_5_12": {
    "textKeyword": "отмечают"
  },
  "P_5_13": {
    "textKeyword": "находится"
  },
  "P_5_15": {
    "textKeyword": "совершил"
  },
  "P_5_16": {
    "textKeyword": "Российской"
  },
  "P_5_17": {
    "textKeyword": "иностранному"
  },
  "P_5_18": {
    "textKeyword": "медицинскую"
  },
  "P_5_19": {
    "textKeyword": "Иностранному"
  },
  "P_5_20": {
    "textKeyword": "пребывающий"
  },
  "P_5_21": {
    "textKeyword": "ответственности"
  },
  "P_5_22": {
    "textKeyword": "административного"
  },
  "P_6_1": {
    "textKeyword": "говорят"
  },
  "P_6_2": {
    "textKeyword": "иметь"
  },
  "P_6_3": {
    "textKeyword": "купить"
  },
  "P_6_4": {
    "textKeyword": "услышать"
  },
  "P_6_5": {
    "textKeyword": "объявление"
  },
  "P_6_6": {
    "textKeyword": "Прослушивание"
  },
  "P_6_8": {
    "textKeyword": "велосипед"
  },
  "P_6_9": {
    "textKeyword": "Вчера"
  },
  "P_6_10": {
    "textKeyword": "Утром"
  },
  "P_6_11": {
    "textKeyword": "воскресенье"
  },
  "P_6_12": {
    "textKeyword": "празднуют"
  },
  "P_6_13": {
    "textKeyword": "находится"
  },
  "P_6_14": {
    "textKeyword": "Конституция"
  },
  "P_6_15": {
    "textKeyword": "советские"
  },
  "P_6_16": {
    "textKeyword": "Российской"
  },
  "P_6_17": {
    "textKeyword": "иностранного"
  },
  "P_6_18": {
    "textKeyword": "государственные"
  },
  "P_6_19": {
    "textKeyword": "правоохранительный"
  },
  "P_6_20": {
    "textKeyword": "иностранный"
  },
  "P_6_21": {
    "textKeyword": "Принудительная"
  },
  "P_6_22": {
    "textKeyword": "освидетельствования"
  },
  "P_7_1": {
    "textKeyword": "говорят"
  },
  "P_7_2": {
    "textKeyword": "стоит"
  },
  "P_7_3": {
    "textKeyword": "объявление"
  },
  "P_7_4": {
    "textKeyword": "предлагает"
  },
  "P_7_5": {
    "textKeyword": "объявление"
  },
  "P_7_6": {
    "textKeyword": "концерте"
  },
  "P_7_8": {
    "textKeyword": "Сегодня"
  },
  "P_7_9": {
    "textKeyword": "пожалуйста"
  },
  "P_7_10": {
    "textKeyword": "Познакомьтесь"
  },
  "P_7_11": {
    "textKeyword": "работали"
  },
  "P_7_12": {
    "textKeyword": "отмечают"
  },
  "P_7_13": {
    "textKeyword": "находится"
  },
  "P_7_14": {
    "textKeyword": "Севастополя"
  },
  "P_7_15": {
    "textKeyword": "напали"
  },
  "P_7_16": {
    "textKeyword": "Российской"
  },
  "P_7_17": {
    "textKeyword": "иностранного"
  },
  "P_7_18": {
    "textKeyword": "дактилоскопической"
  },
  "P_7_19": {
    "textKeyword": "Иностранному"
  },
  "P_7_20": {
    "textKeyword": "продлевается"
  },
  "P_7_21": {
    "textKeyword": "иностранному"
  },
  "P_7_22": {
    "textKeyword": "административного"
  },
  "P_8_1": {
    "textKeyword": "говорят"
  },
  "P_8_2": {
    "textKeyword": "Продукты"
  },
  "P_8_3": {
    "textKeyword": "Самолёт"
  },
  "P_8_4": {
    "textKeyword": "прилетает"
  },
  "P_8_5": {
    "textKeyword": "объявление"
  },
  "P_8_6": {
    "textKeyword": "работает"
  },
  "P_8_8": {
    "textKeyword": "говорит"
  },
  "P_8_9": {
    "textKeyword": "Можно"
  },
  "P_8_10": {
    "textKeyword": "Завтра"
  },
  "P_8_11": {
    "textKeyword": "стоит"
  },
  "P_8_12": {
    "textKeyword": "народного"
  },
  "P_8_13": {
    "textKeyword": "находится"
  },
  "P_8_14": {
    "textKeyword": "Севастополя"
  },
  "P_8_15": {
    "textKeyword": "Жуков"
  },
  "P_8_16": {
    "textKeyword": "Российской"
  },
  "P_8_17": {
    "textKeyword": "устанавливает"
  },
  "P_8_18": {
    "textKeyword": "Иностранные"
  },
  "P_8_19": {
    "textKeyword": "Иностранному"
  },
  "P_8_20": {
    "textKeyword": "определяется"
  },
  "P_8_21": {
    "textKeyword": "иностранному"
  },
  "P_8_22": {
    "textKeyword": "административные"
  },
  "P_9_1": {
    "textKeyword": "говорят"
  },
  "P_9_2": {
    "textKeyword": "метро"
  },
  "P_9_3": {
    "textKeyword": "едет"
  },
  "P_9_4": {
    "textKeyword": "приезжает"
  },
  "P_9_5": {
    "textKeyword": "объявление"
  },
  "P_9_6": {
    "textKeyword": "работает"
  },
  "P_9_8": {
    "textKeyword": "телевизору"
  },
  "P_9_9": {
    "textKeyword": "помнишь"
  },
  "P_9_10": {
    "textKeyword": "приехали"
  },
  "P_9_11": {
    "textKeyword": "настоящее"
  },
  "P_9_12": {
    "textKeyword": "Международный"
  },
  "P_9_13": {
    "textKeyword": "находится"
  },
  "P_9_14": {
    "textKeyword": "Содружество"
  },
  "P_9_15": {
    "textKeyword": "Гагарин"
  },
  "P_9_16": {
    "textKeyword": "Российской"
  },
  "P_9_17": {
    "textKeyword": "распространяются"
  },
  "P_9_18": {
    "textKeyword": "распространяется"
  },
  "P_9_19": {
    "textKeyword": "Иностранный"
  },
  "P_9_20": {
    "textKeyword": "иностранного"
  },
  "P_9_21": {
    "textKeyword": "Государственной"
  },
  "P_9_22": {
    "textKeyword": "административной"
  },
  "P_10_1": {
    "textKeyword": "говорят"
  },
  "P_10_2": {
    "textKeyword": "хочет"
  },
  "P_10_3": {
    "textKeyword": "услышать"
  },
  "P_10_4": {
    "textKeyword": "магазин"
  },
  "P_10_5": {
    "textKeyword": "объявление"
  },
  "P_10_6": {
    "textKeyword": "продукты"
  },
  "P_10_8": {
    "textKeyword": "купить"
  },
  "P_10_9": {
    "textKeyword": "друзьями"
  },
  "P_10_10": {
    "textKeyword": "двадцать"
  },
  "P_10_11": {
    "textKeyword": "Извините"
  },
  "P_10_12": {
    "textKeyword": "Праздник"
  },
  "P_10_13": {
    "textKeyword": "находится"
  },
  "P_10_15": {
    "textKeyword": "состав"
  },
  "P_10_16": {
    "textKeyword": "Российской"
  },
  "P_10_17": {
    "textKeyword": "государство"
  },
  "P_10_18": {
    "textKeyword": "устанавливает"
  },
  "P_10_19": {
    "textKeyword": "Иностранный"
  },
  "P_10_20": {
    "textKeyword": "иностранного"
  },
  "P_10_21": {
    "textKeyword": "Осуществление"
  },
  "P_10_22": {
    "textKeyword": "непогашенную"
  },
  "P_11_1": {
    "textKeyword": "говорят"
  },
  "P_11_2": {
    "textKeyword": "купить"
  },
  "P_11_3": {
    "textKeyword": "праздник"
  },
  "P_11_4": {
    "textKeyword": "центральной"
  },
  "P_11_5": {
    "textKeyword": "объявление"
  },
  "P_11_6": {
    "textKeyword": "Вчера"
  },
  "P_11_8": {
    "textKeyword": "воскресенье"
  },
  "P_11_9": {
    "textKeyword": "Раньше"
  },
  "P_11_10": {
    "textKeyword": "пожалуйста"
  },
  "P_11_11": {
    "textKeyword": "называется"
  },
  "P_11_12": {
    "textKeyword": "отмечают"
  },
  "P_11_13": {
    "textKeyword": "находится"
  },
  "P_11_14": {
    "textKeyword": "Жуков"
  },
  "P_11_15": {
    "textKeyword": "Конституция"
  },
  "P_11_16": {
    "textKeyword": "Российской"
  },
  "P_11_17": {
    "textKeyword": "Иностранный"
  },
  "P_11_18": {
    "textKeyword": "иностранный"
  },
  "P_11_19": {
    "textKeyword": "Иностранный"
  },
  "P_11_20": {
    "textKeyword": "миграционном"
  },
  "P_11_21": {
    "textKeyword": "миграционного"
  },
  "P_11_22": {
    "textKeyword": "административное"
  },
  "P_12_1": {
    "textKeyword": "разговор"
  },
  "P_12_2": {
    "textKeyword": "хотят"
  },
  "P_12_3": {
    "textKeyword": "услышать"
  },
  "P_12_4": {
    "textKeyword": "едет"
  },
  "P_12_5": {
    "textKeyword": "объявление"
  },
  "P_12_6": {
    "textKeyword": "работает"
  },
  "P_12_8": {
    "textKeyword": "можно"
  },
  "P_12_9": {
    "textKeyword": "положение"
  },
  "P_12_10": {
    "textKeyword": "братья"
  },
  "P_12_11": {
    "textKeyword": "говорят"
  },
  "P_12_12": {
    "textKeyword": "отмечают"
  },
  "P_12_13": {
    "textKeyword": "находится"
  },
  "P_12_14": {
    "textKeyword": "напали"
  },
  "P_12_15": {
    "textKeyword": "польско-литовских"
  },
  "P_12_16": {
    "textKeyword": "Российской"
  },
  "P_12_17": {
    "textKeyword": "Иностранный"
  },
  "P_12_18": {
    "textKeyword": "иностранный"
  },
  "P_12_19": {
    "textKeyword": "иностранному"
  },
  "P_12_20": {
    "textKeyword": "миграционный"
  },
  "P_12_21": {
    "textKeyword": "миграционного"
  },
  "P_12_22": {
    "textKeyword": "дисциплинарного"
  },
  "P_13_1": {
    "textKeyword": "говорят"
  },
  "P_13_2": {
    "textKeyword": "Отправление"
  },
  "P_13_3": {
    "textKeyword": "услышать"
  },
  "P_13_4": {
    "textKeyword": "можно"
  },
  "P_13_5": {
    "textKeyword": "объявление"
  },
  "P_13_6": {
    "textKeyword": "работы"
  },
  "P_13_8": {
    "textKeyword": "бесплатно"
  },
  "P_13_9": {
    "textKeyword": "рождения"
  },
  "P_13_10": {
    "textKeyword": "работаешь"
  },
  "P_13_11": {
    "textKeyword": "холодно"
  },
  "P_13_12": {
    "textKeyword": "отмечают"
  },
  "P_13_13": {
    "textKeyword": "находится"
  },
  "P_13_14": {
    "textKeyword": "Конституция"
  },
  "P_13_15": {
    "textKeyword": "относится"
  },
  "P_13_16": {
    "textKeyword": "Российской"
  },
  "P_13_17": {
    "textKeyword": "Иностранный"
  },
  "P_13_18": {
    "textKeyword": "Иностранный"
  },
  "P_13_19": {
    "textKeyword": "иностранному"
  },
  "P_13_20": {
    "textKeyword": "миграционный"
  },
  "P_13_21": {
    "textKeyword": "миграционного"
  },
  "P_13_22": {
    "textKeyword": "Административное"
  },
  "P_14_1": {
    "textKeyword": "говорят"
  },
  "P_14_2": {
    "textKeyword": "можно"
  },
  "P_14_3": {
    "textKeyword": "услышать"
  },
  "P_14_4": {
    "textKeyword": "Скидки"
  },
  "P_14_5": {
    "textKeyword": "объявление"
  },
  "P_14_6": {
    "textKeyword": "выходной"
  },
  "P_14_8": {
    "textKeyword": "учебников"
  },
  "P_14_9": {
    "textKeyword": "отправить"
  },
  "P_14_10": {
    "textKeyword": "перерыв"
  },
  "P_14_11": {
    "textKeyword": "пожалуйста"
  },
  "P_14_12": {
    "textKeyword": "отмечают"
  },
  "P_14_13": {
    "textKeyword": "находится"
  },
  "P_14_14": {
    "textKeyword": "началась"
  },
  "P_14_15": {
    "textKeyword": "Республика"
  },
  "P_14_16": {
    "textKeyword": "Российской"
  },
  "P_14_17": {
    "textKeyword": "Иностранный"
  },
  "P_14_18": {
    "textKeyword": "иностранный"
  },
  "P_14_19": {
    "textKeyword": "иностранному"
  },
  "P_14_20": {
    "textKeyword": "иностранного"
  },
  "P_14_21": {
    "textKeyword": "миграционного"
  },
  "P_14_22": {
    "textKeyword": "исправительных"
  },
  "P_15_1": {
    "textKeyword": "говорят"
  },
  "P_15_2": {
    "textKeyword": "продаются"
  },
  "P_15_3": {
    "textKeyword": "услышать"
  },
  "P_15_4": {
    "textKeyword": "Следующий"
  },
  "P_15_5": {
    "textKeyword": "объявление"
  },
  "P_15_6": {
    "textKeyword": "работает"
  },
  "P_15_8": {
    "textKeyword": "поедем"
  },
  "P_15_9": {
    "textKeyword": "магазине"
  },
  "P_15_10": {
    "textKeyword": "пожалуйста"
  },
  "P_15_11": {
    "textKeyword": "едет"
  },
  "P_15_12": {
    "textKeyword": "народного"
  },
  "P_15_13": {
    "textKeyword": "находится"
  },
  "P_15_14": {
    "textKeyword": "Специальная"
  },
  "P_15_15": {
    "textKeyword": "совершил"
  },
  "P_15_16": {
    "textKeyword": "Российской"
  },
  "P_15_17": {
    "textKeyword": "Иностранный"
  },
  "P_15_18": {
    "textKeyword": "Иностранный"
  },
  "P_15_19": {
    "textKeyword": "иностранному"
  },
  "P_15_20": {
    "textKeyword": "пребывающий"
  },
  "P_15_21": {
    "textKeyword": "миграционного"
  },
  "P_15_22": {
    "textKeyword": "привлечением"
  },
  "P_16_1": {
    "textKeyword": "говорят"
  },
  "P_16_2": {
    "textKeyword": "Записаться"
  },
  "P_16_3": {
    "textKeyword": "услышать"
  },
  "P_16_4": {
    "textKeyword": "иметь"
  },
  "P_16_5": {
    "textKeyword": "объявление"
  },
  "P_16_6": {
    "textKeyword": "прошлой"
  },
  "P_16_8": {
    "textKeyword": "магазине"
  },
  "P_16_9": {
    "textKeyword": "покупатели"
  },
  "P_16_10": {
    "textKeyword": "стадион"
  },
  "P_16_11": {
    "textKeyword": "продуктов"
  },
  "P_16_12": {
    "textKeyword": "отмечают"
  },
  "P_16_13": {
    "textKeyword": "находится"
  },
  "P_16_14": {
    "textKeyword": "Отечественная"
  },
  "P_16_15": {
    "textKeyword": "Гагарин"
  },
  "P_16_16": {
    "textKeyword": "Российской"
  },
  "P_16_17": {
    "textKeyword": "Иностранный"
  },
  "P_16_18": {
    "textKeyword": "Иностранный"
  },
  "P_16_19": {
    "textKeyword": "иностранному"
  },
  "P_16_20": {
    "textKeyword": "пребывающий"
  },
  "P_16_21": {
    "textKeyword": "миграционного"
  },
  "P_16_22": {
    "textKeyword": "административный"
  }
};
